### ISSUE TITLE
New Logo Suggestion...

### ISSUE THREAD

**Issue by SecularSteve** [TeamPiped/Piped#1009]
I decided to throw in my re-take on the logo used at the moment.

![Piped](https://user-images.githubusercontent.com/33793273/165257452-179ac7e5-2492-4ff4-9caa-783c46b6d7fe.png)

Made in Inkscape, released under the CC BY-SA 4.0

ZIP contains SVG and PNG...

[Piped.zip](https://github.com/TeamPiped/Piped/files/8561299/Piped.zip)

**Comment by EdwardLangdon** [comment]
Seriously dude, Please remove the Pipes going in to the alphabet. Sort of Video. I am pretty sure, Kavin will not accept this.

**Comment by trymeouteh** [comment]
I do not care for the white fog look on the left side and the red is too dark of a red.

If it had a ligher red and maybe a different share of red where the black is, it may not be too bad.

**Comment by zeref-dragneel** [comment]
I prefer this kind of logo. If necessary, I will upload this logo file. 😅

<img src="https://i.imgur.com/Ec5XZpq.png" height="200">
<img src="https://i.imgur.com/8uZhxDy.png" height="200">
<img src="https://i.imgur.com/psdHYBo.png" height="200">

**Comment by Mhowser** [comment]
Keep in mind the app is being renamed to Tubular soon.

**Comment by SecularSteve** [comment]
> I prefer this kind of logo. If necessary, I will upload this logo file. 😅
> 
> <img alt="" height="200" src="https://camo.githubusercontent.com/e25cb5b81a028e92bbb5ba2f484534e26764b38005915c61fd5b3c814ae829a6/68747470733a2f2f692e696d6775722e636f6d2f456335585a70712e706e67"><img alt="" height="200" src="https://camo.githubusercontent.com/1370ed972c95e9902078500fff4cb18c564abef544248bc6a7216c63e70f3237/68747470733a2f2f692e696d6775722e636f6d2f38755a687844792e706e67"><img alt="" height="200" src="https://camo.githubusercontent.com/b6393842b4df06f29465d89e53e79f40ac651ff525575357c9cea623c29e812f/68747470733a2f2f692e696d6775722e636f6d2f7073644859426f2e706e67">

Honestly, that one's a better idea...

**Comment by FireMasterK** [comment]
I like these logos, but I don't feel they'll fit well in the current design though, maybe I can reconsider this when the website is redesigned.
