### ISSUE TITLE
Site sometimes does not load. Videos often does not play.

### ISSUE THREAD

**Issue by 1over137** [TeamPiped/Piped#1010]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Interface sometimes does not load. The console says:
Loading failed for the module with source “https://piped.notyourcomputer.net/assets/index.a41c18e7.js”.
The link when clicked opens a javascript file.
Also, many videos do not play.

### To Reproduce

Open https://piped.notyourcomputer.net/
You should either see a black screen or an empty trendings page. The page will not load. Even when it does, videos either do not play or load very slowly, to the point that videos are unwatchable. 
There is at least 400 Mbps connection speed between my computer and this server, and all other applications hosted on the server works normally. Example: https://piped.notyourcomputer.net/watch?v=WkgHkrM9fo0

### Expected behavior

It should load promptly and the videos should play.

### Logs/Errors

No errors on the backend, only access logs
The console sometimes says
`Loading failed for the module with source “https://piped.notyourcomputer.net/assets/index.a41c18e7.js”.`

**Comment by FireMasterK** [comment]
It's likely an issue with that instance, maybe it's a network/configuration error on their end.

Also, only using the official frontend and switching instances through the preferences page is supported.

**Comment by FireMasterK** [comment]
My best guess is that this could be an error on the reverse proxy, or an error in the client.
