### ISSUE TITLE
Missing Resolutions in API Response

### ISSUE THREAD

**Issue by allthrowaway** [TeamPiped/Piped#1016]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Certain videos miss some resolutions on Piped. For example, https://www.youtube.com/watch?v=BSu0u_XgbDo is available on YouTube at 1080p, but it’s only goes up to 720p on Piped.

### To Reproduce

1. Open https://www.youtube.com/watch?v=BSu0u_XgbDo
2. Note that 1080p is available.
3. Query Piped API: https://pipedapi.kavin.rocks/streams/BSu0u_XgbDo
4. Note that `quality` under `videoStreams` only goes up to 720p.

### Expected behavior

The Piped API should return a 1080p `quality` as well.

### Logs/Errors

N/A

**Comment by FireMasterK** [comment]
You're expecting to use the DASH manifest in videos when it's available. This is an OTF stream, so this is the only and best option.

 For example, in https://piped.kavin.rocks/watch?v=BSu0u_XgbDo you see the 1080p option as expected.
