### ISSUE TITLE
Import/Export Playlist

### ISSUE THREAD

**Issue by duyfken** [TeamPiped/Piped#1018]
We now have the ability to create playlists in Piped (#358)... it would be awesome to have the ability to import a playlist from a YouTube link (as they will of course have links containing the IDs of the vids) and also hopefully provide the ability to export playlists (for at least to other instances of Piped/derivatives and ideally for NewPipe as well).

I know I've got a playlist of over 1700 videos I've collated over at least 5 years and I don't want to have to recreate it when migrating away from goggle entirely, I doubt I'll be alone (previously mentioned by @trymeouteh in aforementioned issue)...

**Comment by trymeouteh** [comment]
This is needed for those who want to migrate to another Piped instance or wants to backup their playlists regularly in case their Piped instance goes offline.

**Comment by Bnyro** [comment]
Yes, that's quite easy:
1. You need to get an auth token, either from the dev tools local storage in your browser while being logged in or with an API request
2. Get a list of all available playlists at `/user/playlists/` by using the auth token as header (`Authentication`)
3. Fetch all returned playlists from the previous request individually to obtain a list of all videos and store them into a file

https://github.com/TeamPiped/Piped-Backend/blob/master/testing/api-test.sh#L116-L123 could be helpful.
