### ISSUE TITLE
FIrefox 100 and Subtitle Support

### ISSUE THREAD

**Issue by EdwardLangdon** [TeamPiped/Piped#1024]
In Firefox 100, It supports for Captions to be available in PiP mode, Add support for it in Piped.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/166626419-682c0d73-0b82-4f70-9219-f3f8d02e05a0.png)

I don't see such an option on YouTube.

**Comment by AcousticBirthdayCake** [comment]
If the captions don’t work in PiP mode:

Go to about:config

Find media.videocontrols.picture-in-picture.display-text-tracks.enabled

And make sure it is set to “true”

**Comment by FireMasterK** [comment]
Closing as it seems to work as expected now (maybe firefox changes something?):
![image](https://user-images.githubusercontent.com/20838718/175796390-f5b4ac9d-77b7-4dca-bb8d-cfb6a9b6ec56.png)

**Comment by EdwardLangdon** [comment]
@r-a-y It actual works on the official instance. Don't know about other instance though.

**Comment by r-a-y** [comment]
Thanks for checking, @EdwardLangdon. I think it might be a configuration issue on my end. It works on another Firefox install on another PC I tested.
