### ISSUE TITLE
Hotkey/Shortcut for playback speed

### ISSUE THREAD

**Issue by HyperOrnstein** [TeamPiped/Piped#1030]
Would it be possible to add Hotkeys/Shortcuts to change the playback speed?
On Youtube and Invidious it's ">" and "<".
That would be really nice, thanks for your great work!

**Comment by FireMasterK** [comment]
On piped, it's just shift + > or <

**Comment by HyperOrnstein** [comment]
Sorry, forgot to answer but this doesn't work for me on any systems I've tested it on...
Is this depending on keyboard-layouts? Mine would be QWERTZ.

**Comment by Bnyro** [comment]
It's actually `j` to seek backwards and `l` to seek forward.
