### ISSUE TITLE
Closed Captions on Onion instance doesn't work - CORS Allow Origin Not Matching Origin

### ISSUE THREAD

**Issue by barkoder** [TeamPiped/Piped#1043]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Closed Captions don't work on onion instance but work fine on https://piped.kavin.rocks

### To Reproduce

1. Open http://piped2bbch4xslbl2ckr6k62q56kon56ffowxaqzy42ai22a4sash3ad.onion/watch?v=mLJ1gyIzg78

2. Select any Language(English for example).

3. Notice that CC doesn't show up.

### Expected behavior

Captions should appear like in https://piped.kavin.rocks/watch?v=mLJ1gyIzg78

### Logs/Errors

Console shows `CORS Allow Origin Not Matching Origin`

### Browser, and OS with Version.

Tor Browser

**Comment by FireMasterK** [comment]
This has now been fixed.
