### ISSUE TITLE
Add new public instance

### ISSUE THREAD

**Issue by shimuldn** [TeamPiped/Piped#1054]
Front-end: https://piped.shimul.me/
API: https://pipedapi.shimul.me/
Proxy: https://pipedproxy.shimul.me/

Hosted in India with Cloudflare CDN

**Comment by FireMasterK** [comment]
Added, thanks for hosting an instance!

**Comment by shimuldn** [comment]
I have an unused server in another location. Do i have to create a fresh instance with another subdomain?
What is the bandwidth usages in a month if you have idea?

**Comment by FireMasterK** [comment]
> Do i have to create a fresh instance with another subdomain?

You can either do that or share the database (and perhaps maybe use cockroachdb) and load balance the backend servers.

> What is the bandwidth usages in a month if you have idea?

I'm not too sure but for the official instance, it's about 8TB a day!

**Comment by shimuldn** [comment]
> You can either do that or share the database (and perhaps maybe use cockroachdb) and load balance the backend servers.

I don't have a Cloudflare enterprise plan. Nginx load balance consume double bandwidth and request will go via the main server?

I did test 
https://www.cleverti.com/blog/how-to-build-a-load-balancer-based-on-user-s-location-with-nginx-and-geoip2/

Is there any option like API or Front-end can select different domain based on user location like `usproxy.piped.domain`, `euproxy.piped.domain`, `inproxy.piped.domain`.
