### ISSUE TITLE
[ Feature Request ] Importing Subscriptions from YouTube - CSV File Support

### ISSUE THREAD

**Issue by 8227846265** [TeamPiped/Piped#1058]
Please add support for CSV file from the export of subscription list from [takeout.google.com/takeout/custom/youtube](https://takeout.google.com/takeout/custom/youtube)

Upon checking, there's no way to get the JSON version of the takeout as there's only CSV option available.

**Comment by FireMasterK** [comment]
The CSV format is already supported.

**Comment by 8227846265** [comment]
@FireMasterK - It says on the UI though only support JSON
![image](https://user-images.githubusercontent.com/66582769/168544601-b21d7fac-5e22-44a9-9770-2ac0f67d5a29.png)

**Comment by 8227846265** [comment]
Alright. I uploaded the CSV file, and it was imported without any issue. Perhaps the instruction content could be updated.
