### ISSUE TITLE
[ Bug ] Picture-in-Picture Deleting Video's Media Control

### ISSUE THREAD

**Issue by 8227846265** [TeamPiped/Piped#1059]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When you open a video and load it on Picture-in-Picture (video). Then go to Homepage > then go back to the same video. The PiP will be gone and so is the video's media control.

### To Reproduce

Watch the video below.
* https://streamable.com/d4ao3a

### Expected behavior

The following:
* The PiP should not go missing.
* If the video is opened again. The media control should be available.

### Logs/Errors

N/A

### Browser, and OS with Version.

Windows 11 - Brave Browser

**Comment by FireMasterK** [comment]
Not a bug, since you are navigating away from the video, this should be the expected behavior (unless we get a popup player like youtube).

**Comment by 8227846265** [comment]
Oh right. Understood.

**Comment by 8227846265** [comment]
@FireMasterK - I think this can be re-opened. I forgot that the main issue here is that after the PiP went missing when navigating outside. The media control also went missing.

I think that's a bug because you cannot control the video playback or audio if this happens.

**Comment by 8227846265** [comment]
Upon reproducing. You can still control by keyboard but not with mouse since the media controls that appears when you hover your mouse on the video is not available anymore after the bug happens.
