### ISSUE TITLE
Password lost

### ISSUE THREAD

**Issue by Tommy-01** [TeamPiped/Piped#1075]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Hi,
i have a question and find no other place to ask.
I have lost my password for my Libretube Account.
Is there a way to get the password or to reset it?

The app is still logged in. Maybe i can export it from the app?

Thank you!

I already posted this question there --> https://github.com/libre-tube/LibreTube/issues/274#issuecomment-1133726466
They suggest to try it here.

### To Reproduce

a

### Expected behavior

b

### Logs/Errors

c

### Browser, and OS with Version.

Android 12

### Additional context

Sry if i'm wrong here!

**Comment by nin0-dev** [comment]
On LibreTube, what instance you use?
If it's `kavin.rocks`, then they don't do password resets on this one, sorry.

**Comment by Tommy-01** [comment]
Yes it's kavin.rocks. I will open a new account.
Thank you!
