### ISSUE TITLE
Login/Register Not Working

### ISSUE THREAD

**Issue by khusroohayat** [TeamPiped/Piped#1081]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When try i login/register it is giving me 500, with the popup appearing in screenshot below

![image](https://user-images.githubusercontent.com/5275996/169819293-912f154d-64e2-42cf-b0a6-914c92a03875.png)

### To Reproduce

1. Open Url https://piped.kavin.rocks/login or https://piped.kavin.rocks/register
2. Enter login details
3. Popup show error

### Expected behavior

It should login and take me to feed page

### Logs/Errors

{"error":"javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)\n\tat org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1626)\n\tat org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1659)\n\tat org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.uniqueResult(CriteriaQueryTypeQueryAdapter.java:81)\n\tat me.kavin.piped.utils.ResponseHelper.registerResponse(ResponseHelper.java:641)\n\tat me.kavin.piped.ServerLauncher.lambda$mainServlet$23(ServerLauncher.java:215)\n\tat io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)\n\tat io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection\n\tat org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:111)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)\n\tat org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2122)\n\tat org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2059)\n\tat org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)\n\tat org.hibernate.loader.Loader.doQuery(Loader.java:956)\n\tat org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)\n\tat org.hibernate.loader.Loader.doList(Loader.java:2868)\n\tat org.hibernate.loader.Loader.doList(Loader.java:2850)\n\tat org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)\n\tat org.hibernate.loader.Loader.list(Loader.java:2677)\n\tat org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)\n\tat org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)\n\tat org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)\n\tat org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459)\n\tat org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)\n\tat org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)\n\t... 9 more\nCaused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.\n\tat com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)\n\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)\n\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)\n\tat com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)\n\tat org.hibernate.hikaricp.internal.HikariCPConnectionProvider.getConnection(HikariCPConnectionProvider.java:77)\n\tat org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)\n\t... 29 more\n","message":"org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection"}

### Browser, and OS with Version.

Microsoft Edge

**Comment by MaseSpace** [comment]
I have this exact issue as well.. on my devices that are still signed in the feed page does not load.

**Comment by khusroohayat** [comment]
Yes, it is working fine now. closing the issue. Thanks
