### ISSUE TITLE
Tabbing out while a video plays slows down other applications.

### ISSUE THREAD

**Issue by Flam3z** [TeamPiped/Piped#1084]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When playing a video and tabbing to another application (i.e. playing a game) it tends to stutter alot and when tabbing back into piped the video itself freeze frame.

### To Reproduce

1. Open any video
2. Tab to another application whether it be a game or another video.

### Expected behavior

to be able to change tabs without making other applications slow down.

### Browser, and OS with Version.

Brave 1.39.111 | Windows 10 19044.1706

### Additional context
If more information is needed please let me know.
_No response_

**Comment by FireMasterK** [comment]
I think this is a browser/hardware issue since I was unable to reproduce this. Playing a video will cause some slight slowdowns, [just like how YouTube does](https://piped.kavin.rocks/watch?v=Nd9-OtzzFxs).
