### ISSUE TITLE
[Bug] Logout Option Missing

### ISSUE THREAD

**Issue by Abystus** [TeamPiped/Piped#1093]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

While logged in, there doesn't seem to be a visible option to log out.

### To Reproduce

1. Log into the site
2. Attempt to find log out option

### Expected behavior

An option should be preset (most likely to the right of "Preferences Playlists Feed" in the upper right of the site) to log out of the current session.

### Logs/Errors

None

**Comment by EdwardLangdon** [comment]
It ain't a bug. @FireMasterK didn't add it at start. It is in the works to add.
