### ISSUE TITLE
Videos not playing in Ungoogled Chromium/Fedora 36

### ISSUE THREAD

**Issue by brner** [TeamPiped/Piped#1096]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Certain videos like https://piped.kavin.rocks/watch?v=-KYbHJulEo8 https://piped.kavin.rocks/watch?v=RrRpXs2pkzg and other videos from the channels doesn't play. 

These are from my subscription list and there maybe other videos.

### To Reproduce

Open https://piped.kavin.rocks/watch?v=-KYbHJulEo8 or https://piped.kavin.rocks/watch?v=RrRpXs2pkzg

Videos buffer for a while. Buffering stops and wont play.

### Expected behavior

Videos should play

### Logs/Errors

No logs

### Browser, and OS with Version.

Ungoogled Chromium 102.0.5005.61 with Fedora 36

### Additional context

Tried with Flatpak and Appimage versions of the browser

**Comment by FireMasterK** [comment]
I could not replicate with Brave and Vanilla Chromium on Arch.

Closing, as it was likely a temporary issue with LBRY/Odysee in the past, or something else on your end.
