### ISSUE TITLE
[Feture Request] Hold logged users settings server side

### ISSUE THREAD

**Issue by Axeltherabbit** [TeamPiped/Piped#1097]
I clear my cookies and cache when I close the browser so I have to change the my settings everytime I login.
I have to also change my settings everytime I login from a new device.
User settings are not privacy sensible so it should not be a issue

**Comment by EdwardLangdon** [comment]
Rephrasing your comment would be great. It's hard to understand.

**Comment by FireMasterK** [comment]
Duplicate of #496
