### ISSUE TITLE
Piped logo concept

### ISSUE THREAD

**Issue by pluja** [TeamPiped/Piped#11]
I thought it would be cool for Piped to have a nice logo. Maybe you already have something in mind but I designed this as a concept logo. I can send you the .psd (Photoshop) and .svg if you like it or want to modify it.

Don't worry if you don't like it, I enjoy making these.

<img src="https://i.imgur.com/t9Fo0pl.png" width=350>
<img src="https://i.imgur.com/k5es23z.png" width=350>

**Comment by FireMasterK** [comment]
Oh wow, this looks great! I do love how the letters are literally piped, I really like the second image, it seems to fit well in the dark theme, but I do feel these icons seem a bit too simple, maybe you could add a gradient shade for the colors?

**Comment by pluja** [comment]
Yeah, of course. I'll do it later!

**Comment by pluja** [comment]
Maybe like this?
<img src="https://i.imgur.com/4UxzEaZ.png" width=350>

**Comment by FireMasterK** [comment]
Looks great!

**Comment by pluja** [comment]
I think this should be a final version:
<img src="https://i.imgur.com/GrV60H6.png" width=350>

**Comment by FireMasterK** [comment]
Closing as the logo have been added, thanks again!
