### ISSUE TITLE
Update public instance

### ISSUE THREAD

**Issue by shimuldn** [TeamPiped/Piped#1100]
New details
Front-end: https://piped.shimul.me/
API: https://api-piped.shimul.me/
Proxy: https://proxy-piped.shimul.me/

Hosted in JP, IN, US, DE, SA with Cloudflare CDN
Using Geo based 307 URL rewrite for api-piped.shimul.me, but sharing the same DB so user login and count are same for all apis url.

Old Details:
```
Front-end: https://piped.shimul.me/
API: https://pipedapi.shimul.me/
Proxy: https://pipedproxy.shimul.me/

Hosted in India with Cloudflare CDN
```

**Comment by FireMasterK** [comment]
The API redirects me to https://eu-api-piped.shimul.me/, which isn't resolving for me.

**Comment by shimuldn** [comment]
Fixed not resolving issue.
Not ZA, it's SA (Saudi Arabia)

**Comment by FireMasterK** [comment]
> Not ZA, it's SA (Saudi Arabia)

Updated :+1:

**Comment by shimuldn** [comment]
Thanks
