### ISSUE TITLE
Player (sometimes) not playing livestream video feeds

### ISSUE THREAD

**Issue by hugoamvieira** [TeamPiped/Piped#1106]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When opening livestreams, sometimes the player doesn't play the video feed and just hangs forever. When inspecting the network traffic, the video data seems to be making its way from `ytproxy` to the browser. Upon visiting the official YouTube website, the feed plays as normal there, so it's not a livestream problem.

This doesn't always happen - In fact it doesn't happen most times. I haven't been able to understand what triggers this problem, sadly.

### To Reproduce

1. Open livestream (I tried with https://piped.kavin.rocks/watch?v=QOPPIf7J05c and my local instance equivalent, although this will probably be useless by the time you read it sadly)
2. The player goes black and there's a loading circle forever / video feed never actually shows.
3. Observe network activity - `ytproxy` is returning 200 OK with video data, but the player doesn't seem to be playing.

### Expected behavior

Livestream plays correctly.

### Logs/Errors

No errors or special logs other than the access log in Piped frontend in my deployment. Frontend displays 200 OK calls, no console errors either.

### Browser, and OS with Version.

Tried with Firefox and Chromium on Windows and Fedora Linux, as well as Safari on iOS. All display the same behaviour.

### Additional context

On my deployment, I tried restarting all the bits in the chain (piped frontend, piped backend and ytproxy) as well as hard refreshing each browser between retries, but the problem didn't go away.

On Chromium, it seems to eventually stop downloading segments, as if it knew it wasn't playing them.

On Firefox, it just gets the latest playlist information and keeps downloading the segments forever, as if it were playing the feed normally.

**Comment by hugoamvieira** [comment]
Update: After a while not working, eventually it randomly started working again (both locally on my instance and on the official one). I have no idea why.

**Comment by FireMasterK** [comment]
Is this no longer an issue? Also, we now use a new [Rust-based proxy](https://github.com/TeamPiped/piped-proxy) instead of `ytproxy`.
