### ISSUE TITLE
Setup PWA

### ISSUE THREAD

**Issue by xmha97** [TeamPiped/Piped#1121]
I want to install piped site as an app on Windows (Edge) and Android (Chrome)
Please setup PWA
Similar: #713

**Comment by datanomi** [comment]
This is already possible on both Edge and Chrome
![kuva](https://user-images.githubusercontent.com/76632422/173158102-3e25be52-4656-4fcb-b103-2bdaa9780ecd.png)
![Screenshot_20220611-012246](https://user-images.githubusercontent.com/76632422/173158355-972a4cf2-6da5-4841-830e-d4c2e10a3f8a.jpg)

**Comment by datanomi** [comment]
Hmm, testing it on the official instance doesn't seem to work :/ 
For some reason it works on my instance.

**Comment by FireMasterK** [comment]
I'm closing this as I can't seem to reproduce this, even on the official instance.
I tried Brave on Linux and Android.
