### ISSUE TITLE
Feature Request: Button that resets all settings back to default in Preferences page for Account Users

### ISSUE THREAD

**Issue by Pentaphon** [TeamPiped/Piped#1122]
Let's say I'm logged in with an account. 

There's no easy way to go back to default settings when you are logged in so a button that resets your preferences would be great.

**Comment by Bnyro** [comment]
Preferences are not stored on the account yet, they are only stored locally on your machine.

**Comment by Pentaphon** [comment]
> Preferences are not stored on the account yet, they are only stored locally on your machine.

A reset button should work in any case, no matter if they are stored or not. Thanks for looking into this. It's useful to be able to go back to default since we have so many preferences and probably more to come.
