### ISSUE TITLE
Feature request: close registration  

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [TeamPiped/Piped#1123]
Hi, I wonder if there a way to close the ability to create new accounts? I want to self-host piped but in same time I want to make it private only me who can sign up

**Comment by arisuv** [comment]
I think you should make a fork and disable this feature. then, host your version

**Comment by EsmailELBoBDev2** [comment]
oh okay, which part can I change?? the project seems big and I'm newbie

**Comment by EsmailELBoBDev2** [comment]
Also why not? invidious got that feature...

**Comment by FireMasterK** [comment]
The option is present as a configuration option: https://github.com/TeamPiped/Piped-Backend/blob/master/config.properties#L26-L27

**Comment by EsmailELBoBDev2** [comment]
Thanks
I already looked into the file but did not find anything about it (docker generated it!) so maybe let docker generate full copy instead of this?

**Comment by FireMasterK** [comment]
They've now been added in https://github.com/TeamPiped/Piped-Docker/commit/c4fe0c1ac4f0e93e536e14f16b70956275c9ea23!

Changing config properties still need to be better implemented, however. (perhaps in the script itself)

**Comment by EsmailELBoBDev2** [comment]
I know it's out of scope but seems I created DB and can't remove it :)

I noticed I had to change "changeme" password but clearly I did not notice it and I tried to take the volume down and clean everything, even removed docker folder and recloned it from git but seems the DB exist somewhere and I ran `docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once piped-frontend piped-backend ytproxy varnish nginx caddy postgres watchtower` but no luck too

**Comment by FireMasterK** [comment]
Just delete the data folder. Ensure the password is same as the init password in postgres's docker-compose.

**Comment by EsmailELBoBDev2** [comment]
oh, I forgot to look up in docker-compose. this explains a lot! thanks agian

**Comment by EsmailELBoBDev2** [comment]
Oh right I forgot to mention, I want to add my instance: https://piped.esmailelbob.xyz/ 

It's hosted in Canada and no CDN

**Comment by FireMasterK** [comment]
Your instance has been added! Thanks for hosting an instance :D

**Comment by EsmailELBoBDev2** [comment]
Your welcome and reply in mastodon xD

also it was nice move to rickroll me by visiting your site....

**Comment by EsmailELBoBDev2** [comment]
Hi again can you add my tor version of piped? http://piped.lqs5fjmajyp7rvp4qvyubwofzi6d4imua7vs237rkc4m5qogitqwrgyd.onion/home

**Comment by FireMasterK** [comment]
The suggested way to do that would be to create a copy of the services in the `docker-compose.yml`, and copy the config files, however setting it up isn't easy, I'll add support to the script soon.

Currently, the instances API doesn't support onion URLs either, I'll need to add support for this too.

Also: Your instance seems to go down from time to time and starts failing the healthcheck: https://pipedapi.esmailelbob.xyz/healthcheck, which is likely caused by a database issue.

**Comment by EsmailELBoBDev2** [comment]
> Also: Your instance seems to go down from time to time and starts failing the healthcheck: https://pipedapi.esmailelbob.xyz/healthcheck, which is likely caused by a database issue.

Because I restart it hourly, I noticed when I leave it running I get DB issues indeed
