### ISSUE TITLE
[Question] Official onion API instance? 

### ISSUE THREAD

**Issue by LacledeUn** [TeamPiped/Piped#1125]
The official instant has an onion domain and is convenient to use from a browser. But it was not possible to find an onion address to use with the API.

Does pipedapi.kavin.rocks have an onion mirror?

**Comment by FireMasterK** [comment]
Yes, it is http://pipedihonqyp5fh3ffn5c7i2zlg4lljc4gorefhpydtqiapewy5gprad.onion

**Comment by LacledeUn** [comment]
> Yes, it is http://pipedihonqyp5fh3ffn5c7i2zlg4lljc4gorefhpydtqiapewy5gprad.onion

Thanks!

**Comment by DUOLabs333** [comment]
It seems that it does not work
