### ISSUE TITLE
shorts thumbnail is vertical and too large

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#1126]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The thumbnail is vertical and and too large when the video is a "YouTube shorts" video.

![image](https://user-images.githubusercontent.com/58657617/173254552-0ac7312d-0a1e-4dd1-9144-57e5423d2bc6.png)

### To Reproduce

1. Open this channel https://piped.kavin.rocks/channel/UCPnLtG_pVQAcNGYGGLBEFyA
2. You’ll see that shorts thumbnail is large

scroll down a bit and you’ll see non-shorts video and the difference with shorts, like the screenshot above

### Expected behavior

all thumbnails are rectangle

### Logs/Errors

.

**Comment by FireMasterK** [comment]
Closing this with 187804f9a1c286988f6b5b83f0a5ea5b264248c2.

(There's a bug though when a short is longer than 1 minute, it would display uglily like before)

Potential solutions are either adding a way to detect shorts in NewPipeExtractor, or increase the threshold (however the drawback is, some videos will be incorrectly flagged as shorts then)

**Comment by B0pol** [comment]
It’s not fixed. It seems like it has been fixed on trending page but not on channel page

**Comment by IronMaltese** [comment]
It seems like this issue can be closed
