### ISSUE TITLE
Embed youtube videos

### ISSUE THREAD

**Issue by Duckbilled** [TeamPiped/Piped#113]
Is it possible to use Piped to replace embedded videos?

**Comment by FireMasterK** [comment]
It's currently not, but I'll see if this can done in the future.

This will likely be implemented on a separate hostname.

**Comment by moriel5** [comment]
This will certainly be great, especially together with Privacy Redirect.

**Comment by FireMasterK** [comment]
Closing this with 4ef653df311a0e2ea3c8ee0619176a658e809316.
