### ISSUE TITLE
Improving chapters layout

### ISSUE THREAD

**Issue by kskarthik** [TeamPiped/Piped#1133]
Hi, I am experimenting with horizontal chapters layout

They are scrollable horizontally both on desktop on mobile view 
I would like to hear inputs on these!

![image](https://user-images.githubusercontent.com/11899221/174087319-8b4e43bc-7dd2-43e9-a0f9-d4fedc2ee312.png)

**Comment by FireMasterK** [comment]
These look really nice!

I would just limit the size of title of each chapter, so it looks more uniform

**Comment by kskarthik** [comment]
> I would just limit the size of title of each chapter, so it looks more uniform

yeah working on it now!

**Comment by kskarthik** [comment]
here you go @FireMasterK !
![image](https://user-images.githubusercontent.com/11899221/174104285-09498de2-4019-40fe-9f9b-ef0ddfe48723.png)

**Comment by FireMasterK** [comment]
Looks good! I would just make the thumbnail use the box fully

**Comment by kskarthik** [comment]
also, how do you think about this layout of chapters

![image](https://user-images.githubusercontent.com/11899221/174134180-166f5df5-6125-4959-b7cc-011edb596559.png)

**Comment by IceDBorn** [comment]
Looks great!

**Comment by kskarthik** [comment]
one more improvement

![image](https://user-images.githubusercontent.com/11899221/174144193-9c1824cd-96f9-4598-b06c-c851c03cb669.png)

**Comment by IceDBorn** [comment]
You stretched them?

**Comment by kskarthik** [comment]
@IceDBorn you mean stretched what?

**Comment by IceDBorn** [comment]
The thumbnails

**Comment by IceDBorn** [comment]
Why is this an issue and not a pr btw?

**Comment by EdwardLangdon** [comment]
It would be better if the layout was to the right side of the player mimicking youtube with the option of theatre mode like in YouTube to get the old behaviour.
