### ISSUE TITLE
Another Layout for Chapters

### ISSUE THREAD

**Issue by EdwardLangdon** [TeamPiped/Piped#1142]
It would be better if the New Chapter layout was to the right side of the player mimicking youtube with the option of theatre mode like in YouTube to get the old behaviour.

**Comment by kskarthik** [comment]
@EdwardLangdon  Yup, Added in #1149 

You could close it now

**Comment by FireMasterK** [comment]
This is now complete!

Thanks to @kskarthik!

**Comment by sxe** [comment]
Maybe I am missing something but I can't seem to find a way to disable chapters. I don't use them, so it's just wasted space and a distraction for me. The initial comment asked for a theater mode to handle it similar to YouTube. Is there something like that in place? Or any other way to disable it?

**Comment by kskarthik** [comment]
@sxe there is no user option to disable chapters ATM

**Comment by sxe** [comment]
> @sxe there is no user option to disable chapters ATM

Thanks for the reply. May I create a feature request for it?

**Comment by kskarthik** [comment]
@sxe ok you could
