### ISSUE TITLE
Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by shimuldn** [TeamPiped/Piped#1146]
```
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 482

Varnish cache server
```

From logs:
`nginx           | 172.27.0.1 - - [20/Jun/2022:14:05:49 +0000] "GET /trending?region=US HTTP/1.0" 503 280 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.4972.0 Safari/537.36"`

**Comment by shimuldn** [comment]
Temporary fix for the problem.
```
nano /home/ubuntu/health_Check_piped.sh
[ $(curl -LI "https://{your api url}/feed?$(date +%s)" -o /dev/null -w '%{http_code}\n' -s) != "200" ] && /usr/bin/docker restart varnish
```

and then a cronjob to check the status in very 5 minutes
`crontab -e`
`*/5 * * * * /home/ubuntu/health_Check_piped.sh >/dev/null 2>&1`

**Comment by FireMasterK** [comment]
This should now be fixed with https://github.com/TeamPiped/Piped-Backend/commit/943e4a3de8d15be42b3eddefd90176412a434c35.

**Comment by davidtavarez** [comment]
> Temporary fix for the problem.
> 
> ```
> nano /home/ubuntu/health_Check_piped.sh
> [ $(curl -LI "https://{your api url}/feed?$(date +%s)" -o /dev/null -w '%{http_code}\n' -s) != "200" ] && /usr/bin/docker restart varnish
> ```
> 
> and then a cronjob to check the status in very 5 minutes `crontab -e` `*/5 * * * * /home/ubuntu/health_Check_piped.sh >/dev/null 2>&1`

This did not work. I followed this guide: https://piped-docs.kavin.rocks/docs/self-hosting/

**Comment by FireMasterK** [comment]
```sh
git pull
./configure-instance.sh
```

That should fix things since varnish is not used anymore.

**Comment by davidtavarez** [comment]
Maybe docker images are not updated. I am using docker-compose.

**Comment by davidtavarez** [comment]
> That should fix things since varnish is not used anymore.

Varnish is used here https://github.com/TeamPiped/Piped-Docker/blob/main/template/docker-compose.caddy.yml

**Comment by davidtavarez** [comment]
Just follow the guide https://piped-docs.kavin.rocks/docs/self-hosting/#docker-compose-caddy-aio-script

it won't work.

**Comment by davidtavarez** [comment]
Opened a new issue https://github.com/TeamPiped/Piped/issues/1648
