### ISSUE TITLE
Topic/Audio Channels won't play

### ISSUE THREAD

**Issue by SecularSteve** [TeamPiped/Piped#1150]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

If YT link is an Auto-generated Audio/Topic, it won't play no matter what.
It just remains there loading forever.

![Screenshot_20220624-231118~2](https://user-images.githubusercontent.com/33793273/175668065-c5ad89da-2666-4c00-b87a-36612dde70ad.png)
![Screenshot_20220624-231050~2](https://user-images.githubusercontent.com/33793273/175668067-bed33288-431a-49bb-955c-1471aea53b20.png)

### To Reproduce

1. Open a YouTube Audio Link.
(example: https://piped.kavin.rocks/watch?v=j_nEdStgew0)
2. Attempt to Play.

### Expected behavior

To simply play with no issues, nor infinite load times.

### Logs/Errors

n/a

### Browser, and OS with Version.

Firefox Mobile 101.2.0

### Additional context

This doesn't happen on Invidious, or NewPipe.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/175719294-b88aac68-2bf3-4498-a35f-8cb2df40ed72.png)

Plays fine here, can you see your browser's dev tools for errors?

**Comment by Nizami20052022** [comment]
When will the video preview blur not be resolved?

**Comment by SecularSteve** [comment]
I just tried it on other instances, and found out that this only happens with the official one (at least with me).

I think it's a ping/time-out issue because of different regions.

**Comment by FireMasterK** [comment]
Where are you located/which continent? I could try the servers there then

**Comment by SecularSteve** [comment]
Europe...

**Comment by FireMasterK** [comment]
Thanks, I have identified the problem, and I'm looking at ways I could resolve it.

**Comment by FireMasterK** [comment]
This has now been fixed.
