### ISSUE TITLE
Subscriptions without accounts

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#1158]
I've got an idea on how to implement this :D

**Comment by FireMasterK** [comment]
Yes, but backend work is required to keep the required channels up-to-date too.

**Comment by FireMasterK** [comment]
Implemented at the backend with https://github.com/TeamPiped/Piped-Backend/pull/323.

**Comment by IronMaltese** [comment]
Is this feature going to result in the addition of per-channel RSS feeds without an account on Piped.Kavin.Rocks
