### ISSUE TITLE
Some videos don't show up in feed from subscribed channels

### ISSUE THREAD

**Issue by helpthemfix** [TeamPiped/Piped#1164]
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I noticed multiple channels don't show in my feed on the main instance. for example this video:
`https://piped.kavin.rocks/watch?v=6E3ZS1b5SQA` shows up in my feed on the `mha.fi` instance but not the main one.

### To Reproduce

1. Subscibe to `https://piped.kavin.rocks/channel/UCWPJwoVXJhv0-ucr3pUs1dA` or `https://piped.kavin.rocks/channel/UC1dKnMpbZ-XDp_OhcSWoXoA`
2. Go to feed
3. new videos are not listed in the feed

### Expected behavior

New videos should be listed in the feed just as before. The problem is new.

### Logs/Errors

N/A

### Browser, and OS with Version.

Librewolf 101
Windows 10

**Comment by Keefaetana** [comment]
I see this on the jae.fi instance as well. I noticed missing videos in my feed, and then decided to confirm by going to a channel's home page (e.g. https://yt.jae.fi/channel/UCI3DTtB-a3fJPjKtQ5kYHfA ). After doing so, the most recent videos pop up to my feed - for that specific channel. If I want to see *all* new videos from all my subscriptions in the feed page, I'll have to open every single subscribed channel's home page first.

**Comment by helpthemfix** [comment]
> I see this on the jae.fi instance as well. I noticed missing videos in my feed, and then decided to confirm by going to a channel's home page (e.g. https://yt.jae.fi/channel/UCI3DTtB-a3fJPjKtQ5kYHfA ). After doing so, the most recent videos pop up to my feed - for that specific channel. If I want to see _all_ new videos from all my subscriptions in the feed page, I'll have to open every single subscribed channel's home page first.
> 
> Edit: Waterfox 4.1.3.1, Windows 10.

Wow, that's a nice workaround unitl @FireMasterK looks into it.

**Comment by EdwardLangdon** [comment]
This issue is also in Piped Clients such as Libretube. I think this is a backend issue rather than frotend issue.

**Comment by Keefaetana** [comment]
Weirdly enough, the issue *seems* to have resolved itself for me. At least for the time being. Since I see nothing in the commits that would seem to have been the fix, I'm very cautious to say it's actually fixed.

**Comment by FireMasterK** [comment]
> Weirdly enough, the issue _seems_ to have resolved itself for me. At least for the time being. Since I see nothing in the commits that would seem to have been the fix, I'm very cautious to say it's actually fixed.

The fix was https://github.com/TeamPiped/Piped-Backend/commit/3a009407ad16fca792a16008e1b1288229dc94ed.

Explanation: The pubsub timers would never end up being registered since the server thread was blocking the main thread, so this ran the server on a new thread so the main thread could register the timers.

The reason why it still happens occasionally is because of an unrelated plaguing connection pooling issue, where somehow no connections are returned by hikaricp.

**Comment by Keefaetana** [comment]
> > Weirdly enough, the issue _seems_ to have resolved itself for me. At least for the time being. Since I see nothing in the commits that would seem to have been the fix, I'm very cautious to say it's actually fixed.
> 
> The fix was [TeamPiped/Piped-Backend@3a00940](https://github.com/TeamPiped/Piped-Backend/commit/3a009407ad16fca792a16008e1b1288229dc94ed).
> 
> Explanation: The pubsub timers would never end up being registered since the server thread was blocking the main thread, so this ran the server on a new thread so the main thread could register the timers.
> 
> The reason why it still happens occasionally is because of an unrelated plaguing connection pooling issue, where somehow no connections are returned by hikaricp.

I stand corrected. Thank you for the explanation!

**Comment by EdwardLangdon** [comment]
I still don't see 1 channel in the feed.
