### ISSUE TITLE
The Trending videos seems weird

### ISSUE THREAD

**Issue by prateekmedia** [TeamPiped/Piped#1165]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The trending videos in Piped instance looks very different and weird compared to official Youtube ones.

### To Reproduce

![Screenshot from 2022-06-29 15-07-32](https://user-images.githubusercontent.com/41370460/176405674-a0f61f4a-2f8c-4091-8763-098141104066.png)

### Expected behavior

The trending videos should be like youtube:
![image](https://user-images.githubusercontent.com/41370460/176405558-5cbef19c-f1ca-45f6-9e53-0792d84d7b49.png)

### Logs/Errors

None

### Browser, and OS with Version.

Firefox Arch Linux

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/180015620-155806c2-b348-4fd2-8fe2-1579d77664bc.png)
![image](https://user-images.githubusercontent.com/20838718/180015686-985788de-79da-4327-b90e-cc956ef29046.png)

It looks as expected to me. (Keep in mind that trending feeds are cached for one hour, in my screenshot the cached response's age was 1980 seconds)
