### ISSUE TITLE
Cant load anything on piped

### ISSUE THREAD

**Issue by rubynt** [TeamPiped/Piped#1169]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

In this example i used this video: https://piped.kavin.rocks/watch?v=gMZTAvBYPxs
and here is how it looks for me:
![cantload](https://user-images.githubusercontent.com/75886208/176561351-89611b52-06af-491f-8dec-69b28a137018.png)
Even i cant open the feed, and it doesnt work on other instances

### Expected behavior

Load all of the data and video.

### Logs/Errors

```
Access to fetch at 'https://pipedapi.kavin.rocks/sponsors/gMZTAvBYPxs?category=%5B%22sponsor%22%2C%22interaction%22%2C%22selfpromo%22%2C%22music_offtopic%22%5D' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/sponsors/gMZTAvBYPxs?category=%5B%22sponsor%22%2C%22interaction%22%2C%22selfpromo%22%2C%22music_offtopic%22%5D:1          Failed to load resource: net::ERR_FAILED
main.js:109                  Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (main.js:109:20)
    at Proxy.fetchSponsors (WatchVideo.vue:309:31)
    at Proxy.getSponsors (WatchVideo.vue:383:22)
    at Proxy.mounted (WatchVideo.vue:281:14)
    at tr (runtime-core.esm-bundler.js:155:22)
    at yt (runtime-core.esm-bundler.js:164:21)
    at t.__weh.t.__weh (runtime-core.esm-bundler.js:2687:29)
    at Ru (runtime-core.esm-bundler.js:358:32)
    at Lu (runtime-core.esm-bundler.js:403:9)
watch:1 Access to fetch at 'https://pipedapi.kavin.rocks/streams/gMZTAvBYPxs' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/streams/gMZTAvBYPxs:1          Failed to load resource: net::ERR_FAILED
main.js:109                  Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (main.js:109:20)
    at Proxy.fetchVideo (WatchVideo.vue:306:25)
    at Proxy.getVideoData (WatchVideo.vue:326:24)
    at Proxy.mounted (WatchVideo.vue:249:14)
    at tr (runtime-core.esm-bundler.js:155:22)
    at yt (runtime-core.esm-bundler.js:164:21)
    at t.__weh.t.__weh (runtime-core.esm-bundler.js:2687:29)
    at Ru (runtime-core.esm-bundler.js:358:32)
    at Lu (runtime-core.esm-bundler.js:403:9)
watch:1 Access to fetch at 'https://pipedapi.kavin.rocks/comments/gMZTAvBYPxs' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/comments/gMZTAvBYPxs:1          Failed to load resource: net::ERR_FAILED
main.js:109                  Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (main.js:109:20)
    at Proxy.fetchComments (WatchVideo.vue:320:25)
    at Proxy.getComments (WatchVideo.vue:386:18)
    at Proxy.mounted (WatchVideo.vue:282:80)
    at tr (runtime-core.esm-bundler.js:155:22)
    at yt (runtime-core.esm-bundler.js:164:21)
    at t.__weh.t.__weh (runtime-core.esm-bundler.js:2687:29)
    at Ru (runtime-core.esm-bundler.js:358:32)
    at Lu (runtime-core.esm-bundler.js:403:9)
```

### Browser, and OS with Version.

Chromium Version 103.0.5060.53 (Official Build, ungoogled-chromium) (64-bit) on Void Linux without any addons enabled and cache-cookies cleared. 

### Additional context

The website doesnt work even in incognito mode.

**Comment by rubynt** [comment]
Having the same issue on Firefox 101.0.1 (64-bit) on Void Linux and with its patches. Cant copy paste errors from Firefox because I dont know how.

**Comment by AcousticBirthdayCake** [comment]
Happens to me too on Safari (iOS 15.5) and Firefox. Sometimes for me, the videos may load if you do a hard refresh (ctrl+shift+r).

**Comment by open-meadow** [comment]
I'm having the same issue on Microsoft Edge (103.0.1264.37), Windows 10

**Comment by rogerclotet** [comment]
Same issue here, using Firefox 102.0 (64-bit) on Ubuntu Linux 22.04.

It's not the first time it happens, after a while (1 or 2 days) it usually starts working again, this time it's been like this for 2 days already.

**Comment by rubynt** [comment]
My friend on windows now cant view it

**Comment by rogerclotet** [comment]
Strangely enough, it started working again this afternoon both on desktop and mobile. Now it seems to work perfectly for me.

**Comment by AcousticBirthdayCake** [comment]
It’s working again for me. I think we should close this issue soon.

**Comment by jckso** [comment]
Subscriptions not working now. Can't view feed or manage subscriptions.

**Comment by EdwardLangdon** [comment]
@jckso You are damn right. Feed isn't working.

**Comment by IceDBorn** [comment]
Feed is not working for me too.

**Comment by ngoomie** [comment]
Also been having issues with the feed pretty much all day except for once, no errors are printed out in the console when I attempt to load my feed so there's unfortunately nothing helpful I can paste here. I'm using Firefox 99.0.1 on EndeavourOS, though I suspect that information isn't going to be very helpful since it doesn't seem to be anything about my setup that's causing this to happen.

**Comment by rogerclotet** [comment]
Not working for me again either.

**Comment by PORTB** [comment]
I'm also having this issue. It's happening for invidious too.

**Comment by lordkitsuna** [comment]
This has been happening frequently on my self hosted instance, i have to restart the docker and then it will work again for a short time.

**Comment by deroverda** [comment]
Same issues here. Feed completely empty on windows Firefox and iOS safari. What's the issue?

**Comment by deroverda** [comment]
Randomly worked now on iOS safari. But when I shut it down and re-opened it the feed is empty. Same behavior on Firefox windows. Seems like it's working 1/100 times. Anyway, hope it gets fixed soon.

**Comment by IronMaltese** [comment]
Piped is completely unusable on iOS since this problem happens much more times than it actually works

**Comment by aleandroct** [comment]
same for me on lg tv with webos 6.0. I've solved in a strange way. The video start only if i press  "<-"  on browser and then again   
   "->" when the page reload the video start. If you press f5, for manually reload, don't work

**Comment by ngoomie** [comment]
Was working for a good couple of days, and now it's back to how it was before
