### ISSUE TITLE
Feed goes blank when switching instances

### ISSUE THREAD

**Issue by EdwardLangdon** [TeamPiped/Piped#1184]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Go to Preferences and Change Instance selection to other instance for video fetching. Go to the feed page. The Frontend will show the account logged out and won't load any videos in Feed.

### To Reproduce

1. Go to piped.kavin.rocks/preferences
2. Change Instance
3. Come back to Piped.kavin.rocks/feed
4. Frontend will prompt you to login. On Logging in, It will tell the credentials as incorrect.
5. Need to switch back to the Domain's instance in preferences to see videos in /feed page.

### Expected behavior

The Video should be shown irrespective of the Instance selected in preferences.

### Logs/Errors

Not Available

### Browser, and OS with Version.

Firefox 102, Windows 11

**Comment by kinaskidor** [comment]
Same issue for Firefox 102, 64-bit

**Comment by FireMasterK** [comment]
Piped doesn't support switching authentication and fetching instances separately unlike Libretube. It should be easy to implement, however.

Libretube - https://github.com/libre-tube/LibreTube/issues/332
