### ISSUE TITLE
Feed shows no videos (Empty Feed page)

### ISSUE THREAD

**Issue by ttf76** [TeamPiped/Piped#1188]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The 'Feed' page has no videos. Clicking on the 'subscriptions' button shows all the channels that are subscribed to (as expected). 'Trending' page works fine and loads up with videos as normal. But going to the 'Feed' page (piped.kavin.rocks/feed) shows no videos where the videos should be loaded. In the feed page, can see every other button like the top 'sort' button as well as 'donations' footer. Simply where the videos should show up doesn't show any.
Already tried,
- disabling ads
- turning on all cookies
- Javascript is always on
- running with no extensions
- incognito mode
- clearing all cookies and site data and re logging
- creating a new account
- re importing subscriptions
- changing sort method
- refreshing the page
- staying in the feed page for long period, just to see if it loads later
- changing where piped fetch videos (preference
![Capture](https://user-images.githubusercontent.com/108837626/177647025-665c55f5-db3d-4a60-8401-24f775a92e6c.JPG)
s -> Instance Selection)
- trying on few different updated browsers both firefox and chromium type

Every other part of the website works. for example searching, going into a channel, changing settings.

Some times the feed works and loads the videos when visited. I can't exactly point how this happens as it is extremely rare and random.

### To Reproduce

1. Go to https://piped.kavin.rocks/
2. Log in
3. Go to https://piped.kavin.rocks/feed

### Expected behavior

A feed page with no videos loading up

### Logs/Errors

Here's a code of the 'Feed' page.

<!DOCTYPE html>
<html style="background: #0f0f0f" lang="en">
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width,initial-scale=1.0" />
<link rel="icon" href="/favicon.ico" />
<link title="Piped" type="application/opensearchdescription+xml" rel="search" href="/opensearch.xml" />
<title>Piped</title>
<meta property="og:title" content="Piped" />
<meta property="og:type" content="website" />
<meta property="og:image" content="/img/icons/favicon-32x32.png" />
<meta property="og:url" content="/" />
<meta property="og:description" content="An alternative privacy-friendly YouTube frontend which is efficient by design." />
<script type="module" crossorigin src="/assets/index.739bdd64.js"></script>
<link rel="stylesheet" href="/assets/index.ecb89492.css">
<link rel="manifest" href="/manifest.webmanifest"> <script type="module">try{import("_").catch(()=>1);}catch(e){}window.__vite_is_dynamic_import_support=true;</script>
<script type="module">!function(){if(window.__vite_is_dynamic_import_support)return;console.warn("vite: loading legacy build because dynamic import is unsupported, syntax error above should be ignored");var e=document.getElementById("vite-legacy-polyfill"),n=document.createElement("script");n.src=e.src,n.onload=function(){System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))},document.body.appendChild(n)}();</script>
</head>
<noscript>
        <strong style="color: #fff"
            >We're sorry but Piped doesn't work properly without JavaScript enabled. Please enable it to
            continue.</strong
        >
    </noscript>
<div id="app"></div>
<script nomodule>!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();</script>
<script nomodule id="vite-legacy-polyfill" src="/assets/polyfills-legacy.cf54a3f5.js"></script>
<script nomodule id="vite-legacy-entry" data-src="/assets/index-legacy.324d9fa8.js">System.import(document.getElementById('vite-legacy-entry').getAttribute('data-src'))</script>
</html>

### Browser, and OS with Version.

Most commonly used on Brave Version 1.40.113 (official build) 64-bit,
Also Firefox,
Iridium Browser

### Additional context

Everything worked before a few days ago when Piped got added a few new features

**Comment by mastazi** [comment]
response from `https://pipedapi.kavin.rocks/feed?authToken=xyz` (actual token replaced with xyz)

response code: 500

body:

```json
{
 error: "jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.JDBCConnectionException` to JPA `PersistenceException` : Unable to acquire JDBC Connection\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:374)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:986)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.uniqueResult(AbstractSelectionQuery.java:451)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.uniqueResult(QuerySqmImpl.java:1010)\n\tat me.kavin.piped.utils.DatabaseHelper.getUserFromSession(DatabaseHelper.java:28)\n\tat me.kavin.piped.utils.DatabaseHelper.getUserFromSession(DatabaseHelper.java:18)\n\tat me.kavin.piped.utils.ResponseHelper.feedResponse(ResponseHelper.java:860)\n\tat me.kavin.piped.ServerLauncher.lambda$mainServlet$28(ServerLauncher.java:257)\n\tat io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)\n\tat io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection\n\tat org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:49)\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:110)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:137)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl$1.doPrepare(StatementPreparerImpl.java:90)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)\n\tat org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareStatement(StatementPreparerImpl.java:75)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.lambda$list$0(JdbcSelectExecutorStandardImpl.java:100)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:171)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.lambda$processNext$0(JdbcValuesResultSetImpl.java:89)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advance(JdbcValuesResultSetImpl.java:274)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)\n\tat org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)\n\tat org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:89)\n\tat org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:142)\n\tat org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:32)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:437)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)\n\tat org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:102)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:305)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:246)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:536)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)\n\t... 12 more\nCaused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 1000ms.\n\tat com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)\n\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:181)\n\tat com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)\n\tat com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)\n\tat org.hibernate.hikaricp.internal.HikariCPConnectionProvider.getConnection(HikariCPConnectionProvider.java:76)\n\tat org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)\n\tat org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)\n\t... 36 more\n"
 message: "Converting `org.hibernate.exception.JDBCConnectionException` to JPA `PersistenceException` : Unable to acquire JDBC Connection"
}
```

**Comment by bespokecomp** [comment]
I get exactly the same behavior as OP.

**Comment by CheesyBan** [comment]
Can confirm likely related issue. Created new login, cannot import any subscriptions from takeout csv & feed remains blank.

**Comment by Ivan0xFF** [comment]
It's been broken for a few days for me. Tried both https://piped.kavin.rocks/ and https://piped.tokhmi.xyz/ they both have the same issue.

**Comment by CheesyBan** [comment]
Update: Appears there was some kind of cookie reset even though I have persistence enabled. Anyway. Logged back in and my manually added subs appear in the sub list but feed remains blank. Same issue as OP.

**Comment by brutzel** [comment]
It looks like the database server of the official instance is down. After a while the feed backend request to `/feed?authToken=<TOKEN>` has a timeout and I can see an exception in JSON format:

> Converting `org.hibernate.exception.JDBCConnectionException` to JPA `PersistenceException` : Unable to acquire JDBC Connection
