### ISSUE TITLE
Username + password invalid

### ISSUE THREAD

**Issue by riScoRpIng** [TeamPiped/Piped#1192]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I cannot sign in, it's stated to be incorrect. I just use my credentials as always by bitwarden. 
No changes where made by me.

### To Reproduce

1. Open piped.kavin.rocks
2. Go to sign in
3. Autofill (and also tried manually) by bitwarden
4. Stated to be incorrect

### Expected behavior

It's expected to accept my credentials and log me in and browse through supps.

### Logs/Errors

![Screenshot 2022-07-08 191138](https://user-images.githubusercontent.com/83781941/178040190-563eff13-2815-428e-bbf6-32ce2e62a26c.jpg)

### Browser, and OS with Version.

Firefox 102.0.1 (64-Bit) on Windows 10 21H2 (19044.1766).

**Comment by hbqjren** [comment]
我也是用户名和密码无法登陆。尝试新建一模一样的密码和用户名。成功了，但是变成新用户，Playlists和feed都是空白。Playlists好像导出不了，但是我之前存很多东西。全没有了

**Comment by CheesyBan** [comment]
Can confirm, now unable to login on main instance. Exact same behavior.

**Comment by el-turl** [comment]
Can confirm, and I use Bitwarden as well. Put in my credentials and receive "The username or password you have entered is incorrect."

**Comment by hommegithub** [comment]
Something's wrong with the db lsvel crashed!

**Comment by CheesyBan** [comment]
It appears that this issue, #1195, #1188, and #1193 are all linked to some sort of database corruption. I was able to recreate my account (with my subs lost of course) and successfully log in. I suspect this will not be fixed with a code change, but whoever manages the official instance needs to get this fixed as it makes it all but unusable for regular users.

**Comment by hommegithub** [comment]
> It appears that this issue, #1195, #1188, and #1193 are all linked to some sort of database corruption. I was able to recreate my account (with my subs lost of course) and successfully log in. I suspect this will not be fixed with a code change, but whoever manages the official instance needs to get this fixed as it makes it all but unusable for regular users.

Ditching piped for Invidious until it's fixed 🙈

**Comment by RouterCFW** [comment]
Issue is still happening 😪

**Comment by hommegithub** [comment]
Just wondering if the project is dead or someone from the dev team has responded?  Asking because I am new on posting on GitHub

**Comment by hommegithub** [comment]
Just wondering if the project is dead or someone from the dev team has responded? Asking because I am new to posting on GitHub

**Comment by RouterCFW** [comment]
Fixed now

**Comment by theuema** [comment]
@RouterCFW 

Still not able to login with my credentials!

**Comment by RouterCFW** [comment]
> @RouterCFW
> 
> Still not able to login with my credentials!

The official instance always goes down , I fixed it by using another one
