### ISSUE TITLE
404. Not Found  io.activej.http.HttpError: HTTP code 404: Not found  ActiveJ 5.3

### ISSUE THREAD

**Issue by hommegithub** [TeamPiped/Piped#1193]
###  Links with  #1195 #1192 #1181 #1183 #1184 #1188
Something definitely wrong at the db level - until account got deleted and is a dead end loop, signed up new account and it won't import sub json.

Ditching piped for Invidious until it's fixed.

###  Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I'm guessing it's just me but I constantly get 
404. Not Found error on public instances and my account got deleted.  When I sign up again It won't let me import subscriptions json.  Is constantly on VPN a problem?

![E8EED2F7-27B5-4685-A67B-4B9E56681767](https://user-images.githubusercontent.com/108275509/178073764-767e6bcf-b973-4dd8-8e55-d2868dcddbae.jpeg)

io.activej.http.HttpError: HTTP code 404: Not found

ActiveJ 5.3

### To Reproduce

As titled

### Expected behavior

Login on multiple browser on devices

### Logs/Errors

.

### Browser, and OS with Version.

I use iOS 6, 14, 15 and 16 Safari, also installed Yatte on iOS 15,16 and tvOS 16.

**Comment by hommegithub** [comment]
I think I'm gonna just move to Invidious with public instances after seeing all the bugs reported - please tell me I'm wrong?

**Comment by hommegithub** [comment]
**Links with #1195 #1192 #1181 #1183 #1184 #1188**

Something definitely wrong at the db level - until account got deleted and is a dead end loop, signed up new account and it won't import sub json.

Ditching piped for Invidious until it's fixed.

**Comment by FireMasterK** [comment]
This has now been fixed, the database has been fixed and imports too.
