### ISSUE TITLE
Toggle Audio/Video button on playback page forwards to wrong URL

### ISSUE THREAD

**Issue by honey-roast-coconut** [TeamPiped/Piped#1194]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

https://user-images.githubusercontent.com/109007873/178129428-12673e73-150f-4cd0-b8f7-7fc0d7f043ca.mp4

![image](https://i.gyazo.com/38a386c74326bac6a740befe20182555.png)

### To Reproduce

When clicking headphone/display button

### Expected behavior

Just takes to audio/video version page

### Logs/Errors

No errors found on dev console.

### Browser, and OS with Version.

Windows Edge 103.0.1264.49
Android Chrome 103.0.5060.71

**Comment by kskarthik** [comment]
I observed this too
