### ISSUE TITLE
Import from JSON doesn't work

### ISSUE THREAD

**Issue by LuanHimmlisch** [TeamPiped/Piped#1203]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I'm not able to import a JSON file of subscriptions from New Pipe.

It does show, however, the number of subscriptions being imported. So, it's not a problem with the file.

![](https://user-images.githubusercontent.com/46875694/178680845-1257a36f-813b-4ee6-9d1e-9e998d0eff09.png)

And strangely enough, the endpoint is giving an "ok" response.
 
![](https://user-images.githubusercontent.com/46875694/178681513-c393abf3-afbe-4518-9ede-5e712f25dbab.png)

### To Reproduce

1. Login to your account
2. Go to https://piped.kavin.rocks/import
3. Import a JSON file with subscriptions

### Expected behavior

That the subscriptions are imported

### Logs/Errors

There's none besides just an "ok" response from the server.

```json
{"message":"ok"}
```

### Browser, and OS with Version.

- Mozilla Firefox 102.0.1 (64-bit)
- Manjaro Linux 21.3.3

### Additional context

As showed in an above image, I'm trying to import 500+ subscriptions, but I can confirm this is not the problem or the _only_ problem at least, since I tried to import a JSON with only two subscription with the same degree of success.

**Comment by hommegithub** [comment]
Just wondering if the project is dead or someone from the dev team has responded? Asking because I am new to posting on GitHub

**Comment by JimPix1** [comment]
I'm having this issue as well. I noticed that all my subscriptions disappeared and my account no longer existed in Piped so I made a new one and couldn't import any of my subscriptions. Weird stuff...

**Comment by kovdan01** [comment]
> I'm having this issue as well. I noticed that all my subscriptions disappeared and my account no longer existed in Piped so I made a new one and couldn't import any of my subscriptions. Weird stuff...

The same issue - looks like it's not a unique case

**Comment by LuanHimmlisch** [comment]
By the looks of his GitHub profile, it seems Kavin is taking this week off

**Comment by JimPix1** [comment]
I guess we all need a break haha.
In the meantime I'll use invidious since I have an account there.

**Comment by JustAnotherMalaysian** [comment]
bruh momdnto0

**Comment by Scyt4le** [comment]
Yesterday evening I was finally able to import subscriptions again. Some magic in the background was done.

**Comment by RouterCFW** [comment]
Fixed

**Comment by LuanHimmlisch** [comment]
I was able to import subscriptions as well.
