### ISSUE TITLE
Add new ru instance

### ISSUE THREAD

**Issue by WaffleDZ** [TeamPiped/Piped#1206]
Front-end: https://piped.waffle.wiki/
API: https://pipedapi.waffle.wiki/
Proxy: https://pipedproxy.waffle.wiki/

Hosted in Russia with Cloudflare CDN

**Comment by FireMasterK** [comment]
Added, thanks for hosting an instance!

**Comment by chirag127** [comment]
> Front-end: https://piped.waffle.wiki/ API: https://pipedapi.waffle.wiki/ Proxy: https://pipedproxy.waffle.wiki/
> 
> Hosted in Russia with Cloudflare CDN

https://pipedapi.waffle.wiki is not working
cloudflare banned in ru
