### ISSUE TITLE
Can load/start video

### ISSUE THREAD

**Issue by rubynt** [TeamPiped/Piped#1207]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When i open a video it tries to autostart but the thumbnail showed only, after i try to if fast forward fixes it and it just shows that its loading.

### To Reproduce

idk

### Expected behavior

Play the video

### Logs/Errors

Everything is finished except
```
VideoPlayer.vue:283 Fetch failed loading: HEAD "https://player.odycdn.com/api/v4/streams/tc/xqc-and-greekgodx-get-personal-in-heated/829189a781ffdf4d79109b0098858ae0f694007b/8d85d30567fd79edb1fe9be4412d93723df23dbae32fddf263e0e21cd90865f241514f9143ac8fc93807178169ee71f3/master.m3u8".
```

### Browser, and OS with Version.

Chromium
Version 103.0.5060.53 (Official Build, ungoogled-chromium) (64-bit)

**Comment by FireMasterK** [comment]
It looks like lbry/odysee was down, it should now work.
