### ISSUE TITLE
Captions Don't Follow Pop-out in Picture-in-Picture Mode 

### ISSUE THREAD

**Issue by ryegye24** [TeamPiped/Piped#1228]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When you enable both captions and picture-in-picture mode for a video, the video pops-out into a new window, but the captions remain in the original window.

See attached screenshot for example:

![Screen Shot 2022-07-20 at 9 17 55 AM](https://user-images.githubusercontent.com/12969679/179992171-f652d95a-8b37-4d64-87f2-23a6d4d387ad.png)
.

### To Reproduce

1. Open the official instance at https://piped.kavin.rocks/
2. Start playing any video which includes captions  
3. Click the menu kebab button on the bottom right of the video and enable captions  
4. Click the menu kebab button on the bottom right of the video and enable Picture-in-Picture mode

### Expected behavior

The video pops out in a new window, and the captions are included in that new window.

What actually happens is that the captions remain in the original window which is no longer where the video is visible.

### Logs/Errors

N/A

### Browser, and OS with Version.

Browser: 103.0.5060.53 (Official Build, ungoogled-chromium) (x86_64) 
OS: macOS Big Sur Version 11.6

**Comment by Bnyro** [comment]
The subtitles and the picture-in-picture are handled by an external library, the shaka-player. I don't think we can do anything about this, it's rather an issue of the shaka-player.

**Comment by rezad1393** [comment]
> The subtitles and the picture-in-picture are handled by an external library, the shaka-player. I don't think we can do anything about this, it's rather an issue of the shaka-player.

I dont think this is the issue.
the issue is that firefox has a list of websites that PiP subtitle support is enabled on them.
so maybe it needs to be asked there.


like this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1781556
