### ISSUE TITLE
A simple "Recommended" page

### ISSUE THREAD

**Issue by hajdulak** [TeamPiped/Piped#1235]
### Describe the feature

Ok this might sound like trying to replace the actual YouTube algorithm but with less privacy invasion.

Basically what I suggest is creating a page, which takes some of your recently watched videos plus some of your subscribed channel's videos (and maybe some of your playlist videos), loads related vids for those, diffs them against your history and displays the result, thus creating a simple "for you" page based on what you watch.

### Why would this be useful to add?

This would optionally further enhance the discovery of videos through Piped, substituting for yet another feature of the original frontend, while retaining the same degree of privacy and anonymity.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
There's no way for Piped to do this since we don't store what you watch. Even when logged in, you send requests which are without authentication, and that's by design.

I feel that #821 is a better idea for now.

**Comment by hajdulak** [comment]
I see, I thought they are stored in the user account. Knowing what videos you watched is not exactly a requirement though - loading related videos of videos from your subscriptions, for example, could be an option too.
