### ISSUE TITLE
Disable LBRY on instance deploy

### ISSUE THREAD

**Issue by jae1911** [TeamPiped/Piped#1237]
### Describe the feature

Add a way to totally disable LBRY on deploy with an environment variable like:

`LBRY_DISABLE=true`

### Why would this be useful to add?

General blockchain bullshit & scams, insufferable community, no moderation.

Example of what the LBRY community does:
![](https://bm.jae.su/ShareX/2022/07/Element_iy1nUOJegC.png)

It's either that or I'm gonna block it the dirty way.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by IronMaltese** [comment]
I wish I could read the meme, it's too low quality

**Comment by jae1911** [comment]
> I wish I could read the meme, it's too low quality

@IronMaltese have fun: https://jae.fi/_matrix/media/r0/download/matrix.org/NAipCDwIMdoSGKgWyTlWHhXj
