### ISSUE TITLE
Timestamps with over 4 digits don't work

### ISSUE THREAD

**Issue by candroid-man** [TeamPiped/Piped#1241]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

As discovered by arjun in the official Piped Matrix server, timestamps over 4 digits (00:00:00) do not work at all. 

### To Reproduce

1. Go to a 1+ hour long video with timestamps in the description (https://piped.kavin.rocks/watch?v=q5D55G7Ejs8)
2. Go to the description
3. Try to click a timestamp

### Expected behavior

It's supposed to be a real timestamp and not just text

### Logs/Errors

N/A

### Browser, and OS with Version.

Firefox, EndeavourOS (Arch Linux), but other users have also tested it on different browsers/operating systems

**Comment by Bnyro** [comment]
This appears to work now.
