### ISSUE TITLE
Potentially add instance + question about CF cache/proxying

### ISSUE THREAD

**Issue by dr460nf1r3** [TeamPiped/Piped#1243]
Hey! 

I recently set up a new Piped instance on [piped.garudalinux.org](https://piped.garudalinux.org). The Cloudflare configurations outlined in https://github.com/TeamPiped/Piped/issues/737#issuecomment-1014482130 have been applied accordingly and things are working quite well. 

However, there was one question that came up - according to Cloudflare's TOS it is not allowed to deliver videos while using its services. 

> Unfortunately, while most people respect these limitations and understand they exist to ensure high quality of service for all Cloudflare customers, some users attempt to misconfigure our service to stream video in violation of our Terms of Service. We want to make sure our service is great for everyone, including public service initiatives we run like [Project Galileo](https://www.cloudflare.com/galileo/), [The Athenian Project](https://www.cloudflare.com/athenian/), and [Project Fair Shot](https://www.cloudflare.com/fair-shot/). A handful of people misusing our service limits our ability to run these initiatives.

How does Piped handle this with the above-linked configuration applied? I would like to avoid eventual issues and the termination of the domain at all costs as it handles a complete project's infrastructure.

Thanks and cheers!

**Comment by FireMasterK** [comment]
Hi there,

Thank you for hosting an instance for Piped!

In the official instance, I use a Cloudflare proxied `IMAGE_PROXY_PART` and a non-proxied `PROXY_PART` in my configuration, which will be used for videos. You could do this as well, it would just require another hostname. This would be the safest configuration in my opinion.

I have yet to hear about any instance being terminated by Cloudflare for serving video content so far, but it would be better to avoid potential issues. Cloudflare doesn't like caching videos on their CDN, but so far they've been okay with proxying video content.

Thanks again!

**Comment by moom0o** [comment]
@FireMasterK I recently got hit by a video ban from Cloudflare, weirdly enough it only actually affects my nitter instance for some reason. I think it's because piped doesn't use a video file extension.

But it redirects any nitter video links to https://www.cloudflare-terms-of-service-abuse.com/stream.mp4

Anyway, I turned off cloudflare for the piped video proxy just to be safe.

**Comment by dr460nf1r3** [comment]
So basically the suggestion is to create a separate domain that provides the proxy domain while the "public" domain is used to provide the frontend?

**Comment by FireMasterK** [comment]
No, what I'm suggesting is to add a different hostname for videos, without the Orange cloud, like `piped-videoproxy.garudalinux.org`
![image](https://user-images.githubusercontent.com/20838718/182028716-cb47563b-e97d-4d3d-8970-62b938663c1d.png)

and in the `config.properties` file, you could set it like so:
```properties
IMAGE_PROXY_PART: https://piped-proxy.garudalinux.org
PROXY_PART: https://piped-videoproxy.garudalinux.org
```

**Comment by dr460nf1r3** [comment]
I guess we can close this issue by now, I noticed the instance is already in use and working well 😊
