### ISSUE TITLE
Live streaming channels ignore audio playback only

### ISSUE THREAD

**Issue by glamothe9** [TeamPiped/Piped#1254]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

For some time now, there are radio stations that broadcast live music on youtube. Piped handles them well except for the audio only playback.

### To Reproduce

https://piped.kavin.rocks/watch?v=UedTcufyrHc&listen=1
https://piped.kavin.rocks/watch?v=UedTcufyrHc&listen=0

### Expected behavior

There should be no more video playing when you activate the audio only playback option.

### Logs/Errors

No logs/errors

### Browser, and OS with Version.

Tested on the latest versions of firefox and chromium on Arch

**Comment by FireMasterK** [comment]
This is to be expected, YouTube provided both audio and video together, so not much can be done.
