### ISSUE TITLE
Automatic location service.

### ISSUE THREAD

**Issue by Broniy** [TeamPiped/Piped#1256]
### Describe the feature

Use automatic system location.

### Why would this be useful to add?

Let's see videos of the country we live in.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
I don't think locating users by their IP is a good idea...
Changing it in the settings isn't a big deal and most users don't even use the trending tab.
