### ISSUE TITLE
Cloning playlists causes an 500 error

### ISSUE THREAD

**Issue by Mittelblut9** [TeamPiped/Piped#1259]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When i try to clone a public playlist this error pops out. I tried one with over 500 videos and one with less then 50. Same for both.

### To Reproduce

Open https://piped.kavin.rocks/login
Login
Change instance to `privacy.com.de`
Enter a playlist link (e.g https://www.youtube.com/playlist?list=PLo0Q-cmKH0LBPvvvbjqIY7Jwsnb1wYeyo)
Click "Clone Playlist"
Observe the error

### Expected behavior

The playlist will get cloned into my profile successfully.

### Logs/Errors

```
jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.SQLGrammarException` to JPA `PersistenceException` : could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)
....
```

Full Error:
https://pastebin.com/TiyHrY7E

![Screenshot 2022-07-27 225640](https://user-images.githubusercontent.com/67608550/181370705-77ea5563-b2e6-4e4a-9717-5bc0edef9164.png)

### Browser, and OS with Version.

Firefox 102.0.1 Windows 11

**Comment by FireMasterK** [comment]
@exonip since you're the maintainer of this instance, you would need to run these two commands once to fix this:

```
docker exec -u postgres -it postgres psql -U piped
ALTER TABLE playlists ALTER COLUMN playlist_id TYPE uuid USING CAST(ENCODE(playlist_id, 'hex') AS uuid);
```

**Comment by Exonip** [comment]
@FireMasterK @Mittelblut9 Seems to be working now so this can be closed
