### ISSUE TITLE
More details about the unethical privacy policy of YouTube

### ISSUE THREAD

**Issue by timaschew** [TeamPiped/Piped#1261]
I saw:

> YouTube has an extremely invasive privacy policy which relies on using user data in unethical ways. You give them a lot of data - ranging from ideas, music taste, content, political opinions, and much more than you think.

but are there some more details and perhaps even sources for it?

**Comment by Bnyro** [comment]
Well, when googling for it you probably won't find much about it :p
I can recommend [this article about YouTube](https://en.wikipedia.org/wiki/YouTube_and_privacy) in specific and [this](https://en.wikipedia.org/wiki/Privacy_concerns_regarding_Google#Potential_for_data_disclosure) about Google in general. Most of the policy is the same on all Google services, not only YouTube. For example if you use Maps they got your location and use it for advertising or selling this data. Apart from that Google is known for exchanging data with governments, they don't seem to care about users privacy. See [this](https://hackernoon.com/data-privacy-concerns-with-google-b946f2b7afea) for reference.

**Comment by Bnyro** [comment]
I forgot to mention, other information and  sources can be found on https://piped-docs.kavin.rocks/docs/why/
