### ISSUE TITLE
API: Duration for Shorts is 0

### ISSUE THREAD

**Issue by lu4p** [TeamPiped/Piped#1265]
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

From the API the duration of shorts is always 0.

### To Reproduce

1. Open this Url: https://pipedapi.kavin.rocks/channel/UCXuqSBlHAE6Xw-yeJA0Tunw
2. Search for #SHORTS 
3. Duration of the found video is 0

### Expected behavior

Duration should match the video duration.

### Logs/Errors

/

**Comment by Bnyro** [comment]
This seems to be working as expected now, at least I couldn't reproduce it anymore.

**Comment by lu4p** [comment]
@Bnyro still the same for me can't you reproduce with the link above?

**Comment by Bnyro** [comment]
Oh, you're right, it still seems to be an issue

**Comment by Bnyro** [comment]
Tested with NewPipe, same issue there.
Did some research and found https://github.com/TeamNewPipe/NewPipe/issues/8034 which seems to be exactly what's happening in our case.
