### ISSUE TITLE
Clarification regarding privacy wrt individual instance admins and piped.kavin.rocks

### ISSUE THREAD

**Issue by thecashewtrader** [TeamPiped/Piped#1266]
### Describe your question

I wanted to know what effect changing the instance to other than `kavin.rocks` in https://piped.kavin.rocks/preferences has on (the admin of) `piped.kavin.rocks` being able to see the videos that are watched.

I am assuming that `piped.kavin.rocks` would be able to see atleast the complete url (which would reveal the videos watched), but am not sure.

**Comment by FireMasterK** [comment]
> I wanted to know what effect changing the instance to other than kavin.rocks in https://piped.kavin.rocks/preferences has on (the admin of) piped.kavin.rocks being able to see the videos that are watched.

I can only see the URL you visit the first time, after which the service worker would install and requests would be served using it, locally from within the browser's storage. After which, only update check requests would be made to `piped.kavin.rocks`.

> I am assuming that piped.kavin.rocks would be able to see atleast the complete url (which would reveal the videos watched), but am not sure.

This is not true, the above comment explains why.

I'd also like to add that the official instance keeps no access logs, just like all of my other hosted services.

Let me know if you have any other infrastructure questions!
