### ISSUE TITLE
Unable to register.

### ISSUE THREAD

**Issue by ChocolatePie698** [TeamPiped/Piped#1267]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Register page on my self-hosted instance is broken. I'm unable to register an account on here. I'm using an nginx proxy and looking at logs for piped I'm seeing an error every time I load the page.

### To Reproduce

1. Following the instructions for nginx on https://piped-docs.kavin.rocks/docs/self-hosting/.
2. Run it with docker-compose.
3. Load the page with any browser.
4. Try to make account.

### Expected behavior

To be able to register and use the website.

### Logs/Errors

2022/07/31 08:04:43 [error] 12#12: *4 open() "/usr/share/nginx/html/register" failed (2: No such file or directory), client: 172.20.0.8, server: localhost, request: "GET /register HTTP/1.1", host: "pipedfrontend"

### Browser, and OS with Version.

Firefox, Edge, Chrome, etc.

**Comment by FireMasterK** [comment]
What are the logs in your browser?

**Comment by ChocolatePie698** [comment]
> What are the logs in your browser?

Hmm clicking the register button spills this out 

![2022-07-31-080146_555x124_scrot](https://user-images.githubusercontent.com/37634501/182025557-d7c82138-2ccb-415b-848c-ab48f911a71b.png)

**Comment by ChocolatePie698** [comment]
huh...... i think i got it to work. Looking at that error, pipedapi's cert was being marked as invalid. A new cert fixed all of my problems. Well...... i feel dumb.
