### ISSUE TITLE
Double tap to go +10/-10 seconds

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#127]
Title

**Comment by FireMasterK** [comment]
I did some research on this, https://github.com/google/shaka-player/issues/3127 states that a custom implementation is required

**Comment by Facni** [comment]
Actually, is working for me for some reason
![image](https://github.com/TeamPiped/Piped/assets/112446096/4e9c50ae-4a3f-4eb9-ad6c-24607126d906)

**Comment by FireMasterK** [comment]
This was added when we upgraded shaka-player to [v4.7.0](https://togithub.com/shaka-project/shaka-player/blob/HEAD/CHANGELOG.md#470-2023-12-04), will close this issue now, thanks!
