### ISSUE TITLE
Channels unsubscribe without account

### ISSUE THREAD

**Issue by IronMaltese** [TeamPiped/Piped#1271]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Channels unsubscribe when subscribing to them without an account on iOS

### To Reproduce

1. Subscribe to a bunch of channels
2. They slowly start disappearing from your feed

### Expected behavior

Channels should not be unsubscribed to over time

### Logs/Errors

N/A

### Browser, and OS with Version.

Latest version of iOS

### Additional context

https://user-images.githubusercontent.com/89056889/182297280-6ee56dca-f8a4-452a-b825-5f8083d62664.MOV

**Comment by Bnyro** [comment]
Channels don't get unsubscribed over the time, the subscribe button in the channel page just doesn't show the correct subscription state.

**Comment by IronMaltese** [comment]
> Channels don't get unsubscribed over the time, the subscribe button in the channel page just doesn't show the correct subscription state.

It was hard for me to show this in the video since it happens so randomly and slowly, but my subscriptions have basically all disappeared, notice how in the previous video I had more subscriptions than I do now
![image](https://user-images.githubusercontent.com/89056889/182341860-0ca12720-3c4f-4cd7-a769-8321d20d0db5.png)

**Comment by Bnyro** [comment]
That doesn't really make sense to be honest, if channels vanished then all at once and not one by one...

**Comment by IronMaltese** [comment]
> That doesn't really make sense to be honest, if channels vanished then all at once and not one by one...
> 
> You probably unsubscribed them although it wasn't your intention because the subscribe status was shown wrong.

I subscribed to a bunch of accounts, and my feed looked fine for a bit then I went in and checked how many accounts I've been following and it was 17, I've done nothing since then and now it's at 6

But the pull request might fix this, I'll re-sub to all the channels and update you if anything happens

**Comment by IronMaltese** [comment]
It's still happening :/

![image](https://user-images.githubusercontent.com/89056889/182363725-3284507e-7e50-4bd5-b267-1754d71d4b7c.png)

![image](https://user-images.githubusercontent.com/89056889/182363738-8cc84567-6be4-4a3b-85d0-dfbabd2a82f7.png)

**Comment by Bnyro** [comment]
Are the channels also marked as not subscribed when you search for them manually?

**Comment by IronMaltese** [comment]
They're marked as unsubscribed

**Comment by IronMaltese** [comment]
It only seems to happen when I'm using Piped

**Comment by IronMaltese** [comment]
Interesting note: in my rss reader, my piped feed shows the videos of the unsubscribed channels, but on the website it doesn't show the videos of unsubscribed channels

**Comment by IronMaltese** [comment]
Seems to be fixed now, thanks!

**Comment by IronMaltese** [comment]
![image](https://user-images.githubusercontent.com/89056889/187075881-eb070d53-8c43-4186-8f39-48a7b51d1f97.jpeg)

The problem has happened again, and I went from over 100 subscribed accounts to 34, was there any deleted instances from piped recently? maybe that's the issue

**Comment by Bnyro** [comment]
Local subscriptions are stored in the local storage of your browser.
You can track them by going into the dev tools of your browser -> storage -> local storage -> {url of the Piped instance}. Could you please check how many channels are listed there, so that we can determine whether it's a server or a client side issue? (they are separated by ",")
Thanks in advance :)

**Comment by IronMaltese** [comment]
I've been subscribed to a bunch of channels on my desktop without an account for awhile now, but this bug doesn't occur

It only happens for me on iOS, it's been consistent across different instances including piped.kavin.rocks

I believe WebKit has a different way of handling storage, so while I've only tested this on desktop chromium based browsers, I'll try it on desktop safari and send logs if anything happens🤙

**Comment by IronMaltese** [comment]
Thank you!!
