### ISSUE TITLE
HDR Toggle Needed

### ISSUE THREAD

**Issue by seonwoolee** [TeamPiped/Piped#1275]
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Watching a HDR video on a SDR monitor results in the colors looking flat because Piped is trying to play back the video as if I have a HDR monitor

### To Reproduce

Watch this [HDR video](https://piped.kavin.rocks/watch?v=1eALWqNZh1I) on a SDR monitor
This problem does not happen with [Invidious](https://yewtu.be/watch?v=1eALWqNZh1I)

### Expected behavior

Render the colors assuming a SDR display, not a HDR one. It should either autodetect HDR/SDR correctly, or there should be an option to toggle it manually

### Logs/Errors

N/A

### Browser, and OS with Version.

Firefox 103.0 on Arch Linux

**Comment by FireMasterK** [comment]
I don't see any issues on my SDR monitor, to disable HDR content simply deselect av1 from the "enabled codecs" in settings.
