### ISSUE TITLE
add subsonic compatible API

### ISSUE THREAD

**Issue by jkumeboshi** [TeamPiped/Piped#1276]
### Describe the feature

Would be nice to have a subsonic compatible API, to allow compatible apps such as DSub use Piped as server.

### Why would this be useful to add?

The most useful Dsub feature is that is able to cache songs and to works offline, allowing to listen music also in palces not covered by any network service.
This will also save your mobile plan data when not cover by wifi, as well as decrease unneeded traffic in general.

### Concept(s)

The API could be implemented in the Piped backend itself, but also could be implemented as a separate proxy service that converts Subsonic API to Piped API.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This would be out of the project's scope, I feel this would be better as a separate project.
