### ISSUE TITLE
Not all subtitles are parsed

### ISSUE THREAD

**Issue by iamtakingithard** [TeamPiped/Piped#1281]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Piped seems to not parsing **all** subtitles available for a video. While if you will see YouTube, it will have more subtitles available than Piped.

### To Reproduce

1. Open https://piped.kavin.rocks/watch?v=LBvHI1awWaI
2. See 7 languages available
3. Open YouTube original link
4. 11 languages available (apart from auto-generated ones)

### Expected behavior

By idea, Piped should be able to parse **all** subtitles available from YouTube video.

### Logs/Errors

-

### Browser, and OS with Version.

Brave on OpenSuse Tumbleweed.

**Comment by FireMasterK** [comment]
I actually see all 11 subtitles/captions, with Arch Linux on Brave.

**Comment by AlyoshaVasilieva** [comment]
Scroll up in the captions box, it has all 11 including English
![captions](https://user-images.githubusercontent.com/1284317/183301902-9fb489b0-125d-44b1-936b-a4392d549e96.png)
