### ISSUE TITLE
More information on login and register page

### ISSUE THREAD

**Issue by vanillajonathan** [TeamPiped/Piped#1288]
### Describe the feature

On the register page it is not clear what the registration means and why you should register.

Why should someone register an account? Does it allow you to like/dislike video, comment on videos, add videos to a playlist, star or bookmark videos? What are the benefits?

Does it create a YouTube account, or is it a local Piped account, or a global account that can be used on any Piped instance?

When you login can you use your YouTube account to login? Can you use an account registered on another Piped instance?
What if I forgot my password?

### Why would this be useful to add?

To make it easier to understand what the login and registration means, how it works, what benefits it provide.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
In my opinion, adding this information to the login and register page would overwhelm most users with information they don't need or want to know about it.
It would be a better solution to add information about that to the documentation at piped-docs.kavin.rocks and link it there named as "More info" or something similar.

**Comment by JackTheExecuter** [comment]
I think @vanillajonathan is right. 
It is not really obvious for someone who didn't set up the piped instance.
