### ISSUE TITLE
Way to advertise a status page

### ISSUE THREAD

**Issue by jae1911** [TeamPiped/Piped#1289]
### Describe the feature

Add a way to add a status page via an environment variable, for instance near the buttons in the top right corner.

![image](https://user-images.githubusercontent.com/76598503/183619143-a555ec3e-0a99-4954-a145-f26bfd3d2747.png)

Or maybe it could be put in the footer of the page?

![image](https://user-images.githubusercontent.com/76598503/183619399-dea016b7-8153-4548-aae8-12d603b38a2d.png)

### Why would this be useful to add?

Would be useful so users know where to look for status in case of the API not working.

### Additional context

See [this message](https://matrix.to/#/!EgLVqODCMqgvSrNDkS:matrix.org/$h4_dkh7eAbRO_EpkpEuGZYjG2ChazHRLXAQNEVYmi-M?via=libera.chat&via=matrix.org&via=tchncs.de) in the Matrix channel.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by privacytime101** [comment]
Definitely agree, this would be very useful
