### ISSUE TITLE
Add piped.privacydev.net to instance list

### ISSUE THREAD

**Issue by PrivacyDevel** [TeamPiped/Piped#1291]
### Describe the feature

I would like to get my instance added to the instance list.

| Instance Name | Instance API URL | Instance Location(s) | CDN | Registered Users |
|-----------------------|------------------------|-------------------------------|--------|--------------------|
| privacydev.net | https://api.piped.privacydev.net | 🇺🇸 | No | Registration disabled |

### Why would this be useful to add?

More instances = more better

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Added, thanks for hosting an instance!
