### ISSUE TITLE
Topic channel empty

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1292]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

https://piped.kavin.rocks/channel/UCC2AOoHt1RS4Xk0JexgeJZA is totally empty

### To Reproduce

1. Open https://piped.kavin.rocks/channel/UCC2AOoHt1RS4Xk0JexgeJZA
2. It loads, but nothing is there

Also occurs on my private instance.

### Expected behavior

[On YouTube](https://www.youtube.com/channel/UCC2AOoHt1RS4Xk0JexgeJZA), playlists section, it has 10 playlists, listed under "Albums & Singles"

### Logs/Errors

N/A

**Comment by Bnyro** [comment]
This is an already known [issue of the NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues/501), so there's nothing we can do about it.

These videos can be found by searching them manually as possible work around to still be able to watch these videos.
