### ISSUE TITLE
Light Theme

### ISSUE THREAD

**Issue by moriel5** [TeamPiped/Piped#130]
I understand the importance of having a dark theme, and they many people prefer it, however not everyone does, and many (including me) prefer having a light theme (as long as it isn't too blinding).

**Comment by FireMasterK** [comment]
You may test a preview at https://f5061764.piped.pages.dev/
You may also suggest suggestions/improvements at #219

**Comment by moriel5** [comment]
It certainly needs a lot of work:
![Screenshot from 2021-06-25 03:11:57](https://user-images.githubusercontent.com/20175297/123350471-9cce6400-d54a-11eb-9d73-cf3c09bd77e8.png)
![Screenshot from 2021-06-25 03:12:14](https://user-images.githubusercontent.com/20175297/123350480-a0fa8180-d54a-11eb-8877-d85fddb1d264.png)
![Screenshot from 2021-06-25 03:12:30](https://user-images.githubusercontent.com/20175297/123350491-a3f57200-d54a-11eb-9ec4-e922ef1672be.png)
![Screenshot from 2021-06-25 03:12:54](https://user-images.githubusercontent.com/20175297/123350500-a6f06280-d54a-11eb-8dba-3fa8a949dd0e.png)

**Comment by FireMasterK** [comment]
I think you may not have reloaded the page once you changed the setting, this isn't how it is supposed to look.

![Screenshot_20210625-055856_Brave_-_Nightly](https://user-images.githubusercontent.com/20838718/123351461-a6f16200-d54c-11eb-812d-806f8128c00e.png)
![Screenshot_20210625-055818_Brave_-_Nightly](https://user-images.githubusercontent.com/20838718/123351466-a953bc00-d54c-11eb-8044-d3d6da235311.png)
![Screenshot_20210625-055838_Brave_-_Nightly](https://user-images.githubusercontent.com/20838718/123351471-ab1d7f80-d54c-11eb-8085-8d58c18a92c7.png)

**Comment by moriel5** [comment]
I'll test it again, though I do believe that I had opened, at least the channel pages, in new tabs (I also tested this, with the same results, and the same methodology, on my Razer Phone 2 with Lightning Browser, that relies upon the system WebView)).

**Comment by FireMasterK** [comment]
Closing this with #219 now.
