### ISSUE TITLE
Show playlists when we click on a channel.

### ISSUE THREAD

**Issue by Broniy** [TeamPiped/Piped#1306]
### Describe the feature

Show playlists separately when we click on the channel.

### Why would this be useful to add?

Access channel-specific playlists and manage them more easily.

### Concept(s)

I already explained it.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
can be tracked in #1464
