### ISSUE TITLE
PeerTube support

### ISSUE THREAD

**Issue by KurozyOS** [TeamPiped/Piped#1308]
### Describe the feature

Like LBRY player, add support to play videos from PeerTube servers

### Why would this be useful to add?

More decentralized video service.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Well, there's no way to tell if a YouTube video is available on Peertube. (Accurately, at least)

**Comment by KurozyOS** [comment]
This may be one way to solve this issue [PeerTube - Companion](https://codeberg.org/Booteille/peertube-companion)

**Comment by FireMasterK** [comment]
I've submitted an issue on Peertube's repository at: https://github.com/Chocobozzz/PeerTube/issues/5198

**Comment by KurozyOS** [comment]
> I've submitted an issue on Peertube's repository at: [Chocobozzz/PeerTube#5198](https://github.com/Chocobozzz/PeerTube/issues/5198)

Alright, then lets move this thread there
