### ISSUE TITLE
Playing any video results in "Could not get any stream" error

### ISSUE THREAD

**Issue by kovdan01** [TeamPiped/Piped#1316]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Can't load any video using my custom instance https://piped.kovalev.works (please note that the SSL certificate is self-signed): it results in "Could not get any stream. See error variable to get further details." error. The issue just occurred today, previously I've been using my self-hosted instance for several months and everything was OK. Please note that stuff other than videos loading like searching and preview loading works normally.

What I've tried to do in order to fix the problem:
1. Manually update the containers using the command from the docs https://piped-docs.kavin.rocks/docs/self-hosting/:

   ```
   docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once piped-frontend piped-backend ytproxy varnish nginx caddy postgres watchtower
   ```
2. Run `docker-compose pull && docker-compose down && docker-compose up -d`
3. Update the OS (Ubuntu 22.04)
4. Reboot the OS
5. Just wait for several hours hoping that everything becomes normal :)

Nothing helped.

### To Reproduce

With a web-frontend:
1. Open any video on my custom instance: for example, https://piped.kovalev.works/watch?v=dQw4w9WgXcQ
2. Get "Could not get any stream. See error variable to get further details." error.

With LibreTube Android app:
1. The same as above.
2. Get "There is a problem with the server. Try another instance?" toast message.

### Expected behavior

Expected to get videos playing normally.

### Logs/Errors

Backend server logs:

```
 An error occoured in the path: /streams/SgNQKgz4e50
 org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
      at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
      at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
      at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
      at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
      at me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$0(ResponseHelper.java:74)
      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
      at java.base/java.lang.Thread.run(Unknown Source)
```

Response from JS console:

```
XHRGEThttps://pipedapi.kovalev.works/streams/dQw4w9WgXcQ
[HTTP/2 500 Internal Server Error 1572ms]

{"error":"org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)\n\tat me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$0(ResponseHelper.java:74)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n","message":"Could not get any stream. See error variable to get further details."}
```

### Browser, and OS with Version.

Doesn't matter

**Comment by FarisZR** [comment]
Can confirm the issue on a third party instance.
However, the same video played on the official instance, logs show the same error.

**Comment by FireMasterK** [comment]
@kovdan01 can you run `docker-compose pull && docker-compose down && docker-compose up -d`? It should fix the issue. 


> However, the same video played on the official instance, logs show the same error.

Could not reproduce, the video works fine for me on the official one.

**Comment by kovdan01** [comment]
> @kovdan01 can you run docker-compose pull && docker-compose down && docker-compose up -d? It should fix the issue.

It helped, thanks!
