### ISSUE TITLE
remove ru instances

### ISSUE THREAD

**Issue by chirag127** [TeamPiped/Piped#1320]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

https://piped.waffle.wiki/  is Hosted in Russia with Cloudflare CDN but it is banned now please remove it from https://raw.githubusercontent.com/wiki/TeamPiped/Piped-Frontend/Instances.md , it don't open ever

### To Reproduce

go to https://piped.waffle.wiki/ , it never open

### Expected behavior

https://piped.waffle.wiki/ should work

### Logs/Errors

522 timeout

**Comment by nonetrix** [comment]
xenophobia much?

**Comment by nonetrix** [comment]
Ah yes because removing links will stop Russia from invading Ukraine

- Someone apparently

**Comment by chirag127** [comment]
> Ah yes because removing links will stop Russia from invading Ukraine
> 
> * Someone apparently

No, because it is not working.

**Comment by IronMaltese** [comment]
Yeah the sites down
