### ISSUE TITLE
allow filtering for youtube shorts

### ISSUE THREAD

**Issue by elypter2** [TeamPiped/Piped#1321]
### Describe the feature

an option to hide shorts or only display shorts

### Why would this be useful to add?

it would be nice to be able to filter searches for shorts. maybe as part of a video length filter.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of https://github.com/TeamPiped/Piped/issues/792
