### ISSUE TITLE
Feature request: Option to hide watched video in feed

### ISSUE THREAD

**Issue by snyssen** [TeamPiped/Piped#1329]
### Describe the feature

Coming from Invidious, I really appreciated their ability to hide watched video from your feed as it helped staying on top of your subscriptions. I would love if Piped could implement the same. It would of course need to be an optional user setting, as I am sure a lot of people would prefer to keep the watched videos in their feeds.

Hand in hand with this feature, it would also be great if we could manually set the watch status of a video (though I guess I should create a second issue for this?).``

### Why would this be useful to add?

It helps reduce the noise in the feed view by only showing relevant videos.

### Concept(s)

No need to reinvent the wheel, just take a look at what Invidious has done:
- Checkbox in user settings for toggling the feature on or off
![image](https://user-images.githubusercontent.com/36501744/186687103-a9dd8bfe-b5a5-42ec-897d-4d1f9c40798d.png)
- Video are filtered out of the queried feed list (nothing to show here)
- **Ideally**, Add a button to set a video as viewed:
![image](https://user-images.githubusercontent.com/36501744/186658965-b5f4b070-b7d1-4a5c-a2b6-7f367271e102.png)
- It might be great if there was also a button on the video view to mark video as unwatched, but this is even less necessary

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by soderluk** [comment]
@snyssen The button about hiding the video from the feed is a great feature, is there a reason why this wasn't implemented in this PR @Bnyro ? Should I open a new feature request for it, or is it just not possible?
I have checked the checkbox on hiding watched videos in the feed (in settings), but I still get watched videos in the feed. Refreshing doesn't hide them either.
My feed is filled with videos from a couple of subscriptions, which I would like to hide from the feed, but not unsubscribe from.

**Comment by Bnyro** [comment]
Videos are only hidden when you watched more than 90% of it.

**Comment by soderluk** [comment]
@Bnyro These are videos I've watched 100%.
