### ISSUE TITLE
Block/Allowed channel list

### ISSUE THREAD

**Issue by KurozyOS** [TeamPiped/Piped#1332]
### Describe the feature

User can add a list of blocked channels and they do not appear while searching for them and can't play those videos.

Same goes for allowed, but blocks everything that is not on a list.

### Why would this be useful to add?

For parental purposes, this way we can allow right age group to watch content made for them. This way we can be sure that a 5 year old does not watch content for teens or videos made for older people.

Right now it can only unsubscribe but can be searched for them and play videos. 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Related: #1090
