### ISSUE TITLE
net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by Bellisario** [TeamPiped/Piped#1346]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Seems Piped (API) certificate just expired today and all videos fail loading.

### To Reproduce

1. Open Piped (official instance)
2. Play a video
3. Look the console (... net::ERR_CERT_DATE_INVALID)

### Expected behavior

Piped should work...

### Logs/Errors

GET <LONG_API_URL> net::ERR_CERT_DATE_INVALID

### Browser, and OS with Version.

Chrome 104.0.5112.102, Windows 7.

**Comment by FireMasterK** [comment]
Fixed!
