### ISSUE TITLE
Embedded link previews for wider adoption through discord, etc.

### ISSUE THREAD

**Issue by geffer2** [TeamPiped/Piped#1354]
### Describe the feature

Duplicate of #864 #890 
Reason: 
![image](https://user-images.githubusercontent.com/112468523/187374996-a9f6e78b-9a4c-467d-98cd-cce54d95d64b.png)

### Why would this be useful to add?

Expected to visually behave like youtube links, but doesn't. 

### Concept(s)

"Important to note that individual instance operators can fix this problem through by 1. Patching Piped to generate metadata and 2. Running it through Prerender or Rendertron. My instances that run Piped Material do that for example.

https://piped-material.ftp.sh/watch?v=dQw4w9WgXcQ embeds fine.

Kavin might find it reasonable to add support for generating metadata for the instances that choose to run it through a browser engine, even if his instances don't do that.

Regards,"

"Piped as of now doesn't generate HTML metadata, so it's not possible. If Kavin decides to add support, you can for instance use my prerender-boilerplate (https://github.com/mmjee/prerender-boilerplate) to easily add Prerender support. Do keep in mind this involves running a whole browser for the crawler requests. (Or use Piped-Material if it's really that important for you, it generates metadata)

Regards,"

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
> Duplicate of https://github.com/TeamPiped/Piped/issues/864 https://github.com/TeamPiped/Piped/issues/890

If you knew this was a duplicate, why create a new issue?
