### ISSUE TITLE
Specific Video Only Playable at Up to 1080p on Piped

### ISSUE THREAD

**Issue by moriel5** [TeamPiped/Piped#137]
Video: https://www.youtube.com/watch?v=jX95U1fBM9A
Linus Tech Tips: Touch Me...

On Piped, it only goes up to 1080p (960p), while on NewPipe I can playback or download at up to 2160p (1920p).

**Comment by FireMasterK** [comment]
I've reported this issue to shaka-player, it should take a few days/weeks before its fixed hopefully.

**Comment by FireMasterK** [comment]
Closing with 4cb06c35696520469c0bdb04f18a9a85915df78a.
