### ISSUE TITLE
Scroll up and down in the playlist.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1373]
### Describe the feature

Move up and down the videos in the playlist.

### Why would this be useful to add?

I will see the video I want at the top of the playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
duplicate of https://github.com/TeamPiped/Piped/issues/964
