### ISSUE TITLE
Voice search.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1377]
### Describe the feature

Search videos with voice.

### Why would this be useful to add?

No need to write.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Voice recognition is mostly unreliable and it would miss the goals of this project.
