### ISSUE TITLE
Autoplay Preference for player

### ISSUE THREAD

**Issue by moriel5** [TeamPiped/Piped#138]
This may very well be an a bug within Firefox, not with Piped.

When changing resolution, videos automatically start playing on Piped, but only with Firefox, Edge had no such issue.
Sometimes (rarely) opening a new page on Piped has the video autoplaying, again only on Firefox.

Both Firefox and Edge (possible via flag) have autoplay for both audio and video blocked.

**Comment by FireMasterK** [comment]
Autoplay is enabled in the player, what do you mean?

**Comment by moriel5** [comment]
Then that would indicate a very odd situation, since the autoplay permission is supposed to allow, mute or deny the player from autoplaying until it is interacted with, however with Firefox it occasionally (rarely), it autoplays without any interaction, while on Edge, it does not autoplay at all, even with user interaction, and only manually playing the video starts the video.

I personally dislike having videos autoplaying, which is why I generally block all sites from autoplaying (also could be added as a feature request, to prevent autoplay, similar to what Invidious offers, should I create a new issue for that)?

**Comment by FireMasterK** [comment]
I'll do the needful 👍

**Comment by FireMasterK** [comment]
Closing as this was implemented in 5ceda9fd62dde1a2215f538b9c93e557cb019e18.
