### ISSUE TITLE
Channel sharing.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1380]
### Describe the feature

YouTube channel sharing feature.

### Why would this be useful to add?

It is necessary when you want to share channels.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
It is not necessary when wanting to share channels, copying and pasting the url is still a viable option...
I agree that the feature might be useful but you can't say that you need a feature to do xy because xy is needed...
