### ISSUE TITLE
Limitation for api ?

### ISSUE THREAD

**Issue by F3000** [TeamPiped/Piped#1386]
### Describe your question

Hi , 

I use Yattee on iOS to use the service . 

When I add a new subscription I see only the five newest videos . Is this a limitation ?

**Comment by Bnyro** [comment]
No, it's not. The [web frontend](https://piped.kavin.rocks) and the [Android equivivalent](https://github.com/libre-tube/LibreTube) indeed support showing more.
.In theory it depends on the instance owners configs but by default you can see the last 30 days :)

**Comment by FireMasterK** [comment]
The feed retention is 30 days, we only store the last 30 days worth of videos.
