### ISSUE TITLE
[Feature Request] Keyboard Shortcuts

### ISSUE THREAD

**Issue by moriel5** [TeamPiped/Piped#139]
I was quite surprised that Piped doesn't yet feature any keyboard shortcuts, so here is the request.

Basic ones are pretty obvious:
Horizontal arrow keys: Moving through the video
Vertical arrow keys: Changing volume
Space/Super (however you'd like to call it): Play/Pause
F: Fullscreen
M: Mute

Others should also chime in with suggestions.

**Comment by FireMasterK** [comment]
`google/shaka-player#3223` shows that there is an issue for this already.

I will create a solution such as https://github.com/google/shaka-player/issues/2859#issuecomment-696225256 for now.

**Comment by FireMasterK** [comment]
Added!

**Comment by moriel5** [comment]
Thanks, I'll test it out as soon as I'm on my desktop.

**Comment by moriel5** [comment]
It's working great here, with 2 hitches regarding fullscreen.

1. On both Firefox and Edge: Sometimes it just outrigh doesn't work.
Same happens on YouTube, but no such issue with Invidious.

2. Only Firefox: When pressing F, the browser automatically starts searching for text, since I have that feature enabled.

This does not happen with either YouTube not Invidious, specifically when the video is in focu, however on Piped, this also happens when the video is in focus (i.e., I click within the video box first).

**Comment by FireMasterK** [comment]
I could not replace the first issue with both Firefox Nightly and Edge.

I've just fixed the second issue

**Comment by moriel5** [comment]
Thanks, I'll test things out soon.

Regarding the first point, it may just be something specific to my desktop, since it also happens on YouTube (though interestingly, it doesn't happen with Invidious).
