### ISSUE TITLE
Highlight The url's on discription

### ISSUE THREAD

**Issue by kevin-roan** [TeamPiped/Piped#1395]
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

![image](https://user-images.githubusercontent.com/103060398/188547097-8647600a-a8b6-428c-81e8-6566fb897ecf.png)

### To Reproduce

1.open this url https://piped.kavin.rocks/watch?v=RkOjSwd7akg
2.maximize the description
3.there is no difference between plan text and url.

### Expected behavior

the url's should be highlighted

### Logs/Errors

none

### Browser, and OS with Version.

firefox 104.0-1, ArchLinux

**Comment by Bnyro** [comment]
Note: that's already included in the redesign, issue will be closed when the redesign comes in action
