### ISSUE TITLE
Auto theme broken when system theme is dark

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#1401]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

White background with white text when piped theme is auto and system is dark on firefox
does not happen with other websites
![image](https://user-images.githubusercontent.com/58657617/188982657-1e095a30-2b19-4617-8db5-0e97e0da8d4a.png)
![image](https://user-images.githubusercontent.com/58657617/188982779-f849f0c3-c423-44aa-8a20-23e2c09ae1da.png)

### To Reproduce

1. Either put system theme to dark or in firefox (desktop only) go to preferences, general, language and appearance, website appearance and put dark
2. go to piped preferences and set auto theme

### Expected behavior

The website finds out the system/browser theme is dark theme

### Logs/Errors

.

### Browser, and OS with Version.

Firefox 104 on linux / android / 105 android (outdated nightly) / 106 (updated nightly)
not reproducible on chromium android (and system theme is not supported on chromium linux

### Additional context

no problem with piped dark / light theme, neither with auto and system light, only auto and system dark

**Comment by FireMasterK** [comment]
The bug is caused by the recent migration from windicss to unocss, the `@dark` doesn't work as a variant group. I have already filed an issue upstream.
