### ISSUE TITLE
Does piped use end-to-end encryption on user's personal data?

### ISSUE THREAD

**Issue by Raj2032** [TeamPiped/Piped#1407]
### Describe your question

Does piped store all of my subscribed and previously watched videos and any other information about me using end-to-end encryption on my account?

**Comment by Bnyro** [comment]
The watch history isn't stored on Piped, only locally in your browser or LibreTube.
Your data is stored in a database, but only the password is encrypted.
If you're concerned about privacy regarding Piped you could [host your own instance] (https://piped-docs.kavin.rocks/self-hosting).

**Comment by FireMasterK** [comment]
No, Piped does not use end-to-end encryption, since how would you tell the server what channel information you want? End-to-end encryption makes sense when you control the data, such as in messaging apps, in Piped's case it doesn't make any sense.

**Comment by Raj2032** [comment]
@FireMasterK AH right thanks mate.
