### ISSUE TITLE
Allow browser/user to choose between jpeg and webp for all images

### ISSUE THREAD

**Issue by seffs** [TeamPiped/Piped#1414]
### Describe the feature

Let the browser/user decide whether all images (profile pictures, preview thumbnails, etc) should be loaded as jpeg or webp

### Why would this be useful to add?

Safari/Orion in Catalina/Mojave is unable to load webp images. This results in the following welcome page:

![image](https://user-images.githubusercontent.com/46768740/189341769-4adfb387-8705-43d8-b60e-1fe5875512b9.png)

Other alternatives such as Invidious seem to do use jpeg by default, as all images load normally over there.

### Additional context

This feature _might_ be relevant for MacOS Catalina/Mojave users only.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Not planned, the latest versions of all major browsers support webp, in fact YouTube uses webp by default too. Maybe try using a chromium based browser or Firefox?
