### ISSUE TITLE
Channel Name should appear in Rss Feed

### ISSUE THREAD

**Issue by IronMaltese** [TeamPiped/Piped#1415]
### Describe the feature

When adding a Channel's Rss Feed in a reader, every channel is titled Piped - Feed

### Why would this be useful to add?

It would be best to put the channel's name and nothing else in the title

### Concept(s)

![image](https://user-images.githubusercontent.com/89056889/189345384-11275873-56b7-42b0-8e54-1b7f8142a71a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by thecashewtrader** [comment]
Also to add on, currently the base feed looks like:
```atom
  <title>Piped - Feed</title>
  <subtitle>Piped's RSS unauthenticated subscription feed.</subtitle>
  <id>https://piped.kavin.rocks/feed</id>
```
- All channels have the same `id` field, which is supposed to be unique (could include a link to the channel)
- It might be good to rename the links and wording etc. from RSS to Atom, as they are different specifications (a bit nitpicky)
