### ISSUE TITLE
Does piped offer suggested videos like YouTube does?

### ISSUE THREAD

**Issue by Raj2032** [TeamPiped/Piped#1432]
### Describe your question

Based on what you watch and the stuff that you subscribe to, does piped offer suggested videos to users?

**Comment by Bnyro** [comment]
No, Piped doesn't use any background algorithm that creates user profiles and calculates suggestions based on what you watch and subscribed to.

The goal of the project is to give the user as much privacy as possible by keeping the amount of stored user data as small as possible and not to make people "addicted" to watching videos with the help of an algorithm running in the background.

Feel free to ask if you have any further questions or concerns!

**Comment by Raj2032** [comment]
@Bnyro What about on LibreTube? Can this personalisation caculation be done within the app locally?

**Comment by Raj2032** [comment]
@Bnyro I see thanks
