### ISSUE TITLE
Support for importing or exporting history as watchmaker file

### ISSUE THREAD

**Issue by JustAnOkapi** [TeamPiped/Piped#1440]
### Describe the feature

Be able to save your history as a watchmaker file and/or import a watchmaker history file.

### Why would this be useful to add?

Go from YT to Piped without losing my history.

### Concept(s)

https://github.com/sniklaus/youtube-watchmarker

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's not planned currently. If I remember correctly, there's a way at YouTube to export your watch history like a playlist and import that in Piped.
