### ISSUE TITLE
The trending page is empty and login doesn't work

### ISSUE THREAD

**Issue by luciobortoletto** [TeamPiped/Piped#1442]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

In the official piped.kavin.rocks instance the trending page is empty and I can't login nor register.

### To Reproduce

1. Open piped.kavin.rocks
2. The trending pace is empty.

### Expected behavior

I expected the trending pace and the login to work.

### Logs/Errors

I'm on mobile, I don't know how to do this.

### Browser, and OS with Version.

Firefox Focus Nightly 106.0a1 on Android 12 MIUI 13.

**Comment by luciobortoletto** [comment]
![Screenshot_2022-09-13-21-09-12-718_org mozilla focus nightly](https://user-images.githubusercontent.com/52795018/189989038-f9534ccb-5371-430a-87ad-3595094c6748.jpg)
The other instances work.

**Comment by IronMaltese** [comment]
I noticed that the main instance has blocked my traffic more than it hasn't, and since I don't even use a vpn or Tor with the site I'm not sure why it is so strict, is it cloudflare?

**Comment by aboss10123** [comment]
Can confirm this problem has started since 2 days ago afaik. Can not access on either of my machines. And it seems like it may be an api issue.

**Comment by AlyoshaVasilieva** [comment]
If you go to Preferences and reset them, does that change anything? I noticed the same issue recently while filing a bug report but it went away after a pref reset for some reason.

**Comment by RouterCFW** [comment]
> Can confirm this problem has started since 2 days ago afaik. Can not access on either of my machines. And it seems like it may be an api issue.

Same for me doesn’t matter what I do nothing loads

**Comment by luciobortoletto** [comment]
> If you go to Preferences and reset them, does that change anything? I noticed the same issue recently while filing a bug report but it went away after a pref reset for some reason.

No, the problem still remains.

**Comment by luciobortoletto** [comment]
Is there a way to download the subscriptions list?

**Comment by Bnyro** [comment]
> Is there a way to download the subscriptions list?

No, not while the instance is offline. You'll have to wait until it'll become fixed.

**Comment by Bnyro** [comment]
You'll need to use a different instance for now directly by its frontend url, for example piped.mha.fi, yt.jae.fi or watch.whatever.social. 

A list of all public instances can be found [here](https://github.com/TeamPiped/Piped/wiki).

**Comment by deroverda** [comment]
> You'll need to use a different instance for now directly by its frontend url, for example piped.mha.fi, yt.jae.fi or watch.whatever.social. 
> 
> A list of all public instances can be found [here](https://github.com/TeamPiped/Piped/wiki/instances).

But if I've understood correctly, chancing instances means not being able to log in to your account? How come our accounts aren't synchronized and working across all instances?

**Comment by Bnyro** [comment]
> > You'll need to use a different instance for now directly by its frontend url, for example piped.mha.fi, yt.jae.fi or watch.whatever.social. 
> > 
> > A list of all public instances can be found [here](https://github.com/TeamPiped/Piped/wiki/instances).
> 
> But if I've understood correctly, changing instances means not being able to log in to your account? How come our accounts aren't synchronized and working across all instances?
> 
> Edit: typo 

Instances are hosted by individuals, accounts are not synced!

**Comment by Bnyro** [comment]
> I am also having this issue on multiple browsers/devices. also my preferences appears to be broken somewhat. it does not list instances at all. and I cannot select alot of the options. this happens no matter what instance I am on. and randomly my feed and trending just dont load anything since a couple days ago. happens on waterfox, vivaldi, microsoft edge. clearing cache, resetting prefs doesnt work. editing just to add forgot to mention I have tried disabling all extensions.
> ![vivaldi_coMhviZo3Q](https://user-images.githubusercontent.com/113452619/190293219-7d7de5f7-d726-4831-a90e-af18966ff417.png)
> 

The device doesn't matter since the frontend is just not functional while the backend (https://pipedapi.kavin.rocks) and the list of instances (https://piped-instances.kavin.rocks) are down!
Indeed, other instances like watch.whatever.social should not be affected by the outage of the offical instance!

**Comment by matusf** [comment]
Same here, I've copied the failed login request as curl, executed it, saved the outut and this is the result. 502 Bad Gateway 
![image](https://user-images.githubusercontent.com/18228995/190619482-edddf86a-b2d8-4807-8ee3-85be7616fbab.png)

Seems to be issue with CORS. This is an error from console 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.kavin.rocks/login. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
```

**Comment by luciobortoletto** [comment]
Now everything is working well for me
