### ISSUE TITLE
Video ID starting with - doesn't load

### ISSUE THREAD

**Issue by projectgoav** [TeamPiped/Piped#1443]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Video ID `-BP7DhHTU-I` (Minecraft in Minecraft with Redstone) fails to load. 

On Firefox: 
`Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.` displayed in JS console. Requests fail to complete and no video loads. 

![image](https://user-images.githubusercontent.com/6363155/190222533-5f344071-c0cb-42d7-b312-f30ea4d57e10.png)

On Edge (Chromium): No error is displayed and it appears the network requests have completed, but video still doesn't load. 

![image](https://user-images.githubusercontent.com/6363155/190223042-9087b63d-de23-44f8-95be-11792939e628.png)

### To Reproduce

https://piped.kavin.rocks/watch?v=-BP7DhHTU-I

### Expected behavior

Video loads

### Logs/Errors

See above

### Browser, and OS with Version.

Windows 10 Pro 19043.1889

Firefox: 104.0.2 (64bit)
Edge (Chromium): 105.0.1343.33 (64bit)

**Comment by Bnyro** [comment]
It works perfectly fine for me, it's probably been due to the recent api downtime :)
