### ISSUE TITLE
Chapter toggle shown even on videos without chapters

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1455]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

A button that says "Chapters" is shown next to "Minimize Description", even on videos with no chapters. Pressing it doesn't do anything.

![Non-working button](https://user-images.githubusercontent.com/1284317/191039238-278f5021-8a7f-4d02-8bd9-e65619f88432.png)

### To Reproduce

1. Open https://piped.kavin.rocks/watch?v=-bnW_NmLsTQ
2. See Chapters button
3. It doesn't do anything

### Expected behavior

Button should only appear on videos with chapters. Also, maybe it should have the same height as the Description button.

### Logs/Errors

N/A

**Comment by Bnyro** [comment]
Oh, right, I already fixed that for EFY but not for the current frontend yet
