### ISSUE TITLE
Block autoplay of videos

### ISSUE THREAD

**Issue by EdwardLangdon** [TeamPiped/Piped#1462]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The Video plays automatically even though `AutoPlay` setting is off in preferences.

### To Reproduce

1. Open a Channel/Feed/Playlist
2. Click the Video from same page.
3. Observe the Video being played automatically.

### Expected behavior

The Video should not autoplay at all under any circumstances.

The video doesn't autoplay when opened using 'Open link in new Tab' or reloaded in the same page as described in reproducing.

### Logs/Errors

https://user-images.githubusercontent.com/101938856/191264637-825ccca7-2e84-4fc5-b7dc-367e604b66cb.mp4

Disclaimer : The Video was recorded weeks ago in EFY redesign test site but the issue still persists on the current UI too.

### Browser, and OS with Version.

Brave 1.43.93 on Windows 11 Build 22000.978

**Comment by Bnyro** [comment]
Even when hard coding it as disabled in the code, it starts playing.
I suspect it to be an issue with the `shaka-player`, maybe we should open an issue there if nobody else has an enlightenment :)

**Comment by EdwardLangdon** [comment]
@Ammako Thanks for the heads up !

It's working.
