### ISSUE TITLE
Add youtuber's playlist tab.

### ISSUE THREAD

**Issue by njihil** [TeamPiped/Piped#1464]
### Describe the feature

Greetings, this is Njihil. I really want to access the playlist tab we get when we open a youtuber's page. Like there are some youtubers, who remove their video from the videos tab, and keep it under a playlist in their channel. I wanna gain access to that.

### Why would this be useful to add?

It would help me to access and watch my fav content in piped, without any google interference. 

### Concept(s)

maybe add it near the subscribe button when opened some youtuber's videos page

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by EdwardLangdon** [comment]
This isn't possible unless NewPipeExtractor supports it.
