### ISSUE TITLE
Shorts videos tagged as live feed

### ISSUE THREAD

**Issue by IkelAtomig** [TeamPiped/Piped#1465]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Shorts videos are tagged as Live inside the channel.

### To Reproduce

1. See a shorts video in feed
2. Go to the channel
3. You will see it tagged as `live`

### Expected behavior

It should be tagged shorts on both pages.

### Logs/Errors

![image](https://user-images.githubusercontent.com/101938856/191290728-6e2fe540-6e34-45ef-9907-aac264c74422.png)

In Feed

---

![image](https://user-images.githubusercontent.com/101938856/191290838-588a3ecf-01c7-4af6-b402-060175bb23da.png)

In Channel

**Comment by Bnyro** [comment]
That's not an issue anymore as we're using a different way to determine whether a video is a short now.
