### ISSUE TITLE
SelfHost(Docker Compose)(Caddy) failed with experimental_http3

### ISSUE THREAD

**Issue by ericvicenti** [TeamPiped/Piped#1469]
### Official Instance

self-hosting issue

### Describe the bug

Followed the Docker-Compose-AIO guide here: https://piped-docs.kavin.rocks/docs/self-hosting/

Caddy failed with the following: `Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:4 - Error during parsing: unrecognized protocol option 'experimental_http3'`

FIX THAT WORKED FOR ME: comment out "experimental_http3" from `Piped-Docker/config/Caddyfile`

Issue in source file: https://github.com/TeamPiped/Piped-Docker/blob/95e20fa87d6f177deb069d5a84768a21b7c1fda9/template/Caddyfile#L4

### To Reproduce

Followed the Docker-Compose-AIO guide here: https://piped-docs.kavin.rocks/docs/self-hosting/

### Expected behavior

Caddy should be able to load config

### Logs/Errors

```
caddy           | Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /etc/caddy/Caddyfile:4 - Error during parsing: unrecognized protocol option 'experimental_http3'
```

### Browser, and OS with Version.

Debian 11, latest docker and docker-compose

**Comment by moltenkaizen** [comment]
Same issue here.

**Comment by Soochaehwa** [comment]
`experimental_http3` option has been removed in caddy 2.6
https://github.com/caddyserver/caddy/releases/tag/v2.6.0
