### ISSUE TITLE
Decrease the Size of Player.

### ISSUE THREAD

**Issue by njihil** [TeamPiped/Piped#1482]
### Describe the feature

The player size of every video in the site is increased somehow, i've tried zooming out, but that didn't worked. And no i don't have any ultrawide extension or something. It wasn't like that always, around 7 days ago it was all good. 
![image](https://user-images.githubusercontent.com/112888348/192296729-e1fee82c-5fa7-454a-80e5-9bdf8e8c6662.png)

### Why would this be useful to add?

The player can't even fit in my screen, and i am not a fullscreen person. This would help me a lot to enjoy the content from my fav content creators.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by imyourhuckleberry6** [comment]
i second this. must be a mistake of some kind. no option to 'fix' it in the settings either. it looks awful in this fullscreen mode. who would deliberately do this. it must be a mistake. hopefully will be fixed soon.

**Comment by techgamers2** [comment]
exactly pls return back tht prevoius theatre mode

**Comment by rootedetc** [comment]
This was fixed for a few days for me, but returned as an issue just recently.

**Comment by thecashewtrader** [comment]
@rootedetc Do you still have this issue? It seems to be fixed for me.

**Comment by rootedetc** [comment]
> @rootedetc Do you still have this issue? It seems to be fixed for me.

Fixed for me aswell.
