### ISSUE TITLE
Search watch history.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1487]
### Describe the feature

Search for a video from your watch history.

### Why would this be useful to add?

You need to search for a video from the viewing history.

### Concept(s)

No.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Use Ctrl + F, such functionality doesn't exist on YouTube either.
