### ISSUE TITLE
Create playlists without an account.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1489]
### Describe the feature

It's fun to add playlists without logging in and without registration.

### Why would this be useful to add?

It's even better to create a playlist without logging in.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
There are currently no plans for this since currently, keeping up-to-date information about videos is not feasible on a large scale.
