### ISSUE TITLE
Number of dislikes in comments.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1499]
### Describe the feature

Show the number of dislikes in the comments.

### Why would this be useful to add?

The number of dislikes will appear.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
There's no such thing as dislikes on comments on YouTube.
