### ISSUE TITLE
New sections when you click on a channel

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1500]
### Describe the feature

When you click on a YouTube channel, the other YouTube channels section related to the channel and the About section.Playlists,Home page, Short and live videos.

### Why would this be useful to add?

Easy access to channel related channels.

### Concept(s)

On YouTube, the channels and about section

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by IkelAtomig** [comment]
Only need to add `About`. So, better rename this issue.

**Comment by khusroohayat** [comment]
@IkelAtomig can i work on this?

**Comment by Bnyro** [comment]
That won't be possible without changes in the NewPipe Extractor, so there's nothing you could do about it currently even if you wanted to.

**Comment by IkelAtomig** [comment]
> @IkelAtomig can i work on this?

Ah, That's your wish. I think you misunderstood me as team memebr because of the Contributor Tag ?

**Comment by FireMasterK** [comment]
@khusroohayat feel free to submit a PR to [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor) to add support for this! :) After which, the Piped side of things can be worked on too!
