### ISSUE TITLE
Translator function in comments.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1502]
### Describe the feature

The function of translating comments into the language of our choice.

### Why would this be useful to add?

Even if we don't know the language, we can read the comments.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by jae1911** [comment]
Maybe using [Lingva Translate](https://github.com/thedaviddelta/lingva-translate) since the software has public API endpoints?

**Comment by Fertanima** [comment]
No

**Comment by Fertanima** [comment]
Lingva Translate is not good.

**Comment by Bnyro** [comment]
I'd rather use LibreTranslate because it's fully open source and not related to Google. But still, I don't think that feature should be part of Piped...

**Comment by jae1911** [comment]
I had the problem of LibreTranslate being painfully slow when I was hosting it.

**Comment by Bnyro** [comment]
Not planned for now.
