### ISSUE TITLE
Hey, not sure where to put this, but "piped" kinda sounds like a porn site.

### ISSUE THREAD

**Issue by ChungusHook** [TeamPiped/Piped#1506]
### Describe your question

just something i felt like mentioning.

**Comment by IronMaltese** [comment]
I can't even count the amount of times I've mentioned Piped to people and got that exact response

**Comment by pc00per** [comment]
Yes. Piped (YouTube ingeneral), is infact, a porn site, but without any intercourses.
There, actors b@ng each other. Here YouTube bangs you (& your time, data & privacy)...

Heck, even YouTube has "tube" in it, which doesn't make it sound less pornish than piped...¯\\\_(ツ)_/¯

**Comment by Mhowser** [comment]
I think y'all watch way too much porn 🤨

If you do want a new name suggestion, how about Tubular?

**Comment by jae1911** [comment]
> I think y'all watch way too much porn raised_eyebrow
> 
> If you do want a new name suggestion, how about Tubular?

What about "ILoveHavingSomePrivacyWhileWatchingMyFavouriteContentCreatorsOnTheInternet" or ILHSPWWMFCCCOTI for short.

**Comment by pc00per** [comment]
The true reason is because Piped uses **NewPipe Extractor** as core.
Close this issue, as there's no plan to change names as of now.

**Comment by IronMaltese** [comment]
I don't think this issue should be closed since there's more people that support changing the name than people who don't

**Comment by jae1911** [comment]
Saying it "sounds like a porn site" and "they want to change the name" are totally two different things.

**Comment by FireMasterK** [comment]
The name Piped came since I wanted a really short name, which was two syllables or lesser. I don't think there are any good names currently suggested that are two syllables or lesser. I also don't think it's a good idea to change names just because of a double meaning, there's no trademark issue, etc. There's no real reason to change the name.
