### ISSUE TITLE
Liked videos.

### ISSUE THREAD

**Issue by Bilingest** [TeamPiped/Piped#1516]
### Describe the feature

Bookmarking videos you like.

### Why would this be useful to add?

You like the video, but the process of liking is not related to YouTube. Just the video should go to the Liked Videos section. Similar to a playlist.

### Concept(s)

It would be great to save the videos we like as a Playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
There are no plans to implement this feature, you can use the playlists feature.
