### ISSUE TITLE
Not available on Weblate.

### ISSUE THREAD

**Issue by Bilingest** [TeamPiped/Piped#1520]
### Describe the feature

Not available on Weblate. 

### Why would this be useful to add?

![Screenshot_20221002-075743_Chrome](https://user-images.githubusercontent.com/114754527/193437226-9490c7d7-8154-4f69-9823-c7c8b0901cd9.jpg)
![Screenshot_20221002-075642_Chrome](https://user-images.githubusercontent.com/114754527/193437228-e37acc99-79a7-4d4f-b7d3-06793c9eaf94.jpg)
![Screenshot_20221002-075507_Chrome](https://user-images.githubusercontent.com/114754527/193437229-a43a1343-0a0d-4524-b437-a36b4e633db9.jpg)

### Concept(s)

No

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bilingest** [comment]
Why?

**Comment by Bnyro** [comment]
1. The screenshot doesnt make sense in combination with the title
2. You already opened another issue for Weblate
