### ISSUE TITLE
Number of comments and replies.

### ISSUE THREAD

**Issue by Bilingest** [TeamPiped/Piped#1522]
### Describe the feature

The number of comments and replies should be indicated.

### Why would this be useful to add?

We need to know their number.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are already two open issues for it, one for comments and one for replies
