### ISSUE TITLE
Trend improvement.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1526]
### Describe the feature

Add a Music and Movies section to the Trending section.

### Why would this be useful to add?

What are the Trending Music and Movies.

### Concept(s)

You have added only General section. No music here.

### Additional context

YouTube has this feature

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
The NewPipe Extractor doesn't support it currently and probably never will since it's not built for music players primarily.
