### ISSUE TITLE
Search results are empty or blank

### ISSUE THREAD

**Issue by javierxio** [TeamPiped/Piped#1528]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

No results are returned when requesting a search

### To Reproduce

1. URL:  https://piped.kavin.rocks/results?search_query=jimmy+dore
2. Blank results

### Expected behavior

Should return videos by Jimmy Dore

### Logs/Errors

`Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=jimmy+' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=jimmy+:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=ji' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=ji:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=jimmy+do' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=jimmy+do:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=jo' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=jo:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=joe+ro' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=joe+ro:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=joe+' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=joe+:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=joe+rogan' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=joe+rogan:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=joe+ro' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=joe+ro:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch
results:1 Access to fetch at 'https://pipedapi.kavin.rocks/opensearch/suggestions?query=joe+rogan' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/opensearch/suggestions?query=joe+rogan:1 Failed to load resource: net::ERR_FAILED
SearchSuggestions.vue:62 Uncaught (in promise) TypeError: Failed to fetch`

### Browser, and OS with Version.

Chromium 91
Chrome Version 106.0.5249.91 (Official Build) (64-bit)

**Comment by javierxio** [comment]
The homepage is also blank.

![image](https://user-images.githubusercontent.com/63758477/193700427-6e93581b-78db-432f-9dbb-1eb86f2e0e92.png)

**Comment by javierxio** [comment]
`Access to fetch at 'https://pipedapi.kavin.rocks/trending?region=US' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/trending?region=US:1 Failed to load resource: net::ERR_FAILED
(index):1 Uncaught (in promise) TypeError: Failed to fetch
(index):1 Access to fetch at 'https://pipedapi.kavin.rocks/config' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
pipedapi.kavin.rocks/config:1 Failed to load resource: net::ERR_FAILED
(index):1 Uncaught (in promise) TypeError: Failed to fetch`

**Comment by FireMasterK** [comment]
Does this still happen?

**Comment by javierxio** [comment]
> Does this still happen?

Looks to be good right now.

**Comment by javierxio** [comment]
I accidentally closed the issue and reopened.

**Comment by FireMasterK** [comment]
But if the issue doesn't happen, why did you re-open it?

**Comment by javierxio** [comment]
I didn't know that I could close. I will close now, thanks. @FireMasterK
