### ISSUE TITLE
Audio only mode - server load

### ISSUE THREAD

**Issue by kradant** [TeamPiped/Piped#1530]
### Describe your question

I wonder about the audio only mode functioning. Does the audio only mode reduce the carbon footprint of streaming? 

In other words, does the audio only mode reduce the effective server load? And do you know by how much? 

Thank you!

**Comment by FireMasterK** [comment]
Yes, there is a significant reduction in server bandwidth load. The difference compared to a 1080p video is close to 15x. I'm not sure about the carbon footprint though.
