### ISSUE TITLE
slow CPU usage increase on v2

### ISSUE THREAD

**Issue by numselli** [TeamPiped/Piped#1532]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

CPU usage spikes after about 12 minutes of video playback

### To Reproduce

1. Open any video that is about 15 minutes long ([Video I noticed it with](https://ui-v2.piped.pages.dev/watch?v=J0IMc6sigXE))
2. Open system task manager or  the browsers task manager
3. Sort task manager by top CPU usage
4. Watch the video, at about 12 minutes in the video gets very choppy and the CPU usage spikes to about 400%

### Expected behavior

CPU usage should stay steady at around 30%

### Logs/Errors

Deprecation warning for Event.path

### Browser, and OS with Version.

Brave Version 1.41.100  Chromium: 103.0.5060.134 on Arch linux

**Comment by FireMasterK** [comment]
UI v2 is no longer under development, you should look at EFY - the current efforts on a new UI: https://efy.piped.pages.dev/

**Comment by numselli** [comment]
This issue is occurring on EFY as well
