### ISSUE TITLE
Loading Issues possibly due to proxies or filtering.

### ISSUE THREAD

**Issue by sneakyp07** [TeamPiped/Piped#1535]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I am on school chromebook and I used this site to watch youtube, and the site will work maybe 1 or 2 days out of the week, usually wednesday or saturday, but the rest of the time I load into the website and it doesn't show anything the whole time and you cannot use the website, or it will load the front page but not anything else, or only load the front page and videos on the front page but you cannot search. Sometimes everything will load but the video itself. It might be due to the schools preloaded proxies and filters and such, but it is strange that sometimes the webpage decides to load sometimes. 

### To Reproduce

Go to the main website

### Expected behavior

the website should have loaded the front page, videos, and video previews on search.

### Logs/Errors

n/a (school disables inspect element and console)

### Browser, and OS with Version.

Google chrome on Dell Chromebook with chrome os.

**Comment by javierxio** [comment]
I think this is related:  https://github.com/TeamPiped/Piped/issues/1528

I found a workaround by going into Preferences and changing to a difference instance in the drop-down menu:

![image](https://user-images.githubusercontent.com/63758477/195161591-1f1f6fc1-dc28-46a6-8b3f-959276ecee06.png)
