### ISSUE TITLE
Delete watched videos.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1539]
### Describe the feature

Delete watched videos before and after they are added to the playlist.(Option).

### Why would this be useful to add?

If we want to delete the videos we watched from the playlist.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I'm not a fan of the idea, such functionality doesn't exist on YouTube either. What I find a potential alternate workaround for this feature request is maybe a progress indicator for how much of the video is already watched. You can delete videos easily in one click anyways.
