### ISSUE TITLE
Sort related content.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1540]
### Describe the feature

Sort related content:
1.All.
2.Related.
3.Same Author
4.What you watch.
5. Latest upload
6. From your search
7. LİVE
8. Shorts
9. Trending.

### Why would this be useful to add?

Let us choose what to display in related content.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
There are only 20 related videos per video so sorting or filtering them doesn't make a lot of sense.
