### ISSUE TITLE
Number of subscriptions in the player.

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1542]
### Describe the feature

The number of subscriptions is not displayed in the player.

### Why would this be useful to add?

It was useful to see the number of subscriptions in the player.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by vanduc1102** [comment]
Hello, I am seeing the subscriptions count in playing screen, 
![Screen Shot 2022-10-07 at 23 05 46](https://user-images.githubusercontent.com/3014017/194598600-f0aeb25b-7cb0-4ed5-bcaf-5114631187c8.png)

Is it expected for the ticket ?

**Comment by Bnyro** [comment]
Yep, they're already visible :)
