### ISSUE TITLE
Feeds for groups of channels

### ISSUE THREAD

**Issue by LordMZTE** [TeamPiped/Piped#1546]
### Describe the feature

This feature would allow creating feeds, but instead of showing videos from all subscriptions, only those from a certain selection of channels would be shown.

### Why would this be useful to add?

This would be useful as a more powerful alternative to youtube's notification system.

A user might not want to miss videos from certain channels which would otherwise "get lost" in the normal feed.

Aside from that, it would also be useful for grouping certain topics.

### Concept(s)

- This could be accessed through a button in the top right, next to feed maybe?
- The UI could look similar to playlists.
- It'd be useful to keep track of videos the user has already watched and maybe mark those.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by thecashewtrader** [comment]
I'm not sure if a frontend is the best place to add this kind of a feature, but I'll let Kavin decide. For now, you can use RSS feeds to achieve the same but with a much easier and comfortable interface. They also work for many other services.

Self promotion, but I wrote an article about this some time ago: [ A More Elegant Way Of Using (Not Just) YouTube ](https://rehantdaphedar.xyz/posts/a-more-elegant-way-of-using-not-just-youtube/)

**Comment by LordMZTE** [comment]
You're right! It is a more elegant solution indeed!

**Comment by Serralq** [comment]
I've read your article and it's a good solution, but I think it would still be beneficial to have this feature. Some apps, like LibreTube, depend on this repo and would only implement the feature if upstream also had this feature (https://github.com/libre-tube/LibreTube/issues/1267). The only RSS feed I use on mobile is YouTube so having the RSS feed integrated into the LibreTube would allow me to not switch back to my RSS feed app every time I finish a video just to go back to LibreTube.
