### ISSUE TITLE
Instance: change domain and add new location

### ISSUE THREAD

**Issue by Deon-Trevor** [TeamPiped/Piped#1551]
### Describe your question

I couldn't edit the wiki. Please change:

Front-end: https://piped.syncpundit.com/ ==> https://piped.syncpundit.io/
API: https://pipedapi.syncpundit.com/ ==> https://pipedapi.syncpundit.io/
Proxy: https://pipedproxy.syncpundit.com/ ==> https://pipedproxy.syncpundit.io/
Location: USA, UK
CDN: Cloudflare

**Comment by FireMasterK** [comment]
Updated, thanks for the info!

**Comment by Deon-Trevor** [comment]
> Updated, thanks for the info!

I've added yet a new location: Japan. Please update, thanks so much

**Comment by FireMasterK** [comment]
Updated, thanks!
