### ISSUE TITLE
Watch history improvement.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1563]
### Describe the feature

Sort videos in Watch History by day of the week.

### Why would this be useful to add?

Thanks to this sorting, we can see the days we watched the videos.

### Additional context

YouTube has this feature.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Shadowspear123** [comment]
It would also be nice to be able to delete individual videos from the watch history.

**Comment by Bnyro** [comment]
Duplicate of #1379
