### ISSUE TITLE
No feed found error on feedbin

### ISSUE THREAD

**Issue by specter78** [TeamPiped/Piped#1567]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

On subscribing to `piped.kavin.rocks` feed using feedbin, I am consistently getting no feed found error.

See https://github.com/feedbin/feedbin/issues/682

### To Reproduce

1. Try opening the following feed in Feedbin - https://pipedapi.kavin.rocks/feed/unauthenticated/rss?channels=UC2S0KiGusFDXWcxwEorulsA
2. Error: No feed found

### Expected behavior

Piped RSS should work with feedbin.

### Logs/Errors

NA

### Browser, and OS with Version.

Any

**Comment by Bnyro** [comment]
I've added the feed to Read You on Android and it just works normal as intedend, so it seems like Feedbin requires some additional setup because it handles feeds in a different way than other feed readers?
Did you test other feed urls or feed readers too?

**Comment by specter78** [comment]
I also emailed feedbin and this was their response:

> Unfortunately Feedbin is currently blocked by this feeds publisher. This would need to be fixed on their side. 
> Due to the volume of feeds that Feedbin crawls this can sometimes trigger false positive “protection” measures. This would need to be fixed by the publisher. Feedbin’s traffic can be authenticated using a standard mechanism: https://feedbin.com/help/verifying-feed-requests/

**Comment by FireMasterK** [comment]
This should be fixed?

**Comment by specter78** [comment]
> This should be fixed?

Yes. Thank you.

On a side note, all feeds are presently titled `Piped - Feed`. Instead, they should be titled with either the channel name or playlist name.
