### ISSUE TITLE
How to import playlist backup from TXT files?

### ISSUE THREAD

**Issue by nanedi** [TeamPiped/Piped#1568]
### Describe the feature

Hi

How to import playlist backup from TXT files?

Thanks

### Why would this be useful to add?

If an instance disappears, then I can also transfer the playlist to another instance.

### Concept(s)

Import playlist backup from TXT files.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible yet, there's already an open issue for it.
The download as txt is meant for downloading the playlist content with 3rd party tools, e.g. `yt-dlp -a {filename}`.
