### ISSUE TITLE
Some videos can't be played

### ISSUE THREAD

**Issue by muznyo** [TeamPiped/Piped#1570]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Some videos can't be played on Firefox and it doesn't matter which instance (I already tried watch.whatever.social and piped.kavin.rocks)

On chromium based browser I could watch them without any issue.

### To Reproduce

1. Play a video, for example [this one](https://watch.whatever.social/watch?v=XErLwPxBJZw)
2. The video does not play, black screen is shown, time is stuck at 0:00

### Expected behavior

The video should play without any issues.

### Logs/Errors

![photo_5931762440855468238_w](https://user-images.githubusercontent.com/24987471/195947251-d48ac17f-b43c-4ce3-9af3-b919089fe1f4.jpg)

### Browser, and OS with Version.

Firefox 105.0.2
Fedora Linux 37

### Additional context

I found out if you enable **Disable LBRY for Streaming** check in Preferences page, the videos start playing without issues, but it's a workaround and that check isn't enabled by default.

**Comment by Bnyro** [comment]
Can be played perfectly for me too on Firefox. The browser warning indicates that the failure was due to it being unable to fetch the stream source from Odysee, so maybe there was just a server outage or something like that there maybe? Could you please try playing the video again after disabling LBRY in the settings?

**Comment by FireMasterK** [comment]
Can you try with a fresh profile? I believe you have tweaked `about:config` which is most likely causing issues here.

**Comment by muznyo** [comment]
> Can be played perfectly for me too on Firefox. The browser warning indicates that the failure was due to it being unable to fetch the stream source from Odysee, so maybe there was just a server outage or something like that there maybe? Could you please try playing the video again after disabling LBRY in the settings?

yes it seems like it was a server outage, it works now, so i am closing this issue.
