### ISSUE TITLE
Icons in RSS channel feeds

### ISSUE THREAD

**Issue by LordMZTE** [TeamPiped/Piped#1609]
### Describe the feature

This feature would add icons for the RSS reader to display in RSS feeds of channels. The feed's Icon could be the channel icon (if the feed is only for one channel), whereas the thumbnail could perhaps be included in the RSS body.

### Why would this be useful to add?

It would make it easier to spot channel uploads in RSS feeds.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by RetroAbstract** [comment]
+1. Feed icons being channel icons in 48x48 would be ideal
