### ISSUE TITLE
Public Playlists (And Private Playlists)

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1610]
### Describe the feature

More playlists feature similar to what Invidious offers.

### Why would this be useful to add?

- Public Playlists (Playlists that can e found by anyone searching on the Piped instance)
- Private Playlists (Playlists that can only be accessed by the user who created them. Not unlisted playlists which can be accessed

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I don't think this is a good idea, I highly doubt there's an audience for people who want to share playlists with other Piped users.

**Comment by luckkmaxx** [comment]
Hi there, I was thinking that could be fine.
My case y that I want to share some of my playlists with my wife and sons (wich has a user account in my own instance), but there is only option to share bookmarks but not local playlist. Only is able to share videos one by one with piped or youtube link.
