### ISSUE TITLE
What Happen To The View On YouTube Button?

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1611]
### Describe the feature

There used to be a "View On YouTube Button?" which when clicked on will take you to that video on youtube.com. Please bring this button back and please also add a button for [playlists and channels](https://github.com/TeamPiped/Piped/issues/803).

### Why would this be useful to add?

- To quickly go to the video on youtube.com.
- To quickly bookmark the video with the youtube.com URL and not the Piped instance URL.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by thecashewtrader** [comment]
I could implement this, I just need confirmation that the view on YouTube button removal was accidental/should be reversed.

**Comment by FireMasterK** [comment]
Well, it was replaced by the share button, which has a "Follow Link" button just for this. However, currently, it's quite tedious to generate a YouTube link, so a new UX should be thought of.

**Comment by Bnyro** [comment]
Well, to bring in an other opinion and show my intention of replacing the watch on YT button with a share dialog, here my arguments against re-adding such a button:

1. The button just opens the video on YT directly, without any Proxy or VPN or so in between. As Piped has the goal to improve user's privacy, like that it still makes it way too easy to use YT directly and expose personal data such as the IP address.
2. The share dialog requires the user to do two more steps: Untick the `Piped link` checkbox and press the follow link button. Therefore users have to think more about whether it makes sense to manually choose to get a YT link and open it.
3. Apart from that it's planned to remember the latest used config of the share dialog and therefore, although I'm not a fan of it, following the link would only be two clicks: Open the share dialog, then follow the link.

However, if adding such a button I'd prefer it to be optional and disabled by default as new users for example might not know what the button exists for and accidentally click it just to find themselves afterwards where they've been trying to avoid landing in the end: at YT without a VPN.

**Comment by thecashewtrader** [comment]
@Bnyro How does having a YouTube button enabled by default but asking for confirmation (Vanilla JS `confirm()`), with a config option to disable the confirmation sound?

**Comment by thecashewtrader** [comment]
> I'll have to check how other messaging apps behave.

That's an issue/deficiency in Piped which is [being worked out](https://github.com/TeamPiped/Piped/issues/1362), in 99% of cases other messenger apps won't work any different.

**Comment by Bnyro** [comment]
> @Bnyro How does having a YouTube button enabled by default but asking for confirmation (Vanilla JS `confirm()`), with a config option to disable the confirmation sound?
>
That makes it just way more complicated than needed, apart from that I think it'd be way better if the button was hidden at all if disabled. I doubt a confirm prompt makes sense here, apart from that just adding an option to disable a prompt feels a bit unneeded.

**Comment by thecashewtrader** [comment]
@Bnyro Aight, I'll work on implementing your original suggestion (opt in for the button), but it might take a bit since I'm busy this week 😅

**Comment by Bnyro** [comment]
Otherwise I could do it as well, I just wanted to work on some other issues here too to avoid crushing the 200 open issues :joy:
