### ISSUE TITLE
Hide Recommended Videos Setting

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1613]
### Describe the feature

To make Youtube less addictive, please add settings to show/hide the recommended videos (videos along the side of a video page)

### Why would this be useful to add?

Reduce time spent on Piped/YouTube. Ethical settings to avoid Google want to grab your attention.

### Additional context

There is a setting to show comments, please add one for recommended videos.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/197363448-95774bc7-4457-4ddf-b410-dddda3eb43d6.png)

Already exists as a preference.
