### ISSUE TITLE
Helm chart for Kubernetes deployments

### ISSUE THREAD

**Issue by samip5** [TeamPiped/Piped#1622]
### Describe the feature

Option to install via Helm

https://helm.sh/

### Why would this be useful to add?

It would make it more simple and scalable to deploy the full app on a Kubernetes cluster.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I'd love to support a helm/k8s deployment of Piped, but I have no clue how they work at all, unfortunately!

**Comment by samip5** [comment]
> I'd love to support a helm/k8s deployment of Piped, but I have no clue how they work at all, unfortunately!

First question would be that should the chart live inside the same repository as the app itself or should it be in a separate repository?

**Comment by FireMasterK** [comment]
I would say a new repository, since we've got multiple components - the frontend, backend, proxy, a reverse proxy for caching, etc

**Comment by samip5** [comment]
Hmm, the issue probably actually belongs to the Docker repository, but probably one for Kubernetes makes sense. I have my own charts at samipsolutions/helm-charts and I can try to get it going there first which would become artifacthub discoverable too.

What are you thoughts on creating a new repository under TeamPiped and adding me as outside collaborator on it?

**Comment by samip5** [comment]
I created a repo for it called Piped-Kubernetes as that seems to be the syntax of the other ones. :)

**Comment by FireMasterK** [comment]
That works! Thanks for the help! :)

**Comment by samip5** [comment]
@FireMasterK I have faced an obstacle and that has to do with ytproxy requiring to use sockets, that's not possible when the container is not running inside the same pod, much less host.

I believe this is blocked by https://github.com/TeamPiped/http3-ytproxy/pull/3 / https://github.com/TeamPiped/http3-ytproxy/pull/2.

**Comment by peerau** [comment]
> that's not possible when the container is not running inside the same pod, much less host.

use a PVC, and bind the Pods to run on the same host. :D

**Comment by samip5** [comment]
> > that's not possible when the container is not running inside the same pod, much less host.
> 
> use a PVC, and bind the Pods to run on the same host. :D

That sounds like a whack hack, but then again it should work... Unless it doesn't get scheduled on the same host.

**Comment by FireMasterK** [comment]
> @FireMasterK I have faced an obstacle and that has to do with ytproxy requiring to use sockets, that's not possible when the container is not running inside the same pod, much less host.
> 
> I believe this is blocked by https://github.com/TeamPiped/http3-ytproxy/pull/3 / https://github.com/TeamPiped/http3-ytproxy/pull/2.

If you don't bind any volumes, it will listen on port 8080!

**Comment by FireMasterK** [comment]
You'd likely want to use https://github.com/TeamPiped/piped-proxy now, it's the new replacement written in Rust!

**Comment by samip5** [comment]
Hey @FireMasterK I'm getting back to working on this. Would it be possible to build a container w/o nginx integrated at all for the frontend?

**Comment by FireMasterK** [comment]
> Hey @FireMasterK I'm getting back to working on this. Would it be possible to build a container w/o nginx integrated at all for the frontend as that does seem quite counter-intuitive for a k8s deployment as there usually is already a reverse proxy already?

The current docker setup has 2 nginx containers - one the frontend, which cannot be removed as it's necessary to serve static files.

The second one is used to link all the services together, and can be removed!

**Comment by samip5** [comment]
> The current docker setup has 2 nginx containers - one the frontend, which cannot be removed as it's necessary to serve static files.

I believe the serving of static files could be handled by express or serve npm packages but probably not worth the dependency?

**Comment by FireMasterK** [comment]
I'd stick with nginx, simply because it's much faster, and more lightweight than express / any npm package.

**Comment by MichaelTrip** [comment]
@samip5 i am very interested in your work. Perhaps we can share our knowledge to get the Helm chart going?

**Comment by samip5** [comment]
> @samip5 i am very interested in your work. Perhaps we can share our knowledge to get the Helm chart going?

I have been meaning on doing it similarly how immich has done theirs. https://github.com/immich-app/immich-charts
What do you think of that approach?

**Comment by samip5** [comment]
Hey, @FireMasterK could we at the very least not have to use sed though the assets on frontend startup? Eg, do it via environment variable? I believe that it should be possible to build the frontend according to the environment variable.

**Comment by FireMasterK** [comment]
> Hey, @FireMasterK could we at the very least not have to use sed though the assets on frontend startup? Eg, do it via environment variable? I believe that it should be possible to build the frontend according to the environment variable.

Yes, but at this moment, that's currently going to be a lot of work to get going, unfortunately.

**Comment by samip5** [comment]
> > Hey, @FireMasterK could we at the very least not have to use sed though the assets on frontend startup? Eg, do it via environment variable? I believe that it should be possible to build the frontend according to the environment variable.
> 
> Yes, but at this moment, that's currently going to be a lot of work to get going, unfortunately.

Could you please elaborate on the `lot of work`? There seems to be a very minor amount of references to `pipedapi.kevin.rocks` domain in the source code.

Did I miss any?

The places I found:

- main.js, line 175
- opensearch.xml, line 9
- components/PreferencesPage.vue, line 438

**Comment by FireMasterK** [comment]
Well, one way could be to include an `entrypoint` script, which reads from an environment variable and then runs sed, which would be simpler indeed.

The proper way to do this is probably to include it as a build config variable and then, build the application. But, I want to avoid building the application at all costs.

**Comment by samip5** [comment]
> But, I want to avoid building the application at all costs.

Why?

**Comment by samip5** [comment]
One option for a Kubernetes deployment at least would be to use a initcontainer (initialization container, that starts before the main app container), that does the following:

- Downloads the already built minifed source code
- Does the sed on the assets
- Gives the assets back to the main container to use via shared volume

**Comment by FireMasterK** [comment]
> Why? It would make sense to dynamically build it based on environment variables on container startup.

The problem is docker. It would be difficult to create a mechanism to auto-update a docker-compose setup.

I could add a Dockerfile to build with build environment variables, would that be of any help?

**Comment by samip5** [comment]
> I could add a Dockerfile to build with build environment variables, would that be of any help?

No but if you could publish the dist-ci folder content in compressed package would help.

**Comment by samip5** [comment]
@MichaelTrip Do you happen to have ideas on how to solve this issue with the frontend as you were wanting to help?

**Comment by MichaelTrip** [comment]
> @MichaelTrip Do you happen to have ideas on how to solve this issue with the frontend as you were wanting to help? The chart should otherwise be functional, but just the frontend portion is not.

Hi,

i Just checked the whole conversation, but the init container seems the most viable option indeed. I have to dive into the source code a bit more to understand the inner working of piped.

**Comment by samip5** [comment]
Correction the chart is mostly functional except for backend at the moment.
I got the sed to work on container startup to use an ENV variable in the subtitution. 
It's not perfect in any way (and could potentially break if container is changed up), but should work for now.

**Comment by samip5** [comment]
@FireMasterK It seems the backend is expecting things that are not in the Docker compose files.

```
Exception in thread "main" java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
        at io.sentry.Sentry.initConfigurations(Sentry.java:219)
        at io.sentry.Sentry.init(Sentry.java:188)
        at io.sentry.Sentry.init(Sentry.java:148)
        at io.sentry.Sentry.init(Sentry.java:134)
        at me.kavin.piped.Main.main(Main.java:37)
```

**Comment by FireMasterK** [comment]
Are you providing an empty string for SENTRY_DSN? 🤔

**Comment by samip5** [comment]
> Are you providing an empty string for SENTRY_DSN? thinking

It doesn't seem to default to that so no, but simple enough fix. :)

**Comment by samip5** [comment]
We have a helm chart now available at https://teampiped.github.io/Piped-Kubernetes/ as a helm repo.
It's still quite WIP, but issues are welcome at that repo about it. :)

**Comment by FireMasterK** [comment]
Could we create a CNAME for it? Like helm.piped.video perhaps maybe? I'll add the records required

**Comment by samip5** [comment]
> Could we create a CNAME for it? Like helm.piped.video perhaps maybe? I'll add the records required

We could yes, and please do. I just have no permissions to change the domain there. :)

**Comment by FireMasterK** [comment]
I also noticed that the current setup doesn't really include any caching, could this be somehow optionally added (not all setups may need it, as you could enable it on Cloudflare with special page rules)?

**Comment by samip5** [comment]
> I also noticed that the current setup doesn't really include any caching, could this be somehow optionally added (not all setups may need it, as you could enable it on Cloudflare with special page rules)?

You mean like varnish? I pretty much duplicated the nginx docker compose setup except for the custom nginx config.

**Comment by FireMasterK** [comment]
> You mean like varnish? I pretty much duplicated the nginx docker compose setup except for the custom nginx config.

Yep, exactly! Varnish doesn't play nice with docker, not sure about kubernetes tho

**Comment by samip5** [comment]
> Varnish doesn't play nice with docker, not sure about kubernetes tho

When you say that, what do you mean? In what aspect doesn't it play nice?

**Comment by FireMasterK** [comment]
It doesn't like dynamic hosts / when the IP changes, it starts giving 503s when that happens. We switched from Varnish to Nginx in the docker compose setup.

**Comment by samip5** [comment]
> Out of curiosity, is there any way to install it with simple `helm repo add` and `helm install` commands?

There is, but I haven't documented them yet.

The default values of the chart might not be the best at the moment.

```
helm repo add teampiped https://helm.piped.video
helm install piped teampiped/piped --version 0.0.4
```

**Comment by samip5** [comment]
I have also added the tldr to README of chart.

https://github.com/TeamPiped/Piped-Kubernetes/tree/main/charts/apps/piped#tldr

**Comment by FireMasterK** [comment]
Awesome! I'm curious, how would updates work for this?

**Comment by samip5** [comment]
Currently it's using the latest tag (like the Docker containers), but it could be automated via eg. Renovate to pin to a specific SHA and then use that as latest tag, but it would be better to actually use release versions of things preferably via [semver](https://semver.org).

It's common practice to use Renovate for automatic updates in Kubernetes environments and it can auto-update the images them self when deployed without the need to always update the chart version.

**Comment by samip5** [comment]
@FireMasterK Do you have an account at ArtifactHUB? If not, please create one so I can invite you to an TeamPiped org there, so that it would show up properly there. :)

**Comment by FireMasterK** [comment]
> Currently it's using the latest tag (like the Docker containers), but it could be automated via eg. Renovate to pin to a specific SHA and then use that as latest tag, but it would be better to actually use release versions of things preferably via [semver](https://semver.org).

I see, but my question is would it periodically keep checking the latest tag to see if there's a new SHA for the image?

> @FireMasterK Do you have an account at ArtifactHUB? If not, please create one so I can invite you to an TeamPiped org there, so that it would show up properly there. :)

Just created one with the username `kavin` or email `kavin@kavin.rocks`!

**Comment by samip5** [comment]
> I see, but my question is would it periodically keep checking the latest tag to see if there's a new SHA for the image?

It wouldn't by itself, only when deploying so the options are as follows for that:

1. Automatic chart bump when a next release is available  (it could become annoying depending on how often it changes and due to wanting to follow semver and may be troublesome in the aspect of the different containers not sharing the same SHA).
2. Specify them in values as pinned SHA, and have Renovate keep them updated (would potentially work, unless a end user changes them/overrides in values).
3. Use actual release versions of all components (would need some versioning scheme, and would be preferred)

I'm not really sure which of the options is good to choose from.

>Just created one with the username kavin

Sent an invite to the org on ArtifactHUB.

**Comment by samip5** [comment]
This was the reason why it's useful to be on ArtifactHUB: https://artifacthub.io/packages/search?ts_query_web=piped&sort=relevance&page=1 :)

**Comment by samip5** [comment]
@FireMasterK Could you please enable the showing of funding links on the Piped-Kubernetes respository?

I have added mine and TeamPiped links to it.

**Comment by FireMasterK** [comment]
It doesn't seem to parse, I don't see it as an option on GitHub.

**Comment by samip5** [comment]
> It doesn't seem to parse, I don't see it as an option on GitHub.

Ah, it had to be inside an array, now it does parse. :)

**Comment by samip5** [comment]
@FireMasterK Can I have secret access on the Piped-Kubernetes repo? I would like to add Self-Hosted Renovate there which would require some secrets and adding my bot access to the repository.

**Comment by FireMasterK** [comment]
But for renovate, why not use the free hosted one online? It's already installed and used in other piped repos

**Comment by samip5** [comment]
> But for renovate, why not use the free hosted one online? It's already installed and used in other piped repos

Because the configs and things I have for Renovate I believe needs the self-hosted version, but could be mistaken.

**Comment by FireMasterK** [comment]
Is there any feature missing in the hosted version? I think it should work fine out of the box with that configuration :thinking: 

We don't need the `schedule-renovate` workflow since renovate is run on every commit/push.

**Comment by FireMasterK** [comment]
That's not right I think, we can schedule updates every month/etc in the config I believe.

**Comment by FireMasterK** [comment]
I don't know either, but the hosted renovate runs on every commit and every few hours. :shrug: It's not our infrastructure, so I don't think its our problem

**Comment by samip5** [comment]
So that's a no for the bot?

**Comment by FireMasterK** [comment]
I mean to say I don't understand the need, but we can have the bot if its really necessary.

**Comment by samip5** [comment]
I have added the Renovate config to the repo, but at least it doesn't appear in the hosted dashboard.

**Comment by FireMasterK** [comment]
Just gave the renovate bot perms for the repo! :)

**Comment by samip5** [comment]
Would it be time to close this issue as we have a helm chart?
