### ISSUE TITLE
Feed API returns 500 Internal Server Error

### ISSUE THREAD

**Issue by goodness-from-me** [TeamPiped/Piped#1628]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Right now the `/feed` api returns 500 Internal Server Error.

### To Reproduce

1. Login to your account.
2. Try to load the feed.

### Expected behavior

`/feed` API call should give 200 OK response with the user feed content.

### Logs/Errors

API response contains this error:
```{"error":"jakarta.persistence.PersistenceException: Converting `org.hibernate.exception.SQLGrammarException` to JPA `PersistenceException` : JDBC exception executing SQL [select v1_0.id,c1_0.uploader_id,c1_0.uploader,c1_0.uploader_avatar,c1_0.verified,v1_0.duration,v1_0.is_short,v1_0.thumbnail,v1_0.title,v1_0.uploaded,v1_0.views from videos v1_0 join channels c1_0 on c1_0.uploader_id=v1_0.uploader_id where v1_0.uploader_id in((select s1_0.channel from users u1_0 join users_subscribed s1_0 on u1_0.id=s1_0.subscriber where u1_0.id=?)) order by v1_0.uploaded desc]\n\tat org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:165)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:374)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:986)\n\tat me.kavin.piped.utils.ResponseHelper.feedResponse(ResponseHelper.java:905)\n\tat me.kavin.piped.ServerLauncher.lambda$mainServlet$29(ServerLauncher.java:263)\n\tat io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)\n\tat io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.hibernate.exception.SQLGrammarException: JDBC exception executing SQL [select v1_0.id,c1_0.uploader_id,c1_0.uploader,c1_0.uploader_avatar,c1_0.verified,v1_0.duration,v1_0.is_short,v1_0.thumbnail,v1_0.title,v1_0.uploaded,v1_0.views from videos v1_0 join channels c1_0 on c1_0.uploader_id=v1_0.uploader_id where v1_0.uploader_id in((select s1_0.channel from users u1_0 join users_subscribed s1_0 on u1_0.id=s1_0.subscriber where u1_0.id=?)) order by v1_0.uploaded desc]\n\tat org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:89)\n\tat org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:109)\n\tat org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:95)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:253)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.getResultSet(DeferredResultSetAccess.java:146)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.lambda$processNext$0(JdbcValuesResultSetImpl.java:89)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.advance(JdbcValuesResultSetImpl.java:274)\n\tat org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.processNext(JdbcValuesResultSetImpl.java:85)\n\tat org.hibernate.sql.results.jdbc.internal.AbstractJdbcValues.next(AbstractJdbcValues.java:29)\n\tat org.hibernate.sql.results.internal.RowProcessingStateStandardImpl.next(RowProcessingStateStandardImpl.java:89)\n\tat org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:142)\n\tat org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:32)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:437)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)\n\tat org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)\n\tat org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$0(ConcreteSqmSelectQueryPlan.java:102)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:305)\n\tat org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:246)\n\tat org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:536)\n\tat org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)\n\t... 8 more\nCaused by: org.postgresql.util.PSQLException: ERROR: column \"v1_0.is_short\" does not exist\n\tat org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)\n\tat org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)\n\tat org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)\n\tat org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)\n\tat org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)\n\tat org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)\n\tat com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)\n\tat com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)\n\tat org.hibernate.sql.results.jdbc.internal.DeferredResultSetAccess.executeQuery(DeferredResultSetAccess.java:217)\n\t... 25 more\n","message":"Converting `org.hibernate.exception.SQLGrammarException` to JPA `PersistenceException` : JDBC exception executing SQL [select v1_0.id,c1_0.uploader_id,c1_0.uploader,c1_0.uploader_avatar,c1_0.verified,v1_0.duration,v1_0.is_short,v1_0.thumbnail,v1_0.title,v1_0.uploaded,v1_0.views from videos v1_0 join channels c1_0 on c1_0.uploader_id=v1_0.uploader_id where v1_0.uploader_id in((select s1_0.channel from users u1_0 join users_subscribed s1_0 on u1_0.id=s1_0.subscriber where u1_0.id=?)) order by v1_0.uploaded desc]"}```

### Browser, and OS with Version.

Firefox 106.0
MacOS 13.0

**Comment by vytskalt** [comment]
It randomly started working for me

**Comment by Bnyro** [comment]
Indeed, Kavin resolved the database issue, everything should be back to normal now :party:
