### ISSUE TITLE
Fixed height for video thumbnail

### ISSUE THREAD

**Issue by igoracmelo** [TeamPiped/Piped#1630]
### Describe the feature

I noticed that when I load the page, the thumbnail has no fixed height. This cause some issues:
- Page scroll
- Visual confusion
- Unecessary layout recalculations (not harmful for this scenario)

https://user-images.githubusercontent.com/85039990/198453245-8b7df001-5805-421b-8e7c-62500c4680ed.mp4

### Why would this be useful to add?

It enhances the user experience, more noticeable with mobile networks.

### Additional context

I would like to work on a PR for this, for getting used with the project.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
> I would like to work on a PR for this, for getting used with the project.

Go for it!
