### ISSUE TITLE
Raspberry pi 4 ubuntu server

### ISSUE THREAD

**Issue by opanch** [TeamPiped/Piped#1639]
### Describe your question

Am having difficulty sitting up piped-docker for my raspberry pi 4 its running Ubuntu 22.04.
I try editing the docker-compose.yaml with 1337kavin/piped:hotspot
every time I run docker-compose up -d
I get and error 

```
Pulling piped (1337kavin/piped:hotspot)...
hotspot: Pulling from 1337kavin/piped
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

**Comment by FireMasterK** [comment]
You have a raspberry pi 4, so why not use a 64-bit operating system? Raspbian supports arm64, and most other distros do too.

**Comment by FireMasterK** [comment]
Closing this as this is not an issue in Piped, you are unable to run arm64 docker images, even though the raspberry pi 4 supports arm64.
