### ISSUE TITLE
Music videos do not load/play

### ISSUE THREAD

**Issue by swgrrt** [TeamPiped/Piped#164]
I have the issues, that some videos do not play. They just show the rotating circle in the player.

Example for video not working: https://piped.kavin.rocks/watch?v=WMweEpGlu_U
Example for video working: https://piped.kavin.rocks/watch?v=u6zsHqdNRQ8

**Comment by FireMasterK** [comment]
This is a known issue, this happens only on Music videos after a few days.

The underlying issue is in NewPipeExtractor.

**Comment by FireMasterK** [comment]
Closing this as this has *technically* been fixed in https://github.com/TeamPiped/Piped-Backend/commit/dd26643ba89dc07e4d95fde0d3ff7bc428dd1254.
