### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by aeongdesu** [TeamPiped/Piped#1649]
### Describe your question

Add my instance!
frontend: https://piped.aeong.one
backend(api): https://pipedapi.aeong.one
proxy: https://pipedproxy.aeong.one
CDN: yes (cloudflare)
country: KR

I also set up cf optimizations from https://github.com/TeamPiped/Piped/issues/737#issuecomment-1014482130 .
😊

**Comment by aeongdesu** [comment]
@FireMasterK can you add to https://piped-instances.kavin.rocks/ too?

**Comment by Bnyro** [comment]
They should be in sync as far as I know, maybe it takes sometime until it's refreshing.

**Comment by aeongdesu** [comment]
> They should be in sync as far as I know, maybe it takes sometime until it's refreshing.

Thank you :)

**Comment by FireMasterK** [comment]
Hi, your instance appears to be failing the healthcheck, is anything wrong with the database?

https://pipedapi.aeong.one/healthcheck

**Comment by aeongdesu** [comment]
@FireMasterK It should be works now, i forgot to reset old databases..

**Comment by FireMasterK** [comment]
Nice, I just verified that it's automatically added to the list now.
