### ISSUE TITLE
Can't watch short video

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1650]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Video doesn't play. I see HTTP 503 errors in devtools.

### To Reproduce

1. Open https://piped.kavin.rocks/watch?v=_dGh7p1tZmk
2. It seems to load all but the very end?
3. Video never plays.

### Expected behavior

Video works.

### Logs/Errors

N/A

### Browser, and OS with Version.

Occurs on both Firefox and Chrome.

### Additional context

Occurs on both official instance and my private instance.

**Comment by Bnyro** [comment]
Tested on different devices and can't reproduce.
