### ISSUE TITLE
"Access to content denied" with unauthenticated RSS feeds

### ISSUE THREAD

**Issue by RetroAbstract** [TeamPiped/Piped#1653]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When adding a Piped RSS feed of a channel without using a Piped account, the RSS reader I use (RSS Guard) is unable to fetch articles from the feed and displays: "Network error: Access to content denied".

Screenshot:

![1](https://user-images.githubusercontent.com/103272301/199255840-050f5361-0510-45cf-95b1-0e4a419db0db.jpg)

### To Reproduce

1. Go to piped.kavin.rocks
2. Do not log in
3. Copy the RSS link of a channel
4. Add it to your RSS reader
5. Notice that Piped is denying access to the link's content

### Expected behavior

The expected behavior is the RSS reader being able to "subscribe" to a channel through the copied Piped RSS feed link from said channel.

### Logs/Errors

None

### Browser, and OS with Version.

Not applicable

**Comment by FireMasterK** [comment]
Is this fixed now?

**Comment by RetroAbstract** [comment]
> Is this fixed now?

@FireMasterK No, same as when I submitted the bug report, still "Network error: Access to content denied".

**Comment by FireMasterK** [comment]
What feed reader are you using?

**Comment by RetroAbstract** [comment]
> What feed reader are you using?

@FireMasterK RSS Guard 4.2.5. Just tested it again and it works fine now. Thanks alot for the quick fix
