### ISSUE TITLE
More information in fetched articles from channels

### ISSUE THREAD

**Issue by RetroAbstract** [TeamPiped/Piped#1656]
### Describe the feature

This is a request to have articles fetched from channels include more information such as the video thumbnail & video description, screenshots for comparison:

### 1. **Current article content when fetched from YouTube RSS feed urls:**

![5](https://user-images.githubusercontent.com/103272301/199282593-b3ec7063-e053-490e-9aaf-80d57595e847.jpg)
![6](https://user-images.githubusercontent.com/103272301/199282602-56f9b216-6e99-47ed-ba0d-6e6586544c2a.jpg)

### 2.  **Current article content when fetched from Piped RSS feed urls:**

![7](https://user-images.githubusercontent.com/103272301/199282631-7106fd13-0a81-4213-8757-7c1b6b856602.jpg)

The ideal result would be having the Piped articles have the same amount of information the YouTube articles have.

### Why would this be useful to add?

A cosmetic improvement that makes articles more pleasent to open & read.

### Concept(s)

See the screenshots in the _Describe the feature_ section.

### Additional context

Regarding the thumbnails, this has also been mentioned [here](https://github.com/TeamPiped/Piped/issues/1328).

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by RetroAbstract** [comment]
@FireMasterK is there a chance of seeing this enhancement, [#1415](https://github.com/TeamPiped/Piped/issues/1415) & [#1609](https://github.com/TeamPiped/Piped/issues/1609) implemented in the foreseeable future?

**Comment by FireMasterK** [comment]
> @FireMasterK is there a chance of seeing this enhancement, [#1415](https://github.com/TeamPiped/Piped/issues/1415) & [#1609](https://github.com/TeamPiped/Piped/issues/1609) implemented in the foreseeable future?

Yes, it's quite simple to do and I would also accept PRs for this. Also, please don't tag me.
