### ISSUE TITLE
Number of view

### ISSUE THREAD

**Issue by Nizami20052022** [TeamPiped/Piped#1669]
### Describe the feature

View count shows how many times we've watched each video in our watch history

### Why would this be useful to add?

Watch history contains watched videos, but we need to know how many times we watched each video personally.

### Concept(s)

![SmartSelect_20221103-125550_NewPipe](https://user-images.githubusercontent.com/104249296/199680696-aac04532-25fb-43ae-9e8d-428e69d59ccd.jpg)

### Additional context

It has nothing to do with the number of views a video has on YouTube.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I don't think this is something that most people want, I feel this is a niche feature that serves almost no purpose for users (why would anyone want to know how many times they've watched the same video?!).
