### ISSUE TITLE
Can't register because of a "compromised" password

### ISSUE THREAD

**Issue by stemy2** [TeamPiped/Piped#1670]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I try to register but it fails every time with the error "the password you have entered has already been compromised".

### To Reproduce

1. Try to register

### Expected behavior

Registration successful.

### Logs/Errors

Not applicable.

**Comment by Bnyro** [comment]
Well, that tells you that you really need to use a different password as yours  is part of public lists with collected, leaked passwords! I'd highly recommend you change the password anywhere you use it and  use a different one!
