### ISSUE TITLE
Exporting Playlist as TXT uses Default Instance URL

### ISSUE THREAD

**Issue by Murmiration** [TeamPiped/Piped#1683]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When exporting a playlist from my own Piped instance to a TXT file, I noticed my instance URL was replaced with the default piped instance URL in the txt contents. I assume the intended behavior is for the txt file to actually have the url of the instance exported from.

### To Reproduce

1. View a Playlist from a 3rd Party Instance
2. Export a TXT of playlist
3. List of urls will display `piped.kavin.rocks` instead of the intended instance url

### Expected behavior

The urls in the TXT would be populated with URLs pointing to the specific instance, rather than the default homeserver.

### Logs/Errors

N/A

### Additional context

As I understand it, the TXT export function is to allow for mass-downloading with a tool (yt-dlp for example), so I am unsure if using the official instance as the host is intended behavior. Thought it best to file the issue anyway in case it isn't.

**Comment by Bnyro** [comment]
Yes, it was intended to always use `piped.kavin.rocks` as `yt-dlp` knows how to handle links from `piped.kavin.rocks` properly. When using links of other instances, it might be possible that `yt-dlp` doesn't recognize the instance URL and therefore running `yt-dlp -a` will just fail and users might try to rebuild there playlist on an other instance - which would be kinda unfortunate as the reason would only be one single line of code :wink:
However, we could still change it if there were any benefits of using the instance url. Apart from that you can just run `sed -i "s/piped.kavin.rocks/{new domain}/g" {filename}` to change it which shouldn't be that hard :)
