### ISSUE TITLE
Improve Piped API: add new url field to a piped instance information

### ISSUE THREAD

**Issue by deivastra** [TeamPiped/Piped#1684]
### Describe the feature

Hello, thanks a lot for Piped!
I didnt found where I should post this issue, so put here. Sorry. Also I sent email to kavin email address.

I have create Chrome extension for automatic redirecting to Piped sites when Youtube link clicked.
It's worked fine, but has one issue:
List of piped instances here: `https://piped-instances.kavin.rocks`, but the instance record not contains a domain name where Piped service started.
For example: 
`{ name: 'kavin.rocks (Official)', api_url: 'https://pipedapi.kavin.rocks', ...}`
So, there is no domain `'piped.kavin.rocks'`, only `api_url`, so I can't redirect there directly.
For all other records the same problem.

Could you add to the instance record a field like `url`. For examle:
`{ name: 'kavin.rocks (Official)', url: 'https://piped.kavin.rocks',  api_url: 'https://pipedapi.kavin.rocks', }`

Thanks a lot!

![piped-icon-128](https://user-images.githubusercontent.com/6850322/200110241-194b1bca-8abc-413b-8630-05038d6ae551.png)

![piped-watch-popup](https://user-images.githubusercontent.com/6850322/200109920-586f06fd-85e5-461e-82a3-0a35a06b639a.png)

### Why would this be useful to add?

Then I will can parse a domain name and then redirect.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Hi there,

This is intensionally done, since I don't want to be policing frontend modifications, and the AGPL.

If you really want the frontend URL, you can fetch the API url and follow the redirect.
