### ISSUE TITLE
[Safari] Watch on and Share icons are not visible

### ISSUE THREAD

**Issue by goodness-from-me** [TeamPiped/Piped#1687]
### Official Instance

- [x] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

On Safari "Watch on Youtube" and "Share" SVG icons are not being rendered:
![image](https://user-images.githubusercontent.com/42966950/200191595-8715c53d-6675-4c44-8b17-9a461013cde5.png)

### To Reproduce

Having recent Safari browser (16.1) in my case.
1. Open any video.
2. Observe the "Watch on" and "Share" buttons.

### Expected behavior

Icons should be displayed on Safari.

### Logs/Errors

No logs/errors.

### Browser, and OS with Version.

MacOS 13.0
Safari 16.1

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/200205986-1c61f0cc-b4c2-4127-b46c-da63b5a18033.png)

Things work fine on Safari 15.6, I don't have Safari 16.1 on a mac available to test. However, things work fine on iOS with Safari v16.0.

**Comment by goodness-from-me** [comment]
Nevermind, it was my content blocker :(
