### ISSUE TITLE
"Odia" translation completed

### ISSUE THREAD

**Issue by GET100PERCENT** [TeamPiped/Piped#1700]
### Describe the feature

I have completed "Odia" translation using the weblate. Add this language to Piped.

### Why would this be useful to add?

Odia is a mother tongue of about ten crores of people.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by GET100PERCENT** [comment]
![chrome_screenshot_9 Nov 2022 21_26_37 GMT+05_30](https://user-images.githubusercontent.com/116144024/200878379-a2873590-9812-48b2-ac94-1d4d669c354c.png)

**Comment by GET100PERCENT** [comment]
You can see in the upper screenshot that even if the language is selected Odia, the preferences page is not translated into Odia.

**Comment by GET100PERCENT** [comment]
I have translated all strings, but this happens, which is not expected.

**Comment by GET100PERCENT** [comment]
I have replaced the reserved character with the new character   ।   as suggested by you on strings 117, 119 and 147.
But still the preference page doesn't translate to Odia.

**Comment by FireMasterK** [comment]
Hi there,

Please be patient as transitions have to be manually merged currently.

It should now work as expected, as it's been deployed. 

Thanks!
