### ISSUE TITLE
Encountering an 'Error HTTP 451 - Unavailable For Legal Reasons'

### ISSUE THREAD

**Issue by Cade66** [TeamPiped/Piped#1704]
### Describe your question

Hi,

I'm discovering an **_Error HTTP 451 - Unavailable For Legal Reasons_** for a YouTube video and I'd wish to know why this video is nevertheless available on Invidious, at least on the yewtu.be instance.

Video : https://piped.kavin.rocks/watch?v=tEB8shTqDB0 displays _**Error HTTP 451 - Unavailable For Legal Reasons**_
Video : https://yewtu.be/watch?v=tEB8shTqDB0 displays correctly

**_Error HTTP 451 - Unavailable For Legal Reasons_** includes a link to https://lumendatabase.org/notices/29443361

I understand the legal stance but not the fact it is not effective on Invidious instances.

Thanks.

**EDIT** : it appears, here and at this time, that any video linked to `https://piped.kavin.rocks/watch?v=[VIDEOID]` opened from any page other than `https://piped.kavin.rocks/` leads to this **_Error HTTP 451 - Unavailable For Legal Reasons_**

Channels are not concerned
The same video opened from `https://piped.kavin.rocks/` itself plays correctly

**Comment by FireMasterK** [comment]
[piped.video](https://piped.video) now exists, and so do the mirrors at https://github.com/TeamPiped/Piped#mirrors

**Comment by Cade66** [comment]
Pardon my ignorance but I always naively thought that all Piped instances had Clouflare as their ISP.
The issue made me search for other instances and I discovered that some had a different ISP.
Choosing an instance with an ISP other than Cloudflare resolved the issue, because indeed the culprit was Cloudflare, not Piped.

**Comment by FireMasterK** [comment]
Well, Cloudflare wrongly blocked access to Piped in this case.

**Comment by Cade66** [comment]
> Well, Cloudflare wrongly blocked access to Piped in this case.

Exactly. And errors happen to bring some light once you decide to try to understand. Happy the title of my post was changed.
Piped works really very well, need to say. I guess I can emphasize on that given this post, even if I labeled it as a question only.

**Comment by Bnyro** [comment]
> Should piped.video be included in https://piped-instances.kavin.rocks?
> 
piped-instances.kavin.rocks only contains the API URLs which is still pipedapi.kavin.rocks for piped.video at the moment and thus no changes are needed. If Kavin ever decides to move the backend to piped.video it'll need to be changed but that doesn't seem to be the case currently.

**Comment by debpalash** [comment]
> [piped.video](https://piped.video) now exists, and so do the mirrors at https://github.com/TeamPiped/Piped#mirrors

It's actually Cloudflare TOS violation, as per them when my instance also got around 40TB of bandwidth a month. Suddenly i saw a blocked/redirect on each video element. Then following an email with TOS reminder. Apparently **Cloudflare don't allow free accounts to use streaming hosting sites.**

**Comment by FireMasterK** [comment]
> It's actually Cloudflare TOS violation, as per them when my instance also got around 40TB of bandwidth a month. Suddenly i saw a blocked/redirect on each video element. Then following an email with TOS reminder. Apparently **Cloudflare don't allow free accounts to use streaming hosting sites.** @FireMasterK 

The official instance doesn't use Cloudflare for proxying video content
