### ISSUE TITLE
F to fullscreen doesn't work

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#172]
According to https://github.com/TeamPiped/Piped/issues/139 it was already implemented so it's a regression

**Comment by FireMasterK** [comment]
I cannot replicate this whatsoever, both on Brave and Firefox on Windows and Linux (Gnome 40).

**Comment by B0pol** [comment]
I can on Firefox 88, ungoogled chromium 88, gnome web 40, on linux (gnome 40)

**Comment by B0pol** [comment]
I found the problem!

https://github.com/TeamPiped/Piped/blob/master/src/components/Player.vue#L120

I added a console.log(e.code) to see what key it detects

It logs key as if I have a QWERTY keyboard layout but I don't.
F key on my keyboard layout isn't at the same as place as QWERTY, therefore it doesn't work. It says I'm pressing slash `/`.
If I press the key where F is located on QWERTY, it works.

**Comment by B0pol** [comment]
You should use `e.key` instead. See [MDN doc for KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code).

**Comment by FireMasterK** [comment]
Very interesting! I'll will change this in a few hours.

**Comment by FireMasterK** [comment]
Could you see if https://650b3348.piped.pages.dev/ fixes the issue?
(#176)

**Comment by B0pol** [comment]
It does
