### ISSUE TITLE
Remove Whatever Tinfoil instance

### ISSUE THREAD

**Issue by privacytime101** [TeamPiped/Piped#1723]
### Describe your question

Not sure if this was the right issue template. Please remove watch.whatevertinfoil.de/watchapi.whatevertinfoil.de from the instance list.

Users: The instance **will continue to operate as normal** until April 5th of 2023 (quite a while to make backups!), just not displayed in the instance list. Reminders will be displayed on the frontend as we get closer to the date. Feel free to continue using it until then.

**Comment by FireMasterK** [comment]
Removed!
