### ISSUE TITLE
Live stream displayed but not working

### ISSUE THREAD

**Issue by bonswouar** [TeamPiped/Piped#1736]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

On my self hosted instance I can only see a static page of the live videos _(but they do appear in my feed so apparently not related to #1730)_
In the console log there are two 403 (see below for log)
Same error if I try to open the pipedproxy URL directly.

Is it some misconfiguration from my part? Or some kind of banned IP?
Everything else works fine though

### To Reproduce

1. Open a livestream

### Expected behavior

Should play

### Logs/Errors

> 403. That’s an error.
Your client does not have permission to get URL /api/manifest/hls_playlist/expire/4444/ei/slfdl-_gAQ/ip/123.123.123.123/id/lld.1/itag/233/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/133/sgoap/gir=yes;itag=139/hls_chunk_host/rr5---sn-4g5ednkl.googlevideo.com/playlist_duration/3600/manifest_duration/3600/vprv/1/playlist_type/DVR/mh/hP/mm/44/mn/sn-4g5ednkl/ms/lva/mv/u/mvi/5/pl/22/dover/13/pacing/0/short_key/1/keepalive/yes/fexp/24001373,24007246/mt/1668215529/host/manifest.googlevideo.com/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,playlist_duration,manifest_duration,vprv,playlist_type/sig/qlsqld-vP1r_wsGaOFcDlssllszBStCYCYCIHTdzpFkZlP-lsls/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl/lsig/lsls-slls-lsls=/playlist/index.m3u8?host=manifest.googlevideo.com from this server. That’s all we know. 

_(anonymized some parts just in case)_

### Browser, and OS with Version.

Firefox 102.4 - Debian 11

### Additional context

It works if I change to kavin.rocks instance for example

**Comment by FireMasterK** [comment]
Have you deployed your instance recently? If not, could you run (if deployed with Piped-Docker):
```sh
docker-compose down
git pull
./configure-instance.sh
docker-compose pull && docker-compose up -d
```
and see if that fixed your issue! We've recently rewritten the proxy in Rust.

**Comment by bonswouar** [comment]
I installed it a couple of days ago, I've just tried to reset it as you recommended but still the same error.
Also I had it configured on a different port and behind an htaccess (for the frontend), but I also did revert that without any change.

Maybe there's something wrong with my reverse proxy?
I'm using apache, configured it for the 3 domains on https, and with the following rules:
```
UseCanonicalName on
ProxyPreserveHost on
Header set Access-Control-Allow-Origin "*"
```

Thank you for your help!

**Comment by FireMasterK** [comment]
Can you try adding `AllowEncodedSlashes On` too?
I believe Apache2 is the culprit in this case.

**Comment by bonswouar** [comment]
Unfortunately `AllowEncodedSlashes` doesn't fix it, so annoying to find out the origin of this kind of problem!
I've also tried to disable `UseCanonicalName`, set `Header add Host` and `RequestHeader set Host` manually... Always that 403.
Any idea how I could investigate further?

**Comment by FireMasterK** [comment]
Take the URL, and bypass Apache2 using curl:
```sh
curl -v -H "Host: pipedproxy.domain.test" http://127.0.0.0:8080/api/manifest...
```
If that doesn't throw an error, its definitely something with Apache

**Comment by bonswouar** [comment]
Ok found it!! Thanks for the hint that was effectively a bad apache configuration :)
What fixed the problem is adding ` nocanon` after the ProxyPass URL

**Comment by bonswouar** [comment]
Thanks again!

Here is my working Apache2 configuration (repeated for each domain) in case that could help someone:
```apache
<IfModule mod_ssl.c>
  <VirtualHost *:443>
    ServerName piped.yourhost.com

    ProxyPass /  http://127.0.0.1:8080/  nocanon
    ProxyPassReverse /  http://127.0.0.1:8080/

    ProxyPreserveHost on
    Header set Access-Control-Allow-Origin "*"
    AllowEncodedSlashes On
    
    # Facultative htaccess for frontend
    <Proxy *>
        Order deny,allow
        Allow from all
        AuthUserFile /home/piped/piped-htpasswd
        Authname "Password Required"
        Authtype Basic
        Require valid-user
    </Proxy>

    CustomLog /var/log/apache2/piped.yourhost.com-access.log combined
    ErrorLog  /var/log/apache2/piped.yourhost.com-error.log

    SSLCertificateFile /etc/letsencrypt/live/piped.yourhost.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/piped.yourhost.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
  </VirtualHost>
</IfModule>
```
