### ISSUE TITLE
piped.video URLs unsupported by yt-dlp

### ISSUE THREAD

**Issue by RetroAbstract** [TeamPiped/Piped#1739]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

The new links for piped (https://piped.video/) don't work with yt-dlp. The previous piped.kavin.rocks URLs worked fine with it

### To Reproduce

Copy any URL from https://piped.video/ 
Run yt-dlp with it
Notice it doesn't work

### Expected behavior

Expected behaviour would be piped.video URLs to work with yt-dlp just as the piped.kavin.rocks links do.

### Logs/Errors

Not applicable

### Browser, and OS with Version.

Not applicable

### Additional context

None

**Comment by FireMasterK** [comment]
This is something that we can't control, only the folks over at `yt-dlp` can do something about it, sorry!
