### ISSUE TITLE
switching audio track for the video

### ISSUE THREAD

**Issue by p0kza** [TeamPiped/Piped#1741]
### Describe the feature

When i go on some videos, the original language of it should be english but it uses a different one.
I think the problem is with videos that have multiple audio tracks, like the last mrbeast video.
It happens on all instances

1. Open the last mrbeast video on the official instance (https://piped.video/watch?v=kX3nB4PpJko)
2. The video isn't in english

### Why would this be useful to add?

There should be a way to choose the audio track for the video, or to use a default language, to be able to watch the video on the original language. Maybe it could use the general "language selection" setting for this. 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Closing with https://github.com/TeamPiped/Piped/commit/5a268b26bd13c844bb8b183837152f130cb42c52.
