### ISSUE TITLE
Random video freezes on Safari PWA

### ISSUE THREAD

**Issue by farverio** [TeamPiped/Piped#1748]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I’ve experienced this big both on an iPad and iPhone. On some videos, when I press play initially, the video will not play and I cannot pause the video. The time stamp on the bottom changes, from showing both the starting time and total time to just the starting time. The loading spinner will not stop going in circles and, again, cannot be paused.

This occurs even when trying to adjust the starting time from 0:00. If I switch to audio only mode, the audio will play. But if I toggle back to the video, it will continue to not work.

i can switch devices and the second device often will be able to play it, so seems like a client side issue.

I’ve also connected to Web Inspector and see 200s on the network tab and no logs in the console.

### To Reproduce

I haven’t identified what types of videos this is reproducible on, given that it works on  a second device with the same video. My assumption is some cache is being loaded and relied on, so that some error gets caught in memory (it tries to play before its preloaded) or similar.

### Expected behavior

I press play and the video plays.

### Logs/Errors

No errors I could see in console. Network shows 200 responses for videoplayback requests

### Browser, and OS with Version.

Safari, iPad os and iOS. Both on latest

### Additional context

Wish I had more to contribute. It occurs at least one a day and is frustrating. I’m glad to help debug if there’s more guidance but maybe deploying more logs in the frontend around the vue methods that this interacts with could help better debug moving forward

**Comment by goodness-from-me** [comment]
+1 on this. Same problem on my iPad and iPhone.

**Comment by valynor** [comment]
Did you try deleting your piped history? I had a similar issue recently and that fixed it for me.

**Comment by valynor** [comment]
This problem just hit me too, just a little bit weirder: 

On my desktop (Brave, macOS) piped still works without issues. 
On my iPhone: still works

On my iPad mini 5: same instance, same preferences as above: videos do not play anymore (endless spinner) 

I tried the usual, clearing history&website data, removing the piped PWA completely, rebooting ... no change. 
Other instances including piped.video show the same issue. 

piped.mha.fi with the new Efy UI works, though.

**Comment by farverio** [comment]
@FireMasterK  does this coincide with any other bug tickets that could benefit from improved logging out debug capabilities on the vue FE? Putting help wanted doesn’t seem as actionable. To me, it seems like additional logging is best next step for this and other tickets. And that might be a higher priority.

Thoughts?

**Comment by FireMasterK** [comment]
Well, what logging would you suggest that may help with this issue? I can't think of anything at the top of my mind.

> help wanted doesn’t seem as actionable

I've added it simply since I don't own any apple devices.

I test on iOS / iPad OS / OSX via BrowserStack, and have faced none of these issues on it.

Fixing issues that I can't reproduce / test is a low priority for me, sorry. PRs are always welcome!

**Comment by FireMasterK** [comment]
I might have an idea on how to debug this, can you go to https://shaka-player-demo.appspot.com/demo/#audiolang=en-GB;textlang=en-GB;uilang=en-GB;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=ALL_CONTENT;panelData=drm:CLEAR,DASH,MP4;build=compiled and try changing the language / playing the video there?

**Comment by valynor** [comment]
@FireMasterK 
Tried playing the video on the URL you provided as requested a couple of times on my ipad mini. Does not play. Hope you can find something useful in the logs.

**Comment by KraiiFox** [comment]
+1 I also have this issue on my ipad. Most of the times it just spins endlessly, sometimes the audio plays for a split second and stops. Tried using other browsers, brave is the only one that worked for some reason. Both my self hosted and public instance has this issue.
