### ISSUE TITLE
playback goes blank on prolonged pause (chromium)

### ISSUE THREAD

**Issue by asklow** [TeamPiped/Piped#1757]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

As the title says, the video playback when paused, goes blank after certain period of time (on chromium based browsers. Not sure about firefox/others).

### To Reproduce

1. Open chromium based browser
2. Pause a video in the middle
3. Wait for 20 ~ 30 seconds

### Expected behavior

The paused video should stay as it is, without blanking.

### Browser, and OS with Version.

All chromium based browsers.

### Additional context

Many users pause a video for a while to read something. Blanking out in the midst of reading  makes it unusable.

**Comment by FireMasterK** [comment]
I use chromium on a daily basis and have never encountered this issue, it's likely due to an issue in your OS or browser configuration.

Judging by the symptoms, it seems like something is wrong with your GPU drivers.
