### ISSUE TITLE
Add link[rel="alternate"] pointing to YouTube version 

### ISSUE THREAD

**Issue by Bnyro** [TeamPiped/Piped#1765]
### Describe the feature

Add a `<link>` element to `WatchVideo.vue` looking as following:
`<link rel="alternate" href="https://www.youtube.com/watch?v={videoId}">`

### Why would this be useful to add?

That might allow videos from Piped instances that are not on the official instance list to still be able to become downloaded via yt-dlp.

see https://github.com/iv-org/invidious/pull/1730 and https://github.com/yt-dlp/yt-dlp/pull/5441

Are there any reasons against it @FireMasterK ?
Otherwise I would just add it :)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Damn, looks like we need a 3rd party dependency for that, e.g. https://www.npmjs.com/package/vue-head

**Comment by FireMasterK** [comment]
It won't help since we're not SSR rendered, so the client would never see it.
