### ISSUE TITLE
Playlist not found

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1771]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

So as the title says, trying to add a video to a created playlist (in this case a playlist I've labeled 'favorites') causes a 'Playlist not found' error message to pop up. This has been happening for about an hour now, so I'm just wondering when a fix will be pushed out. 

### To Reproduce

1. Open this URL at https://piped.video
2. Go to a video of your choosing and try to add it to one of your playlists
3. See that the 'Playlist not found' error message pops up

### Expected behavior

Videos should be able to go on to your playlist without issue

### Logs/Errors

'Playlist not found'

### Browser, and OS with Version.

Firefox on Ubuntu 20.04

**Comment by hazelnutcoffeelover** [comment]
okay we are now into hour 3 here and still it's broken

I've cleared the browser cache, purged the Ublock cache in case that it was doing it, nothing. I still cannot add videos to my playlist.

**Comment by dhalc** [comment]
Same issue on the official instance. Tried on Garuda Linux instance and it works as expected. I have experienced it both on Brave (ReviOS 11 22H2) and LibreTube (LineageOS 19).

**Comment by hazelnutcoffeelover** [comment]
yup. 12 hours later and it's *still* broken. incredible.

guess Freetube and Invidious are the way to go huh? at least they work properly.

**Comment by Bnyro** [comment]
Deleting your account was the only right decision, who do you think you are?!
