### ISSUE TITLE
piped-backend docker compose error

### ISSUE THREAD

**Issue by NextGenOP** [TeamPiped/Piped#1773]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I tried to run instance with docker and nginx, but got this error

### To Reproduce

1. Git clone repo
2. ./configure-instance.sh
3. Choose nginx
4. docker-compose up

### Expected behavior

No error so I can use docker-compose up -d

### Logs/Errors

piped-backend    | Error: A fatal exception has occurred. Program will exit.
piped-backend    | Error: Port Library failed to initialize: -86                                     piped-backend    | Error: Could not create the Java Virtual Machine.                                 piped-backend    | Error: A fatal exception has occurred. Program will exit.
piped-backend    | Error: Port Library failed to initialize: -86                                     piped-backend    | Error: Could not create the Java Virtual Machine.                                 piped-backend    | Error: A fatal exception has occurred. Program will exit.

### Browser, and OS with Version.

Debian 10

**Comment by AlyoshaVasilieva** [comment]
How much RAM does the system you're running Piped on have? I *think* OOM is one of the reasons the JVM can give that error

**Comment by NextGenOP** [comment]
> How much free RAM does the system you're running Piped on have? I _think_ OOM is one of the reasons the JVM can give that error

Only 2Gigs of ram.

**Comment by FireMasterK** [comment]
This was fixed a while back! :)
