### ISSUE TITLE
Extremely long chapter titles squish video

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1776]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When a chapter title is very large, the video is very small. Also the chapter thumbnail is very small, and not aligned with other thumbnails.

![screenshot](https://user-images.githubusercontent.com/1284317/202729087-881c7a00-d29c-47cc-8f7b-f41d41befcef.png)

### To Reproduce

1. Open https://piped.video/watch?v=XYMqJzKylK8
2. Compare video size to chapters

More of an effect if your browser isn't fullscreen

### Expected behavior

Video takes priority over chapter titles

### Logs/Errors

N/A

### Additional context

YouTube truncates the chapter title and only seems to show it on mouseover

**Comment by thecashewtrader** [comment]
I can work on this.
