### ISSUE TITLE
Private instance

### ISSUE THREAD

**Issue by mohammadrafigh** [TeamPiped/Piped#1792]
### Describe your question

Is there a config that makes Piped instance private, or at least prevents accessing the service without authentication?

**Comment by Bnyro** [comment]
The only thing that would be possible is to disable new registrations but that's probably not what you're looking for.

**Comment by mohammadrafigh** [comment]
Yep. Can I request it as a feature? because currently for some reason the backend java process is hogging my CPU every 10 mins or so... I guess maybe someone is doing nasty things.

**Comment by thecashewtrader** [comment]
> No, that's not possible. If you want to do so you will need to restrict access through your nginx configuration manually e.g. with HTTP Authorization or find a different way.

Just to add to this, [this LandChad article](https://landchad.net/auth/) is good for getting started with nginx authentication.

**Comment by mohammadrafigh** [comment]
Thank you, I know about nginx authentication but in some cases like using LibreTube, it will break things.

**Comment by FireMasterK** [comment]
Duplicate of #441

I'll accept PRs, but I have no interest in implementing this feature.
