### ISSUE TITLE
Videos won’t play at all on iPad os 16

### ISSUE THREAD

**Issue by RouterCFW** [TeamPiped/Piped#1793]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Videos won’t play on the latest iOS dev beta 

### To Reproduce

Play video

### Expected behavior

Video should play but doesn’t

### Logs/Errors

Can’t check

### Browser, and OS with Version.

Ipad os 16.2 beta 3

**Comment by Inrumpo** [comment]
I see the same issue on an iPad Pro 10.5 running on iOS 15.7.1.

**Comment by privacytime101** [comment]
@FireMasterK I've had two users report this to me before and I'm having the same issue myself now.


Testing on a random video, here's everything that seemed useful I found in the console:

Warning: `Changing tracks while abr manager is enabled will likely result in the selected track being overriden. Consider disabling abr before calling selectVariantTrack().`

![Screenshot 100](https://user-images.githubusercontent.com/109485589/205548732-9e9c1b34-716f-45a8-8ee1-864a04da64d1.png)

Some videoplayback requests failed:
![Screenshot 102](https://user-images.githubusercontent.com/109485589/205548788-e7393b11-66ab-495d-9fe7-1f77453c070c.png)
Success (`https://watchproxy-us.whatever.social/videoplayback?expire=...`):
![Screenshot 103](https://user-images.githubusercontent.com/109485589/205549391-832a788d-edd6-4de2-8d63-edf0b440d3a4.png)
Failed (`https://watchproxy-us.whatever.social/videoplayback?expire=...`):
![Screenshot 104](https://user-images.githubusercontent.com/109485589/205548842-af458936-a422-488b-a7f3-42f4fdab6893.png)


I'm able to reproduce the issue, let me know if anything else is needed from console

**Comment by mr-sihc** [comment]
for me too, on ipad air 12.5.6 tried 3 browsers, no images load and the videos don't play

**Comment by mr-sihc** [comment]
it work totally fine on m.youtube.com

**Comment by FireMasterK** [comment]
> it work totally fine on m.youtube.com

Sure, that's because we don't support Jpeg on Piped :shrug:

**Comment by FireMasterK** [comment]
Should be live already :+1:

**Comment by mr-sihc** [comment]
hmm.. still doesnt work for me, is it the ios version that you dont support or is it the site?
safari only sometimes shows controls for the video and no resolutions(except Automatic) and playback speed is 0x sometimes
i can change volume slider, but not the video progress i dont see how far the video lasts ether listen mode doesnt change anything...

**Comment by privacytime101** [comment]
Can confirm that it's working on my side now (iPadOS 16.2 Beta)

**Comment by mr-sihc** [comment]
i'll do that, though it may not work because i am on ios 12

**Comment by mr-sihc** [comment]
still nothing...
