### ISSUE TITLE
Number of views in the watch history.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#1797]
### Describe the feature

The number of views must be shown in the watch history.

![Screenshot_20221122-112256_YouTube](https://user-images.githubusercontent.com/112704336/203250758-6c76abc0-10fe-4e86-85d5-ff71688ef133.jpg)

### Why would this be useful to add?

I think we need to know the number of views of the video.

### Concept(s)

I have sent a screenshot.

### Additional context

.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible because the view count is a dynamic parameter and hence change every few days, so saving it in the database doesn't make sense.
