### ISSUE TITLE
Adjust the displayed videos to the location when searching

### ISSUE THREAD

**Issue by Fertanima** [TeamPiped/Piped#1803]
### Describe the feature

Search for a video and the displayed videos should be displayed according to the location

### Why would this be useful to add?

If we are searching for something in our native language, the video content should be displayed according to the location and search language

### Additional context

There should be an option to set search suggestions locally.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This can't be done, the location is determined by the Piped backend server's location. You can't do anything about this as even changing your settings on YouTube doesn't help.
