### ISSUE TITLE
How do I get "Livestreams" or "Shorts" video list of a specific channel using Piped's api

### ISSUE THREAD

**Issue by upstroke-version** [TeamPiped/Piped#1806]
### Describe your question

I've read Piped api documentation from here(https://docs.piped.video/docs/api-documentation/).
Now, I'm able to get channel's "Videos" list using https://pipedapi.kavin.rocks/channel/:channelId.
However, this api's output does not contain "Livestreams" and "Shorts" videos info, and I was not able to figure out how to do it.

Is there an api for getting channels "Livestreams" and "Shorts" videos info?

**Comment by Bnyro** [comment]
When sending a request to fetch a channel, e.g. https://pipedapi.kavin.rocks/channel/UCWFjJaI19jDrzYgwKRfbr0w there's a field called `tabs`. Those contain the name of the tab as well as a specific `data` string.
To get a tab, you will need make a request to `channels/tabs` by passing the `data` string from above as query (query name is "data"). 
An example request could be https://pipedapi.kavin.rocks/channels/tabs?data=%7b%22originalUrl%22%3a%22https%3a%2f%2fwww.youtube.com%2fUCWFjJaI19jDrzYgwKRfbr0w%2fstreams%22%2c%22url%22%3a%22https%3a%2f%2fwww.youtube.com%2fUCWFjJaI19jDrzYgwKRfbr0w%2fstreams%22%2c%22id%22%3a%22UCWFjJaI19jDrzYgwKRfbr0w%22%2c%22contentFilters%22%3a%5b%22livestreams%22%5d%2c%22sortFilter%22%3a%22%22%2c%22baseUrl%22%3a%22https%3a%2f%2fwww.youtube.com%22%7d] 
Note that the query has to be URL encoded, hence the request looks a bit ugly.

For reference you can have a look at https://github.com/libre-tube/LibreTube/blob/master/app/src/main/java/com/github/libretube/api/PipedApi.kt#L71-L75 and https://github.com/TeamPiped/Piped-Backend/blob/1157d5dfaab0b22bc3db70a79366d7e07c88c77a/testing/api-test.sh#L24-L26 :)
