### ISSUE TITLE
Rename "Watch" to "View"

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1807]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When you enable the "Show Watch on YouTube button" in the preferences, a "Watch on YouTube" button will appear on videos, channels and playlists.

Please change the preference name to "Show View on YouTube button" and change the button on the videos, channels and playlists to be "View on YouTube"

The reason for changing "Watch" to "View" is that when viewing a channel or playlist, you are not watching anything, but wanting to view the page on Youtube itself.

### To Reproduce

Go to the preferences
Enable "Show Watch on YouTube button" 
Go to any video, channel or playlist

### Expected behavior

Preference setting will display as "Show View on YouTube button"

Buttons on videos, channels and playlists will display as "View On YouTube"

### Logs/Errors

None

### Browser, and OS with Version.

All

### Additional context

I would like to thank the devs and contributors for making this button and setting available in Piped.

https://github.com/TeamPiped/Piped/issues/803
https://github.com/TeamPiped/Piped/issues/1611

**Comment by thecashewtrader** [comment]
I've submitted a PR for this, however it'll require some changes to the translations too.
