### ISSUE TITLE
Request to add my instance

### ISSUE THREAD

**Issue by Daviteusz** [TeamPiped/Piped#1808]
### Describe your question

Can you add my instance to list?

- Frontend: https://piped.daviteusz.eu/
- API:            https://pipedapi.daviteusz.eu/
- Proxy:        https://pipedproxy.daviteusz.eu/
- CDN:          Cloudflare
- Country:    DE

**Comment by Bnyro** [comment]
I always get `1020, Access denied`, is the instance meant for public or only for private use?
If nobody except you is allowed to access it it doesn't make sense to add it to the list of public instances.

**Comment by Daviteusz** [comment]
I forgot to change the firewall, the instance should already be available.

**Comment by Bnyro** [comment]
> I forgot to change the firewall, the instance should already be available.
>
Works now, perfect :)

**Comment by FireMasterK** [comment]
Added, thanks for hosting an instance!

**Comment by IkelAtomig** [comment]
@Daviteusz - Error 1033 by Agro Tunnel in your instance.

**Comment by Daviteusz** [comment]
@IkelAtomig Sorry.

I lost a good network and can no longer host my instance publicly. @FireMasterK Please remove from the list.
Thanks.
