### ISSUE TITLE
Support other video endpoints

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#181]
Let's take a random video

https://piped.kavin.rocks/watch?v=S2dRcipMCpw

It includes

https://piped.kavin.rocks/S2dRcipMCpw
https://piped.kavin.rocks/watch/S2dRcipMCpw
https://piped.kavin.rocks/embed/S2dRcipMCpw
https://piped.kavin.rocks/w/S2dRcipMCpw
https://piped.kavin.rocks/v/S2dRcipMCpw
https://piped.kavin.rocks/shorts/S2dRcipMCpw

They are all supported by NPE

**Comment by FireMasterK** [comment]
Even NewPipe has trouble with this: https://www.youtube.com/TheFineBros

**Comment by FireMasterK** [comment]
Closing with 5e791a51f5b977c75b20b4aa436307a39cb643b6.

Merging the https://piped.kavin.rocks/S2dRcipMCpw one with #6.
