### ISSUE TITLE
Request to add my instance - piped.hostux.net

### ISSUE THREAD

**Issue by Raistlingru** [TeamPiped/Piped#1811]
### Describe your question

Can you add my instance to list?

    Frontend: https://piped.hostux.net/
    API: https://piped-api.hostux.net/
    Proxy: https://piped-proxy.hostux.net/
    CDN: No
    Country: FR

Thx !

**Comment by Bnyro** [comment]
Looks like Kavin already added it, thanks for hosting an instance!
