### ISSUE TITLE
Unable to install using docker-compose

### ISSUE THREAD

**Issue by neurokrish** [TeamPiped/Piped#1813]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Trying to install Piped using docker-compose. The container keeps restarting due to the following error,

`Exception in thread "main" java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
        at io.sentry.Sentry.initConfigurations(Sentry.java:216)
        at io.sentry.Sentry.init(Sentry.java:185)
        at io.sentry.Sentry.init(Sentry.java:145)
        at io.sentry.Sentry.init(Sentry.java:131)
        at me.kavin.piped.Main.main(Main.java:37)`

What does this mean and how to move forward?

Thanks.

### To Reproduce

I am using the following docker-compose file,

`services:
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "127.0.0.1:3456:8080"
        volumes:
            - ./config.properties:/app/config.properties
        depends_on:
            - postgres
    postgres:
        image: postgres:15-alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=XXXX`

### Expected behavior

The expected behavior is to be able to run Piped using the docker-compose file. However, I am stuck due to some Java errors I am not familiar with.

### Logs/Errors

`Exception in thread "main" java.lang.IllegalArgumentException: DSN is required. Use empty string to disable SDK.
        at io.sentry.Sentry.initConfigurations(Sentry.java:216)
        at io.sentry.Sentry.init(Sentry.java:185)
        at io.sentry.Sentry.init(Sentry.java:145)
        at io.sentry.Sentry.init(Sentry.java:131)
        at me.kavin.piped.Main.main(Main.java:37)`

**Comment by FireMasterK** [comment]
Are you using https://github.com/TeamPiped/Piped-Docker? I doubt that you are
See https://docs.piped.video/docs/self-hosting/

**Comment by neurokrish** [comment]
@FireMasterK , I am using the docker-compose information from [here](https://github.com/TeamPiped/Piped-Backend/blob/master/docker-compose.yml). Is this any different?

Will go through the link you provided!

**Comment by FireMasterK** [comment]
Yes, it is, you're supposed to use that for development only usually.

**Comment by neurokrish** [comment]
@FireMasterK , thank you. Please close this issue then. I will follow the official method you posted here. 

Great project!
