### ISSUE TITLE
Documentation for using Redirector Extension for Piped

### ISSUE THREAD

**Issue by MintMain21** [TeamPiped/Piped#1815]
### Describe the feature

In the ReadMe file, there is a brief segment on Extensions, with the only recommended extensions being LibRedirect and Piped-Redirects. 

I have been slowly transitioning from the use of LibRedirect to the use of [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), and have had to make my own redirection rules to accommodate the likes of Invidious, Nitter, Breeze Wiki, etc. The biggest benefit to me is specifically free reign to use URL Parameters in redirects to customize global preferences in both standard and private browsing modes.

I think this github page would benefit from instructions on how to configure these redirects in Redirector, including accomodating for URL Parameters.

### Why would this be useful to add?

I have found LibRedirect (the most popular option of it's kind) to be unstable in the past, and at present it does not offer any leeway for URL Parameters on Invidious, Nitter, Piped etc (see https://github.com/libredirect/libredirect/issues/491). 

Redirector is not only a lightweight alternative that can function fine on Firefox Android, but it is the most flexible option for configuring URL Parameters. 

I think new users especially would benefit from being able to configure Piped redirects in Redirector as they please using a ready made guide.

### Concept(s)

I have written a similar guide for the Invidious Documentation that (at the time of writing) has yet to be accepted into the official branch. (https://github.com/iv-org/documentation/pull/298) I would be happy to write up a similar guide for Piped. 

### Additional context

At present, I consider Piped to be the best web-based private front-end for YouTube, and I think people deserve to be able to experience everything it can offer, including URL Parameters. (Evidence of others using Redirector for Piped can be found here: https://github.com/TeamPiped/Piped/issues/786)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
If you're still interested, please feel free to create a small PR with some example configuration, or else, please close this issue. Thank you.
