### ISSUE TITLE
SponsorBlock Manual Skip. Auto Skip, Show In Seekbar settings

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1824]
### Describe the feature

In the Piped preferences, you can choose weather to auto skip a segment or not. Please change this to allow users to choose weather to auto skip, manual skip or just show the segment in the seekbar.

### Why would this be useful to add?

To allow users to customize the SponsorBlock settings and choose what segments to auto skip, what ones to manual skip, etc.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Closing in favor of #894
However, choosing it manually for each category probably won't be a thing, it's rather gonna be a global setting
