### ISSUE TITLE
Videos don't load

### ISSUE THREAD

**Issue by DogCatPuppyLover** [TeamPiped/Piped#1828]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Occasionally, all Piped instances will appear to go down, then start working again for a few days, then go down again. It's almost as if I'm getting rate-limited, but it happens on most instances simultaneously (some instances stop working before others, but they eventually all go down.) I don't know if this is a problem on my end (maybe an extension?), or with Piped. I've been on the fence about making an issue for a while (this has been happening for months), because I thought it might be a temporary server issue, but it's probably worthwhile to report it.

### To Reproduce

1. Open [this URL](https://piped.kavin.rocks/watch?v=le5uGqHKll8)
2. The video may not load (whether or not it loads is unpredictable)

### Expected behavior

The video and website should load.

### Logs/Errors

XHRGEThttps://pipedapi.moomoo.me/streams/le5uGqHKll8
CORS Missing Allow Origin

XHRGEThttps://pipedapi.moomoo.me/sponsors/le5uGqHKll8?category=["sponsor","interaction","selfpromo","music_offtopic"]
CORS Missing Allow Origin

XHRGEThttps://pipedapi.moomoo.me/comments/le5uGqHKll8
CORS Missing Allow Origin

EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. shaka-player.ui.js:952:241
McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support. shaka-player.ui.js:957:162
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.moomoo.me/streams/le5uGqHKll8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503.
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.moomoo.me/comments/le5uGqHKll8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503.
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.moomoo.me/sponsors/le5uGqHKll8?category=%5B%22sponsor%22%2C%22interaction%22%2C%22selfpromo%22%2C%22music_offtopic%22%5D. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503.
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Failed to load ‘https://fonts.kavin.rocks/s/materialiconsround/v107/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmM.otf’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘Error: no-response :: [{"url":"https://fonts.kavin.rocks/s/materialiconsround/v107/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmM.otf","error":{}}]’. workbox-8731d5a0.js:1:212
Failed to load ‘https://fonts.kavin.rocks/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxP.ttf’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘Error: no-response :: [{"url":"https://fonts.kavin.rocks/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxP.ttf","error":{}}]’. workbox-8731d5a0.js:1:212
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.kavin.rocks/s/materialiconsround/v107/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmM.otf. (Reason: CORS request did not succeed). Status code: (null).
downloadable font: download failed (font-family: "Material Icons Round" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://fonts.kavin.rocks/s/materialiconsround/v107/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmM.otf
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://fonts.kavin.rocks/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxP.ttf. (Reason: CORS request did not succeed). Status code: (null).
downloadable font: download failed (font-family: "Roboto" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://fonts.kavin.rocks/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxP.ttf

### Browser, and OS with Version.

Firefox on Windows 11

### Additional context

The bug is reproducable on the official instance sometimes, but not right now.

**Comment by FireMasterK** [comment]
That's an instance issue since it works great on the official one.

**Comment by DogCatPuppyLover** [comment]
Maybe, but piped.kavin.rocks currently doesn't work, and if I remember correctly, piped.video has had problems like this in the past

**Comment by FireMasterK** [comment]
`piped.kavin.rocks` and `piped.video` are the same. You're using the `pipedapi.moomoo.me`, instance, which is down currently, hence why its not listed in https://piped-instances.kavin.rocks/ due to it failing automatic healthchecks.

**Comment by FireMasterK** [comment]
cc @moom0o

**Comment by DogCatPuppyLover** [comment]
here's a screenshot from piped.kavin.rocks:

![Screenshot 2022-11-27 at 16-51-26 Piped](https://user-images.githubusercontent.com/79656307/204169927-f338b7f3-ad6a-4c95-b569-8a151d5e0483.png)

here's a screenshot from piped.video (of the same video):

![Screenshot 2022-11-27 at 16-52-21 Piped](https://user-images.githubusercontent.com/79656307/204170024-5b554f02-4033-4484-8890-d8de381b1c3f.png)

the log files say that i'm using pipedapi.moomoo.me, for some reason, even though i'm on piped.kavin.rocks. i think this might be a problem with libredirect.

**Comment by FireMasterK** [comment]
In that case libredirect is redirecting users to instances that are down. Open a bug report with them.

**Comment by DogCatPuppyLover** [comment]
It looks like the problem was in my preferences--under "Instance", it was using a custom instance (i think moomoo.me). The problem went away when I set the instance to kavin.rocks. I suspect that when syncing settings, libredirect also wrongly syncs the "Instance" setting, which should be unique to each instance.
