### ISSUE TITLE
Removed video gives false geo-restriction error

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1829]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When a video has been removed by the uploader and the instance does not have a georestriction checker set up, Piped will give a false georestriction error when trying to view the video.

### To Reproduce

1. Open video ID 3NmxpeeIUes on an instance with no georestriction checker set up ([watch.whatever](https://watch.whatever.social/watch?v=3NmxpeeIUes) currently doesn't have one, neither does my private instance)
2. Receive "This instance does not have a geo restriction checker set in its configuration" error
3. Open video ID 3NmxpeeIUes on [piped.video](https://piped.video/watch?v=3NmxpeeIUes) or [YouTube](https://www.youtube.com/watch?v=3NmxpeeIUes)
4. Receive error that the video is unavailable

### Expected behavior

Ideally the error would always be "video unavailable"

edit: Wait, I looked at the recent backend commits. Does YouTube sometimes simply say "unavailable" when actually the video is georestricted?

### Logs/Errors

N/A

**Comment by FireMasterK** [comment]
> Does YouTube sometimes simply say "unavailable" when actually the video is georestricted?

Yes, this is why you get that error :P
