### ISSUE TITLE
Redirect To YouTube Setting

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#1835]
### Describe the feature

A preference which when enabled. When you go to a video, channel or playlist on a Piped instance, it will redirect you to that video/channel/playlist on youtube.com

### Why would this be useful to add?

I like Piped mainly for the private subscription feed. I use a VPN and ad blockers. I am not concerned using youtube.com. And sometimes videos do not load on Piped.

Such a feature will reduce the load on a Piped instance.

### Concept(s)

 A setting in the account preferences.

### Additional context

An alternative to consider
https://github.com/TeamPiped/Piped/issues/794

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Won't be done for the same reason in https://github.com/TeamPiped/Piped/issues/794#issuecomment-1032487311
