### ISSUE TITLE
Audio Only mode

### ISSUE THREAD

**Issue by opusforlife2** [TeamPiped/Piped#186]
Yo. I just went through the Features list and saw this listed. But I've been using Piped for a long time and never came across such a button. Where is it?

**Comment by FireMasterK** [comment]
It was once a thing when VideoJS was still being used, but then never got ported when the shaka-player migration happened.

Added it as a Preference in b8ac67b7afd756e5abd2e0a626d8dd6cb3d87ec9.

**Comment by opusforlife2** [comment]
What about a Headphones icon like Invidious?

**Comment by FireMasterK** [comment]
I'll see if that can be added.

**Comment by FireMasterK** [comment]
Closing this with 426c5669f0bb08a263c82376318e78caf866a5d6.

It's currently not added in search results though, that would be done later when search results items are merged with https://github.com/TeamPiped/Piped/blob/master/src/components/VideoItem.vue.

**Comment by opusforlife2** [comment]
Just tested it. Works awesome!
