### ISSUE TITLE
522 Timeout errors

### ISSUE THREAD

**Issue by 0xC4aE1e5** [TeamPiped/Piped#1875]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When clicking the register button, it doesn't do anything and the API call fails with status 522. 

### To Reproduce

1. Go to https://piped.video/register
2. Enter a username and password
3. Click Register
4. It will take forever, and error with 522 in the Network tab in Chromium.

### Expected behavior

When clicking Register, it should take a few moments and redirect somewhere.

### Logs/Errors

```
Access to fetch at 'https://pipedapi.kavin.rocks/register' from origin 'https://piped.video' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
index.a6866503.js:788          POST https://pipedapi.kavin.rocks/register net::ERR_FAILED 522
fetchJson @ index.a6866503.js:788
register @ RegisterPage.b2d87a8d.js:1
t.onClick.e.<computed>.e.<computed> @ RegisterPage.b2d87a8d.js:1
hn @ index.a6866503.js:1
xt @ index.a6866503.js:1
n @ index.a6866503.js:1
index.a6866503.js:788                  Uncaught (in promise) TypeError: Failed to fetch
    at Proxy.fetchJson (index.a6866503.js:788:25711)
    at Proxy.register (RegisterPage.b2d87a8d.js:1:309)
    at t.onClick.e.<computed>.e.<computed> (RegisterPage.b2d87a8d.js:1:1569)
    at hn (index.a6866503.js:1:14228)
    at xt (index.a6866503.js:1:14307)
    at HTMLAnchorElement.n (index.a6866503.js:1:55816)
```

### Browser, and OS with Version.

ungoogled-chromium version 106.0.5249.119 (yes, I don't have time to update it), on Windows 64-bit

Also happens in LibreTube.

### Additional context

Also, this issue was written with piped.video, but it happens in piped.kavin.rocks as well.

**Comment by FireMasterK** [comment]
Should be fixed now!
