### ISSUE TITLE
Play with Playlist

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#188]
I'm currently looking for the best solution.

**Comment by FireMasterK** [comment]
The true/best solution will be through https://github.com/TeamNewPipe/NewPipeExtractor/issues/671.

**Comment by dotamir** [comment]
@FireMasterK I took a look at the issue you've mentioned. But couldn't find any good information about the solution. I'm looking for a contribution to this issue, would you please provide more information?

Thanks in advance.

**Comment by FireMasterK** [comment]
There are 2 ways this could be done:

- Handle it like how YouTube does (preferred)
- Handle it like how NewPipe does (limited and would use multiple requests)

If you want to solve it **right** now, only the NewPipe way is possible. To describe it in more detail:
- Play the current video in the `v` parameter. (done already)
- Fetch the playlist in `list` (and the necessary continuations required to find the video)
- Assign the `index` parameter if not present.
- Make the necessary UI changes

To go the YouTube way (when the above-linked issue is solved):
- Modify the way video and playlist data is fetched.
- Assign an `index` parameter if not present.
- Make the necessary UI changes.
