### ISSUE TITLE
Recorded stream is not played at all

### ISSUE THREAD

**Issue by goodness-from-me** [TeamPiped/Piped#1880]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I have found out that this recorded stream video is not being played by neither official nor non-official instances:
https://piped.video/watch?v=WXZIq7UAggs

### To Reproduce

1. Open url: https://piped.video/watch?v=WXZIq7UAggs
2. Try to play video.

### Expected behavior

Video should start playing.

### Logs/Errors

No errors in console and network tab.

### Browser, and OS with Version.

**Browser:** Safari 16.1 , Edge 108.* , Firefox 107.0.1
**OS:** MacOS 13.0.1

**Comment by FireMasterK** [comment]
Plays fine for me 😕

**Comment by goodness-from-me** [comment]
Oh, it now works for me :/
Hence closing the issue.
