### ISSUE TITLE
How to Marge audio video urls into single stram?

### ISSUE THREAD

**Issue by actuallyabhi** [TeamPiped/Piped#1897]
### Describe your question

I am trying to implement a web app with pipes apis. 
But I'm not sure how to integrate separate audio, video link from api into one.
Please help me out!

**Comment by FireMasterK** [comment]
Hi, you'd have to use DASH! You can see how we create a manifest:

https://github.com/TeamPiped/Piped/blob/90ecb0ab21edb21da7cc7dfe79b7177cc0abb44c/src/components/VideoPlayer.vue#L271-L273

https://github.com/TeamPiped/Piped/blob/master/src/utils/DashUtils.js

**Comment by actuallyabhi** [comment]
@FireMasterK Got it Thanks a ton!

**Comment by actuallyabhi** [comment]
video is not playing
btoa()  is deprected using encodeURI component instead
after saving file as .mpd it plays in vlc for like 20s seconds then stuck.
please help
```
import React, { createElement, useEffect, useRef, useState} from 'react'
import dash from './DashUtils'
import ShakaPlayer from 'shaka-player-react';
import 'shaka-player/dist/controls.css';



const App = () => {
  const controllerRef = useRef(null);

  const [data,setData] = useState([])


  useEffect(() => {
    FetchVideoURL()
  },[])

 const FetchVideoURL = async () => {
    const response = await fetch('https://pipedapi.tokhmi.xyz/streams/17jCLuDU-Qk')
    const data = await response.json()
   const {videoStreams, audioStreams, duration } = data
      console.log(videoStreams, audioStreams, duration)
      setData([...videoStreams, ...audioStreams])
      genrateDash()
  }


  const genrateDash = async  () => {
    const genratedFile = dash.generate_dash_file_from_formats(data)
    const uri =  'data:application/dash+xml;charset=utf-8,' + encodeURIComponent(genratedFile)

    controllerRef.current.player.load(uri)    
  }



    return (
      <div>  
        <ShakaPlayer          
          ref={controllerRef}
        />
      </div>
    )
  
}


export default App

```

**Comment by actuallyabhi** [comment]
@FireMasterK Made it working Yay!
Thanks for your assistance!

Working code in case someone needs it
`import React, { createElement, useEffect, useRef, useState} from 'react'
import dash from './DashUtils'
import ShakaPlayer from 'shaka-player-react';
import 'shaka-player/dist/controls.css';



const App = () => {
  const controllerRef = useRef(null);

  const [data,setData] = useState([])


  useEffect(() => {
    FetchVideoURL()
  },[])

 const FetchVideoURL = async () => {
    const response = await fetch('https://pipedapi.tokhmi.xyz/streams/17jCLuDU-Qk')
    const data = await response.json()
   const {videoStreams, audioStreams, duration } = data
      console.log(videoStreams, audioStreams, duration)
      setData([...videoStreams, ...audioStreams])
      genrateDash()
  }


  const genrateDash = async  () => {
    const genratedFile = dash.generate_dash_file_from_formats(data)
    const uri =  'data:application/dash+xml;charset=utf-8,' + encodeURIComponent(genratedFile)

    controllerRef.current.player.load(uri, 0, 'application/dash+xml');    
  }



    return (
      <div>  
        <ShakaPlayer          
          ref={controllerRef}
        />
      </div>
    )
  
}


export default App
`

**Comment by FireMasterK** [comment]
That's incredible news :)
