### ISSUE TITLE
Only 360p available on Piped, 1080p+ on YouTube

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1901]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

On some videos, Piped only has 360p available even though YouTube itself has much higher qualities available. I *think* this happens mostly for low-view-count videos.

### To Reproduce

1. Open https://piped.video/watch?v=BoTqMzB-2Cw
2. Only video quality is 360p (it's loading itag 243)
3. Check YouTube itself
4. Quality 1080p60 is available
5. Check https://pipedapi.kavin.rocks/streams/BoTqMzB-2Cw ([pastebin](https://bin.snopyta.org/?3ca4001c4b404906=#8tghYCtCWfQEYci2CtWc4uaCAeGao3gW3SZdAsJGYwNq))
6. 1080p60 is available under `videoStreams`, and in HLS ([pastebin](https://bin.snopyta.org/?0c12b8ce1c821ecc=#2FmLkEpurMiVMiWzLy78WreX7d8tjFftUqsGVSKGoA1Q)), DASH is null

This specific video is ~2 days old. I've seen it resolve over time so I assume something about the video changes on YouTube's end at some point. As far as I can remember, the videos I've seen it happen to have had low view counts.

(method to find low view count videos: https://old.reddit.com/r/gaming/new/?limit=100, page through looking for what are basically spam posts of YT vids)

### Expected behavior

Piped has the same quality as YouTube

### Logs/Errors

N/A

**Comment by FireMasterK** [comment]
It looks like that video is available in webm only for 360p :confused: 
1080p is only available in in mp4/avc
You currently only see 360p, since we can't switch between codecs. This is because shaka doesn't support smooth video codec switching yet.

However, this may change with https://github.com/shaka-project/shaka-player/pull/4766

**Comment by Atemu** [comment]
I just hit this issue.

It appears upstream now supports the required functionality: https://github.com/shaka-project/shaka-player/pull/5470

Could this be fixed now?

**Comment by McBaumwolle** [comment]
Was there maybe an update on this? I host my own Piped instance and I tried everything, however the video resolution is maxed out at 360p. :/
