### ISSUE TITLE
Consider mirroring the repos to Codeberg

### ISSUE THREAD

**Issue by throwaway-d** [TeamPiped/Piped#1908]
### Describe the feature

I believe you should mirror your repo to Codeberg

### Why would this be useful to add?

1. Codeberg is libre, free, open-source, privacy-friendly, non-profit
2. GitHub is privacy-invasive, proprietary
3. People on Codeberg like me can contribute to the project
4. GitHub can take down your repos

### Concept(s)

Here are some sources for you:
1. https://sfconservancy.org/GiveUpGitHub
2. https://docs.codeberg.org/advanced/migrating-repos
3. https://github.com/humanetech-community/awesome-humane-tech/issues/33
4. https://github.com/ungoogled-software/ungoogled-chromium/discussions/1894
5. https://cadence.moe/blog/2022-07-03-git-forge-opinions-github-gitlab-gitea-sourcehut
6. https://github.com/andersju/webbkoll/issues/35

### Additional context

Many front-ends also are living on Codeberg at the moment:

- https://codeberg.org/video-prize-ranch/rimgo
- https://codeberg.org/SimpleWeb/SimplyTranslate-Web
- https://codeberg.org/Hyperpipe/Hyperpipe
- https://codeberg.org/zyachel/quetre

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by throwawayaccountfor** [comment]
### FAQ
1. **Q:** - GitHub Actions -- this is a huge time saver for me
          - Forcing all contributors to modify their current setup and move to another hosting -- we may just lose contributors in the end
    
   **A:** As I said, we only just _mirror_. The repo will be available and contributable on **both** sites.

2. **Q:** - Transferring issues -- is this possible? Issues here represent a technical knowledge base we can't live without
          - Transferring wiki and all edit history -- possible?

    **A:** Yes, it is possible.
a. Example for issues:

- https://github.com/andersju/webbkoll/issues/35
- https://codeberg.org/dataskydd.net/webbkoll/issues/35
- https://github.com/andersju/webbkoll/issues/33
- https://codeberg.org/dataskydd.net/webbkoll/issues/33
- https://github.com/zyachel/quetre/issues/7
- https://codeberg.org/zyachel/quetre/issues/7

b. Example for commits:
- https://codeberg.org/dataskydd.net/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6
- https://github.com/andersju/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6

c. Example for wiki:
- https://github.com/Freeyourgadget/Gadgetbridge/wiki/Home/_history?page=2
- https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Home?action=_revision

3. **Q:** Despite having mirror/s, the project will still continue to be operated from GitHub for development, so having yet another mirror doesn't solve anything.

   **A:** You can create issues, contribute, view the repos on there without going to GitHub! Example:
- https://github.com/libredirect/libredirect
- https://codeberg.org/LibRedirect/libredirect
- https://github.com/zyachel/quetre
- https://codeberg.org/zyachel/quetre

**Comment by throwaway-d** [comment]
BTW, I've written a seperate repo about mirroring to Codeberg: https://codeberg.org/HexagonCDN/Mirror_to_Codeberg

**Comment by FireMasterK** [comment]
You have a mirror on my private Gitea server: https://git.kavin.rocks/kavin/Piped

I have no plans to accept contributions from Codeberg since I want to streamline development to one platform only.

Also: Codeberg doesn't allow you to create self-updating mirrors, unlike Gitea.

I also just created a mirror on Gitlab: https://gitlab.com/FireMasterK/Piped

If forgefed takes off however, I will reconsider my stance on this
