### ISSUE TITLE
Words not on Weblate.

### ISSUE THREAD

**Issue by Fidannyan** [TeamPiped/Piped#1909]
### Describe the feature

![Screenshot_20221222-062611_Chrome](https://user-images.githubusercontent.com/120574401/209043879-16ed08ed-899a-4362-9969-07aeae235fe7.jpg)
![Screenshot_20221222-061901_Chrome](https://user-images.githubusercontent.com/120574401/209043887-b32eb3a8-7a6a-497c-963b-04073ac72720.jpg)
![Screenshot_20221222-061631_Chrome](https://user-images.githubusercontent.com/120574401/209043892-b6576e88-d2af-4110-b499-9b26bcc21df1.jpg)

### Why would this be useful to add?

Words not on Weblate

### Concept(s)

Words not on Weblate

### Additional context

Words not on Weblate

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
They're by the shaka-player.
