### ISSUE TITLE
Add search filters

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#191]
https://github.com/TeamNewPipe/NewPipeExtractor/blob/6db4bea8ca51ac40a8f831527b274ad50895070e/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/linkHandler/YoutubeSearchQueryHandlerFactory.java#L64-L71

**Comment by FireMasterK** [comment]
Closing with 929b1c07c009caa01b222ff0e3432d8e2b39fb96.

**Comment by 07416** [comment]
```
            availableFilters: [
                "all",
                "videos",
                "channels",
                "playlists",
                "music_songs",
                "music_videos",
                "music_albums",
                "music_playlists",
            ],
            selectedFilter: "all",
```

Can the filters by passed in search (the search field) in anyway (for instance `music-albums:` would seek for albums only)?

I'm attempting to automate more with [Firefox' keyword search](https://support.mozilla.org/en-US/kb/how-search-from-address-bar).

**Comment by FireMasterK** [comment]
Create a new issue for that since it's a feature request.
