### ISSUE TITLE
Moving away from Jitpack

### ISSUE THREAD

**Issue by hugoamvieira** [TeamPiped/Piped#1911]
### Describe your question

Hey there,

Jitpack has been down for over 24 hours now - See [this issue](https://github.com/jitpack/jitpack.io/issues/5337) to track what's been going on.

As I understand it, the [Piped-Backend NPE module](https://github.com/TeamPiped/Piped-Backend/blob/master/build.gradle#L10) is hosted by them, so when trying to build the backend, it now fails as it can't pull that dependency.

Given that not only did they go down, they are still down over 24h later, and even worse than that, they have been radio silent the entire time with hundreds of people sending them messages through various channels, I think it would be wise to consider moving away from Jitpack for dependency hosting.

My apologies if this is the wrong type of issue to post on - I don't really think this is a bug or a feature request, so I felt like this was the closest type available.

**Comment by Bnyro** [comment]
Thanks for the suggestion, however we currently don't plan to move away from Jitpack.
It's the simplest way to use Java libraries hosted on GitHub such as reqwest4j and Kavin's NewPipe Extractor fork and the downtimes are really low all in all.

**Comment by FireMasterK** [comment]
I actually publish reqwest4j to maven central, but automating the release cycle for NewPipeExtractor would be challenging currently
