### ISSUE TITLE
Returns 404 on URLs with channel alias

### ISSUE THREAD

**Issue by signnd** [TeamPiped/Piped#1914]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Piped returns a 404 when visiting a channel URL using channel aliases (youtube.com/@[channel-alias]). 

### To Reproduce

1. Visit a channel using the channel alias URL (e.g. https://piped.video/@flossycarter)

### Expected behavior

URL points to the channel and displays it

### Logs/Errors

Piped returns a 404 Page not found.

### Browser, and OS with Version.

Microsoft Edge 108.0.1462.46, Windows 11

### Additional context

Piped already supports youtube.com/(channel-name), youtube.com/user/(channel-name) and youtube.com/c/(channel-name) URL structures but is not yet supporting channel aliases

**Comment by float3** [comment]
I would like to see this fixed as well

**Comment by signnd** [comment]
Implemented in #2190
