### ISSUE TITLE
"Popular" section like trending and feed 

### ISSUE THREAD

**Issue by pGeek64** [TeamPiped/Piped#1918]
### Describe the feature

Can there be a Popular section in the 'piped.kavin.rocks' instance like invidious does

### Why would this be useful to add?

would be helpful for people who don't really know what to watch and doesn't like the trending cringe 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Dupe of #821
