### ISSUE TITLE
ADD more granular and faster speed options

### ISSUE THREAD

**Issue by allanlaal** [TeamPiped/Piped#1922]
### Describe the feature

speed selection would have speeds up to 4x (I know of ppl who can handle 8x too)

### Why would this be useful to add?

literally saves 2..4x time =)

### Concept(s)

same ui as now

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can now press `Shift` and `s` at the same time to open a dialog which allows setting a custom playback speed.
