### ISSUE TITLE
how I can publish my instance

### ISSUE THREAD

**Issue by starnakin** [TeamPiped/Piped#1923]
### Describe your question

Sorry I don't have understand where is the form to put my instance on this page https://github.com/TeamPiped/Piped/wiki/Instances

**Comment by Bnyro** [comment]
Please provide all the information needed here, we'll add it to the list if it's been set up properly.

**Comment by starnakin** [comment]
OK thank you
Name: Chauvetcorp
URL: https://pipedapi.chauvet.pro/
Location : France
CND: I don't understand what it is so probably no
Users: I don't know how to get it

**Comment by Bnyro** [comment]
see https://www.cloudflare.com/learning/cdn/what-is-a-cdn/ for info about CDN, if you don't use Cloudflare you probably don't have it anyways.

**Comment by Bnyro** [comment]
The user count is located at  https://pipedapi.chauvet.pro/registered/badge, but you don't have to worry about that.

**Comment by starnakin** [comment]
Thank you but I don't want setup a CDN

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!

**Comment by starnakin** [comment]
Hi, Can you remove my instance ? (The instance doesn't work  since #2487 ). I will rehost an instant later but currently I can't change my IP.

**Comment by Bnyro** [comment]
Sure, thanks for hosting an instance for the time being and I hope we'll see it back again soon :)

**Comment by starnakin** [comment]
Hi ! I'm back
