### ISSUE TITLE
piped instances do not render on safari ipados 9.3.5

### ISSUE THREAD

**Issue by thiccelf83** [TeamPiped/Piped#1925]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

On Safari (ipad mini 2 ios 9.3.5), all piped instances render as just blackness. i tested youtube and invidious instances to see if it was a technical issue, both worked. 

user agent: mozilla/5.0 (ipad; CPU OS 9.3.5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, Like geck). version/9.0 Mobile/13G36 Safari/601.1 
(unsure which of these is safari version)

### To Reproduce

On an ipad or iphone running ios 9.3.5 or earlier, open any iny piped instance, you wil lsee that it shows only a black screen.

That same instance will work on pc, android and even some of my more antiquated machines.

### Expected behavior

Piped to render its layout, video and site itself

### Logs/Errors

I am not a technical user, and this is my first ipad, I am trying right now to connect the device to my pc to use web inspector to provide more technical data, will follow up when I have success in that.

### Browser, and OS with Version.

IpadOS 9.3.5 On Safari 601.1 

Entire user agent -user agent: mozilla/5.0 (ipad; CPU OS 9.3.5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, Like geck). version/9.0 Mobile/13G36 Safari/601.1 

### Additional context

I know that some people will say that it shouldnt work. But, half the advantage of amazing services like pipd and invidious is that theyre light enough to run on older machines, something youtube cannot do. People had to compile skytube from source to watch videos before services like this started to crop up.

It only seems natural to make sure it works on somewhat older devices, this ipad is only from 2013 and is not that antiquated, it browses most sites like amazon, youtube, 4chan, twitter without any issues besides cert errors.

**Comment by FireMasterK** [comment]
Please reply with helpful information which can help debug the issue, such as logs from the JavaScript console.

I also believe images won't load, without Safari 14, since that was the version Apple **finally** added support for webp images.

So, this might, unfortunately, be a lost cause due to Apple.

**Comment by thiccelf83** [comment]
no... its because you used a ridiculous, pain in the ass technology like
webp that no one likes just for muh sleek and modernism

**Comment by thiccelf83** [comment]
the fact that you'd say taht when regular youtube and invidious work just
fine on safari just proves you are everything wrong with developers

**Comment by thiccelf83** [comment]
so basically this just a vanity project here to be different without offering any real benefit and being far more discriminating than even youtube due to the attraction for awful globally hated techs like webp

webps for a bunch of low res thumbnails 

that entire feature is just a vanity plant because developers like you literally cannot help but adding the NEWEST and SLEEKEST and most MODERN crap to your apps, no matter the cost, all because it pads your ego

trash, garbage

**Comment by thiccelf83** [comment]
BTW IT DOESNT WORK ON CURRENT CHROME ON IOS 15 EITHER SO YOUR EXCUSE IS INVALID AND YOUR JUST STUPID
