### ISSUE TITLE
[Bug] Youtube Live Stream not playing with Audio only Option 

### ISSUE THREAD

**Issue by OpenWick** [TeamPiped/Piped#193]
For example lofi hiphop stream  https://piped.kavin.rocks/watch?v=DWcJFNfaw9c isn't playing when audio only option is turned on.

**Comment by FireMasterK** [comment]
This is technically impractical to fix because YouTube sends both video and audio together.

To combat this, audio only mode is ignored in livestreams now in e243adb111ef21777450b56ff5bdcbd710130028.

**Comment by OpenWick** [comment]
Thanks for responding. But if I am not mistaken NewPipe can live stream without video. I don't know how they do it. May be if possible u can take a look into it. Any way thanks for this alternative
