### ISSUE TITLE
Piped Channel Profiles

### ISSUE THREAD

**Issue by duyfken** [TeamPiped/Piped#1936]
### Describe the feature

Currently we can access channel profiles that have been provided through Youtube. However, clicking the username visible in a Piped playlist, leads to the Piped homepage. What I'm proposing is the ability to set a channel profile and subsequently a privacy setting for the profile of a Piped account.

This would allow for a banner, profile picture and description, like Youtube profiles, to be uploaded if a profile is set to Public.

On the flipside, any account on Piped would default to Private, which would entirely remove the visibility of the Piped username that created the playlist and doesn't provide access to a channel profile at all (but playlists would still be accessible using direct links).

### Why would this be useful to add?

Provide extra privacy by default by removing the username/link on Piped playlists or allow public Piped profiles for people that choose to create privacy aware playlists for the public who are willing to avoid Youtube.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's beyond the scope of Piped.
