### ISSUE TITLE
Piped has been consistently down for the past week now

### ISSUE THREAD

**Issue by AntiquatedTeapot** [TeamPiped/Piped#1963]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

So for the past week the main Piped instance (and others I'm presuming) have been consistently down for a full week now. The page simply sits there and doesn't load anything, and likewise nothing loads when trying to play a video. Now, there have been times where I've been able to watch one or two videos, but this doesn't last long as the site goes right back to being down. (sidenote - the Piped Instances status webpage claims it's up and fine, but that's obviously false. Might be worth looking into?)

What is going on here?

### To Reproduce

1. Open this URL at https://piped.video
2. Wait to see if the main page loads
3. See that it doesn't

### Expected behavior

The instance should be working with no hiccups, obviously. 

### Logs/Errors

N/A

### Browser, and OS with Version.

Mozilla Firefox

**Comment by Bnyro** [comment]
Most nodes of the official instance work fine, there are issues with a few of them currently. However, that's not an issue of the project itself but of some servers of the official instance.
Other instances are not affected by that though.
Closing as it's not related to the project.
