### ISSUE TITLE
Comment text is "null" instead of actual comment

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#1967]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Text of a comment just reads `null`

### To Reproduce

1. https://piped.video/watch?v=-rodBIsXTfM
2. Kayodoms' comment reads "null"
3. https://www.youtube.com/watch?v=-rodBIsXTfM
4. Kayodoms' comment reads "we gonna ignore the fact that this dude jumped 10ft in the air? [#bunnies](https://www.youtube.com/hashtag/bunnies)"

### Expected behavior

Comments should contain correct text.

I don't think hashtags are supported by Piped, so maybe the link should be stripped.

### Logs/Errors

N/A

**Comment by TobiGr** [comment]
The bug is fixed upstream now
