### ISSUE TITLE
403 from react-native 

### ISSUE THREAD

**Issue by polsust** [TeamPiped/Piped#1971]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When trying to fetch any data from the official instance (https://pipedapi.kavin.rocks) from inside a react-native app a 403 is returned

It doesn't happen with other instances

### To Reproduce

1.  Get a react native enviroment setup https://reactnative.dev/docs/0.60/enviroment-setup
2.  Perform an http request to the official instance of piped

### Expected behavior

I expected to receive the data I was trying to fetch

### Logs/Errors

[AxiosError: Request failed with status code 403]

### Browser, and OS with Version.

`Host machine:` Arch linux
`Mobile device:` android
`React native vertsion:` 0.70.6

**Comment by FireMasterK** [comment]
Do you know what is the user agent from your application? I could whitelist it then

**Comment by PolSust** [comment]
Is this it?
```
musicapp/1.0.1 Mozilla/5.0 
(Linux; Android 13; sdk_gphone64_x86_64 Build/TPB4.220624.004; wv)
AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.74 Mobile Safari/537.36

```
Will this make it work on any device ?

**Comment by FireMasterK** [comment]
> Will this make it work on any device ?

Yes!

Let me know if it works now.

**Comment by PolSust** [comment]
It doesn't, I'm still getting a 403

**Comment by PolSust** [comment]
Hey ! Could you try whitelisting this one ?

```
musika/1.0.1 Mozilla/5.0 
(Linux; Android 13; sdk_gphone64_x86_64 Build/TPB4.220624.004; wv)
AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.74 Mobile Safari/537.36a
```
