### ISSUE TITLE
Unauthenticated RSS feeds partially broken

### ISSUE THREAD

**Issue by RetroAbstract** [TeamPiped/Piped#1979]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

For several days now, about half of the channels I subscribe to via unauthenticated RSS feeds are not reachable through the RSS Reader I use (RSS Guard). 

The Unreal Engine Youtube channel for example (https://pipedapi.kavin.rocks/feed/unauthenticated/rss?channels=UCBobmJyzsJ6Ll7UbfhI4iwQ), when RSS Guard either tries to fetch new articles (videos) from the feed or fetch the feed's metadata, I'm met with: "Network error: unknown error (InternalServerError)" as shown in the screenshot below. (_The metadata is already present as it had already been previously fetched when the feed was reachable_)

![10](https://user-images.githubusercontent.com/103272301/212213683-531906de-5957-4e13-aa73-4f4d12db274a.jpg)

The DigitalFoundry Youtube channel has no issues fetching new articles & the feed's metadata as shown below:

![11](https://user-images.githubusercontent.com/103272301/212214224-2d99bbed-fc86-4417-b968-935aaa03b94d.jpg)

I do not know what determines a piped feed bring broken or not. I doubt it's due to a channel not having uploaded recently as some feeds that upload daily which are in my feed subscription list are affected by this issue.

I also doubt it is an issue with RSS Guard as I have tested with different builds of the reader and was met with the same issue each time.

(Side note: Big thanks to @Bnyro for recently improving the RSS feeds regarding channel icons, names & video thumbnails)

### To Reproduce

There are no proper steps on how to consistently reproduce this as the issue varies from feed to feed.

### Expected behavior

Expected behavior is for RSS Guard to be able to fetch all piped feed metadata & videos (given the channel has recently uploaded of course).

### Logs/Errors

Not applicable

### Browser, and OS with Version.

Not applicable

### Additional context

This is the error log that's presented when opening the link of a seemingly broken piped RSS feed in a browser:

error:	"com.rometools.rome.io.FeedException: Invalid XML\n\tat com.rometools.rome.io.impl.Atom10Generator.fillContentElement(Atom10Generator.java:491)\n\tat com.rometools.rome.io.impl.Atom10Generator.populateEntry(Atom10Generator.java:305)\n\tat com.rometools.rome.io.impl.Atom10Generator.addEntry(Atom10Generator.java:137)\n\tat com.rometools.rome.io.impl.Atom10Generator.addEntries(Atom10Generator.java:123)\n\tat com.rometools.rome.io.impl.Atom10Generator.populateFeed(Atom10Generator.java:109)\n\tat com.rometools.rome.io.impl.Atom10Generator.generate(Atom10Generator.java:78)\n\tat com.rometools.rome.io.WireFeedOutput.outputJDom(WireFeedOutput.java:312)\n\tat com.rometools.rome.io.WireFeedOutput.outputString(WireFeedOutput.java:125)\n\tat com.rometools.rome.io.WireFeedOutput.outputString(WireFeedOutput.java:101)\n\tat com.rometools.rome.io.SyndFeedOutput.outputString(SyndFeedOutput.java:52)\n\tat me.kavin.piped.server.handlers.auth.FeedHandlers.unauthenticatedFeedResponseRSS(FeedHandlers.java:296)\n\tat me.kavin.piped.server.ServerLauncher.lambda$mainServlet$36(ServerLauncher.java:334)\n\tat io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)\n\tat io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:250)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)\n\tat java.base/java.lang.Thread.run(Unknown Source)\nCaused by: org.jdom2.input.JDOMParseException: Error on line 1: The reference to entity \"rs\" must end with the ';' delimiter.\n\tat org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:234)\n\tat org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:303)\n\tat org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1184)\n\tat com.rometools.rome.io.impl.Atom10Generator.fillContentElement(Atom10Generator.java:489)\n\t... 16 more\nCaused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 199; The reference to entity \"rs\" must end with the ';' delimiter.\n\tat java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanAttribute(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)\n\tat java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)\n\tat org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)\n\t... 19 more\n"

message:	"Invalid XML"

**Comment by Bnyro** [comment]
Apparently the issue is caused by the changes I made to the RSS feed. The solution to it is probably hidden somewhere in the docs of rome, it fails to parse the feed we create to xml but the error doesn't tell us why exactly unfortunately.
It might be because we're using `\n` for new lines, maybe we should try formatting the video information as html instead using `<br />`.
If Kavin doesn't have a better idea I'll try to do so tomorrow, although changes may be low that it's the actual issue.

**Comment by RetroAbstract** [comment]
This issue seems to be happening again, but instead of some feeds completely broken & others working fine, RSS Guard will successfully reach Piped feeds ~50% of the time in an inconsistent way.

The pattern is inconsistent, an example of what it's like: Network Error > Successful Connection > Successful Connection > Network Error  > Network Error > Network Error > Network Error > Successful Connection > Network Error > Network Error > Successful Connection.

Every feed has a different pattern, resulting in very inconsistent article/video fetching in RSS Guard everytime it pings all the Piped feeds.
