### ISSUE TITLE
No search result when there is an space at the end of the search term

### ISSUE THREAD

**Issue by ahangarha** [TeamPiped/Piped#1987]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Just search 'ruby ' or anything else that ends with space. There will be no result.

### To Reproduce

Open [this link](https://piped.video/results?search_query=ruby+ ) and see the result

### Expected behavior

Obviously to show the search result

### Logs/Errors

-

### Browser, and OS with Version.

Firefox 108.0.2 (64-bit) on Ubuntu

### Additional context

I think this is needs a simple trimming of search term

**Comment by FireMasterK** [comment]
I cannot reproduce this, the link you provided works fine, please provide logs from your browser.

**Comment by ahangarha** [comment]
Well, it is working now. When I reported this, I tried multiple instances and in none of them I could get results if there was a space at the end.

In any case, happy to see it is working now.
