### ISSUE TITLE
/feed responding "No host in query parameters."

### ISSUE THREAD

**Issue by mastazi** [TeamPiped/Piped#1993]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

when loading my Feed, a request is made to

`feet?authToken={token}`

I'm getting response code 200 and response body:

```
No host in query parameters.
```

and because of that, in the JS console I see

```
Uncaught (in promise) SyntaxError: Unexpected token 'N', "No host in"... is not valid JSON
```
and the /feed page is completely empty (it should instead show videos of channels I'm subscribed to)

### To Reproduce

1. go to the official Piped instance
2. log in
3. visit the /feed page
4. open dev tools and go to the network tab
5. refresh the page
6. observe the response of the /feed?authToken={token} call that is done in the background
7. switch to the console tab in dev tools and observe the JS error.

### Expected behavior

/feed?authToken={token}  should return a body in JSON format , not the string "No host in query parameters."

As a result of that, the /feed page should display recent videos from my subscribed channels

### Logs/Errors

Uncaught (in promise) SyntaxError: Unexpected token 'N', "No host in"... is not valid JSON
Promise.then (async)
mounted @ FeedPage.0586dc2d.js:1
(anonymous) @ index.2d950148.js:1
hn @ index.2d950148.js:1
xt @ index.2d950148.js:1
t.__weh.t.__weh @ index.2d950148.js:1
Of @ index.2d950148.js:1
Af @ index.2d950148.js:1
Promise.then (async)
Ef @ index.2d950148.js:1
ma @ index.2d950148.js:1
(anonymous) @ index.2d950148.js:1
dl @ index.2d950148.js:1
ci @ index.2d950148.js:1
pf @ index.2d950148.js:1
(anonymous) @ index.2d950148.js:1
dl @ index.2d950148.js:1
ci @ index.2d950148.js:1
pf @ index.2d950148.js:1
(anonymous) @ index.2d950148.js:1
dl @ index.2d950148.js:1
ci @ index.2d950148.js:1
pf @ index.2d950148.js:1
(anonymous) @ index.2d950148.js:1
dl @ index.2d950148.js:1
ci @ index.2d950148.js:1
pf @ index.2d950148.js:1
(anonymous) @ index.2d950148.js:1
dl @ index.2d950148.js:1
ci @ index.2d950148.js:1
pf @ index.2d950148.js:1
set value @ index.2d950148.js:1
be @ index.2d950148.js:762
(anonymous) @ index.2d950148.js:762
Promise.then (async)
X @ index.2d950148.js:762
T @ index.2d950148.js:762
install @ index.2d950148.js:762
use @ index.2d950148.js:1
(anonymous) @ index.2d950148.js:788

### Browser, and OS with Version.

Brave [Version 1.46.153 Chromium: 108.0.5359.128 (Official Build) (64-bit)](https://brave.com/latest/) on Linux Ubuntu 20.04

**Comment by FireMasterK** [comment]
Fixed a few days back, thanks for reporting this!
