### ISSUE TITLE
8K support.

### ISSUE THREAD

**Issue by Ilhamiii** [TeamPiped/Piped#1995]
### Describe the feature

Watch videos with 8K support.

### Why would this be useful to add?

Let's watch the video in 8K quality.

### Concept(s)

No

### Additional context

What is the maximum quality YouTube supports?

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
We have support already. Enable AV1 in your preferences.
