### ISSUE TITLE
>1080p resolutions became not available for non-AV1 videos

### ISSUE THREAD

**Issue by goodness-from-me** [TeamPiped/Piped#2006]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I have noticed that all the videos I watch on Piped are now playing at 1080p max and there are no higher resolutions in "Resolution" option. This wasn't happening before. I tried multiple instances, same result.

I also have noticed that it doesn't apply to Shorts, e.g. this Short is available at 1920p: https://piped.video/watch?v=DUp3P12lZQM

Another observation: AV1 videos have 1440p and 4K resolutions available if AV1 is selected in Preference and browser supports AV1 playback.

### To Reproduce

Precondition: AV1 video codec is deselected in Preferences.

1. Open https://piped.video/watch?v=nr4kmlTr9xw
2. Check "Resolution" option.
3. Observe 960p as highest available resolution.
4. Check the same video on YouTube: https://youtu.be/nr4kmlTr9xw
5. Observe more resolutions available than on Piped.

### Expected behavior

Piped should have the same video resolution options as on YouTube.

### Logs/Errors

N/A

### Browser, and OS with Version.

I think it's not browser and OS -dependent.
Tried on:
- Safari 16.2 running on MacOS 13.1
- Firefox 109 running on MacOS 13.1
- Chromium 109 running on Android 13
- Safari 16.2 running on iPad OS 16.2

### Additional context
My preferences:
![image](https://user-images.githubusercontent.com/42966950/213863852-482ba897-be34-44b4-8a1d-ca8a90fafc19.png)

**Comment by FireMasterK** [comment]
> AV1 videos have 1440p and 4K resolutions available if AV1 is selected in Preference and browser supports AV1 playback.

Expected behavior, since shaka-player, doesn't support smooth codec switching, which is required for mixing different codecs together.

**Comment by goodness-from-me** [comment]
Thanks for the clarification.
I chose VP9 and deselected all other codecs and 4K videos are back!
