### ISSUE TITLE
LocalHost SSL ERROR

### ISSUE THREAD

**Issue by WreckingBANG** [TeamPiped/Piped#2007]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I wanted to install Piped for my local network for testing purposes. I followed the instructions  https://docs.piped.video/docs/self-hosting/  and set the IP-Address of the Server as Hostname.

Now i get a SSL_ERROR_INTERNAL_ERROR_ALERT when trying to reach the Server with the IP-Address.

### To Reproduce

1. install Piped locally.
2. set IP-Address as Hostname
3. Open the Browser and try opening the Website

### Expected behavior

normal Piped overview

### Logs/Errors

SSL_ERROR_INTERNAL_ERROR_ALERT

### Browser, and OS with Version.

108.0.2 (64-bit) on ZorinOS

### Additional context

The Server is running Ubuntu

**Comment by FireMasterK** [comment]
> Piped for my local network for testing purposes

This is actually an unsupported use-case for Piped.

You could edit your `/etc/hosts` file, and add self-signed TLS certificates yourself on your server.

To get a working/updating subscriptions feed, you have to expose your API to the internet.

You could expose it through something like ngrok / cloudflare tunnels for example, and configure the `API_URL` configuration value.

**Comment by WreckingBANG** [comment]
Ok, Thank you. I will think about doing it.

**Comment by AeliusSaionji** [comment]
local-hosting unsupported is a shame for those of us who access self hosted resources through a vpn. 

Is there any chance the project could amend its pov on this?

**Comment by WreckingBANG** [comment]
This is how i got it working: https://gist.github.com/WreckingBANG/405235949c655cd8246188ba25c42277
