### ISSUE TITLE
YouTube Music search doesn't work anymore!

### ISSUE THREAD

**Issue by rozari0** [TeamPiped/Piped#2014]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

If I search for any music and apply the Music: songs filter piped returns an empty page. 

### To Reproduce

1. Go to the official instance 
2. Search for your favorite singer or song
3. Select **YT Music: songs**

### Expected behavior

Should show result from YT music.

### Logs/Errors

:(

### Browser, and OS with Version.

Mull 109.1.1 (Build #21091120) on Android 9

**Comment by Bnyro** [comment]
Can't reproduce, maybe it's been caused by a temporary server outage?

**Comment by rozari0** [comment]
> Can't reproduce, maybe it's been caused by a temporary server outage?

Maybe, I tested with other instances as well. 

It's working fine now. :)
