### ISSUE TITLE
Feed doesn't automatically update channels I'm subscribed to.

### ISSUE THREAD

**Issue by nanedi** [TeamPiped/Piped#2017]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Feed doesn't automatically update channels I'm subscribed to.

### To Reproduce

This would be an automated task.

### Expected behavior

When a channel posts a new video but it doesn't show up in my feed.
Self hosted server.

### Logs/Errors

No

### Browser, and OS with Version.

No

**Comment by AlyoshaVasilieva** [comment]
Is your server accessible to the public internet? If `pipedapi` is firewalled off then YouTube can't contact your server to notify of new videos

**Comment by nanedi** [comment]
Yes of course.
Some channels some new videos not all new videos.

Thanks

**Comment by Bnyro** [comment]
Duplicate of #1130
