### ISSUE TITLE
CORS error at my instance

### ISSUE THREAD

**Issue by alefvanoon** [TeamPiped/Piped#202]
![image](https://user-images.githubusercontent.com/53198048/122341783-b5aa9a00-cef8-11eb-9e57-bfba94466933.png)

**Comment by alefvanoon** [comment]
for all video.
im running latest proxy and backend.

**Comment by FireMasterK** [comment]
Are you using nginx?
If so use
```
add_header Access-Control-Allow-Origin *;
add_header Access-Control-Allow-Headers *;
if ($request_method = OPTIONS ) {
   return 200;
}
proxy_buffering on;
proxy_set_header Host $arg_host;
proxy_ssl_server_name on;
proxy_set_header X-Forwarded-For "";
proxy_set_header CF-Connecting-IP "";
proxy_hide_header "alt-svc";
sendfile on;
sendfile_max_chunk 512k;
tcp_nopush on;
aio threads=default;
aio_write on;
directio 2m;
proxy_hide_header Cache-Control;
proxy_hide_header etag;
proxy_http_version 1.1;
proxy_set_header Connection keep-alive;
proxy_max_temp_file_size 0;
access_log off;
proxy_pass http://unix:/tmp/http-socket/http-proxy.sock;
```
for your proxy.

The problem seems to be that:
```
Access-Control-Allow-Origin *;
Access-Control-Allow-Headers *;
```
headers are not added.

**Comment by alefvanoon** [comment]
Im not using nginx.

**Comment by FireMasterK** [comment]
What are you using then?

**Comment by alefvanoon** [comment]
hosting on heroku :))))

**Comment by FireMasterK** [comment]
How does that even work?!

Did you create 2 apps - one for the backend and one for the proxy?

You could try https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nginx

You would have to create a config file based on: https://github.com/heroku/heroku-buildpack-nginx/blob/main/config/nginx.conf.erb

**Comment by FireMasterK** [comment]
Closing this as there's nothing else actionable on my side.

Let me know if there's any way I can help.

**Comment by alefvanoon** [comment]
Thanks for your helping, i'm working on it.
