### ISSUE TITLE
White flash when loading page

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#203]
There is always a **really** annoying white flash before the page becomes dark

**Comment by FireMasterK** [comment]
https://user-images.githubusercontent.com/20838718/122574462-4bffcc80-d06d-11eb-8c85-49b97d05268f.mp4

It's almost non-noticeable from what I can tell, it likely takes less than a second on my laptop.

How long does it last/take on your browser?

**Comment by B0pol** [comment]
Less than a second too but it’s really annoying as it **flashes**. If you are in the dark it destroy your eyes

**Comment by FireMasterK** [comment]
Should be fixed in 5f2ec062a0404a6ded337af0e5d8c58e456980dc now. 👍
