### ISSUE TITLE
double tap to forward / rewind

### ISSUE THREAD

**Issue by asklow** [TeamPiped/Piped#2035]
### Describe the feature

Instead of fullscreen, double tap to forward / rewind on smartphones should make a good sense.

### Why would this be useful to add?

Welp, currently there's no way to forward / rewind precisely other than inaccurate seekbar.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Duplicate of #127
