### ISSUE TITLE
Video isn’t playing

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#204]
https://piped.kavin.rocks/watch?v=RGU-4iVs7X4

NewPipe can play a 360p video and piped-backend also provide that 360p video https://pipedapi.kavin.rocks/streams/RGU-4iVs7X4. I can play it with mpv

**Comment by FireMasterK** [comment]
Fixed in b18c34eb78d2683ea96d02bedf87257ff29aecc1.

**Comment by B0pol** [comment]
Ok I can play but it says quality = automatic but it is 360p **only** and will always be 360p so it should say 360p

**Comment by FireMasterK** [comment]
The problem with doing that is that these videos are loaded without a manifest.

To achieve this (and to play 360p in a video with 720p), a dash/hls manifest needs to be created.

**Comment by FireMasterK** [comment]
This will be tracked in #207

**Comment by FireMasterK** [comment]
Strangely, this example you provided now has actual streams tracks that can be used for DASH.

**Comment by B0pol** [comment]
Yes, sometimes YouTube won't upload all video qualities, you have to wait few hours
