### ISSUE TITLE
Really bad subscriptions feed reliability issues on another instance

### ISSUE THREAD

**Issue by Ammako** [TeamPiped/Piped#2040]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I use adminforge.de instance. In recent months the feed has gotten really unreliable. I had assumed there were issues with youtube itself, from things I've read on other issues, but I realized yesterday that actually, all works perfectly on official Piped instance.

On individual channels' subscription pages, everything seems fine. The videos show up there with the proper upload date. but the subscription feed doesn't reflect that. Videos often don't show up right away, and once they do show up, the upload date shown on the feed can vary wildly. In some cases the upload date shown on Feed is far back enough in the past that the video gets buried lower down the subscription feed and I miss it entirely. In the most extreme cases I have seen several weeks' discrepancy in video upload dates. If I switch to official Piped instance for authentication, the feed works perfectly, video upload dates are correct and videos show up when they should.

I emailed the instance owners about this, and they say I'm the first to report something like this. This has been going on for months for me, and I can reproduce the problem very easily, but they say they're not able to reproduce it themselves. So I'm not sure what's going on. They asked me to report here instead (I'll link them to this issue so they can chime in and hopefully collaborate on finding what the problem is.)

### To Reproduce

1. Use piped.adminforge.de
2. Worst example: subscribe to https://piped.adminforge.de/channel/UCv0cBz_Vdmd84xYl7gKWwQA
3. Check discrepancy in upload date between channel page, and subscriptions feed

### Expected behavior

The feed should show videos reliably, with as similar of an upload date as possible as their individual channel pages show (I'm aware that Youtube itself has a problem and that identical upload times between feed and channel pages isn't possible, but this is a different problem entirely.)

### Logs/Errors

(Not sure what kind of logs are needed here, maybe they'd need to provide those themselves? but if they're not able to reproduce it on their end then I'm not sure what kind of logs they could give...)

### Browser, and OS with Version.

Edge 109.0.1518.70 on Windows 10

### Additional context

Note: Piped and LibreTube are equally affected. I'm only showing Piped screenshots for convenience.

<details>
  <summary>Channel page:</summary>
  
  ![image](https://user-images.githubusercontent.com/108308111/215330461-33d4e41d-7054-488f-8710-08e56bfe8518.png)
  
</details>

<details>
  <summary>Feed:</summary>
  
  adminforge.de:
  ![image](https://user-images.githubusercontent.com/108308111/215330770-b64d82b0-f42f-42bd-b57d-7d0b214bb669.png)
  
  Piped official:
  ![image](https://user-images.githubusercontent.com/108308111/215330743-f50b4785-978f-4b5e-b689-82e157b07e64.png)
  
</details>

<details>
  <summary>Full feed comparisons:</summary>
  
  adminforge:
  ![image](https://user-images.githubusercontent.com/108308111/215331051-8892fba2-5e49-42c4-912b-1ff85ef85705.png)
  
  Piped official:
  ![image](https://user-images.githubusercontent.com/108308111/215331077-e963abfe-fe6e-4661-b7df-c44bff6ade11.png)
  
</details>

**Comment by Warden20** [comment]
This happens in the official instance sometimes

**Comment by FireMasterK** [comment]
Can you take a look at the pubsub debug info for channels that aren't working?

You have to go to https://pubsubhubbub.appspot.com/subscribe

Enter a callback URL for your instance, for example the official instance's one is https://pipedapi.kavin.rocks/webhooks/pubsub (just change the hostname)
Enter the affected channel topic, for example https://www.youtube.com/xml/feeds/videos.xml?channel_id=UC3U1k6n2HLZ2BlMoAXhNsEA (you'll have to change the channel ID)

I'd recommend looking at the `State` and `Last delivery error` fields.

For example, see https://pubsubhubbub.appspot.com/subscription-details?hub.callback=https%3A%2F%2Fpipedapi.kavin.rocks%2Fwebhooks%2Fpubsub&hub.topic=https%3A%2F%2Fwww.youtube.com%2Fxml%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUC3U1k6n2HLZ2BlMoAXhNsEA&hub.secret=

**Comment by FireMasterK** [comment]
> Ah interesting, thank you for the debug info. This explains at least _my_ problem. I am still in early development of my cluster, which is why the site is not public yet. (no DNS/ port forwarding). That would explain why the webhook would not ...hook. (right?)

Yes, that's exactly it. You need to be exposed publically for it to work.

**Comment by FireMasterK** [comment]
Closing this issue as the channel in the original issue comment work as expected on the adminforge.de instance.

My best guess is the many silent improvements that I have made have helped.

If this issue resurfaces, please send a comment in #1130
