### ISSUE TITLE
cannot see video 4k

### ISSUE THREAD

**Issue by iZel345** [TeamPiped/Piped#2042]
### Describe your question

https://rimgo.pussthecat.org/S5vG6gW

**Comment by FireMasterK** [comment]
Do you see the 4k option when viewing the same video on YouTube?

Do you have AV1 enabled in your preferences?

**Comment by goodness-from-me** [comment]
Try to disable H264 codec in Preferences as well. It helped me.

**Comment by iZel345** [comment]
> 

I tried to enable AV1 but it doesn't change anything. I tried an another video, I cannot see video in 4K.

**Comment by iZel345** [comment]
It's weird because on brave I cannot see video in 4k, but in firefox I can.
