### ISSUE TITLE
reqwest4j crashes on self-signed certificates (backend)

### ISSUE THREAD

**Issue by yFkC1gTR59txdch2dGWT** [TeamPiped/Piped#2050]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

After this https://github.com/TeamPiped/Piped-Backend/pull/511 got merged and pushed to docker the container crashes often when running on a self-hosted instance with a self-signed certificate

### To Reproduce

Host your own version locally with a self-signed certificate

### Expected behavior

Previous behavior or a configurable parameter to allow for insecure certificates 

### Logs/Errors

```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("pipedapi.example.org")), port: None, path: "/webhooks/pubsub", query: None, fragment: None }, source: hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: InvalidCertificateData("invalid peer certificate: UnknownIssuer") } }) }', src/lib.rs:60:30```

**Comment by FireMasterK** [comment]
Can you provide full logs? I don't think the backend should ever connect to itself...
