### ISSUE TITLE
Reduce space taken by videos

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#206]
(2nd time! see #71)

If you play any music song, video will be larger than screen.

Steps to reproduce
1. Play a music song. I mean YouTube music so use search filters or pick this video https://piped.kavin.rocks/watch?v=QBujjGr_ZxY

Screenshots (using firefox screenshot)
- full screen (needs two entire screens to view title)  
![Screenshot 2021-06-18 at 15-20-19 Friday (Dopamine Re-Edit) - Piped](https://user-images.githubusercontent.com/58657617/122567275-ca964300-d048-11eb-9988-3828d4c03495.png)
![Screenshot 2021-06-18 at 15-21-55 Friday (Dopamine Re-Edit) - Piped](https://user-images.githubusercontent.com/58657617/122567475-fdd8d200-d048-11eb-93b3-b3a04161ddbd.png)
- full page  
![Screenshot 2021-06-18 at 15-20-32 Friday (Dopamine Re-Edit) - Piped](https://user-images.githubusercontent.com/58657617/122567349-dbdf4f80-d048-11eb-822e-9cc542191bec.png)

**Comment by FireMasterK** [comment]
I'm aware of this but I'm not sure how this should be handled.

Currently the video is expanded to the maximum width of the container, and can hence overflow downwards.
