### ISSUE TITLE
Wierd ? characters on my instance

### ISSUE THREAD

**Issue by pr0ton11** [TeamPiped/Piped#2094]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Using the latest frontend docker container, on [my instance](https://piped.pr0.tech/), I have these very weird ? characters on some video titles.
I checked the charset of the page, but it seems to be utf-8.
Could someone help me figure out the issue?

### To Reproduce

Open my instance
See in the Trending page some video titles have ? in the title

### Expected behavior

No ? in the title

### Logs/Errors

No errors, everything is a clear 200 when I inspect the page

### Browser, and OS with Version.

Firefox

### Additional context

I am rebuilding the container to include a workaround for replacing the URL at runtime instead of on build time. This should not affect the actual frontend though.

**Comment by pr0ton11** [comment]
Found the issue myself. It was because I was using the GraalVM Image. I switched to the default one and now it's gone.

**Comment by FireMasterK** [comment]
Weird that GraalVM has encoding issues :thinking:
