### ISSUE TITLE
Call to /feed?authToken={token} returning 520

### ISSUE THREAD

**Issue by mastazi** [TeamPiped/Piped#2096]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When I load the feed page, the layout is loaded (nav, title, footer etc.) but there are no videos displayed.

Opening the Dev tools, I can see that the call to /feed?authToken={token} is returning code 520, and the response body is empty.

### To Reproduce

1. log in
2. make sure you are using an account that is subscribed to some channels
3. navigate to https://piped.kavin.rocks/feed
4. check if you can see any video thumbnails & titles (I can't).

### Expected behavior

My account is subscribed to many channels (about 500) so the feed should be full of videos.

### Logs/Errors

![Screenshot from 2023-02-12 10-50-53](https://user-images.githubusercontent.com/1661655/218285934-444db904-1bb2-4ea4-bccb-1c5ab4bb1960.png)
![Screenshot from 2023-02-12 10-51-01](https://user-images.githubusercontent.com/1661655/218285938-38bf477b-a3d3-476b-b9ca-bf187006749b.png)

### Browser, and OS with Version.

Brave [Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (64-bit)](https://brave.com/latest/)
on Ubuntu Ubuntu 22.04.1 LTS

**Comment by mastazi** [comment]
Just an update to say that this same issue came back today.

**Comment by mastazi** [comment]
Today back to getting 520

**Comment by FireMasterK** [comment]
Hi, this should be fixed a while back!
