### ISSUE TITLE
Self-Hosted Piped instane not loading properly.

### ISSUE THREAD

**Issue by Raccoon727** [TeamPiped/Piped#2097]
### Describe your question

I decided to self-host my own Piped instance. Following [this official guide](https://docs.piped.video/docs/self-hosting/#docker-compose-nginx-aio-script) I ssh'd into my VPS installed git docker and docker-compose, cloned the repo, ran the configure-instance.sh script created the A records at epik.com ran docker-compose up -d and pasted the same nginx config at /etc/nginx/sites-available/piped.conf

```
server {
    server_name piped.cosmicraccoon.xyz pipedapi.cosmicraccoon.xyz pipedproxy.cosmicraccoon.xyz ;

    location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_set_header Host $host;
    }
} 

+some other stuff from certbot for https 
```
My VPS is running Debian 10 and when i run  `# systemctl status nginx` everything is looking fine, no errors or warnings.

When I go to [piped.cosmicraccoon.xyz](https://piped.cosmicraccoon.xyz) the user interface thing is there like I can see the Piped logo and the menus  "Preferences Login" etc. but under Trending it's empty and when I try to search again it's empty and nothing loads.

If you go to [piped.cosmicraccoon.xyz](https://piped.cosmicraccoon.xyz) you can see what I mean.

There are 4 errors when I press F12 on the website.

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.cosmicraccoon.xyz/config. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

`Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource. `

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.cosmicraccoon.xyz/trending?region=US. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.`

and 

`Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.`

In the repo I cloned I can see a folder named "config" and inside it some some nginx example configs for the frontend, api and proxy. Could it have something to do with those ?

I also created a symlink with
`ln -s /etc/nginx/sites-available/piped.conf /etc/nginx/sites-enabled`

Anyone know why this is happening and how I can fix it ? Thank you.

**Comment by luckkmaxx** [comment]
I had that issue. I dont remember what I did, but I think it was the "entrypoint" option in the piped-fronted compose lines.
There is a part thats says `pipedapi.kavin.rocks/....` after the slash you should set your own api domain. This is something I didnt noticed before, and I think THAT is what fixed the empty site without videos.

**Comment by Raccoon727** [comment]
I'm not sure I understand. In which file is the entrypoint option ?

**Comment by luckkmaxx** [comment]
I was talking about the docker-compose.yaml file. But I think you have a problem with your nginx config.
Your errors says 'Reason: CORS header ‘Access-Control-Allow-Origin’ missing' wich makes me think your '/etc/nginx/sites-available/piped.conf' has something wrong or missing.
I cant help you with that. I use "Nginx Proxy Manager" and I haven't to create the .conf file myself there (It is done in a webUI)

**Comment by luckkmaxx** [comment]
maybe in the line:
proxy_set_header Host $host;

yoy missed to change '$host' to the real host ip...

**Comment by FireMasterK** [comment]
You should normally get a JSON response with the status code 200.

**Comment by Raccoon727** [comment]
I'm on a trip right now and I only have my phone so I will try getting it to work when I get back home.
