### ISSUE TITLE
Is yet a way to fix the feed update on locally-self-hosted instance?

### ISSUE THREAD

**Issue by luckkmaxx** [TeamPiped/Piped#2103]
### Describe your question

As I saw on some theads, if you have a non externally reachable instance, then you cant get the subscriptions feed being propperly updated.
There was a workaround setting a cronjob, wich AFAIK this no longer works.
I dont want to expose my instance to the world, so right now my experience is bad, since I have to enter on every channel to check and look for new content.

Is there another workaround (or work in progress) to fix this?

Thanks in advance.

**Comment by luckkmaxx** [comment]
Today I've noticed that "shorts" are being updated on feed. Is it weird, dont you think? because.... well, if one type of video is working why not the rest of them?

**Comment by FireMasterK** [comment]
I've been considering/thinking about just letting such instances fetch/update feeds from a public instance instead of from YouTube.

**Comment by luckkmaxx** [comment]
Well if that solves this issue, wich, as I read is here at least a pair years ago, then go ahead!.
I will test it in my local network instance when have it done, and report here or wherever the results.

**Comment by FireMasterK** [comment]
Sure, let's move this to #707 since this is just a duplicate.

**Comment by luckkmaxx** [comment]
I have to add that recently I changed my instance to work with external dns (duckdns).
Then all worked as expected (feeds page is updated with new videos)
BUT this only worked for two days, then AGAIN I have to access on every subscription page to get the new videos.

I am a little confused. This is supposed to be working well!
