### ISSUE TITLE
Embed videos in RSS feeds

### ISSUE THREAD

**Issue by jensodeg** [TeamPiped/Piped#2130]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

When subscribing to a channel feed using an RSS reader, posts do not include an embedded video player, only a clickable thumbnail link to the video URL.

### To Reproduce

1. Get a Piped channel RSS feed URL, like this one: https://pipedapi.kavin.rocks/feed/unauthenticated/rss?channels=UC6nSFpj9HTCZ5t-N3Rm3-HA
2. Subscribe to the feed in an RSS feed reader
3. Open up any post in that feed

### Expected behavior

I expected an embedded Piped video inside the RSS feed, since Piped supports embedding, and embedding RSS posts works fine in general with Youtube RSS feeds.

### Logs/Errors

N/A

### Additional context

I've tested this with Feedly and Feedbin.

**Comment by Bnyro** [comment]
Is there any RSS feed reader that actually supports HTML embeds?
Neither Read You on Android nor any feed reader in the internet (e.g. https://rssviewer.app/) seem to support it, so I don't really think supporting that makes sense (and I can't add it without being able to test it).

**Comment by jensodeg** [comment]
I watch YouTube videos embedded inside posts using Feedbin.

**Comment by Bnyro** [comment]
Looking at https://www.youtube.com/feeds/videos.xml?channel_id=UCX6OQ3DkcsbYNE6H8uQQuVA, it seems like YouTube is using the [Media RSS specification](https://www.rssboard.org/media-rss#media-content).

In order for the video to be able to be played, YouTube somehow uses the Adobe Flash player to play the video directly, which won't be possible for us.

However, it seems like we can use [media:player](https://www.rssboard.org/media-rss#media-player), which is able to play videos in a browser console.

Not sure if the RSS library we use supports the Media RSS specification though.
