### ISSUE TITLE
Cache small streams for offline replay (mainly audio streams)

### ISSUE THREAD

**Issue by opusforlife2** [TeamPiped/Piped#2133]
### Describe the feature

Just like Newpipe, I would like to be able to turn off internet and replay a song on Piped multiple times. Currently, the stream is downloaded again upon replaying.

### Why would this be useful to add?

Feature parity with Newpipe, and data saving.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope due to the additional complexity this would add to Piped.
