### ISSUE TITLE
Some video titles are translated into English.

### ISSUE THREAD

**Issue by Qaz-7** [TeamPiped/Piped#2145]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

In Piped, some Turkish video titles are translated into English.The video title should be shown as written by the creator.It is displayed correctly in the player

### To Reproduce

1.https://piped.video/watch?v=EN-os8J8z_A&t=0
2.This video
3.Location: Turkey
4.The trending page has this video.

### Expected behavior

The title should be displayed as written.Anticipate the translation.

### Logs/Errors

There is no need for that

### Browser, and OS with Version.

1.Chrome 110.0.5481.153 version
2.Android 12
3.This is not related to the browser.
4.Server or Piped problem

### Additional context

![Screenshot_20230228-135522_Chrome](https://user-images.githubusercontent.com/124310688/221822055-1eebabd8-73c5-4cce-9a88-c5eb81bc95dc.jpg)

**Comment by Bnyro** [comment]
That's not an issue of Piped, it's rather one of the NewPipe extractor.
