### ISSUE TITLE
Unable to add videos on self hosted piped

### ISSUE THREAD

**Issue by aamirahmad170** [TeamPiped/Piped#2156]
### Describe your question

Hi,

I installed piped and used hosts files to redirect to my local VM.

now how to add new videos to piped ?

Amir

**Comment by FireMasterK** [comment]
Subscribe to some channels?

**Comment by aamirahmad170** [comment]
no i want to play my own videos hosted on my server. is that not what this is for?
please help

**Comment by erazemk** [comment]
No, Piped is a YouTube frontend, so it only proxies YouTube videos, it doesn't host videos by itself. What you might be looking for is PeerTube.

**Comment by FireMasterK** [comment]
You might want to look at peertube instead!
