### ISSUE TITLE
add pipedapi.alefvanoon.xyz

### ISSUE THREAD

**Issue by alefvanoon** [TeamPiped/Piped#216]
Hey, Please add https://pipedapi.alefvanoon.xyz to https://github.com/TeamPiped/Piped/wiki/Instances .

**Comment by FireMasterK** [comment]
Hey, I see you are using cloudflare but are not allowing origin cache control..

Please add a page rule like so:

URL: pipedapi.alefvanoon.xyz/*
with the following settings:
![image](https://user-images.githubusercontent.com/20838718/122973108-7f649300-d3ae-11eb-88ce-e459595f686d.png)

**Comment by alefvanoon** [comment]
Thanks, it's done now.
![image](https://user-images.githubusercontent.com/53198048/122976774-9b821900-d349-11eb-8c3b-24425980cb4f.png)

**Comment by FireMasterK** [comment]
Perfect!
One last thing:
Change Browser `Cache Control` to `Respect Existing Headers`
Like so:
![image](https://user-images.githubusercontent.com/20838718/122979862-ae323780-d3b5-11eb-8ffd-8a4f0c360a82.png)

**Comment by alefvanoon** [comment]
> Change Browser `Browser Cache TTL` to `Respect Existing Headers` as this can override what Piped sets it to.
Done!

**Comment by FireMasterK** [comment]
Awesome, thanks again!

The instance has been added now.
