### ISSUE TITLE
Add duration to RSS feed

### ISSUE THREAD

**Issue by vwkd** [TeamPiped/Piped#2167]
### Describe the feature

It would be great if a feed entry in the RSS feed also contains the duration of the video.

The duration could be added to the title or the description.

### Why would this be useful to add?

It would allow to filter the RSS feed based on the duration. For example, one could filter a high-frequency news channel feed for only occasional long in-depth videos.

### Concept(s)

For example, a feed entry with the duration at the end of the title could look like this

```
<entry>
    <title>Some title | Some channel | 42:21</title>
    <link rel="alternate" href="https://piped.video/watch?v=abcdef" />
    <author>
      <name>Some channel</name>
      <uri>https://piped.video/channel/zyxwuv</uri>
    </author>
    <id>https://piped.video/watch?v=abcdef</id>
    <updated>2001-01-01T10:00:00Z</updated>
    <published>2001-01-01T10:00:00Z</published>
    <content type="xhtml">
      <div xmlns="http://www.w3.org/1999/xhtml">
        <a href="https://piped.video/watch?v=abcdef">
          <img src="https://pipedproxy.kavin.rocks/vi/abcdef/maxresdefault.jpg?host=i.ytimg.com" />
        </a>
      </div>
    </content>
    <dc:date>2001-01-01T10:00:00Z</dc:date>
  </entry>
```

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
I'm not sure I like the idea of adulterating the title of videos. I would like additional feedback from RSS users.

**Comment by RetroAbstract** [comment]
> I'm not sure I like the idea of adulterating the title of videos. I would like additional feedback from RSS users.

I second OP's FR, however I think having the video duration in a feed entry's content body below the video thumbnail would be much better than having it in the title. 

Including the video description and maybe a "shorts" indicator in the feed entry's content body would also be great as it would allow for more precise filtering aswell.
