### ISSUE TITLE
[suggestion] adding noscript for `/embed/`, linking to normal video site

### ISSUE THREAD

**Issue by eladkarako** [TeamPiped/Piped#2168]
### Describe the feature

something like youtube's:  

![2023-03-04_153455](https://user-images.githubusercontent.com/415238/222905403-6161f604-73c2-4061-a0c0-d82c65a32d76.png)

would be very helpful in the `/embed/` pages.

there is a very little to add to the page,  
mostly this is it..  

```html
<html ... >

<body>

...
....

    <noscript>
      <div class="player-unavailable">
        <h1 class="message">An error occurred.</h1>
        <div class="submessage"><a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">Try watching this video on www.youtube.com</a>, or enable JavaScript if it is disabled in your browser.</div>
      </div>
    </noscript>
  </body>
</html>
```

you can base the instance on whatever subdomain `/embed/` is from,  
since no js is available you'll have to render that part in the html in the server-side, or just use `pipe.video`, even a textbox with the video id, or a "watch in youtube" link would be helpful.

### Why would this be useful to add?

I usually have javascript disabled across every page,  
unless I specifically allow it.  
Chrome is strict for iframes in pages that have javascript disabled,  
even if I allow `piped.video` and all its subdmains and can play the `/embed/` page by itself in a new page, it won't work on actual pages.  
and enabling javascript support for 3rd-party page just to view its iframe is counter-effective, security wise. normally in YouTube, I'll just click the link, to open the video in a new tab, but piped pages do not have that (hence the suggestion) 

### Concept(s)

(see "Describe the feature")

### Additional context

(none)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This is unfortunately not possible, since we don't have any server-side rendering at this time, unfortunately!
