### ISSUE TITLE
Piped-Backend: Fatal glibc error: CPU does not support x86-64-v2, host machine too old or fixable with a workaround?

### ISSUE THREAD

**Issue by DutchComputerKid** [TeamPiped/Piped#2182]
### Describe your question

Now I do not suppose many will have this issue, but did glibc get updated to version 9 and above last night in the docker container?

Piped-Backend no longer works, restarting every few seconds. Is there a way to work around this or not at all?
Machin in question is an HP DL585 G5, AMD Opteron over 4 sockets.

**Comment by FireMasterK** [comment]
Hi, can you see if replacing the image from 1337kavin/piped:latest to 1337kavin/piped:hotspot fixes this? (In docker-compose.yml)

**Comment by DutchComputerKid** [comment]
Yes, that worked! But for anyone else having this issue in the future, what is the difference?

**Comment by DutchComputerKid** [comment]
Ahhh thats why, I see. This question may be closed then, until gcc 9 appears again.
