### ISSUE TITLE
Watched videos aren't hidden on some browsers

### ISSUE THREAD

**Issue by monke0192** [TeamPiped/Piped#2227]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

On some browsers (Firefox, Safari, Chromium) watched videos are not hidden in the feed.

### To Reproduce

1. Click and fully watch a video in the feed
2. Return back to the feed page

### Expected behavior

The watched video should be hidden

### Logs/Errors

N/A

### Browser, and OS with Version.

OS: macOS Ventura 13.2.1
Browsers:
+ Firefox Developer Edition 112.0b3
+ Chromium 111.0.5563.64
+ Safari 16.3

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/pull/3024
