### ISSUE TITLE
[Live Streams] Confusing and mixed content showing

### ISSUE THREAD

**Issue by Oxtie** [TeamPiped/Piped#2228]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Mixed contents are showing up in LiveStream because contents are NOT sorted according to number of people viewing AND In a Live stream, contents that show ("2 mintues ago" or "17 minutes ago" or XX minutes/hours ago) should NOT show up.

### To Reproduce

Go to Piped home page, then a content channel's home page, click Livestream button and notice mixed non-live contents

### Expected behavior

Only True "Live" content should have been visible and rest should've been HIDDEN

### Logs/Errors

no errors, just incorrect content 

### Browser, and OS with Version.

Vivaldi latest

**Comment by Bnyro** [comment]
If it really would be an issue, then it would be one of the NewPipe Extractor, feel free to provide that feedback at the [PR for it](https://github.com/TeamNewPipe/NewPipeExtractor/pull/951) accordingly.
However, the livestream tab shows already finished, past livestreams too which should explain it, I don't see an issue here.

**Comment by FireMasterK** [comment]
You see what exactly what's available on YouTube. If it shows up like that on YouTube, it will on Piped too.
