### ISSUE TITLE
Error after installation with Docker-Compose Caddy AIO script

### ISSUE THREAD

**Issue by edco100** [TeamPiped/Piped#2250]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

I followed the exact process as described in the official documentation. After the last step, running:

`docker-compose up -d`

I encountered the following error:

`Error response from daemon: driver failed programming external connectivity on endpoint caddy (ad7623a30c062e89b8894c73c1e614371e6a5210de9b9ae7aea795e60613745b): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use`

The caddy container doesn't seem to start up properly.

When I opened the domain in the browser I see the standard Apache page.

### To Reproduce

1. Follow the official guide
2. run docker-compose up -d

### Expected behavior

I was expecting to open the domain that I specified and see the piped page.

### Logs/Errors

After the docking compose command:

`[+] Running 42/42
 ⠿ watchtower Pulled                                                                                        21.3s
   ⠿ 7e1f4ce8770d Pull complete                                                                              4.1s
   ⠿ cc408d374d64 Pull complete                                                                              6.0s
   ⠿ 4412f0a27731 Pull complete                                                                              7.8s
 ⠿ nginx Pulled                                                                                             33.3s
   ⠿ 8c7e1fd96380 Pull complete                                                                              4.8s
   ⠿ 86c5246c96db Pull complete                                                                              6.3s
   ⠿ b874033c43fb Pull complete                                                                             10.6s
   ⠿ dbe1551bd73f Pull complete                                                                             14.2s
   ⠿ 0d4f6b3f3de6 Pull complete                                                                             16.6s
   ⠿ 2a41f256c40f Pull complete                                                                             19.8s
 ⠿ piped Pulled                                                                                             34.7s
   ⠿ 74ac377868f8 Pull complete                                                                              3.2s
   ⠿ a182a611d05b Pull complete                                                                              5.9s
   ⠿ e58ce1bd2f23 Pull complete                                                                             10.6s
   ⠿ e1b7fbdee987 Pull complete                                                                             14.1s
   ⠿ 69057d918af6 Pull complete                                                                             16.2s
   ⠿ 3f5c6ef9a1e7 Pull complete                                                                             19.6s
   ⠿ 30dbaa6f42a4 Pull complete                                                                             22.3s
 ⠿ caddy Pulled                                                                                             28.2s
   ⠿ ef5531b6e74e Pull complete                                                                              5.4s
   ⠿ 27e3e797818b Pull complete                                                                              8.0s
   ⠿ 5cebb4c80b39 Pull complete                                                                             12.1s
   ⠿ 90648ba22c19 Pull complete                                                                             14.8s
 ⠿ pipedfrontend Pulled                                                                                     39.6s
   ⠿ 2a9360541423 Pull complete                                                                             23.7s
   ⠿ 6f4d2fb801f9 Pull complete                                                                             25.5s
 ⠿ postgres Pulled                                                                                          36.3s
   ⠿ 63b65145d645 Pull complete                                                                              2.5s
   ⠿ c441836541d9 Pull complete                                                                              4.5s
   ⠿ d49de1a24361 Pull complete                                                                              6.4s
   ⠿ 6c609d08dc3c Pull complete                                                                             13.0s
   ⠿ e801cecfb07c Pull complete                                                                             15.7s
   ⠿ 98756d431840 Pull complete                                                                             17.6s
   ⠿ d991736c9c5a Pull complete                                                                             20.6s
   ⠿ c708ebe2e647 Pull complete                                                                             24.9s
 ⠿ piped-proxy Pulled                                                                                       32.7s
   ⠿ 7807d201190a Pull complete                                                                              6.7s
   ⠿ b4c9df939e84 Pull complete                                                                             11.4s
   ⠿ 0c3feededca2 Pull complete                                                                             13.5s
   ⠿ f93d0b095da6 Pull complete                                                                             15.8s
   ⠿ 703798d07f89 Pull complete                                                                             18.9s
[+] Running 9/100
 ⠿ Network piped-docker_default       Created                                                                1.6s
 ⠿ Volume "piped-docker_caddy_data"   Created                                                                0.5s
 ⠿ Volume "piped-docker_piped-proxy"  Created                                                                0.4s
 ⠿ Container watchtower               Started                                                               22.9s
 ⠿ Container caddy                    Starting                                                              37.8s
 ⠿ Container postgres                 Started                                                               23.4s
 ⠿ Container piped-proxy              Started                                                               26.5s
 ⠿ Container piped-backend            Started                                                               15.5s
 ⠿ Container piped-frontend           Started                                                               21.3s
 ⠿ Container nginx                    Started                                                               20.2s`

The the actual error:

`Error response from daemon: driver failed programming external connectivity on endpoint caddy (5846b1d62bce767ad47c5839463c48b20ddcda3c63a8d9128eeb8be87820b410): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use`

### Browser, and OS with Version.

Ubuntu 22.04. on a VM on a remote server
Brave Browser

### Additional context

I apologize if I missed something obvious... I'm still learning.

Thank you!

**Comment by FireMasterK** [comment]
You already have something running on port 80, hence why you can't run with Caddy, since it requires ports 80 and 443.

You should run the nginx version instead, which is intended if you already have a reverse proxy.

**Comment by edco100** [comment]
Thank you for the fast answer. I didn't know that I have a reverse proxy already running since this is a fresh server.

Can I just run the nginx version now or do I have to uninstall everything?

**Comment by FireMasterK** [comment]
> I didn't know that I have a reverse proxy already running since this is a fresh server.

Weird, you can see what's running/listening on port 80 and 443 with `netstat -tunpl | grep -i listen`.

> Can I just run the nginx version now or do I have to uninstall everything?

You can run `docker-compose down` and then run the configure instance script again!

**Comment by edco100** [comment]
Thank you for you help!
