### ISSUE TITLE
Feature request: RSS subscriptions

### ISSUE THREAD

**Issue by Duckbilled** [TeamPiped/Piped#226]
It would be nice to follow channels and playlists via RSS

**Comment by FireMasterK** [comment]
To follow channels, please use URLs like: https://www.youtube.com/feeds/videos.xml?channel_id=UCLXo7UDZvByw2ixzpQCufnA
I have no intentions to allow them for channels, however, I will consider playlists.

**Comment by FireMasterK** [comment]
Closing this with aa81677450b5f505df922f5bf3b58582dd09cd91.
