### ISSUE TITLE
Built-in proxy load balancing

### ISSUE THREAD

**Issue by FarisZR** [TeamPiped/Piped#2278]
### Describe the feature

It would be great if piped had an internal way to load balance between yt-proxies, the most bandwidth heavy part of piped

### Why would this be useful to add?

It makes it easier to balance bandwidth and provide faster speed to users, without relying on an external load balancer, that's very expensive most of the time (Cloudflare $5 for 2 origins, and $5 per additional origin, with costs per DNS request.)

### Concept(s)

Round-robin (proxy2.domain, proxy1.domain), or depending on usage.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Hi, you should have one proxy per backend (with the same ip), otherwise, you would have issues on certain videos, like music videos. You should then load balance the backends instead. Hope this helps!
