### ISSUE TITLE
Add bidi support(RTL)

### ISSUE THREAD

**Issue by alefvanoon** [TeamPiped/Piped#230]

**Comment by FireMasterK** [comment]
Where do you expect support for this?

For the titles, description, etc?

**Comment by alefvanoon** [comment]
For all :)
![image](https://user-images.githubusercontent.com/53198048/123621502-2175e800-d7c0-11eb-8313-98a9099f3268.png)
![image](https://user-images.githubusercontent.com/53198048/123621603-3eaab680-d7c0-11eb-9487-3b9c10e7b7e1.png)
all of them have problem with RTL text...

**Comment by FireMasterK** [comment]
Could you see if https://3eecaf0e.piped.pages.dev/ has anything missed?

**Comment by alefvanoon** [comment]
Nice job! thanks.
working well.
