### ISSUE TITLE
Add Option to share the original youtube-link

### ISSUE THREAD

**Issue by caminsha** [TeamPiped/Piped#232]
First: Thanks for this great web application.

I would be nice to have a link somewhere in the frontend to the original youtube-link. It should not be something fancy or something like that.

I have the following usecase: people are using different addons/extensions/apps which redirect them to their preferred youtube-frontend and they break when another url will be there.

So the solution would be to just add a small text with the original youtube-link which can be copied.

**Comment by FireMasterK** [comment]
Closing this with c599d56db6252ac6f177c69dc35fc8b7d2888189.

You should be able to right-click and copy the URL.

**Comment by caminsha** [comment]
> Closing this with [c599d56](https://github.com/TeamPiped/Piped/commit/c599d56db6252ac6f177c69dc35fc8b7d2888189).
> 
> You should be able to right-click and copy the URL.

That fix was very fast. It works as I expected it to work. Thanks for the work!
