### ISSUE TITLE
_redirects config makes CloudFlare pages builds to cause ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by lbrdt** [TeamPiped/Piped#2325]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

While building the frontend on cloudflare pages, the redirects causes the website to redirect too often and fail. While the `public/_redirects` was added 5 months ago, cloudflare pages would consider it invalid, and ignore it.

![image](https://user-images.githubusercontent.com/87078313/233820122-a384840e-9c90-4840-be66-140d4e550565.png)

But recently, they were suddenly considered valid, and builds from then on cause the redirect problem.

![image](https://user-images.githubusercontent.com/87078313/233820169-b4da01f1-6475-432e-b292-c7ad99fbf8c0.png)

It's caused by this [line](https://github.com/TeamPiped/Piped/blob/aabd0919ab40ffdc9d1fd65cf06ac744306bc029/public/_redirects#L1), removing it solves the problem on Cloudflare.

### To Reproduce

1. fork the repo
2. link or upload the repo to cloudflare pages (Set `NODE_VERSION` environment variable to `20.0` during setup)
3. deploy the project
4. wait for the deployment to complete successfully
5. go to the deployment domain

### Expected behavior

Piped pages should load, however it causes infinite redirect loop

### Logs/Errors

While trying to debug the problem and looking through the deployment logs, I found that this redirect was causing the infinite loop. 

### Additional context

removing the line in the `_redirects` file and deploying again solved the problem

**Comment by FireMasterK** [comment]
It's a Cloudflare bug, not a Piped bug.

**Comment by lbrdt** [comment]
> It's a Cloudflare bug, not a Piped bug.

okay, time to hit up cloudflare support. Just wanted to ask if `cf.piped.video` is affected by this? If so I might need to move
