### ISSUE TITLE
add my instance

### ISSUE THREAD

**Issue by no-logs** [TeamPiped/Piped#2339]
### Describe your question

https://piped.no-logs.com/

**Comment by FireMasterK** [comment]
Hi, what's the backend URL and country of your instance? Your instance seems to be malfunctioning since it seems to default to the `kavin.rocks (Official)` instance.

**Comment by no-logs** [comment]
Hi, yes I used their proxy and api as backend, is it ok?

**Comment by Bnyro** [comment]
No, instances listed in the wiki must have their own proxy and backend.
