### ISSUE TITLE
like and dislike icons doesnt appears

### ISSUE THREAD

**Issue by techgamers2** [TeamPiped/Piped#2350]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

like and dislike icons doesnt appears
![no like icon ](https://user-images.githubusercontent.com/44696073/235412475-f10ab3ad-e651-4a9d-a336-2bbf9058f435.jpg)

### To Reproduce

open any video and play ( use chrome://flags website dark mode)
![flags](https://user-images.githubusercontent.com/44696073/235412508-93829bbb-8d26-4ca1-aca0-300dd47e576c.jpg)

### Expected behavior

like /dislike icon doesnt appear

### Logs/Errors

like and dislike icons doesnt appears

### Browser, and OS with Version.

Microsoft Edge
Version 112.0.1722.64 (Official build) (64-bit)

### Additional context

like /dislike icons appears in redesign efy version but not in official piped.video ( i tried both light / dark theme in preferences got same result :(

**Comment by FireMasterK** [comment]
This isn't really a bug here, but rather a bug in Edge/chromium. I don't think there's much Piped can do. The website is already in dark mode, so you don't need to use fancy flags anyways.

**Comment by techgamers2** [comment]
it is a visual bug here coz redesign efy has no issue also i use tht fancy flag feature browser wide everytime i visit piped i cant disable it ( almost every other site i visited to this date has no issue with tht fancy flag feature ) it is just a simple color inversion tht skips images but for some reason its not skip those like buttons

**Comment by techgamers2** [comment]
its ok if this issue is not fixable .. i will manage ( also thanks for keeping this project alive as a low end gamer normal youtube takes a long time to load ur piped is really fast ) also special thanks for adding indian server (keep it up bro )

**Comment by FireMasterK** [comment]
I disagree since this is an issue with chromium/edge deciding to incorrectly invert a light svg icon, to dark, hence causing the issue in the first place.

However, it looks like it might be fixable by forcibly making the browser disable this feature: https://developer.chrome.com/blog/auto-dark-theme/#detecting-auto-dark-theme

Reopening the issue hence

**Comment by techgamers2** [comment]
![image](https://user-images.githubusercontent.com/44696073/235432007-53ce59c0-0acc-4557-857a-25ae0972624b.png)
thank you it worked <3
