### ISSUE TITLE
[question] would it be possible to include a "watch on youtube" link, on (often) 502 errors cases

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#2358]
### Describe the feature

<img src="https://user-images.githubusercontent.com/415238/235929527-55e27ba1-ca17-447c-afff-8897cb6e3d40.gif" />

- https://github.com/TeamPiped/Piped/issues/2099  

### Why would this be useful to add?

(nope)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by wrhou** [comment]
Why not just enable the 'Show Watch on YouTube button' option in preferences?
