### ISSUE TITLE
Include proxy url in instance list

### ISSUE THREAD

**Issue by ChunkyProgrammer** [TeamPiped/Piped#2375]
### Describe the feature

I think urls for proxying images and videos should be included in the instance list.

### Why would this be useful to add?

It'd be useful for converting a youtube image link to a piped image link

### Additional context

https://github.com/TeamPiped/instances-api may need to be updated to support this new field too

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Can I understand the use case for this? I don't see why someone would want to convert only images to piped proxy links...

Piped instances are also designed in a way that the video proxy will be unique to the node you are connected to. (eg: pipedproxy-ams-2.kavin.rocks, pipedproxy-ams-3.kavin.rocks, pipedproxy-bom.kavin.rocks, etc)

**Comment by ChunkyProgrammer** [comment]
Hi,
I'm starting to add Piped API support to FreeTube (see: https://github.com/FreeTubeApp/FreeTube/pull/3488).
We currently save links to the channel's image in the subscription file to avoid refetching data when showing the channels that a user is subscribed to.
For Invidious, it's pretty easy to convert from a youtube image to an invidious image ([example](https://github.com/FreeTubeApp/FreeTube/blob/c93c1d065da230fdac040952ea73a49f0607d3da/src/renderer/helpers/api/invidious.js#L103 )) when displaying one of the images saved in the subscription file but for piped we'd either need to get the proxy url somehow or take a different approach for changing the image.

Being able to convert video links does not matter for my use case but if my request is too niche, I'm sure I can figure something else out 🙂

**Comment by FireMasterK** [comment]
If you do rewrite channel banner URLs with the proxy, please also rewrite them in a way that YouTube serves webp. This way, Piped's proxy does not need to convert the jpeg image to webp to save some CPU.

Example code to do so: https://github.com/TeamPiped/Piped-Backend/blob/0536236657ca6f9636485f5e20a7a9d5e2bcc1ed/src/main/java/me/kavin/piped/utils/URLUtils.java#L64-L66

For example https://pipedproxy.kavin.rocks/ytc/AGIKgqMP6gHKgB5Vry0KGHKg4PF7gHMKs2XRfQvpXwIXRA=s68-c-k-c0x00ffffff-no-rj?host=yt3.ggpht.com turns into https://pipedproxy.kavin.rocks/ytc/AGIKgqMP6gHKgB5Vry0KGHKg4PF7gHMKs2XRfQvpXwIXRA=s68-c-k-c0x00ffffff-no-rw?host=yt3.ggpht.com
