### ISSUE TITLE
Public Instance List

### ISSUE THREAD

**Issue by KozmikNano** [TeamPiped/Piped#2388]
### Describe your question

Would it be possible to have my instance added to the public list? Here's some info about my instance:

- Main: piped.kozmik.studio
- API: pipedapi.kozmik.studio
- Proxy: pipedproxy.kozmik.studio
- Location: USA
- It's behind Cloudflare

**Comment by Bnyro** [comment]
Kavin already added it to the instance list apparently, thanks for hosting an instance!

**Comment by KozmikNano** [comment]
Sweet! Thank you!Sent from my iPhoneOn May 14, 2023, at 11:37, Bnyro ***@***.***> wrote:﻿
Kavin already added it to the instance list apparently, thanks for hosting an instance!
