### ISSUE TITLE
[Feature request] Share video URL at current timestamp

### ISSUE THREAD

**Issue by tuxayo** [TeamPiped/Piped#2394]
### Describe the feature

Have a share URL button or right click that can include the current timestamp to the link. Timestamped URLs already work with the following syntaxes:

&start=4m2s
&t=3m5s
&t=185s

### Why would this be useful to add?

To share a video directly to the right moment. Or to save the current timestamp of a long video when closing the browser to immediately jump back in.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
![image](https://github.com/TeamPiped/Piped/assets/20838718/8b8dd43d-b9a9-4756-9d8c-0a04a7f9667a)

You already have one...
