### ISSUE TITLE
Add "isShort" to stream api endpoint

### ISSUE THREAD

**Issue by Zocker1999NET** [TeamPiped/Piped#2402]
### Describe the feature

Add a key `isShort` with either true or false as value to the information retrieved about an video on the `/streams` endpoint.

### Why would this be useful to add?

Currently, this parameter only seems to exist when searching for & retrieving streams e.g. by going through channels / playlists / related streams. But if this would be added to the actual stream endpoint, it would be way easier to retrieve this information on a per-stream base and so would be easier to programmatically use that.

### Concept(s)

This may look like that when requesting https://pipedapi.kavin.rocks/streams/dQw4w9WgXcQ :
```json
{
  "title": "Rick Astley - Never Gonna Give You Up (Official Music Video)",
  …
  "isShort": false,
  …
}
```
(many other keys removed)

### Additional context

I've also searched for other parameters, which seem to indicate, if a video is a short, however, I could not find any. An example for both kinds (non-short vs short):

- non-short: https://pipedapi.kavin.rocks/streams/dQw4w9WgXcQ
- short: https://pipedapi.kavin.rocks/streams/IpxUWGG_na8

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This is not really possible due to limitations by YouTube.

**Comment by Zocker1999NET** [comment]
I just found out: According to [Google](https://support.google.com/youtube/answer/12779649?hl=en&co=GENIE.Platform%3DDesktop), any video, which is up to 60 seconds long and has either a square or vertical aspect ratio is considered a short when uploaded. There is neither a flag which creators can set nor is the hashtag `#shorts` required (according to Google it "just" helps their recommendation system).

Now, for historical accuracy, it would be great to know if videos from before the introduction of YouTube Shorts, which still fulfill the requirements for a short, are now considered to be one (otherwise, Piped could check for that as well).

So this may just be implemented in the Piped API checking for this conditions, would you accept such a change?
Because, as I understand it now, YouTube maybe hasn't even a flag in their DB for shorts (and their frontend is just checking for those requirements as well), making this check more than appropriate to implement in another frontend & API.
