### ISSUE TITLE
Add region parameter

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#241]
It would save region for a device for each users.

It can be used for e.g. trending and other pages if useful

**Comment by FireMasterK** [comment]
I found the list of supported regions: 
https://github.com/TeamNewPipe/NewPipeExtractor/blob/6db4bea8ca51ac40a8f831527b274ad50895070e/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/YoutubeService.java#L201-L217

However, the challenge seems to be getting the country's name.

**Comment by FireMasterK** [comment]
Closing with b5a0ca8324d88e9f40d72607ecda2723c1efa363.
