### ISSUE TITLE
New public instance on South America

### ISSUE THREAD

**Issue by redr00t** [TeamPiped/Piped#2416]
### Describe your question

Hello, how are you? It seems that there are no instances in South America, so I created a new public one for everyone!! It would be great if you could add it to the official list. Below, I will leave the instance details written.

Name: Vyper
URL: https://vyper.me
API: https://yapi.vyper.me
Location: Chile (CL)
CDN: Yes, Cloudflare.
Registration Allowed: True

**Comment by Bnyro** [comment]
Added, thank you for hosting an instance!
