### ISSUE TITLE
Piped Docker is broken

### ISSUE THREAD

**Issue by manuelkamp** [TeamPiped/Piped#2428]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Yesterday it worked fine, today it did not load any video in the subscibed videos page. Just the loading circle. On all devices (LG Smart TV, iPad, iPhone, PC, Laptop, Android Smartphone). I tried to update the Docker container already. Same effect. Logged out, not able to log back in (with correct credentials). Also it is not possible to register a new account. It just seems to be broken?

### To Reproduce

open piped and try login

### Expected behavior

login works
registering new account works
seeing list of subscribed videos

### Logs/Errors

I do not know how to get logs from docker (I usually only do LXC)

**Comment by gladiatormax** [comment]
I second this, having the same problem.

**Comment by FireMasterK** [comment]
Can you look for your browser's logs?

**Comment by nooz** [comment]
same issue here, all subs gone and clicking import does nothing, although playlists are still there and general playback is working okay

**Comment by FireMasterK** [comment]
> same issue here, all subs gone and clicking import does nothing, although playlists are still there and general playback is working okay

Sounds like a database issue, can you check your backend and postgres logs?

**Comment by FireMasterK** [comment]
Closing this for now, let me know if there are any more persistent issues!
