### ISSUE TITLE
Show Format File Size in the API

### ISSUE THREAD

**Issue by deniscerri** [TeamPiped/Piped#2429]
### Describe the feature

The streams api endpoing is near perfect. It only misses the file size of the audio/video stream.

### Why would this be useful to add?

My app [YTDLnis](https://github.com/deniscerri/ytdlnis) is planning to use piped as an api for my youtube queries. It is a downloader app so its essential for the user to know how much space a certain format will take.

### Concept(s)

![image](https://github.com/TeamPiped/Piped/assets/64997243/37b5cb76-0d22-45af-9c3b-91181ad4611c)
![image](https://github.com/TeamPiped/Piped/assets/64997243/fd868077-e2e3-4ab4-ba12-453ee46c6971)

### Additional context

Currently im using invidious for my api queries but yours gives way more details. Its just this filesize missing. Please take this request into consideration

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not possible without change sin the NewPipe Extractor.

**Comment by deniscerri** [comment]
![image](https://github.com/TeamPiped/Piped/assets/64997243/ea221247-7630-4981-b329-beb4448321d3)
Newpipe shows filesizes? Are they using a different component?

**Comment by Bnyro** [comment]
I think they either calculate it based on the file format or make a HEAD request to the file's URL to get the `Content-Length` header.

**Comment by Bnyro** [comment]
See https://github.com/libre-tube/LibreTube/issues/3278 for a discussion about it

**Comment by Qaz-7** [comment]
https://github.com/TeamNewPipe/NewPipeExtractor/issues/1064#issuecomment-1555994228
