### ISSUE TITLE
Remove instance of "Esmail EL BoB"

### ISSUE THREAD

**Issue by MagicLike** [TeamPiped/Piped#2435]
### Describe your question

Esmail is actively forbidding members or supporters of the LGBTQIA+ community to use their services via a TOS document*.
This is absolutely queerphobic and extremely discriminating. Therefore I ask to remove their instance `piped.esmailelbob.xyz` / `esmailelbob.xyz` / `pipedapi.esmailelbob.xyz` from the list & upptime, to not further support their actions.

*See the commit here: https://github.com/EsmailELBoBDev2/upptime/commit/c46b9bfd03b211dff2b87737da2de33629685a5a

**Comment by Bnyro** [comment]
Thank you for informing us about that unacceptable behavior, the instance has been removed from the instances list!

**Comment by MagicLike** [comment]
> Thank you for informing us about that unacceptable behavior, the instance has been removed from the instances list!

Thank you fro the quick reply! :heart:

**Comment by ahmed12345678910111213141516** [comment]
proud to be queerphobic 
you trashy people aren't any different from Facebook or Twitter, forcing people to think like your shity ass mindset
there are billions of people who don't even want to discuss the grossnes of LGBBQ
are you going to ban us all?? 
were we wrong to simply ask for our platform to be clean from that shit?
where is the freedom and decentralized
that you always spoke about?
