### ISSUE TITLE
Resume playing where you left off

### ISSUE THREAD

**Issue by raisedintheusa** [TeamPiped/Piped#2448]
### Describe the feature

It would be nice if the "Skip to the last watched point" feature in Piped-Material was available in classic Piped as well.

### Why would this be useful to add?

To easily pick up where you left off in the event of some interruption such as the browser crashing, the tab being closed or discarded.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
We already have this feature. You'll just have to enable the "Watch History" option in the preferences.
