### ISSUE TITLE
Resolution chosen in settings not applying

### ISSUE THREAD

**Issue by t3dium** [TeamPiped/Piped#2453]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

The default video resolution chosen in settings isn’t being applied to watched videos, they all default to “auto” as the quality.

### To Reproduce

1. Set a resolution in settings (tried multiple)
2. Watch a video and see if the quality respects the chosen default from settings 

### Expected behavior

For the default video resolution chosen in settings to be applied to videos.

### Logs/Errors

not applicable 

### Browser, and OS with Version.

Reproduced this bug this across platforms, fedora 38/win11 firefox latest version, ipados 16.4.1 safari

**Comment by FireMasterK** [comment]
It's applying correctly, but the player still shows auto. This is a know issue in shaka-player (the player we use).
