### ISSUE TITLE
Add auto theme

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#246]
It automatically switches between light and dark based on browser's device

**Comment by FireMasterK** [comment]
https://github.com/darkreader/darkreader/issues/5586#issuecomment-822052073

This would mean that we won't qualify to be in dark reader's global dark list.

**Comment by B0pol** [comment]
No.

1. This would mean we can't put auto theme as default if we want to be in dark reader's global dark list. If you don't put it default it's fine.
2. Why would all users be negatively impacted by a third-party addon? You should just disable dark reader on this site, like you probably do for lots of other websites.

**Comment by FireMasterK** [comment]
> If you don't put it default it's fine.

Reopening under this note.

> You should just disable dark reader on this site, like you probably do for lots of other websites.

I hate doing that, and luckily that happens rarely usually.

**Comment by FireMasterK** [comment]
Closing this with 9b79a9c8489958a92e8b70f2b8f63343160b1be6.

**Comment by B0pol** [comment]
Hmm it's not really great. 

It requires a refresh to apply changes (and therefore for **every** open tabs).
Should I open a new issue for that?

**Comment by FireMasterK** [comment]
Sure!
