### ISSUE TITLE
Automatically change theme without page reload

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#247]
Currently the auto theme requires page reload. 

It becomes really annoying when you open multiple tabs and have to reload all of them

**Comment by FireMasterK** [comment]
I had an attempt at this.

To summarize this, VueJS makes this almost impossible in the way `computed` properties are cached when using `localStorage`.

I really don't think this is a huge issue considering that clicking on any item would cause a re-render, thus changing the theme without a reload.

The other option I could attempt is reloading all other open tabs.

**Comment by B0pol** [comment]
Listen on prefers-color-scheme media query?

Otherwise generally it's done with a media query in CSS and the browser automatically handles it.

**Comment by FireMasterK** [comment]
> generally it's done with a media query in CSS and the browser automatically handles it.

This seems like a possible solution, 3 different classes could be made and the class can be assigned based on the theme selected.

**Comment by fasduswisdom** [comment]
i mean you do have .dark and .light

**Comment by FireMasterK** [comment]
This is complete (from a while ago). The auto theme no longer requires a reload as it uses a media query.
