### ISSUE TITLE
Request to add instance: piped.astartes.nl

### ISSUE THREAD

**Issue by zaggynl** [TeamPiped/Piped#2492]
### Describe your question

URL URL: https://piped.astartes.nl
API URL: https://pipedapi.astartes.nl
Proxy URL: https://pipedproxy.astartes.nl
Location: The Netherlands (NL)
Registration Allowed: No

**Comment by Bnyro** [comment]
Do you use a CDN?

**Comment by FireMasterK** [comment]
No, they don't!

**Comment by zaggynl** [comment]
No CDN at this time.

**Comment by FireMasterK** [comment]
Your instance has been added, thank you for hosting an instance again!
