### ISSUE TITLE
Could you please add support for YunoHost ?

### ISSUE THREAD

**Issue by iwannet** [TeamPiped/Piped#2497]
### Describe the feature

Could you please add support for [yunohost](https://yunohost.org/)  Someone already requested it but i think it will not be done cuz there are over 100 apps in the request list. [Applist](https://yunohost.org/en/packaging_apps)
[request list](https://yunohost.org/en/apps_wishlist)

### Why would this be useful to add?

This would make it more easier to deploy your own piped instance making the big instances less laggy and faster.

### Additional context

[Tutorial i think ?](https://yunohost.org/en/packaging_apps)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by iwannet** [comment]
This feature would be really nice cuz the servers are so laggy right now and i always need to switch instances.

**Comment by FireMasterK** [comment]
Hi, is there any blocker in Piped that prevents it from being packaged for YunoHost? If not, the issue should be opened in their issue tracker instead.

**Comment by iwannet** [comment]
I dont think there are any blockers that prevent piped being packaged for yunohost. Someone already requested it on the request list from yunohost itself, but the list is so big that piped will never be done so maybe someone off you could do it or maybe i could try to learn it.

**Comment by iwannet** [comment]
And the maker also needs to keep it up to date, im willing to do it. But i dont know how, and i dont know many programming languages.

**Comment by FireMasterK** [comment]
I see, I will close this issue then.

If you're just an end user, you might be interested in #2503 instead/too, which I just opened. It would help anyone operate their own small instance for free.
