### ISSUE TITLE
Seekbar improvements - time and focus

### ISSUE THREAD

**Issue by raisedintheusa** [TeamPiped/Piped#2498]
### Describe the feature

Suggestion to add a time marker along with the preview when hovering over the seekbar, instead of having to click and drag to find the desired time in the video. Also, the seekbar preview currently covers up the time when hovering near the beginning of the video, again making it difficult to find a specific time.

Also, when clicking on the seekbar, pressing the spacebar to play also scrolls the page down and other shortcuts like JKL do not work since the focus has been shifted away from the video player. Seems the focus should remain on the video player when clicking the seekbar.

### Why would this be useful to add?

More quickly and easily skip to the desired time in the video.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by yonikek** [comment]
Seems the feature has been added but it's bugged on light mode.
![Screenshot from 2023-07-14 00-31-08](https://github.com/TeamPiped/Piped/assets/92832837/2d55efe2-eaa1-4653-8110-9cc7db191740)
