### ISSUE TITLE
How to manage users in self hosted instance

### ISSUE THREAD

**Issue by luckkmaxx** [TeamPiped/Piped#2506]
### Describe your question

My self-hosted instance runs in docker.
I want to be able to manage my instance users (Family, friends)
Is there a way to easily manage database?
I mean any UI to manage the users database, avoiding to edit it directly in command line.

**Comment by FireMasterK** [comment]
Hi, currently we don't have any UI to manage users, nor is there something planned currently.

**Comment by luckkmaxx** [comment]
Ok thanks, I will take a look at [pgadmin](https://hub.docker.com/r/dpage/pgadmin4/) and see if its a good alternative to manage users.
Maybe I will need to know wich tables stores accounting data. Later.
