### ISSUE TITLE
Piped-backend docker image creates endless amounts of http://libreqwest_*.so files in docker images /tmp folder

### ISSUE THREAD

**Issue by cronyakatsuki** [TeamPiped/Piped#2509]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.video/) or is API related.

### Describe the bug

Recently after updating my piped docker instance I experience issues with my vps and have seen that a docker container started using up almost all my storage on system.

After running this script
```bash
for container in $(docker ps --all --quiet --format '{{ .Names }}'); do                                              main
    echo "$(docker inspect $container --format '{{.GraphDriver.Data.MergedDir }}' | \
      grep -Po '^.+?(?=/merged)'  ) = $container"
done
```
I have diagnosed that the Piped-backend image was creating this files endlessly till it fills up storage completely.

### To Reproduce

I don't know what the steps to this happening are

### Expected behavior

Piped backend not creating this files.

### Logs/Errors

If there is a need for specific logs tell me, I have for now disabled the service and will wait for further instructions.

### Additional context

The vps is a debian 11 hosted on vultr if that helps.

**Comment by cronyakatsuki** [comment]
Wrong repo, sorry!

**Comment by FireMasterK** [comment]
> If there is a need for specific logs tell me, I have for now disabled the service and will wait for further instructions.

That would've helped you find the root cause of the issue, the backend is likely starting and crashing rapidly, hence causing unnecessary temp files, since they are created on startup.

Anyways, I'm pushing an update to fix this - https://github.com/TeamPiped/reqwest4j/commit/1c58bc2dba7425ac24a38662ce58aa7e949494d2.
