### ISSUE TITLE
Rate limit column & uptime column on instances list

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#2520]
### Describe the feature

Please add two columns on the piped instances list

- rate limit
- uptime

### Why would this be useful to add?

For users to know if a instance is rate limited or not and to know the uptime of an instance.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by trymeouteh** [comment]
I guess a solution for uptime would be to add a link at the bottom of the piped instance to https://status.piped.video/

**Comment by Bnyro** [comment]
Uptime is implemented, ratelimited instances no longer show up in the instances list.
