### ISSUE TITLE
Disabling search suggestions

### ISSUE THREAD

**Issue by codenyte** [TeamPiped/Piped#2533]
### Describe the feature

Option in the settings to disable search box input being sent to the server as the search query is still being typed out, only query the server when the user hits Enter.

### Why would this be useful to add?

Search suggestions essentially turn a search box into a keylogger. Everything the user types in is immediately sent to the Piped API and then to Google. Some users (including me) are not happy with this behavior, so I think there should be an option in the settings to disable it. I believe that a search query should only be submitted when the user explicitly intends to execute the search function by pressing 'Enter'. Also, I believe it should be opt-in (so turned off by default) to save bandwidth and prevent Piped Backend Servers from being rate limited.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
We should keep the option enabled by default for now in my opinion, to not confuse any users.
