### ISSUE TITLE
Can't add custom instance 

### ISSUE THREAD

**Issue by sakgoyal** [TeamPiped/Piped#2535]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I can't add my custom piped instance to the app. When I enter the details, it says "please use a URL that works". I followed the steps that piped gave using docker and caddy. 

I am able to access it through a browser so I'm not sure what I'm doing wrong

### To Reproduce

Verify "piped.[redacted].dev" is working
Add that URL for the frontend
Add "pipedapi.[redacted].dev" for the API URL
Click add instance
Error happens here. Instance is not added

### Expected behavior

The instance should be added

### Browser, and OS with Version.

Android

**Comment by FireMasterK** [comment]
I think you wanted to open this issue in the LibreTube repository instead? I don't think this is a Piped bug.

**Comment by Bnyro** [comment]
You need to add `https://` before the URL.

**Comment by sakgoyal** [comment]
You're right. this was in the wrong place. But adding the `https` fixed it. Thank you @Bnyro
