### ISSUE TITLE
Resolution of the live stream (using the API)

### ISSUE THREAD

**Issue by hhkrob1** [TeamPiped/Piped#2557]
### Describe your question

Hi, guys.

**Details:**
I read the [API documentation for piped](https://piped-docs.kavin.rocks/docs/), get information of the video use by Endpoints(/streams/:videoId). 

1. not livestream:
Response have videoStreams of array, so I can get different resolutions of the video url.

2. is livestream:
videoStreams of array in Response is empty, but I find the key hls can get livestream url, but I play in MPV(or other player), the resolutions always 360p, wait a minute, last change to 1080p.
3. the API documentation for piped mentions use URL Parameters(quality=1080) can specify a resolution, but it may only be used for browser web addresses.

4. access piped video website from browser, the live stream can select multiple resolutions, so the livestream can play in multiple resolutions.

**Question:**
Is there a way to get the livestream url of other resolutions? 

Thank you so much!

**Comment by Bnyro** [comment]
For live streams, you either need to use the `dash` field or the `hls` field returned by the API. Both of them provide different resolutions and audio qualities, you can imagine the DASH or HLS manifest being like a list of URLs to different video and audio sources with different qualities for the stream.
So what you would need to do is to download the file from the link on the `hls` or `dash` field and extract the URLs from it manually. Some players like MPV should support playing `hls` or `dash` streams directly though and allow to change the quality in their player.
URL parameters don't have any impact here.

**Comment by hhkrob1** [comment]
> For live streams, you either need to use the `dash` field or the `hls` field returned by the API. Both of them provide different resolutions and audio qualities, you can imagine the DASH or HLS manifest being like a list of URLs to different video and audio sources with different qualities for the stream. So what you would need to do is to download the file from the link on the `hls` or `dash` field and extract the URLs from it manually. Some players like MPV should support playing `hls` or `dash` streams directly though and allow to change the quality in their player. URL parameters don't have any impact here.

Thank you so much! I get it. 'hls' include all video tracks information, it's better player support select video tracks, like MPV,  key shortcut ('_') can do it.
