### ISSUE TITLE
Listen mode/Only audio not working on streaming

### ISSUE THREAD

**Issue by MariojGG** [TeamPiped/Piped#2569]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Only audio mode does not work in live videos, video keeps playing.

### To Reproduce

1- Open any streaming in any browser ([https://piped.video/watch?v=jfKfPfyJRdk](url))
2- Go listen mode
3- Video keeps playing

### Expected behavior

Static image and only audio

### Browser, and OS with Version.

Brave 1.52.126 on Windows 11, but same problem in any browser

**Comment by FireMasterK** [comment]
This is because YouTube serves them together. We can't unfortunately get only the audio I'm afraid.
