### ISSUE TITLE
Issues with some videos

### ISSUE THREAD

**Issue by DanielProg39** [TeamPiped/Piped#2585]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Some videos are not playing or load for a very long time. Sometimes an error 403 occurs if I start watching not from the beginning. One day I have this issue with one video, next day the video loads and plays fine but some other video has this issue. This only happen in piped.video and piped.kavin.rocks websites, other instances work as intended.

### To Reproduce

1. Open a video (f. ex. [this](https://piped.video/watch?v=9Ov93YjTZ70))
2. Wait...

### Expected behavior

Video to quickly load and play

### Logs/Errors

![2023-06-22 18 00 54 piped video b1486d2ba7c7](https://github.com/TeamPiped/Piped/assets/63293432/511ea412-00fd-4dee-97e0-7108037c3a0e)
![2023-06-23 14 47 18 piped video](https://github.com/TeamPiped/Piped/assets/63293432/fb5871c2-49fb-4947-8dc6-6174b190403a)
![2023-06-23 14 56 21 piped video 26974c5e258a](https://github.com/TeamPiped/Piped/assets/63293432/ed29a429-8ecd-4e69-bd53-fa1ba43abc06)
![2023-06-23 14 58 06 piped video 26865eb9cf59](https://github.com/TeamPiped/Piped/assets/63293432/7a01ccd0-ca0a-4ff5-a930-0a92504d9f65)

### Browser, and OS with Version.

Firefox 114, Chromium 114, both on Ubuntu 18.04 and on Fedora 38

**Comment by DanielProg39** [comment]
Everything seems to work properly, but I'll leave this open for some time until I make sure there are no such incidents anymore

**Comment by AlyoshaVasilieva** [comment]
I'm also experiencing this, both on the official instance and my private instance. Most recently https://piped.video/watch?v=qquDUeGWloE (loud), it seems to load video segments at ~50KB/s. The same occurs on the Piped instance on my VPS, but that VPS can download the entire video using yt-dlp in about 1 second (reports 40MB/s).

![streamspeed](https://github.com/TeamPiped/Piped/assets/1284317/ef610703-9820-4fb0-b61e-aa22a26b9120)

Some videos load fine with expected speeds.

**Comment by techgamers2** [comment]
Initial player response is not valid issue

**Comment by DanielProg39** [comment]
Everything was fine for couple days, but it happened again
![image](https://github.com/TeamPiped/Piped/assets/63293432/e0ffd7b4-37c4-4775-b761-4d31128764d7)

**Comment by AlyoshaVasilieva** [comment]
Very slow videos was fixed for my private instance by https://github.com/TeamPiped/Piped-Backend/pull/639

**Comment by FireMasterK** [comment]
Let me know if you still can reproduce this issue.

**Comment by DanielProg39** [comment]
Ok, so far so good
