### ISSUE TITLE
ConnectionRefused in piped server on opening video

### ISSUE THREAD

**Issue by data-niklas** [TeamPiped/Piped#2599]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Call to `api.lbry.com` fails, e.g.: `https://api.lbry.com/yt/resolve?video_ids=Kb_EOVLFDUE` fails in I assume https://github.com/TeamPiped/reqwest4j/blob/3ff902794acaeb430e47291d14131bf51b20cda7/reqwest-jni/src/lib.rs#L64.

I assume this occurs due to this code here: https://github.com/TeamPiped/Piped-Backend/blob/d4d0a4092862667f50116988651ab4b6ae4b2558/src/main/java/me/kavin/piped/utils/LbryHelper.java#L21

I am also unable to access `https://api.lbry.com/yt/resolve` on all my machines. 

### To Reproduce

1. Go to the piped frontpage
2. Click on any video
3. Watch the server logs

### Expected behavior

The video page loads and plays

### Logs/Errors

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.lbry.com")), port: None, path: "/yt/resolve", query: Some("video_ids=Kb_EOVLFDUE"), fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }', src/lib.rs:64:30
```

### Browser, and OS with Version.

Newest Firefox on NixOS

### Additional context

It stopped working for no apparent reason. I do not auto-update the piped services using watchtower and the services worked on the same version of Piped before. Might be an issue with api.lbry.com

**Comment by FireMasterK** [comment]
> I do not auto-update the piped services using watchtower and the services worked on the same version of Piped before.

Definitely the problem here, update your instance!

**Comment by FireMasterK** [comment]
> The instance works again without updating any docker image. At the same time I am able to access `api.lbry.com` again. It seems that the requests sent to the API failed. 
> 
> Is there any plan to gracefully handle errors to these API's?

Complaining about bugs that have been fixed many months ago, not updating your instance, and then reporting an already fixed issue isn't really fair. We include watchtower, so that you don't face as few issues as possible and have very minimal maintainance to do.

Please ensure you're running the latest version of everything before you open an issue again.
