### ISSUE TITLE
Video Shader/Overlay Effects

### ISSUE THREAD

**Issue by SecularSteve** [TeamPiped/Piped#2601]
### Describe the feature

The option to put a filter shader and/or and overlay over the video you're watching for fun.

For example, an "enhanced colour" shader, a "black and white" shader, a "VHS" shader, maybe even a "3D glasses" shader.

### Why would this be useful to add?

It would be a unique gimmick that sets this Client apart from the others.

May or may not bring more people in.

### Concept(s)

https://github.com/shader-slang/slang

https://en.wikipedia.org/wiki/Shading_language

### Additional context

It's not mandatory. Just a suggestion.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
This isn't a goal of this project, however, I'm open to contributions to implementing such a thing!
