### ISSUE TITLE
initial player response invalid

### ISSUE THREAD

**Issue by itsmmt305** [TeamPiped/Piped#2605]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

upon tapping on any video title, the video doesnt play and a text appears stating "initial player response invalid"

### To Reproduce

go to piped.kavin.rocks
pick a video
click on it

### Expected behavior

it shall play

### Logs/Errors

![Screenshot_2023-06-28-11-26-49-016_com brave browser](https://github.com/TeamPiped/Piped/assets/94820934/d98003fa-958f-48b2-9d9e-e08af78e99b9)

### Browser, and OS with Version.

Brave 1.52.126 android

### Additional context

i use a dns

**Comment by p0mad** [comment]
same here on usual internet! ( without changing anything on network side!)

**Comment by Cade66** [comment]
I use three Piped instances of which 1 -- at this very time -- encounters the "initial player response not valid" issue:
https://piped.hostux.net/ : ISSUE
https://piped.adminforge.de/ : FLAWLESS
https://piped.syncpundit.io/ : FLAWLESS

**Comment by Mhowser** [comment]
same issue here on latest desktop brave browser with Linux:
![image](https://github.com/TeamPiped/Piped/assets/24195572/caceca27-8a98-4d21-a3f8-9e44f6f25661)

**Comment by goodness-from-me** [comment]
https://piped.palveluntarjoaja.eu is also affected.

**Comment by PianXie** [comment]
I use piped.yt which is also affected. There is also an Invidious running on this server, which also stopped working at the same time.

Piped: https://piped.yt/watch?v=u0mpJoCl_k4
Invidious: https://proxied.yt/watch?v=u0mpJoCl_k4

Since Invidious doesn't work either, I suspect that Youtube is blocking the IP addresses. Maybe the admins of the instances can find clues in the logs.

**Comment by DanielProg39** [comment]
Maybe it can be related to #2585

**Comment by DanielProg39** [comment]
> Maybe it can be related to #2585

I mean this
![image](https://github.com/TeamPiped/Piped/assets/63293432/ed8168d3-5d87-4a7a-8347-b8a036c06e23)

**Comment by PianXie** [comment]
> My instance works, at video.howdytx.technology. Is it really YT rate-limiting us? Don't they have better things to do?

The trend of what Youtube is up to is clear: https://blog.thefrenchghosty.me/posts/im-not-invidious/

**Comment by Cade66** [comment]
> Yeah, it's like every day with piped

Not here. Among the three I mentioned above (piped.hostux.net, piped.adminforge.de, piped.syncpundit.io) issues are extremely seldom and and as far as I remember never occur on all three instances at the same time, hence all that is required is to switch from one to another.

No idea if the present issue is related to this but within those instances the one that fails (piped.hostux.net) is shown in Piped Preferences as NOT Up to Date whilst piped.adminforge.de IS. As for piped.syncpundit.io it never appears in the Instances List and uses a Custom Instance I have no info about and keep only as a Rescue instance should others fail.

To make it short : there are quite many Piped instances available and i'm wondering if the fact some occasionally fail is worth a post.

**Comment by AlyoshaVasilieva** [comment]
>  Newpipe, Songtube and skytube have 0 of these issues and afaik they all work in a similar way.

These all work locally and likely with a residential IP address, whereas Piped instances generally have multiple users and are hosted in a datacenter (rate-limits are typically stricter for datacenter IPs than residential)

**Comment by Cade66** [comment]
Newpipe, Songtube and skytube are all for Android.
PCs still alive, and Piped does the job nicely.

**Comment by techgamers2** [comment]
> Newpipe, Songtube and skytube are all for Android. PCs still alive, and Piped does the job nicely.

do u know how many times i hav to click on "watch on youtube button" when trying to use piped as daily driver ... its just frustrating so many error sometimes its instances issue sometimes its piped issue

**Comment by techgamers2** [comment]
> Yeah, it's like every day with piped, I get that Youtube isn't intended to be used with a 3rd party api like this but Newpipe, Songtube and skytube have 0 of these issues and afaik they all work in a similar way.

 agreed piped and libretube both having too many problems very frequently ...

**Comment by parallelqw** [comment]
Can reproduce on my instance (piped.pfcd.me).
I *mainly* think it is because of rate limits, #2487 referenced to my instance as working and ever since its been a great increase on the bandwidth. We probably got rate limited.
The problem is I can't set a floating IP specifically for Piped and change once a month, since it is really expensive for us.
Also changing main IP once/twice a month will cost us a lot of maintenance. That's where I got stuck for now.

**Comment by Bnyro** [comment]
We continue tracking this at #2487
