### ISSUE TITLE
How to transfer my piped subscriptions back to youtube account ?

### ISSUE THREAD

**Issue by techgamers2** [TeamPiped/Piped#2607]
### Describe your question

i hav been using piped for long time facing lot of issue now i hav accumalated subscriptions in piped account but i want to go back to youtube is there an easy way to transfer my piped subscription .json file to youtube account ?

**Comment by Telkhine** [comment]
I don't know about YouTube itself, but you can import your `subscription.json` file to something like FreeTube. That's what I do when piped is having issues.

**Comment by amogusussy** [comment]
You probably can't. Google's takeout feature is just a way to comply with various data protection agencies, and they'll probably never support something like this.

The issues are probably instance-specific. Try changing instance. I used to use piped.kavin.rocks, but it had some playback issues every few weeks, so I moved to piped.projectsegfau.lt. You could try that first if you prefer piped over youtube. If you still prefer youtube, follow the steps below.

Here's a script I've just made to open all the channel links that you aren't subbed to on youtube in firefox. (please ignore the messy code).

```
import json
from subprocess import Popen

with open("./subscriptions.json", "r") as f:
    ps = f.read()
piped_subs = json.loads(ps)

with open("./subscriptions.csv", "r") as f:
    ys = f.read()

yt_urls = []
for i in ys.split("\n"):
    x = i.split(",")
    try:
        yt_urls.append(x[1].split("/")[-1])
    except:
        continue

piped_urls = []
for i in piped_subs["subscriptions"]:
    piped_urls.append(i["url"].split("/")[-1])

for i in piped_urls:
    if i not in yt_urls:
        Popen(["firefox", f"https://www.youtube.com/channel/{i}"])
```

The `subscriptions.json` file is the exported piped subscriptions.

The `subscriptions.csv` is the exported youtube subscriptions (from google Takeout). 

Move the takeouts .csv, and piped subscriptions.json file to the same directory as this script.

Also, if you're not using firefox, replace it with whatever browser you do you. If you're on window, you might have to add ".exe" to the end of it.

**Comment by techgamers2** [comment]
i already use piped.projectsegfau.lt all video failed to load ... thanks for the script i will give it a try

**Comment by techgamers2** [comment]
> ov

i know i cant directly inject my piped subscription to google account i m asking is there an extension or script tht supports a way to make piped subscription .json file to automatically open all channel one by one and sub in youtube account

**Comment by techgamers2** [comment]
> You probably can't. Google's takeout feature is just a way to comply with various data protection agencies, and they'll probably never support something like this.

i know i cant directly inject my piped subscription to google account i m asking is there an extension or script tht supports a way to make piped subscription .json file to automatically open all channel one by one and sub in youtube account

**Comment by amogusussy** [comment]
It might be an issue with your browser then. Maybe try opening the same instances in a different browser to test. You could also make a new profile in your browser (on firefox it's at about:profiles), and test it on that.

Also, you open dev tools (press F12), go to the network tab, and see if there's any specific error messages that come up. If there are, you should make a new issue with that info.

**Comment by techgamers2** [comment]
nah bro i already switched back to youtube its not about one issue i faced lot of issue this past year (some were piped related some where instances related )  .... coz youtube is something we use everyday ( its like search engine) and when info is not available due to unexpected error it just aint worth this much work for privacy
with [enhancer for youtube](https://www.mrfdev.com/enhancer-for-youtube) extension and [gressyfork javascript](https://greasyfork.org/en/scripts/by-site/youtube.com?sort=total_installs) i can make youtube look like piped and for privacy i create a dummy google account with max [uBo](https://github.com/gorhill/uBlock) settings with [custom filters](https://filterlists.com/) coz i need 100% uptime instead of minor frequent hiccups

**Comment by techgamers2** [comment]
> I don't know about YouTube itself, but you can import your `subscription.json` file to something like FreeTube. That's what I do when piped is having issues.

thanks i imported my piped subscription to freetube and then i exported them as .csv file and then i imported my subscription back to youtube using [importer](https://www.limbuscode.com/subs-imp-yt) extension
