### ISSUE TITLE
Th search takes forever

### ISSUE THREAD

**Issue by stemy2** [TeamPiped/Piped#2612]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I tried to search for a video, but the screen is stuck on a spinning icon no matter how long i wait.

### To Reproduce

1. Go to the official instance.
2.  Search for something.

### Expected behavior

The results.

### Browser, and OS with Version.

Firefox 114.0.2
Mint 21.1

**Comment by FireMasterK** [comment]
This should be fixed now on the official instance.
