### ISSUE TITLE
Entire Project is Broken Right Now!

### ISSUE THREAD

**Issue by SaucyOfficiale** [TeamPiped/Piped#2614]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I get this error every time I click on a video or search : https://ibb.co/vBR6Hvk

Please fix! I can't use Piped at all right now.

Also doesn't work on Safari at all. Something must've broken today.

### To Reproduce

1. Search/click on video at Piped

### Expected behavior

The video will load.

### Browser, and OS with Version.

Chrome Version 114.0

**Comment by FireMasterK** [comment]
Duplicate of #2487
