### ISSUE TITLE
Raspberry Pi 4: no matching manifest for linux/arm/v8

### ISSUE THREAD

**Issue by firejoust** [TeamPiped/Piped#2619]
### Describe your question

> $ sudo docker-compose up -d
```
Creating network "piped-docker_default" with the default driver
Creating volume "piped-docker_caddy_data" with default driver
Creating volume "piped-docker_piped-proxy" with default driver
Pulling piped-proxy (1337kavin/piped-proxy:latest)...
latest: Pulling from 1337kavin/piped-proxy
ERROR: no matching manifest for linux/arm/v8 in the manifest list entries
```

I'm new to using docker and I would like to self host Piped on my Raspberry pi 4. Using `docker manifest inspect` I discovered there are manifest entries for arm64. How do I proceed?

**Comment by FireMasterK** [comment]
If you're using Raspberry Pi OS, are you using the 64-bit version? It looks like you might be running on the 32bit version

**Comment by firejoust** [comment]
`uname -m` returns aarch64 so I'm pretty sure it's the 64 bit version

**Comment by firejoust** [comment]
> $ sudo docker manifest inspect 1337kavin/piped-proxy
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:fdfefdec52d8ea14017f22981f27e87494f5c3877f168f57df63e7955378cb5b",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1157,
         "digest": "sha256:612b59a72918062403588f3c82d6d258b976af3e756abe3cbcd7298e0d3adcb5",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```

**Comment by firejoust** [comment]
Any updates? This is the only thing stopping me from self hosting

**Comment by FireMasterK** [comment]
> ERROR: no matching manifest for linux/arm/v8 in the manifest list entries

I'm not  really sure why it's not `linux/arm64/v8` instead, which is the arm64 version of docker?

**Comment by Bnyro** [comment]
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.

**Comment by tareefdev** [comment]
> `uname -m` returns aarch64 so I'm pretty sure it's the 64 bit version

This is not enough, I had to check the output of `getconf LONG_BIT` to know that I am really having 32bit on userland.
