### ISSUE TITLE
No shorts on channel page

### ISSUE THREAD

**Issue by shrugal** [TeamPiped/Piped#2624]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The shorts tab on the channel page doesn't show any shorts anymore. They do show up on the YouTube page, as well as on the Piped feed.

### To Reproduce

1. Open any channel page
2. Switch to shorts tab
3. Nothing is shown

Example: https://piped.video/channel/UCsBjURrPoezykLs9EqgamOA?tab=shorts

### Expected behavior

It should show the list of shorts.

### Logs/Errors

The API request for the shorts just returns `{"nextpage":null,"content":[]}`

### Browser, and OS with Version.

Tested in Chrome (114.0.5735.199) and Firefox (114.0.2) on Windows 11.

**Comment by IkelAtomig** [comment]
Reproducible. I can't see too.

**Comment by Bnyro** [comment]
Seems like breaking changes by YouTube which need to be fixed at the NewPipe extractor.

**Comment by FireMasterK** [comment]
This has now been fixed.
