### ISSUE TITLE
What are the system requirements for self hosting?

### ISSUE THREAD

**Issue by doingstuffs** [TeamPiped/Piped#2637]
### Describe your question

Hey, I want to host a Piped instance on a VPS and was wondering what the estimated system requirements are?
Does Piped use a lot of RAM, CPU or storage? Or will I be fine using a 512gb RAM, 1 vCore, 15gb storage VPS?
I intend to make it a private instance, so it will only have one active user.

**Comment by DarkCat09** [comment]
On my VPS, Piped takes about 1-1.5 GB of RAM, 2 vCPU is enough.

But it's Alpine Linux with [Piped-Alpine](https://github.com/DarkCat09/Piped-Alpine).  
If you're going to self-host using Docker, remember about Docker's overhead, so you will need about 4 GB RAM for server where only Piped is hosted.

**Comment by Bnyro** [comment]
If only being used by few users, your system requirements should be sufficient. However, if you want to host a public instance, there could possibly be some major performance issues with that hardware.
