### ISSUE TITLE
Can't middle mouse click on logo to open in a new tab.

### ISSUE THREAD

**Issue by amogusussy** [TeamPiped/Piped#2644]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

A few days ago, I made this (#2623) issue saying that saying that clicking the logo button should take you directly to the preferred homepage.
@Bnyro fixed this issue with #2629, but it introduced a new bug, where you can't open in a new tab, since it's using JavaScript events, rather than anchor tags like it did before.

The best way I can think of fixing this bug is to just set the `href` value of the logo to whatever the preferred homepage is, which keeps the ability to open in a new tab, which still fixing the bug described in @2623.

### To Reproduce

1. Go to any piped instance that's using a version of piped after the `b18e964dc5848c13ab6a332848f1fb42c7d06f72` commit.
2. Middle mouse click, or right click on the top logo
3. It doesn't do anything for middle clicking, and right clicking doesn't bring up any options to open in a new tab.

### Expected behavior

It should just open in a new tab.
If you want to see how it should work normally, just middle click on any other anchor link.

### Browser, and OS with Version.

Flatpak Librewolf (114.0.2-1) on Void Linux.

**Comment by Bnyro** [comment]
I changed the behavior to use JS events because otherwise you need to reload the page before the link gets updated.
But well, there's nothing better we can do about it.

**Comment by amogusussy** [comment]
Thank you :)
