### ISSUE TITLE
Add option to configure using environment variables

### ISSUE THREAD

**Issue by kubo6472** [TeamPiped/Piped#2650]
### Describe the feature

Like #2503 I'd like to make my setups easier by allowing all the options from config.properties to be passable as docker environment variables

### Why would this be useful to add?

A lot easier deployment of the current docker images (nothing monolithic/combined yet) on sites like fly.io for free.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
You can already use the same configuration properties as environment variables.
