### ISSUE TITLE
Use the YouTube share button to play videos on piped

### ISSUE THREAD

**Issue by aaliomer** [TeamPiped/Piped#2670]
### Describe the feature

to avoid copy/pasting URLs of videos, use the Android share feature to play videos immediately on piped. That would be an awesome UX feature 

### Why would this be useful to add?

Simple and very valuable (bank for the buck feature)
I keep copy pasting URLs and it is really annoying and preventing me from using piped

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by DarkCat09** [comment]
You can use [LibreTube](https://github.com/libre-tube/libretube) as a Piped client, or [UntrackMe](https://f-droid.org/packages/app.fedilab.nitterizeme/) if you just want to modify links.

**Comment by Bnyro** [comment]
I second [UntrackMe](https://f-droid.org/packages/app.fedilab.nitterizeme/) or [LibRedirect](https://libredirect.github.io/).

Out of scope for Piped directly as there are enough better ways to do this already.
