### ISSUE TITLE
Typing in search bar and pressing Enter doesn't search

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [TeamPiped/Piped#2675]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Pressing Enter no longer triggers a search.

### To Reproduce

1. Go to https://piped.video
2. Type "gamers nexus" in the search bar
3. Hit Enter
4. Nothing happens

Either tab, Enter (to select then activate the new search button), clicking search button, or selecting an autocomplete result must be done now.

### Expected behavior

Enter triggers a search.

### Browser, and OS with Version.

Current Chrome and Firefox on Windows 10.

**Comment by Vanerio** [comment]
Hi!
I would like to add that Enter still does not work in Brave (Android) on the Feed page. As you can see in the following screenshots, when on the Feed page, there is no Enter button, there is a button that just shifts the focus to the Filter combobox, but does not proceed to search. It works on the Trending page and in Firefox (Android).
![trending](https://github.com/TeamPiped/Piped/assets/111604545/90fa48df-978f-45db-867e-ffc4b0ad5256)
![feed](https://github.com/TeamPiped/Piped/assets/111604545/c383db01-cc67-44cb-ab83-99467fdd1c0a)
Thank you!
