### ISSUE TITLE
DeArrow is enabled no matter the preference

### ISSUE THREAD

**Issue by Bnyro** [TeamPiped/Piped#2683]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

See below

### To Reproduce

1. Load the trending page
2. See the videos

### Expected behavior

Title and thumbnail shouldn't be updated after a certain time, and no network request to the DeArrow route should be made.
However, they do, no matter the preference value of DeArrow.

### Browser, and OS with Version.

N'importe quoi.

### Additional context

Didn't yet look into the code, probably a typo for the preference key.

**Comment by FireMasterK** [comment]
Looks like I forgot to add the preference check in https://github.com/TeamPiped/Piped/commit/d6acb3e098b18a7ddb2a1f4518e4318380202d0b. 😅
