### ISSUE TITLE
This should have an independant API(for logged in users)

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#270]
Currently it sends auth requests to `https://pipedapi.kavin.rocks/register` and if i visit just `kavin.rocks` i get a rick roll -.-

How can i independently host my subscriptions etc?

**Comment by FireMasterK** [comment]
You cannot host subscriptions independently, you would have to host the entire Piped-Backend stack to host your own subscriptions.

**Comment by IvRRimum** [comment]
@FireMasterK So basically if i setup https://github.com/TeamPiped/Piped-Backend on my server, i would be able to host it on my own, right? Great work btw!!!

**Comment by FireMasterK** [comment]
Yes, correct!

Thank you!
