### ISSUE TITLE
Customize landing page/ default homepage/ default feed menu

### ISSUE THREAD

**Issue by Shadowspear123** [TeamPiped/Piped#271]
Lovely project! Especially appreciate PWA compatibility in iOS. 
Invidious used to have options to customize how you'd like the page to look when you load it, as does Newpipe (Don't show trending videos, don't show suggested videos, don't show comments, etc.). Would really appreciate if this could be implemented in this project as well. It was one of the things I really like about invidious.

**Comment by FireMasterK** [comment]
Closing this with 584f1854e22b5f13f680869c97ef966e25340cb7.

I'm moving rest of your suggestions to #277.
