### ISSUE TITLE
New instance: https://piped.drgns.space/

### ISSUE THREAD

**Issue by dragongooses** [TeamPiped/Piped#2714]
### Describe your question

Hello! I'm hosting an instance here:

Frontend: https://piped.drgns.space/
API: https://pipedapi.drgns.space/
Proxy: https://pipedproxy.drgns.space/
Country: US
Registration: Allowed!

It's hosted in my homelab (ISP is provider), without cloudflare.

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!
