### ISSUE TITLE
please help - how to analyse why migrated piped is not working?

### ISSUE THREAD

**Issue by eleaner** [TeamPiped/Piped#2727]
### Describe your question

I decided to move my piped from x86 host to arm64.
made tarball, moved with scp, started (upgraded database from 13 to 15 in the meantime)
in addition I changed url and switched caddy to nginx (behind my global traefik)

i go to my address - and nothing
well. technically this
![image](https://github.com/TeamPiped/Piped/assets/5169203/904ca2af-956c-401a-8c6e-9bd02be413e7)

I am looking into logs and I cannot spot anything that obviously indicates something is wrong
maybe this?
`piped-backend   | PubSub: queue size - 0 channels`

**Comment by FireMasterK** [comment]
Anything in the browser logs?

**Comment by eleaner** [comment]
@FireMasterK 
good advice, thank you
`Access to fetch at 'https://pipapi.TLD/config' from origin 'https://pip.TLD' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

so I kind of know what is wrong but still don't know how to fix it in traefik2

**Comment by eleaner** [comment]
ok, so it is embarassing 

in my traefik config i missed to add url to api and proxy
after adding it - everything works!

thank you!
