### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by probonopd** [TeamPiped/Piped#275]
It would be nice if one could sort the search results by date.

**Comment by FireMasterK** [comment]
We would require NewPipeExtractor to add support for this first.

**Comment by krafi99** [comment]
@

> We would require NewPipeExtractor to add support for this first.

Can you take help from Invidious source code for this and other sorting features? Invidious has all of that!!

**Comment by FireMasterK** [comment]
No, you would have to wait for https://github.com/TeamNewPipe/NewPipeExtractor/pull/904 to get merged first.

**Comment by Bnyro** [comment]
duplicate of #1376
