### ISSUE TITLE
Can't view view videos in muse India YouTube channel

### ISSUE THREAD

**Issue by Gamer750** [TeamPiped/Piped#2753]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When visiting the  muse India YouTube channel video is not loading

### To Reproduce

Open the URL

https://piped.video/channel/UCYYhAzgWuxPauRXdPpLAX3Q

### Expected behavior

Not loading videos

### Browser, and OS with Version.

Android on using libretube app

**Comment by iamwacko** [comment]
Is this really a piped issue? The list of videos won't load for me on [YouTube](https://www.youtube.com/@MuseIndiaChannel/videos) either.

**Comment by Bnyro** [comment]
Behaves kinda buggy on YouTube, so I'd assume it's their issue actually, as @iamwacko mentioned.

**Comment by Gamer750** [comment]
> Behaves kinda buggy on YouTube, so I'd assume it's their issue actually, as @iamwacko mentioned.

But I could watch videos on muse India using newpipe

**Comment by Gamer750** [comment]
This channel can only visited in India any way bypass restriction without using vpn
