### ISSUE TITLE
The show comments button on youtube kids videos, or videos with disabled comments, shows either "NaN", or -1.

### ISSUE THREAD

**Issue by amogusussy** [TeamPiped/Piped#2755]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

On all youtube kids videos or videos where the uploader has disabled comments, the number of comments is marked as being either -1, or Not a Number.

### To Reproduce

- Enable `Minimize Comments by default` in the settings
- Go to any video made for kids. For example, https://piped.kavin.rocks/watch?v=YXwnKgSXFKE.
- Look at the "Show Comments"
- It says `-1` instead of telling that it's been disabled.

### Expected behavior

The button shouldn't show up, and should instead just have a string saying something along the lines of "Comments have been disabled for this video."

### Browser, and OS with Version.

Flatpak Librewolf on Void Linux.

**Comment by Bnyro** [comment]
#2767
