### ISSUE TITLE
Sweep: correctly rewrite video descriptions timestamp links

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#2770]
### Details

The following video description is being incorrectly rewritten:
```
1. &nbsp;(<a href="https://www.youtube.com/watch?v=ZoChI5raLxM&amp;t=0">0:00</a>) FREYJA.sys～システム・フレイヤ～
```

It is incorrectly rewritten to:
```
1. &nbsp;(<a href="<a href=">0:00</a>)" target="_blank"&gt;/watch?v=ZoChI5raLxM&amp;t=0"&gt;0:00) FREYJA.sys～システム・フレイヤ～
```

The correct output should be:
```
1. &nbsp;(<a href="/watch?v=ZoChI5raLxM&amp;t=0">0:00</a>) FREYJA.sys～システム・フレイヤ～
```

The relevant code is in the `getVideoData` function in `WatchVideo.vue` and `main.js`.

**Comment by kevinlu1248** [comment]
sweep: Retry

**Comment by wwzeng1** [comment]
Hey @FireMasterK sorry about that! We added 5 more tickets.

**Comment by wwzeng1** [comment]
Appreciate you reporting the bug
