### ISSUE TITLE
Infinite Scrolling doesn't work

### ISSUE THREAD

**Issue by KY246** [TeamPiped/Piped#2776]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The webpage only loads one page of videos and doesn't have infinite scrolling.

### To Reproduce

1. Go to: https://piped.video/feed
2. Scroll to the bottom

### Expected behavior

More videos appear once the page is scrolled all of the way.

### Logs/Errors

On the Trending page, I don't get any errors in the console (but still see the problem)
On the Feed page, I get this error:
```
Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Proxy.loadMoreVideos (FeedPage-fb746523.js:1:2060)
    at Proxy.handleScroll (FeedPage-fb746523.js:1:2317)
loadMoreVideos @ FeedPage-fb746523.js:1
handleScroll @ FeedPage-fb746523.js:1
scroll (async)
ev @ index-1a536219.js:5
(anonymous) @ index-1a536219.js:5
Promise.then (async)
Ze @ index-1a536219.js:5
$ @ index-1a536219.js:5
(anonymous) @ index-1a536219.js:5
Promise.then (async)
G @ index-1a536219.js:5
w @ index-1a536219.js:5
install @ index-1a536219.js:5
use @ index-1a536219.js:1
(anonymous) @ index-1a536219.js:25
```

### Browser, and OS with Version.

Windows 11 (22H2)
Brave Browser - Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

I'm also getting the same behaviour on:
Firefox ESR - 102.14.0esr (64-bit)

**Comment by FireMasterK** [comment]
You have likely run out of videos. The trending page has 50 videos, and the feed has only 1 month of content from your subscribed channels.
