### ISSUE TITLE
playlist freezes deleting multiple videos from a playlist (only 1 gets deleted)

### ISSUE THREAD

**Issue by ChuckBartowski91** [TeamPiped/Piped#2783]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Hello, if I try to delete videos from a playlist it won't load anymore for a while, in addition deleting more videos it won't save all of them.

### To Reproduce

1. Open playlist
2. Delete videos

### Expected behavior

Update playlist, go back normally and easily reopen it. 

### Logs/Errors

Crash Log from libretube if can be of any use:

retrofit2.HttpException: HTTP 504 
	at retrofit2.KotlinExtensions$await$2$2.onResponse(SourceFile:175)
	at retrofit2.OkHttpCall$1.onResponse(SourceFile:9)
	at androidx.lifecycle.ViewModelProvider.onSuccess(SourceFile:34)
	at androidx.work.Worker$2.run(SourceFile:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9b25d3b, Dispatchers.IO]
    

### Browser, and OS with Version.

Firefox 116.0.1 on windows 10 but does on libretube app too.

**Comment by Bnyro** [comment]
Could you please provide the error logs from the browser console too?

**Comment by FireMasterK** [comment]
How large are your playlists?

**Comment by FireMasterK** [comment]
> Yeah i think i found the problem, the playlist has 4274 videos so i think requires a lot of time to refresh.
> 
> I tried another playlist with 100 videos and i don't get so much freezing. I'll create another playlists and when i see that it starts to lock up again i'll create one more.

Thanks for that info! I think this should be easily fixable.

The problem is that hibernate generates (1000s of in this case) extremely inefficient queries when manipulating lists, so we can use native SQL queries.
