### ISSUE TITLE
Discord Embeds do not show the content of the Piped video page

### ISSUE THREAD

**Issue by Wolfy76700** [TeamPiped/Piped#2787]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Unlike official YouTube pages, Piped pages do not produce comprehensive content embeds on Discord, thus preventing Discord users from seeing what was shared

![Screenshot_1385](https://github.com/TeamPiped/Piped/assets/1964201/3ad23cd9-a6bf-4f7c-aebb-79803ce0aaef)

### To Reproduce

1. Share a Piped link through Discord

### Expected behavior

The Piped link should produce a comprehensive Discord embed, akin to YouTube’s

![Screenshot_1386](https://github.com/TeamPiped/Piped/assets/1964201/f7bb555b-de69-451b-9d2e-b79927bbfaa2)

### Browser, and OS with Version.

Discord Stable 218224 on Windows 11 and Android

**Comment by Bnyro** [comment]
That's not yet supported, see https://github.com/TeamPiped/Piped/issues/1362
