### ISSUE TITLE
Browser Compatibility

### ISSUE THREAD

**Issue by chkrforoldcompatbility** [TeamPiped/Piped#2791]
### Describe your question

The website that uses Piped doesn't load the content for the last version for Chromium Apps that support Windows 8.1 and below.
Ex.  The content (such us the thumbnail, the search result and video) on Piped.video site doesn't work on Chrome Version 109.0.5414.149 (The last version of Chrome for Windows 8.1). as it recognized the browser as old. But it is weird the Contents work when it was being viewed in "Inspect" especially in mobile view (in inspect). What could possibly the problem.

BTW. There is an app called Spotube Music Player which uses Piped API. In order for music to run it will connect to default browser (Edge) to connect to the internet. However Since the browser cannot be updated anymore the music won't play due to the Piped API cannot be played on old browser. How can we fix it? Is it the problem from Pipe, which compatibility issue with old browser? I hope someone can answer this. And I am sorry I'm not a tech guy nor developer.

EDIT:
Okay I seemed found the problem. My Cloudflare Ray ID and IP is being blocked . I don't know the reason but why am I being blocked? Now I cannot access the API "https://pipedapi.kavin.rocks/" and my device doesn't show contents that runs buy this API. You can freely close the issue if no one's gonna reply. Thank

![image](https://github.com/TeamPiped/Piped/assets/141900449/a48bd878-69fe-4757-a465-3a9b83d249bb)

I hope the developer remove the limits for OLD browsers

**Comment by chkrforoldcompatbility** [comment]
Okay I seemed found the problem. My Cloudflare Ray ID and IP is being blocked. I don't know the reason but Why? You can close now the issue if no ones gonna comment
![image](https://github.com/TeamPiped/Piped/assets/141900449/08bc290e-27f6-4080-b672-6572b5c04b97)

**Comment by 3hr80FEZwlir** [comment]
Two questions. 

First: does the error occur with gecko based browsers, for example Mullvad or Firefox? 

Second: do you use VPN, is your computer behind a VPN or do you connect to a network with many other users (for example in a college)?

**Comment by Bnyro** [comment]
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.
