### ISSUE TITLE
Some videos are available only in 360p

### ISSUE THREAD

**Issue by DanielProg39** [TeamPiped/Piped#2794]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I opened a [video](https://piped.video/watch?v=ubCFcG0HtOo) and noticed a pretty bad quality, so I went to this video in [YouTube](https://www.youtube.com/watch?v=ubCFcG0HtOo) and it turns out that it's available in 1080p on YouTube, whereas in Piped the only option is 360p. I also noticed this issue in one other video, but most are not prone to this.

Piped:
![image](https://github.com/TeamPiped/Piped/assets/63293432/5afbe24c-c706-4617-b1fb-e6e790a2f503)

YouTube:
![image](https://github.com/TeamPiped/Piped/assets/63293432/d70a6cd2-5ee2-4918-a26c-507ea11a1be3)

### To Reproduce

1. Open this [video](https://piped.video/watch?v=ubCFcG0HtOo)
2. Open video quality list
3. 360p and Auto are shown
4. Open [YouTube link](https://piped.video/watch?v=ubCFcG0HtOo)
5. Open video quality list
6. 1080p is available

### Expected behavior

The quality should be the same as in YouTube for all videos.

### Browser, and OS with Version.

Chromium 115

**Comment by Fntoomen** [comment]
I have options to view this video in:
* 1080p
* 720p
* 360p
* 144p

**Comment by DanielProg39** [comment]
I opened the video now, all quality options are present.
