### ISSUE TITLE
Make channel groups exportable

### ISSUE THREAD

**Issue by matchboxbananasynergy** [TeamPiped/Piped#2799]
### Describe the feature

An option to export channel groups, either independent of the current subscription export option, or as part of it.

### Why would this be useful to add?

As someone who uses Piped without an account, I rely on being able to export all of my settings/subscriptions/playlists etc. to be able to replicate my experience on another device/browser.

Currently, channel groups (which are a very useful feature) are not exportable, meaning that I am unable to replicate my setup in case my browser's data is wiped, or I need to do so on another device.

My understanding is that this would likely persist across devices if I had an account, but I'd rather not create one. Seeing as a lot of work has gone into making it so that Piped can be used without one, it'd be fantastic for that to be the case with channel groups too.

### Concept(s)

There could be the existing option to export subscriptions, as well as another option that exports subscriptions, along with channel group data.

That way, if someone wants to export their subscription without any of the grouping, they could still do that.

There could either be separate buttons to do that, or the current buttons could be extended with a checkbox or additional option to include channel groups in the export, whatever feels best UX-wise.

### Additional context

This is an additional request, which I'm putting in this last section because I don't quite know if it is possible in the first place.

It would be amazing if exporting subscriptions and channel groups made it possible to import that into LibreTube and have those same channel groups there, but I'm unsure if the two implementations are interoperable.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Subscription groups are not synced per account, hence using an account wouldn't change anything about that.
Do you have a suggestion for a format for exporting subscription groups? Are you aware of any other projects that support that, so that we could use the same format in order to be compatible with them?

**Comment by 9p6** [comment]
I've noticed groups are not exported in `preferences.json`. Perhaps they should be added there too?

Also do groups export really need separate file? It would make sense to keep them together with subscriptions
