### ISSUE TITLE
PipedApi from piped.kavin.rocks is dead now

### ISSUE THREAD

**Issue by maxrave-dev** [TeamPiped/Piped#2803]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Get 502 Bad Gateway Status when use GET request to pipedapi.kavin.rocks
![image](https://github.com/TeamPiped/Piped/assets/113747128/fee56f5f-08b7-4245-9513-587cd910b055)

### To Reproduce

Get request : https://pipedapi.kavin.rocks/streams/FbNvIirNaQY

### Expected behavior

-

### Browser, and OS with Version.

Edge  115.0.1901.203, Win 11

**Comment by maxrave-dev** [comment]
Still bad gateway

**Comment by Hate9** [comment]
Yeah, this is still definitely a problem. I'm having the same issue.
