### ISSUE TITLE
Can't get subscriptions due to CORS

### ISSUE THREAD

**Issue by mastazi** [TeamPiped/Piped#2819]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When visiting the subscriptions page, the page is empty but instead it should display a list of channels.

Please note that only the subscriptions page is affected. I am able to use the feed (videos published by channels I follow) with no issues.

### To Reproduce

1. open https://piped.kavin.rocks/subscriptions
2. you should be able to see a list of the channels you have subscribed to
3. no channels are visible
4. upon opening dev tools, the CORS-related error which is pasted below is visible

### Expected behavior

you should be able to see a list of the channels you have subscribed to

### Logs/Errors

Access to fetch at 'https://pipedapi.kavin.rocks/subscriptions' from origin 'https://piped.kavin.rocks' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Browser, and OS with Version.

Brave Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)
on Ubuntu 22.04.3 LTS

### Additional context

This issue happened to me a few days ago, then I was able to see my subscriptions again, then it came back. I'm not sure what was the cause of the intermittent behaviour.

Anyway now it seems I can reproduce the problem every time since at least 24 hours ago.

**Comment by Seb3thehacker** [comment]
Issue here too in LibreTube.

**Comment by Bnyro** [comment]
No, LibreTube doesn't care about CORS.

**Comment by mastazi** [comment]
Today the issue is resolved from my end. I can see that the subscriptions are now being retrieved from `piped.` subdomain, not from `pipedapi.` so I guess the devs implemented some kind of proxy for the api.

**Comment by Bnyro** [comment]
No, we didn't? Data is still fetched from the `pipedapi` endpoint.
Anyways, if it works, we can close it.

**Comment by mastazi** [comment]
@Bnyro I already explained that it has been intermittent. Reread the ticket.
