### ISSUE TITLE
Instance selection doesn't work

### ISSUE THREAD

**Issue by AlphaNERD-** [TeamPiped/Piped#2829]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I am currently unable to either select an instance from which Piped runs off nor an authentication instance. The selection boxes remain empty. I tested this in Vivaldi on Android and Windows. LibreTube still allows me to select an instance, however shows a toast message stating that it cannot load a fresh list of instances.

I made an account on kavin.rocks (libre) and cannot log in on my desktop because i don't know how to access the frontend of kavin.rocks (libre) and can't select kavin.rocks (libre) on a frontend somewhere else.

### To Reproduce

1. Open any instance of Piped in your browser
2. Go to settings
3. Scroll down to instances
4. Click the combo box next to instance and see that it is empty
5. Check the checkbox next to "Use different authentication instance"
6. Click the combo box below to see that it too is empty

### Expected behavior

The instance combo box should show the currently selected instance and upon opening should reveal a list of more instances.

### Browser, and OS with Version.

Vivaldi 6.1.3035.302 on Windows

**Comment by Bnyro** [comment]
That's because https://piped-instances.kavin.rocks/ is down currently. 
The reason for that might be #2828.
