### ISSUE TITLE
Add Save/Exit button to preferences state

### ISSUE THREAD

**Issue by dotamir** [TeamPiped/Piped#283]
Hi. I just saw this repo and already fall in love with Piped. That's so cool. Good work 👍 

I've been playing with the application but when I opened the Preferences section, I was kinda confused which how I'm gonna exit from Preferences and even how can I save my settings?

I'd like to do contribute here and I can work on this issue.

**Comment by FireMasterK** [comment]
Sure! Feel free to work on this! I can assign this to you if you'd like.

**Comment by dotamir** [comment]
@FireMasterK Sure. Please assign it to me and I'll take care this week.
