### ISSUE TITLE
Authentication-only instance

### ISSUE THREAD

**Issue by Sir-Photch** [TeamPiped/Piped#2832]
### Describe your question

The docker setup only handles cases for spinning up the full stack of piped.
I'd like to set up a authentication-only instance though. Is this possible? Which part of the piped stack would I need?

Ideally, I would then be able to then choose my self-hosted instance for authentication at other frontends. 

I suspect the privacy benefits of piped would be kept that way?

**Comment by FireMasterK** [comment]
You would just require the backend and the database. Yes, privacy wise, you should be better indeed.

**Comment by Sir-Photch** [comment]
I see. But if I see correctly, in the current webinterface, you cant specify the URL for the custom instance, right?

**Comment by FireMasterK** [comment]
Yes, we have an open issue for that: #1434

**Comment by Sir-Photch** [comment]
Because in the end, all I had to do was to build the backend with 
```console
./gradlew shadowJar
```
Create a piped user and database in postgres and adjust the connection string in `config.properties`. I can't test it, but the program doesn't crash. 🤷🏼‍♂️ 
I also just commented out / set every setting that I don't need to false.

**Comment by Bnyro** [comment]
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.
