### ISSUE TITLE
Sorry, you have been blocked, you are unable to access kavin.rocks

### ISSUE THREAD

**Issue by Bellisario** [TeamPiped/Piped#2833]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Cloudflare blocked a computer searching for songs from the official Piped instance through API.

Could you please unblock the computer?\
Cloudflare says I need to share the "Cloudflare Ray ID", I put it on the "Logs/Errors" section.

### To Reproduce

I don't know if this is reproducible just by following these steps (as IP address, browser, etc. is also part of the "negative" score), but:

1. on my player musicale.tk, search "tiziano ferro"
2. results will fail to load
3. open devtools and find the error regarding the API in the console
4. open that URL
5. find the message "Sorry, you have been blocked"

### Expected behavior

Not being blocked just by using the API as expected and using the service properly, without abusing the API usage.

### Logs/Errors

Cloudflare Ray ID: `7f915b5f1b613752`

### Browser, and OS with Version.

Chrome `109.0.5414.120` on a Windows 7 computer.

### Additional context

That's the second day this computer has been blocked.\
The strange thing is that I'm using a Mac on the same network and I have no issue.

![photo_2023-08-19 11 44 59](https://github.com/TeamPiped/Piped/assets/72039923/b317e9aa-c594-4798-b9fb-e92d17d8688d)

**Comment by Bellisario** [comment]
### Update

Today searching `dua lipa` (always filtering by song only) on my Mac shows a 502 error (probably related to #2487 and #2809) but I'm not personally blocked, also if I'm on the same network of the Windows computer.

P.S.: I won't risk by searching "tiziano ferro" also on my Mac for testing as this could be the keyword that activated the block on the other computer.

**Comment by FireMasterK** [comment]
Hi, does this still happen?

I made some firewall changes to block some old browsers earlier, and forgot that chromium has dropped support for a lot of older Windows devices. (hence a lot of old Windows versions like 7, 8, etc have old browsers that can't be updated and were incorrectly blocked)

**Comment by Bellisario** [comment]
Yes, seems to work now.\
I used the same query `tiziano ferro` and this time it was not blocked (I'll close the issue!).
