### ISSUE TITLE
Bypass Geo restriction without using vpn

### ISSUE THREAD

**Issue by Gamer750** [TeamPiped/Piped#2837]
### Describe your question

I need to watch Muse India YouTube channel it can only viewed on India. Is there any way to bypass geo restriction without using vpn

**Comment by amogusussy** [comment]
You can just use an Indian piped instance.
https://piped.in.projectsegfau.lt/

**Comment by Gamer750** [comment]
Still can't view

**Comment by Gamer750** [comment]
It is showing like this 
![IMG_20230822_182100](https://github.com/TeamPiped/Piped/assets/141329708/fbb3f1a9-7e1f-468a-a66c-fc50fba3ecaf)

**Comment by MuubNito** [comment]
Maybe try it out on the website?

**Comment by FireMasterK** [comment]
It appears like the instance seems to be using a different IP in the backend and proxy for that instance. In this case, the IP is not an Indian one.

**Comment by Bnyro** [comment]
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.
