### ISSUE TITLE
direct subdomain wont work

### ISSUE THREAD

**Issue by amirmohamadamini** [TeamPiped/Piped#2852]
I have just set up my own instance, piped.looleh.xyz (note that 'Looleh' means 'pipe' in Persian), and positioned it as the primary layer behind CloudFlare CDN. The primary reason I chose to establish a Piped instance is due to the fact that in Iran, where I reside, YouTube is inaccessible through all Internet Service Providers (ISPs). Piped effectively overcomes this issue by bypassing the restriction. Occasionally, ISPs intentionally disrupt CloudFlare CDN IPs to impede the increasing traffic of VPNs operating over the CDN.

As a precaution, I require a subdomain that allows a direct connection to the server in the event of any disruptions on the CloudFlare network. Unfortunately, I lack the knowledge on which configuration file to modify for this purpose. I deployed the instance using the AIO script.

**Comment by MuubNito** [comment]
I don't understand most of Piped instances at all, but this may be related to issue 2809...

**Comment by amirmohamadamini** [comment]
nope, its not relevant to my problem.

**Comment by amirmohamadamini** [comment]
an update to issue:
I just found out i have to change config files of API, frontend and proxy. and add direct subdomains.
