### ISSUE TITLE
Add farside service as balancing on Instance dropdown

### ISSUE THREAD

**Issue by repparw** [TeamPiped/Piped#2853]
### Describe the feature

Use https://github.com/benbusby/farside as balancing between available instances, adding it to Instance dropdown

### Why would this be useful to add?

This would make it so you can use farside to auto-pick between available instances, useful for balancing and for when your default instance is offline, and only hard set your authentication instance.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
The instance API is well aware of health checking instances, we don't need farside. The instances dropdown list currently only lists instances that are working without issues.
