### ISSUE TITLE
New instance piped.looleh.xyz

### ISSUE THREAD

**Issue by amirmohamadamini** [TeamPiped/Piped#2865]
### Describe your question

Hello! I'm hosting an instance here:
Frontend: https://piped.looleh.xyz
API: https://api.looleh.xyz
Proxy: https://pr.looleh.xyz
Country: Netherland
Registration: Allowed

It's behind cloudflare CDN.

**Comment by FireMasterK** [comment]
Added, thank you for hosting an instance!
