### ISSUE TITLE
Pre-load sections after sponsor block segments

### ISSUE THREAD

**Issue by amogusussy** [TeamPiped/Piped#2871]
### Describe the feature

This feature would fetch the parts of a video that come after a sponsor segment that is set to automatically skip, and ignore the parts inside of the skipped segment.

### Why would this be useful to add?

This would make loading videos faster. Right now, piped only starts to fetch the parts of the video that have been skipped by SB after they've been skipped, which usually causes a several second delay.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
The Shaka player library handles the pre-loading, and the only possibility we have is to set how many second it preloads starting from the current position. Thus, not possible.
