### ISSUE TITLE
New instance: pi.ggtyler.dev

### ISSUE THREAD

**Issue by ggtylerr** [TeamPiped/Piped#2878]
### Describe your question

Hi there. Just started hosting Piped on my main node. It mentions adding new instances on the wiki but there seems to be no option to edit it (or GH updated it and I'm dumb.) Sorry if this is the incorrect way of doing it.
* Frontend: https://pi.ggtyler.dev
* Backend: https://piapi.ggtyler.dev
* Proxy: https://piproxy.ggtyler.dev
* Country: US (NYC)
* Registration: Allowed
---
Some extra notes:
* I'm currently only hosting this on my NYC1 node since it's the only one I have that has IPv6 functionality. However, in the future, I'll be adding more, and users are allowed to access select nodes using a subdomain. i.e. `nyc1.pi.ggtyler.dev`. I would appreciate it if this was mentioned or supported in some way.
* This does not use any kind of CDN.
* I post service board updates on https://ggtyler.dev/other/frontends and on [my Twitter](https://twitter.com/ggtylerr) (and probably on Mastodon or Firefish soon)

**Comment by FireMasterK** [comment]
Hi, if you're running an instance in multiple locations, you may want to consider using CockroachDB in Piped so accounts would work across regions. You could additionally use some kind of GeoDNS or anycast setup to automatically route users to the closest API server.

**Comment by ggtylerr** [comment]
I've tried GeoDNS over an nginx config, I don't think it worked at all. I think I'm just not smart enough for it, all of the proper setups I've seen either uses Google Cloud or CF. I'm not switching to CF, and Google Cloud is paid :/ I'll look into CockroachDB in the future though, thank you.

**Comment by FireMasterK** [comment]
The official instance uses it. I don't know about the gdrp stuff though, will need to check and document.

**Comment by ggtylerr** [comment]
LMK when you get around to it :) BTW is there a chatroom for hosters on Matrix (or a different platform)?

**Comment by ggtylerr** [comment]
Joined the public room, thank you :)

**Comment by FireMasterK** [comment]
Added (already), thank you for hosting an instance again!
