### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/webm; codecs="vp9"') is unsupported.

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#288]
Since Today midday i get this(Yandex browser inspect elements -> console)

**Comment by IvRRimum** [comment]
Works on chrome, but not yandex browser

**Comment by FireMasterK** [comment]
Looks like Yandex browser has an incorrect implementation of the MSE supported API.

Here's a list of supported browsers by shaka-player:
![image](https://user-images.githubusercontent.com/20838718/126381474-fefb32d0-7adc-408c-add2-cf28039eb956.png)

Since Yandex browser is not listed, there is nothing I can do, unfortunately.

**Comment by IvRRimum** [comment]
It was working on yandex browser few hours before. Did you do a backend update?

**Comment by FireMasterK** [comment]
No, there's nothing new, some videos support both WebM and MP4 streams, whereas some videos have only MP4. The only way it can play videos is when the video only supports mp4.

Normally, such an issue would not happen as shaka-player is smart enough to detect whether a codec is supported by the browser or not, and then choose streams accordingly, but in this case Yandex browser is doing something weird.

**Comment by IvRRimum** [comment]
Seems that there already is a pull request for this: https://github.com/yandex-pcode/shaka-player/pull/4

Will try to contact the shaka guys so they can merge it into master

**Comment by IvRRimum** [comment]
Wait, no. It's already merged https://github.com/google/shaka-player/pull/3072

**Comment by FireMasterK** [comment]
I'll take a look at this tomorrow when I install this.

**Comment by IvRRimum** [comment]
I created a pull request with a fix, can you please merge it: https://github.com/TeamPiped/Piped/pull/293

**Comment by FireMasterK** [comment]
I've created a fix on my own by taking a portion of your fix and simplified it. :)
