### ISSUE TITLE
New instance: watch.pluto.lat

### ISSUE THREAD

**Issue by wcw2x** [TeamPiped/Piped#2886]
### Describe your question

Hello! I recently started to host a Piped instance and would love to see it on the list.

**Frontend**: https://watch.pluto.lat/
**API**: https://watchapi.pluto.lat/
**Proxy**: https://watchproxy.pluto.lat/
**Country**: United States
**Registration**: Allowed

(privacy policy will be available on pluto.lat soon)
It's not behind a CDN.

**Comment by FireMasterK** [comment]
Added, thank you for hosting an instance!
