### ISSUE TITLE
Have been using it for past couple days. Cache issues?

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#289]
So, have been using this as a full time replacement to youtube for past couple of days. Sometimes SOME videos don't show up under Feed, but after CTRL+SHIFT+R, it suddenly shows up. Looks like a possible cache issue.

I will add examples in this issue whenever it happens again.

**Comment by IvRRimum** [comment]
This seems to be not related to cache. It seems that you have to open the channel(like search for it in the searcher) and only then the Feeds channels get updated. This definitely needs fixing.

**Comment by FireMasterK** [comment]
Are these videos by any chance a scheduled premiere?

**Comment by IvRRimum** [comment]
No, those videos where already posted an available in youtube for few hours already

**Comment by IvRRimum** [comment]
Yeah, this is really easy to replicate and really messes up the Feed experience :( I will try to setup backend localy tomorrow and take look, if it's still not resolved by then.

**Comment by FireMasterK** [comment]
Could you give me a few channel IDs which are facing this issue? I can check the pubsub subscribed status for them.

**Comment by IvRRimum** [comment]
Alright, here: https://www.youtube.com/c/LTVZiņudienests/videos?app=desktop

In feeds newest video from this channel shows: 20 hours ago - /watch?v=PCVdA6CkA5E
Newest video on youtube - /watch?v=lMoMRfOTj1A

When i open channel LTV zinu dienests trough search(in piped), then click on that channel(important!), then go to feeds and refresh the page, it shows the newest videos in feeds now.

**Comment by FireMasterK** [comment]
This should get fixed automatically in 4 days, I have had an incorrect configuration in all of my servers for PubSub, this should work soon!

**Comment by IvRRimum** [comment]
Okey, awesome. Will wait then! Leave the issue open please, i will close after 4 days

**Comment by FireMasterK** [comment]
Yes, that's what I'm going to do :)

**Comment by jb137** [comment]
> This should get fixed automatically in 4 days, I have had an incorrect configuration in all of my servers for PubSub, this should work soon!

My self hosted setup exhibits the same problem. Feeds are not updated unless one visits the channel page. Could you elaborated on how this involves an issue on your server?

**Comment by FireMasterK** [comment]
> My self hosted setup exhibits the same problem. Feeds are not updated unless one visits the channel page. Could you elaborated on how this involves an issue on your server?

Have you set `API_URL` in config.properties?

**Comment by jb137** [comment]
API_URL: http://piped-api.<local_domain>

I run both piped-api and piped-proxy locally.

**Comment by FireMasterK** [comment]
> I run both piped-api and piped-proxy locally.

You need to be accessible over the internet for PubSub to work (to get subscriptions to update)

**Comment by jb137** [comment]
Why is this? And what is this PubSub?

**Comment by jb137** [comment]
I found the reference to PubSub. Would it be and option to update the feed without the external pubsub requirement? The feed refreshes when you visit a channel. Could this be done periodically? Or on a (refresh) command?

**Comment by IvRRimum** [comment]
Looks like it has started working. I will use it fully this week, will report back if its alright, or are there more issues.

**Comment by IvRRimum** [comment]
This is resolved

**Comment by sdfg2** [comment]
@IvRRimum how did you resolve this?  I'm facing the same issue.

**Comment by FireMasterK** [comment]
> @IvRRimum how did you resolve this? I'm facing the same issue.

You should ensure that `API_URL` is publically reachable.

**Comment by sdfg2** [comment]
> > @IvRRimum how did you resolve this? I'm facing the same issue.
> 
> You should ensure that `API_URL` is publically reachable.

It is.
