### ISSUE TITLE
Modify source code

### ISSUE THREAD

**Issue by wcw2x** [TeamPiped/Piped#2890]
### Describe your question

I'm running Piped with Docker and was trying to build an image with a different <title> (just to test), but when I build it and pull the image on the server the code doesn't change. I tried to change App.vue, index.html and even main.js.

e.g: <title> on the main source code was Piped, changed to XYZ, built the image, but when pulled in Docker it continues to be Piped.

It's not the cache, as I tried with different browsers and the same thing was happening. How could I do it?

**Comment by FireMasterK** [comment]
The title is modified at various locations in the code, are you sure that your title isn't being overridden by the page you're visiting for example? Are you also sure that you're using the right image in the docker compose file?

**Comment by wcw2x** [comment]
_**Are you also sure that you're using the right image in the docker compose file?**_ Yes, absolutely. `docker container list` shows my image.

_**The title is modified at various locations in the code, are you sure that your title isn't being overridden by the page you're visiting for example?**_ A few hours ago I tried to add the Plausible script and the same thing happened. The entire index.html appear to be overwritten by some code.
