### ISSUE TITLE
Piped not playing livestreams

### ISSUE THREAD

**Issue by hugoghx** [TeamPiped/Piped#2898]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When opening a livestream, the piped frontend just displays the spinning icon.

I noticed this 2 days ago after a frontend update. It's happening in piped.video too when playing a livestream. From the looks of it, it's some frontend problem as the proxy is replying with data but no playback occurs, and also I can watch the livestreams on the phone through Yattee.

I built the frontend from source, version `master @ cc478fd5` and it now works. I suspect the shaka player update broke something.

### To Reproduce

1. Open livestream on piped.video
2. Observe the spinning loading icon that does not go away - The livestream never loads.

### Expected behavior

It should load and play.

### Browser, and OS with Version.

I tried on a variety of browsers (Firefox, Brave, Edge, Safari) and OSes (Windows, iOS)

### Additional context

Whilst loading, there is network activity with the proxy.

**Comment by Cade66** [comment]
Same here (Firefox 115.2.0/Win7), yet I have two Piped instances which render live streams correctly:

https://efy.piped.pages.dev/ : **not** included in [Piped instances list ](https://github.com/TeamPiped/Piped/wiki/Instances)
https://piped.privacydev.net/ : included in [Piped Instances list](https://github.com/TeamPiped/Piped/wiki/Instances)

Tested with several live streams, i.e. Euronews Live (EN and FR), Sky News Live, France 24 Live (EN and FR).

**Comment by hugoghx** [comment]
I have isolated this problem to the `shaka-player` updates. Any version after `4.3.9` does not work, however, starting off of current main and updating the package to 4.3.9 restores the livestream functionality.

I'm unsure why updating the package leads to this behaviour.

**Comment by maathimself** [comment]
> I have isolated this problem to the `shaka-player` updates. Any version after `4.3.9` does not load livestreams, however, starting off of the current `master` branch and reverting the package to `4.3.9` restores the livestream functionality.
> 
> I'm unsure why updating the package leads to this behaviour.

Would you happen to know how to revert shaka-player using docker compose?

**Comment by hugoghx** [comment]
> Would you happen to know how to revert shaka-player using docker compose?

I am also using docker compose to deploy software. What I did was clone this repo, then on the `master` branch, downgrade `shaka-player` to `4.3.9` [here](https://github.com/TeamPiped/Piped/blob/master/package.json#L25). Then, I used `pnpm` to update the lock file. 

Here's a patch with the changes: [shaka-player-downgrade.patch](https://github.com/TeamPiped/Piped/files/13060373/shaka-player-downgrade.patch)


Finally, I changed the Docker Compose service definition to build the image from my local piped repo (which we just made the changes to)
```yaml
  piped:
    build:
      context: "<path/to/piped>"
      dockerfile: "Dockerfile"
    ...
```

instead of
```yaml
  piped:
    image: "1337kavin/piped-frontend:latest"
    ...
```

From there, Docker builds the image and runs it. Keep in mind that now you will need to maintain this yourself. You won't get updates automatically from the upstream image, you need to actively pull the latest `master`, rebase your branch off of that, then re-build the image to update.

**Comment by Orygaw** [comment]
The solution is currently not working, do you have any ideas for a solution?
