### ISSUE TITLE
Where can I see the .onion instances of Piped?

### ISSUE THREAD

**Issue by Ashvith10** [TeamPiped/Piped#2899]
### Describe your question

In the wiki, I cannot see .onion domain links of Piped? Where are they listed?

**Comment by Jeidnx** [comment]
There is no official list of instances that support tor. Some instances do offer tor variants, you can find them with this handy one-liner:
```
curl https://piped-instances.kavin.rocks 2&> /dev/null | jq '.[].api_url' | xargs curl -i 2&> /dev/null | grep  onion-location
```

It will query the instance list, connect to every server and then filter for the ones returning the `onion-location` header.
