### ISSUE TITLE
Media stream keeps playing(audio) even when you have left the current page(without hard refresh)

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#290]
Looks like vue navigator doesnt end the video stream after route change.

**Comment by IvRRimum** [comment]
I see a guy who forked this project and fixed the issue https://github.com/agent31750/Piped/commit/87e922e06d6971a94e9f5086805ce388aa1c22ec

**Comment by IvRRimum** [comment]
This happens randomly tho. Trying to figure out how exactly to reproduce the issue consistently

**Comment by FireMasterK** [comment]
> I see a guy who forked this project and fixed the issue [agent31750@87e922e](https://github.com/agent31750/Piped/commit/87e922e06d6971a94e9f5086805ce388aa1c22ec)

That is not a fix, that is an old commit of mine.

I've faced this issue once or twice, I still do not have a way to reproduce this consistently either.

**Comment by IvRRimum** [comment]
Found it, from video view page. Right at the last second of the video(right before it redirects to next one), click on feeds, after few seconds the new video audio will start playing, even tho your on the feeds page.

Whats weird, that when you are in any video( like video show page) and you click on feeds. the pages title doesnt change, but stays of the video you where watching.

**Comment by FireMasterK** [comment]
Should be fixed now, do let me know if it's not!
