### ISSUE TITLE
Add an option to display more videos on the feed page (older than a month)

### ISSUE THREAD

**Issue by Moonstone3010** [TeamPiped/Piped#2923]
### Describe the feature

Videos on the feed page are limited to the latest from the last month. I understand that this restriction is intentional and affects the performance of the instances. However, it would be useful to have an option to manually expand the loading of videos older than a month, e.g. by adding an option `load videos older than...`.

### Why would this be useful to add?

With a very large number of subscriptions, it's hard to watch everything in a month. Currently, to solve this, you have to open each channel and check if any video has been missed.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Hi, this setting is currently up to the instance operator's discretion. The default value is 30 days and can be modified by the configuring the `FEED_RETENTION` configuration property. You may request your instance operator to raise that value to have a longer feed.
