### ISSUE TITLE
Update watch.pluto.lat

### ISSUE THREAD

**Issue by wcw2x** [TeamPiped/Piped#2943]
### Describe your question

Hi again,

I've moved to Hetzner after having some serious problems with Linode and would like to update some informations about my instance (watch.pluto.lat).

**API**: api.watch.pluto.lat
**Proxy**: proxy.watch.pluto.lat
**Country**: Finland
**CDN**: No

**Comment by Bnyro** [comment]
Uprated, thanks for the info :+1:
