### ISSUE TITLE
[API] Return non-relative paths for HLS streams

### ISSUE THREAD

**Issue by Cynosphere** [TeamPiped/Piped#2945]
### Describe the feature

HLS streams currently return relative paths, which not all players (and sadly ffmpeg) handle this well

### Why would this be useful to add?

ffmpeg does not properly understand relative paths from HLS streams

### Additional context

I am in a context (Discord bot) where the library I'm using for streaming audio (Dysnomia, maintained fork of Eris) relies heavily on ffmpeg. I cannot use normal audio stream URLs because of their short expiry time, which cannot be worked around (thanks Google!). I've dealt with this issue for years and the only solution was to use InnerTube (youtubei.js) but I want to move away from using YouTube's API directly.

I would've tried to report this to ffmpeg, but that's a headache in it of itself that I do not want to deal with to most likely be told "this is a duplicate".

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Hi, I'm unable to reproduce this with the following command:
```sh
ffmpeg -i $(curl -s "https://pipedapi.kavin.rocks/streams/jNQXAC9IVRw" | jq -r .hls) -c copy test.mkv
```
