### ISSUE TITLE
New instance: piped.seitan-ayoub.lol

### ISSUE THREAD

**Issue by unstablemaple** [TeamPiped/Piped#2952]
### Describe your question

My instance is up.

Frontend: https://piped.seitan-ayoub.lol/
https://watch.seitan-ayoub.lol/ also redirects to the frontend as well.
API: https://piped-backend.seitan-ayoub.lol/
Proxy: https://piped-proxy.seitan-ayoub.lol/
Hosted in: Germany
Registration: Allowed

**Comment by Bnyro** [comment]
It seems like your proxy doesn't operate properly? Neither images nor videos seem to load.

**Comment by unstablemaple** [comment]
Hmm, that's weird, it was working 5 hours ago. Now I get this whenever I try to access it:

`2023/09/15 12:31:17 [crit] 22#22: *1686 connect() to unix:/var/run/ytproxy/actix.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.2.137, server: piped-proxy.seitan-ayoub.lol, request: "GET /vi/FV3bqvOHRQo/maxresdefault.jpg?host=i.ytimg.com HTTP/1.1", upstream: "http://unix:/var/run/ytproxy/actix.sock:/vi/FV3bqvOHRQo/maxresdefault.jpg?host=i.ytimg.com", host: "piped-proxy.seitan-ayoub.lol"`

Any idea how to fix this?

**Comment by Bnyro** [comment]
Seems like the proxy isn't running. Are you using the docker container?

**Comment by unstablemaple** [comment]
Yes, surprisingly the issue only occurs when I run nginx from a separate `docker-compose.yml`. Is there something I should account for?

**Comment by Bnyro** [comment]
No clue, I use the Debian nginx package on my instance.

**Comment by Bnyro** [comment]
Feel free to ping me here when your instance is operating properly, then I'll add it to the list.

**Comment by unstablemaple** [comment]
Solved it! If anyone encounters the same issue with nginx, then just create a new volume with `docker volume create piped-proxy` , and edit `docker-compose.yml` for nginx and piped to have this at the end:

```
volumes:
    piped-proxy:
         external: true
```
         
This should allow nginx to share that volume with the proxy and `actix.sock` will be accessible to nginx.

**Comment by unstablemaple** [comment]
@Bnyro check if it works now, thanks.

**Comment by Bnyro** [comment]
Works great :+1:

One last thing I need to know: do you use a CDN?

**Comment by unstablemaple** [comment]
@Bnyro No. Why is that recommended? Cloudflare's CDN actually destroys the purpose of a frontend like this as it blocks tor and VPN connections, on top of that, they can access the data being sent.

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!

I don't use a CDN myself, but I think it's recommended due to faster response times (Feel free to ask in the Matrix room if you're looking for an answer from someone who's more familiar with that).
