### ISSUE TITLE
How to host on GitHub Pages?

### ISSUE THREAD

**Issue by idontplayminecraft** [TeamPiped/Piped#2969]
### Describe your question

How do I host piped in GitHub pages

**Comment by Bnyro** [comment]
The backend can't be hosted on GitHub. For the frontend, you're better off with using something like vercel.

Otherwise you can look into tutorials on how to deploy Vue apps with GitHub pages.

**Comment by FireMasterK** [comment]
There's really no point in just hosting the frontend, you might as well access a public mirror, or use the IPFS mirror. :)
