### ISSUE TITLE
No full screen on iPad

### ISSUE THREAD

**Issue by Inrumpo** [TeamPiped/Piped#298]
Starting a video on my iPhone SE 2020 (iOS 14.7 / Safari browser app) does allow me to view that video isolated in full screen (by tilting the device to landscape orientation).

Unfortunately, this doesn't happen on my iPad Pro 10.5 (iPadOS 14.6 / Safari browser app). I haven't found a way to isolate the video in the same manner and watch in in full screen.

**Comment by m5arish** [comment]
Had the same issue, make sure you’re not in private mode.

**Comment by FireMasterK** [comment]
> Starting a video on my iPhone SE 2020 (iOS 14.7 / Safari browser app) does allow me to view that video isolated in full screen (by tilting the device to landscape orientation).
> 
> Unfortunately, this doesn't happen on my iPad Pro 10.5 (iPadOS 14.6 / Safari browser app). I haven't found a way to isolate the video in the same manner and watch in in full screen.
> 


> Had the same issue, make sure you’re not in private mode.

@Inrumpo can you confirm that you're not in private mode?

**Comment by FireMasterK** [comment]
Closing this due to a lack of response.

**Comment by Inrumpo** [comment]
I'm using it like a web app in Safari (-> to home screen). Shouldn't be in private mode.

**Comment by FireMasterK** [comment]
I've been told it doesn't work there either.

**Comment by Inrumpo** [comment]
That's correct. Full screen is not possible on my iPad in Safari (private and non-private), Firefox and as a web app. That's why this issue was created.

**Comment by FireMasterK** [comment]
I'm sorry, but this is likely a limitation by IOS/iPad OS itself. I don't think there's anything I can do here.

**Comment by m5arish** [comment]
> I'm sorry, but this is likely a limitation by IOS/iPad OS itself. I don't think there's anything I can do here.

It’s not iPadOS issue as it’s working fine on invidious.
