### ISSUE TITLE
Video won’t load

### ISSUE THREAD

**Issue by Abdurrahman-m11** [TeamPiped/Piped#2984]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The video won’t load and it always stop after a second it loads. It also happens when I put it to the lowest quality.

### To Reproduce

Probably make a option to download it

### Expected behavior

It won’t lag anymore 

### Browser, and OS with Version.

I use google

**Comment by Doktor515** [comment]
There is such a problem.timeout happens.Video does not load and stops. Happens in one video

Link:https://www.youtube.com/watch?v=6pqbFiHHrbk&t=0

**Comment by Bnyro** [comment]
That looks like either the instance is overloaded or your internet connection is bad.
