### ISSUE TITLE
Navigation bar is hidden / not visible

### ISSUE THREAD

**Issue by acidghost** [TeamPiped/Piped#2987]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The navbar is hidden / not visible:

![image](https://github.com/TeamPiped/Piped/assets/1787979/72c22466-0a6d-419a-8998-2808b61ee949)

### To Reproduce

1. Open homepage or feed
2. The navbar is not there

### Expected behavior

The navbar should be visible. This is how it should show as seen in Safari:
<img width="1840" alt="Screenshot 2023-09-26 at 08 24 17" src="https://github.com/TeamPiped/Piped/assets/1787979/2df59884-9472-4934-936f-8bda748a5dd2">

### Browser, and OS with Version.

Firefox 117.0.1 on macOS 13.6.

**Comment by acidghost** [comment]
This userscript seems to fix it for desktops but does not work for mobile screen sizes:

```js
// ==UserScript==
// @name        Show nav menu - piped.video
// @namespace   Violentmonkey Scripts
// @match       https://piped.video/*
// @grant       none
// @run-at      document-idle
// @version     1.0
// @author      acidghost
// @description 26/09/2023, 15:05:29
// ==/UserScript==
(function () {
  'use strict';

  const app = document.getElementById("app");
  (new MutationObserver(check)).observe(app, { childList: true, subtree: true });

  function check(changes, observer) {
    const navMenu = app.querySelector("nav > ul:first-of-type");
    if (navMenu) {
      observer.disconnect();
      navMenu.classList.remove("hidden");
    }
  }
})();
```

**Comment by Cynosphere** [comment]
It happens if SponsorBlock's "third party site support" option is enabled, since a recent update to SponsorBlock made it work on Piped again.

**Comment by acidghost** [comment]
That's good to know. @Cynosphere do you know which version of SponsorBlock fixed it?

**Comment by Cynosphere** [comment]
> not sure what you meant to write but it's not fixed in SponsorBlock.
SponsorBlock's third party support didn't used to work on Piped until then.

**Comment by FireMasterK** [comment]
I'll close this issue in this case, as it's not an issue here!
