### ISSUE TITLE
Feed is not updated

### ISSUE THREAD

**Issue by MacCZ** [TeamPiped/Piped#299]
Hello, 

after usuing Piped I have found a problem with updating feed. When I click on feed I see old published videos, but not new ones, then I have to click on every channel I subscribed to update my feed. 
Or am I missing some setting that changes regularity of updating feed?

**Comment by FireMasterK** [comment]
Could you give an example channel ID?

**Comment by Inrumpo** [comment]
I'm experiencing a similar issue. My newly imported subscriptions do/did not update. I'm seeing roughly one day worth of videos not listed in my feed. 
But: One recent video (released ~30min ago) has been added to my feed now. Therefore things might be working again.

**Comment by MacCZ** [comment]
> Could you give an example channel ID?

For example channel called “TeslaDaily” 
Channel ID - UCgYkuL87rUwiBl7tqfN53Eg

**Comment by FireMasterK** [comment]
https://pubsubhubbub.appspot.com/subscription-details?hub.callback=https%3A%2F%2Fpipedapi.kavin.rocks%2Fwebhooks%2Fpubsub&hub.topic=https%3A%2F%2Fwww.youtube.com%2Fxml%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUCgYkuL87rUwiBl7tqfN53Eg&hub.secret=

The channel seems to be last subscribed about an hour ago, let me know if this problem happens again.

**Comment by MacCZ** [comment]
Okay it happened again. But with different channel. 
Channel called “Bjørn Nyland”
Channel ID - UCG1QcV31eoSaX4rE8avQL4A

+ screenshot for reference 
![17592169-F75C-42B9-AC82-C013CD982D69](https://user-images.githubusercontent.com/50764475/126669581-3afe9800-dc19-4e94-b562-cabe152f0dff.jpeg)

![006EAC2C-B6AC-44C2-9F2F-ADA534F2A969](https://user-images.githubusercontent.com/50764475/126669590-a0be8dcd-a1f8-4f9d-9970-1b76bab7cc37.png)

**Comment by FireMasterK** [comment]
I'm going to say wait for 3 days, since the problem seems to be exactly the same as #289.

**Comment by MacCZ** [comment]
I will wait for sure. Thanks in advance!
