### ISSUE TITLE
Countries in the Country Selection dropdown are ordered by code, not by name

### ISSUE THREAD

**Issue by venn-xx** [TeamPiped/Piped#300]
Country lists are typically read in alphabetical order of name, not code.

**Comment by venn-xx** [comment]
I have a pull request I can submit for this if desired

**Comment by FireMasterK** [comment]
Sure, feel free to!

**Comment by venn-xx** [comment]
> Sure, feel free to!

Thanks! I can't push my branch to the repo in order to create a PR, do you need to give me push access to the repo?

**Comment by FireMasterK** [comment]
You would have to create a fork, and then create a branch and push there. Then you will be able to create a PR.

**Comment by FireMasterK** [comment]
Closing this as #303 was merged.
