### ISSUE TITLE
ultralow audio only, regardless of video quality

### ISSUE THREAD

**Issue by Daniel6372** [TeamPiped/Piped#3016]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

No matter the selected video quality, the ultralow opus audio stream is selected (600).

Similar to https://github.com/TeamPiped/Piped/issues/1300, but even lower quality.

### To Reproduce

1. Open any video
2. Notice the low quality audio, open DevTools Network tab
3. Verify that the itag value in the GET request for the audio stream is 600

### Expected behavior

Highest quality opus audio (251) is selected, at least with high quality video options.

### Browser, and OS with Version.

Firefox 118 / Fedora Workstation 38

**Comment by Daniel6372** [comment]
I have now noticed 249 as well on a few other videos, which is the second lowest quality audio option.

**Comment by charonfaustinus** [comment]
I've noticed this since they're trying to implement support for multilanguage audio. It could've broken something in the process.

**Comment by snematoda** [comment]
should be fixed now with #3143 :)
