### ISSUE TITLE
 Video control iOS/iPadOS 

### ISSUE THREAD

**Issue by m5arish** [TeamPiped/Piped#302]
Can the website use native iOS/iPadOS video player. I don’t see the “15 seconds fast forward and backward” also “airplay” button.

thank you

**Comment by FireMasterK** [comment]
> Can the website use native iOS/iPadOS video player

No, you cannot, sorry.

> I don’t see the “15 seconds fast forward and backward”

There is no "15 seconds fast forward and backward" button implemented in shaka-player.

> “airplay” button

I think this can be added, I will take a look at this.
