### ISSUE TITLE
https://piped.video/trending

### ISSUE THREAD

**Issue by MikrosKokoras** [TeamPiped/Piped#3022]
### Describe your question

I am not able to access https://piped.video/trending. Seems like there is something wrong. Is it only me?
*Sorry if there is a similar question.

![Pipedvideo](https://github.com/TeamPiped/Piped/assets/63351524/1fbf0171-ca16-46ee-95d6-e0b53ec0c83a)

**Comment by Bnyro** [comment]
Works fine here.
