### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by r2fo** [TeamPiped/Piped#3026]
### Describe your question

Hi,
I've setup a Piped instance and I'm wondering if it can be added to the list. The server is hosted by Oracle in Amsterdam (NL) and it's behind Cloudflare. I followed the instructions at https://github.com/TeamPiped/Piped/issues/737#issuecomment-1014482130. 

~~Just to be sure, I separated the image proxy and video proxy as apparently Cloudflare does not like to proxy video's https://github.com/TeamPiped/Piped/issues/1243#issuecomment-1200426541.~~ 

To fix the refresh loop, I applied the fixes which are mentioned at https://github.com/TeamPiped/Piped/issues/1932#issuecomment-1369198255

Is there anything else I can improve? Currently cache everything is only enabled for pipedproxy.rafo.tech, should I enable it for the frontend/api too?

Frontend: https://piped.rafo.tech
API: https://pipedapi.rafo.tech
Proxy: https://pipedproxy.rafo.tech
~~Image proxy: https://pipedproxy.rafo.tech
Video proxy: https://pipedvideoproxy.rafo.tech~~

**Edit**: Because I kept getting error codes 1002 (CORS errors) and 3015(?) during video playback, I reverted the change and both images and videos are now using pipedproxy.rafo.tech again.

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!

I don't see any special that should be improved in your setup, the only thing that might have to be considered in the future if there are many users is using a proxy/VPN between the server and YouTube to prevent rate limiting.
