### ISSUE TITLE
New instance: piped.12a.app

### ISSUE THREAD

**Issue by angus6b23** [TeamPiped/Piped#3030]
### Describe your question

Hello! I recently started to host a Piped instance and would love to see it on the list.

Frontend: https://piped.12a.app/
API: https://pipedapi.12a.app/
Proxy: https://pipedproxy.12a.app/
Country: Netherlands
Registration: Allowed

It's not behind a CDN.

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!

**Comment by angus6b23** [comment]
Please remove the instance from the list as the vps provider is not very happy about hosting the instance. Thank You.
