### ISSUE TITLE
Video at 1080p suddenly stops and buffers forever

### ISSUE THREAD

**Issue by gianmarcogg03** [TeamPiped/Piped#3031]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When I watch a video forced in 1080p, at some random point, usually near the middle of the video, it will stop playing and show the buffer spinner. Nothing can make that video play again (like scrubbing around, changing the video quality, etc.), except for reloading the whole page. I've had this happen on multiple instances.

### To Reproduce

1. Open some moderately long video
2. Set its quality to 1080p
3. Watch until the middle of the video or around that time

### Expected behavior

The video should keep playing since the network is still working properly.

### Browser, and OS with Version.

LibreWolf 118.0.2-1 on Arch Linux.

### Additional context

Among my browser extensions, I have installed uBlock Origin and JShelter. Not sure if they could be affecting the problem.

**Comment by mattbhenley** [comment]
@gianmarcogg03 I was experiencing the same issue so I disabled my extensions. After refreshing, I no longer experienced the buffering issue. Just wanted to share.

**Comment by gianmarcogg03** [comment]
> @gianmarcogg03 I was experiencing the same issue so I disabled my extensions. After refreshing, I no longer experienced the buffering issue. Just wanted to share.

This works most of the time, but I still get this issue occasionally.

**Comment by FireMasterK** [comment]
Hi, this should no longer happen with 32c234258b6e7f05815e40d08886620e8edd5e6a now.
