### ISSUE TITLE
self-hosting privately? caddy throws "ambiguous site definition"

### ISSUE THREAD

**Issue by draeath** [TeamPiped/Piped#3034]
### Describe your question

I'm looking to run a local Piped instance on my local network just for my household - no external access.

I'm trying to follow the instructions [here](https://docs.piped.video/docs/self-hosting/) re: Caddy and I'm not able to proceed - the caddy container just restarts constantly, reporting:

    {"level":"info","ts":1697523791.2935977,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
    Error: adapting config using caddyfile: ambiguous site definition: REDACTED.localdomain

This is an internal hostname - it resolves, but is invalid externally.

I suspect this has to do with automated TLS handling, as searching for this error lead me to ACME related stuff, which is what (if i recall correctly) Let's Encrypt uses?

----

1. Is Piped suitable to run in this manner at all, or is it expected for it to be externally accessible?
2. Do I actually need a reverse proxy at all in this sort of configuration? If not, I'm assuming I can just select 'nginx' and then, well, not run it and connect directly to the frontend? I guess I could just try it, but I figured it wouldn't hurt asking in case I might be handling a footgun and that being confirmed would be helpful for me, as well as anyone else who might find their way to this issue trying to accomplish the same task.

----

This use case seems entirely undocumented. It would be nice if some guidance was added to the documentation on this, if it's at all to be supported.

If it's *not* a supported use case, or even just discouraged, a note about that on that page would be welcome, to help others avoid "wasting" their time.

**Comment by draeath** [comment]
Hmm. I've hit a brick wall. Any guidance would be appreciated.

I set up my local DNS resolver with some hostnames and followed the self-hosting instructions for ngingx. I can see traffic landing in the nginx container, but all that I get is the default nginx welcome page. I'm not sure what I've done wrong.

(the only deviation I've done is to comment out the watchman container, which seems useful only to update the stack and doesn't like podman)

    # running containers
    root@rpi4:~/Piped-Docker# podman-compose ps
    ['podman', '--version', '']
    using podman version: 4.3.1
    podman ps -a --filter label=io.podman.compose.project=piped-docker
    CONTAINER ID  IMAGE                                      COMMAND               CREATED        STATUS            PORTS                 NAMES
    56be50811ff4  docker.io/1337kavin/piped-proxy:latest     /app/piped-proxy      8 minutes ago  Up 8 minutes ago                        piped-proxy
    7d7639130a51  docker.io/library/postgres:15              postgres              8 minutes ago  Up 8 minutes ago                        postgres
    ef2a68d36d41  docker.io/1337kavin/piped:latest                                 8 minutes ago  Up 8 minutes ago                        piped-backend
    ce10357b2408  docker.io/1337kavin/piped-frontend:latest                        8 minutes ago  Up 8 minutes ago                        piped-frontend
    6df1ce499078  docker.io/library/nginx:mainline-alpine    nginx -g daemon o...  8 minutes ago  Up 8 minutes ago  0.0.0.0:8080->80/tcp  nginx
    exit code: 0
    
    
    # my host-side nginx configuration
    root@rpi4:~/Piped-Docker# cat /etc/nginx/sites-enabled/piped 
    server {
        listen [::]:80;
        listen 80;
        server_name piped-proxy.localdomain piped-frontend.localdomain piped-backend.localdomain;
    
        location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        }
    }
    
    server {
        listen [::]:443 ssl;
        listen 443 ssl;
        server_name piped-proxy.localdomain piped-frontend.localdomain piped-backend.localdomain;
        ssl_certificate     /etc/nginx/tls/rpi4.localdomain.crt;
        ssl_certificate_key /etc/nginx/tls/rpi4.localdomain.key;

        location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        }
    }
    
    
    # showing the hostnames used are all valid with respect to the server (works for client too)
    root@rpi4:~/Piped-Docker# for i in piped-proxy piped-frontend piped-backend piped; do host "${i}.localdomain"; done
    piped-proxy.localdomain has address 192.168.0.4
    piped-frontend.localdomain has address 192.168.0.4
    piped-backend.localdomain has address 192.168.0.4
    piped.localdomain has address 192.168.0.4
    
    
    # generated docker-compose.yml with watchman commented out as noted
    root@rpi4:~/Piped-Docker# cat docker-compose.yml 
    version: "3"
    
    services:
        pipedfrontend:
            image: 1337kavin/piped-frontend:latest
            restart: unless-stopped
            depends_on:
                - piped
            container_name: piped-frontend
            entrypoint: ash -c 'sed -i s/pipedapi.kavin.rocks/piped-backend.localdomain/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
        piped-proxy:
            image: 1337kavin/piped-proxy:latest
            restart: unless-stopped
            environment:
                - UDS=1
            volumes:
                - piped-proxy:/app/socket
            container_name: piped-proxy
        piped:
            image: 1337kavin/piped:latest
            restart: unless-stopped
            volumes:
                - ./config/config.properties:/app/config.properties:ro
            depends_on:
                - postgres
            container_name: piped-backend
        nginx:
            image: nginx:mainline-alpine
            restart: unless-stopped
            ports:
                - "8080:80"
            volumes:
                - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
                - ./config/pipedapi.conf:/etc/nginx/conf.d/pipedapi.conf:ro
                - ./config/pipedproxy.conf:/etc/nginx/conf.d/pipedproxy.conf:ro
                - ./config/pipedfrontend.conf:/etc/nginx/conf.d/pipedfrontend.conf:ro
                - ./config/ytproxy.conf:/etc/nginx/snippets/ytproxy.conf:ro
                - piped-proxy:/var/run/ytproxy
            container_name: nginx
            depends_on:
                - piped
                - piped-proxy
                - pipedfrontend
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.piped.rule=Host(`piped-frontend.localdomain`, `piped-backend.localdomain`, `piped-proxy.localdomain`)"
                - "traefik.http.routers.piped.entrypoints=websecure"
                - "traefik.http.services.piped.loadbalancer.server.port=8080"
        postgres:
            image: postgres:15
            restart: unless-stopped
            volumes:
                - ./data/db:/var/lib/postgresql/data
            environment:
                - POSTGRES_DB=piped
                - POSTGRES_USER=piped
                - POSTGRES_PASSWORD=changeme
            container_name: postgres
    #    watchtower:
    #        image: containrrr/watchtower
    #        restart: always
    #        volumes:
    #            - /var/run/docker.sock:/var/run/docker.sock
    #            - /etc/timezone:/etc/timezone:ro
    #        environment:
    #            - WATCHTOWER_CLEANUP=true
    #            - WATCHTOWER_INCLUDE_RESTARTING=true
    #        container_name: watchtower
    #        command: piped-frontend piped-backend piped-proxy varnish nginx postgres watchtower
    volumes:
        piped-proxy: null
    
    
    # nginx container output showing it's receiving the traffic
    root@rpi4:~/Piped-Docker# podman logs nginx 2>&1 | tail -3
    10.89.0.1 - - [17/Oct/2023:07:52:29 +0000] "GET / HTTP/1.0" 200 615 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0" "-"
    2023/10/17 07:52:30 [error] 30#30: *4 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 10.89.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.0", host: "piped.localdomain", referrer: "https://piped.localdomain/"
    10.89.0.1 - - [17/Oct/2023:07:52:30 +0000] "GET /favicon.ico HTTP/1.0" 404 153 "https://piped.localdomain/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0" "-"
    
    
    # my reverse proxy is nginx on the host
    root@rpi4:~/Piped-Docker# systemctl status nginx.service
    ● nginx.service - A high performance web server and a reverse proxy server
        Loaded: loaded (/lib/systemd/system/nginx.service; enabled; preset: enabled)
        Active: active (running) since Tue 2023-10-17 07:52:08 UTC; 10min ago
        Docs: man:nginx(8)
        Process: 5998 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
        Process: 5999 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Main PID: 6000 (nginx)
        Tasks: 5 (limit: 9245)
        Memory: 4.2M
            CPU: 112ms
        CGroup: /system.slice/nginx.service
                ├─6000 "nginx: master process /usr/sbin/nginx -g daemon on; master_process on;"
                ├─6001 "nginx: worker process"
                ├─6002 "nginx: worker process"
                ├─6003 "nginx: worker process"
                └─6004 "nginx: worker process"
    
    Oct 17 07:52:08 rpi4.localdomain systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
    Oct 17 07:52:08 rpi4.localdomain systemd[1]: Started nginx.service - A high performance web server and a reverse proxy server.


![image](https://github.com/TeamPiped/Piped/assets/987449/a2a4e6fc-cb1d-479b-928a-77e14e1e8065)

**Comment by samip5** [comment]
If one sees the default nginx page, you can make the assumption that it's matching to the default virtual host nginx comes with, and either you need to disable it, or fix your vhost definitions.

**Comment by draeath** [comment]
I think you perhaps missed that the connection is going to the NGINX container.

I already verified it is going to the correct virtual host on the proxy NGINX running outside the pod.

**Comment by samip5** [comment]
> I think you perhaps missed that the connection is going through to the NGINX container _within_ the pod.
> 
> I already verified it is going to the correct virtual host on the proxy NGINX running outside the pod, and not the default vhost.

Wdym by pod? Kubernetes Pod?

**Comment by draeath** [comment]
A pod is an association of containers. Docker compose runs pods.

**Comment by Bnyro** [comment]
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.

**Comment by robertgro** [comment]
For local development purposes, it is recommended to follow the guidelines at https://github.com/TeamPiped/Piped#forking-and-contributing and use **[pnpm](https://pnpm.io/installation)** to issue ```pnpm install``` as well as ```pnpm serve``` to run a local development clone. 

You can easily do this with a local clone/fork of this repository in Visual Studio Code on Windows. 

If you encounter an error like ```[[eslint] Delete `CR` [prettier/prettier]]```, add ```rules: {'prettier/prettier': ['error', {endOfLine: 'auto'}]},``` within the end of the scope of the `module.exports` to the _.eslintrc.cjs_ file included and get started.
