### ISSUE TITLE
How to create backup using a script?

### ISSUE THREAD

**Issue by SinTan1729** [TeamPiped/Piped#3035]
Many of the Piped instances seem to go down constantly. I've had to move instances many times due to an instance becoming very unreliable. I can't move my subscriptions, settings etc. if the old instance isn't working.

Is it possible to get the backups using a script? (Well, it's definitely possible, I'm asking if it's reasonable easy.) I can't find anything in the API. The things I want to backup on a daily basis are: subscription list, channel groups, preferences, and playlists.

**Comment by Bnyro** [comment]
You can ask such questions in the Matrix room which is linked in the README, that's not in scope for the project to explain such use cases.
