### ISSUE TITLE
Small List of Enhancements/Features i would like to see Piped.video if possible

### ISSUE THREAD

**Issue by XSpark0** [TeamPiped/Piped#3038]
### Describe the feature

1. Comments: Would like to see option to Sort by Newest and Oldest. (Currently i can only see Top Comments.)

2. Captions: Would like an option in Preferences where i can replace Subtitle's Black Bars with Drop Shadow. (Bring Drop Shadow option that exist in YouTube player to Piped.)

3. Recommendations: Would like to see option to choose to enable showing of Suggested Videos like on YouTube in Preferences > Default Homepage: Recommendations. (Currently Recommendations only show under Video.)

4. Country: Option to quickly Choose Different Countries on Trending Page so i can quickly change Countries to see what is Trending in various Countries without having to go to Preferences page every time.

5. Channels: Add Search option in Channels pages so i can search videos within that Channel just like on YouTube.

### Why would this be useful to add?

It would improve Piped.video for everyone.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please only one add one suggestion per issue as it's very difficult to overview otherwise. (Or create a discussion instead, I'll convert this one to a discussion for now)

**Comment by Bnyro** [comment]
1, 3 and 5 are not possible due to missing NewPipe Extractor support.
