### ISSUE TITLE
How to enable geo restriction checker in docker?

### ISSUE THREAD

**Issue by charonfaustinus** [TeamPiped/Piped#3043]
### Describe your question

I hosted my own piped instance, then I played [this video](https://www.youtube.com/watch?v=1ZHrx5fCkeY) It said "This instance does not have a geo restriction checker set in its configuration" How do I enable that? Or are there any docs about how to set it up?

**Comment by Bnyro** [comment]
Please consult one of our [public chat rooms](https://github.com/TeamPiped/Piped#public-chat-rooms) for help with hosting an instance or general questions concerning how Piped works. We're deprecating the question label in issues.
