### ISSUE TITLE
Let administrators set instance url without having to modify sources

### ISSUE THREAD

**Issue by PureTryOut** [TeamPiped/Piped#3049]
### Describe the feature

Currently if you selfhost an instance you need to replace https://pipedapi.kavin.rocks in the source of the frontend with your own URL. In case of OCI containers this means replacing entrypoint with `ash -c 'sed -i s/pipedapi.kavin.rocks/CUSTOM_URL/g /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'` (where `CUSTOM_URL` is your own url).

It would however be better if the url could be changed via environment variables or some config file. I am personally running Piped using Podman rather than Docker and it seems to handle entrypoints on the command-line differently and I had tons of trouble figuring out why my instance was still proxying through kavin.rocks rather than my own proxy and it was because I failed to properly configure it to use my own backend (so it used pipedapi.kavin.rocks instead). I've managed to now by mounting a new entrypoint in the container and using that instead which just does the same logic as before, but I really shouldn't have to edit the sources in the first place.

### Why would this be useful to add?

No need to hackingly edit the sources anymore when starting up the frontend.

### Additional context

The code seems to suggest there already is a config option for it, https://github.com/TeamPiped/Piped/blob/master/src/main.js#L174, but I don't see where I would set that.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can already set the BACKEND_HOSTNAME env variable in order to do so when using the docker image.

I've updating the docker compose example files and documentation accordingly.
