### ISSUE TITLE
Feed only updates if I visit the channel with fresh videos

### ISSUE THREAD

**Issue by gio-giorgio** [TeamPiped/Piped#3063]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

My feed looked the same since 5 days ago, and it was not updating. I found this weird, so I visited a specific channel that had videos published today. Then, after opening the feed again, the videos from that channel in particular appeared as well. The same thing happened with another channel.

In the official instance, I do not have the same problem.

Thank you.

### To Reproduce

1. Open https://piped.123456.xyz/feed
2. Observe it's not updated since 5 days ago
3. Open a random channel from the subs list
4. Open https://piped.123456.xyz/feed again
5. Now it shows videos from that channel in the feed

### Expected behavior

The feed is not updating

### Browser, and OS with Version.

Firefox 118.0.2, Windows 11

**Comment by FireMasterK** [comment]
Hi, I'm pretty sure your domain has expired!

**Comment by gio-giorgio** [comment]
Apologies for the confusion.

That is a placeholder for my actual domain, which I don't expose it to the internet.

**Comment by FireMasterK** [comment]
Do you expose your Piped API hostname to the internet? That's necessary since feed updates are sent using the pubsubhub. You need to allow the `/webhooks/` path for Google's IPs

**Comment by gio-giorgio** [comment]
I am not following, so far. 

I have all docker containers running with my server, and they all have internet access. I just don't need to expose the ports because I use a VPN, and my domain is just for SSL certificates. I am also using a reverse proxy.

Is there no way of being able to refresh my subs without exposing stuff on the internet? Seems weird.

**Comment by FireMasterK** [comment]
> Is there no way of being able to refresh my subs without exposing stuff on the internet? Seems weird.

Yes, see #707 for more info. This is a duplicate.
