### ISSUE TITLE
piped.lunar.icu

### ISSUE THREAD

**Issue by shakasan** [TeamPiped/Piped#3064]
### Describe your question

Hello,

As I'm really new to Libretube/piped, maybe I'm wrong with this issue, sorry if it's the case.

I made several tests de 3 last days to discover Piped and I ended to choose lunar.icu

But through my tests, I figure out that if I create an account (on lunar.icu instance) and login to it on libretube (android), I can't login with the same credentials on piped.lunar.icu. Even more strange, I have been able to login 1 time on piped.lunar.icu and after that, can't anymore. And Logout/Login still work on Libretube.

And the opposite is happening as well.
If I create an account on piped.lunar.icu, I can't login on libretube (android).

But the same as described above with kavin.rocks instance work properly.

And I'm using bitwarden password manager in all cases, so no human error at this level, as I everytime deleted account for after a test and thus using the same credentials.

Is there something I missed in the process ?
Or an issue with lunar.icu instance ?

Thanks for the help/clarification.

And thanks for this great app :)

**Comment by FireMasterK** [comment]
Hello, while using Piped on the web, you're recommended to only use `piped.video`, IPFS or the mirrors at https://github.com/TeamPiped/Piped#mirrors. You can switch instances from the preferences menu. Anything else you use is at your own risk as we don't monitor frontend to see if they're misconfigured or malicious in nature. In this case, it looks like the instance's frontend is misconfigured to use `kavin.rocks`.

**Comment by shakasan** [comment]
Ok, thanks for your help, I made it works as expected.
