### ISSUE TITLE
Feature request: Hide seen videos in Feed 

### ISSUE THREAD

**Issue by igorkulman** [TeamPiped/Piped#307]
It would be great to have an option to hide all the already seen videos in the Feed. Invidious offers this option for example.

**Comment by BirdInFire** [comment]
@igorkulman @FireMasterK, can with this one, reduce luminosity on already viewed video option, like that we see all video and can differentiate easily already viewed video.

**Comment by Bnyro** [comment]
closing in favor of #1329
