### ISSUE TITLE
Backend: NullPointers when trying to import playlist

### ISSUE THREAD

**Issue by samip5** [TeamPiped/Piped#3079]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

It seems that playlist import doesn't appear to work with the route `/user/playlists/create`

### To Reproduce

1. Export your already existing playlist from YouTube via Google Takeout
2. Notice that it may be in different language than English
3. See that the import fails with a ERROR 500 and NullPointer in backend logs

### Expected behavior

I would have expected it to have imported my playlist.

### Logs/Errors

```
An error occoured in the path: /user/playlists/add
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.textValue()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
        at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$46(ServerLauncher.java:415)
        at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
        at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:249)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

### Browser, and OS with Version.

Not applicable

**Comment by Facni** [comment]
I have the same problem

**Comment by abuturabofficial** [comment]
I had the same problem, manually added the playlists, now `export to jason` button for playlists not working (it worked once). I think I should open a new issue.

**Comment by Facni** [comment]
#2866

**Comment by FireMasterK** [comment]
Is there an example playlist file that could be shared?

**Comment by Facni** [comment]
[Animación-vídeos.csv](https://github.com/TeamPiped/Piped/files/13222372/Animacion-videos.csv)

**Comment by klamares** [comment]
I'm having the same problem here, but it's a little different. 

When I try to "Restore Preferences" then the import section is broken and when I go to the "Feed" section there is a box that says "Do you want to delete the playlist" (not sure if it's totally accurate traduction).
![Screenshot 2023-12-01 at 22-24-26 Piped](https://github.com/TeamPiped/Piped/assets/152656777/2835407e-3eef-4574-8e21-b723ca1f71d8)

 And I can only press on "Yes" and when I did it, I have an error.
![Screenshot from 2023-12-01 22-25-14](https://github.com/TeamPiped/Piped/assets/152656777/d0019cde-5681-4dfd-a076-3bf56f3933d9)

I hope this will help.

**Comment by kmoschcau** [comment]
I just had the same problem and after some digging it looks like the front-end sends an empty JSON object to the back-end, although the back-end expects a name property. I will look around a bit more, see if I find anything.

**Comment by kmoschcau** [comment]
As a workaround for Takeout playlists, you can add this to the beginning of the CSV:
```csv

,,,,<playlist name>


<rest of the original file>
```

**Comment by samip5** [comment]
Thanks, that workaround did the trick for now.

The blank lines are indeed needed as well.
