### ISSUE TITLE
Picture in Picture disappear on next video

### ISSUE THREAD

**Issue by jcubic** [TeamPiped/Piped#308]
I've used the Picture in Picture feature, it works nice but when the next video shows up the video was all black. I need to stop and run again.

Also when Picture in Picture runs correctly the main video is disabled. But after the video changed I got the main video playing.

Another issue it that when Picture in Picture is running you can click on another video and you have two videos playing at once.

System: Fedora GNU/Linux XFce Google Chrome

**Comment by FireMasterK** [comment]
This will be fixed in next shaka-player release. (When the video changes, the pip window will be removed.)

**Comment by FireMasterK** [comment]
This has been fixed a while ago.
