### ISSUE TITLE
new instance 

### ISSUE THREAD

**Issue by Ry3nlNaToR** [TeamPiped/Piped#3081]
Hi, I currently running a private instance but want to take it public.

Its hosted in the UK running at OVH, its behind Cloudflare for frontend/api/Image-proxy videos are steam directly from the server without CF

The address are:
FRONTEND_URL: https://piped.game.yt
API_URL: https://piped-api.game.yt
IMAGE_PROXY_PART: https://piped-proxy.game.yt
PROXY_PART: https://piped-videoproxy.game.yt

Ryan

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!

**Comment by Ry3nlNaToR** [comment]
Hi,  The instance will be getting migrated to a new server in the next 24/48 hours, the country where the server is hosted will now be DE, ideally I preferred to keep the same country but the estimated monthly bandwidth usage according to bandwidth monitor made it problematic to find a other provider where hosting it would be cost effective.

The reason of the move the current VM is suffering performance issues especially IO, iowait is average over 20% plus the backend is suffering from OutOfMemoryError I know I can allocate the backend more memory to hopefully resolve that issue but the current VM is limited on memory.

Sorry for any inconvenience caused.

Ryan

**Comment by Bnyro** [comment]
Okay, thanks for the info.

Just let me know when the migration is done and I'll update the country in the instance list.

**Comment by Ry3nlNaToR** [comment]
> Okay, thanks for the info.
> 
> Just let me know when the migration is done and I'll update the country in the instance list.

Will do, I deleted my last reply was going to resend it quoting you're last reply so you get notified but that seem to be unnecessary 😀.

**Comment by Bnyro** [comment]
I'm automatically being pinged on every comment once I've interacted with the issue myself at least once (e.g. writing a comment, closing it, etc).

**Comment by Ry3nlNaToR** [comment]
Hi, Its been moved, it took a bit longer than planned run into a few issues but working fine now,

**Comment by Ry3nlNaToR** [comment]
Hi, the instance no longer use a cdn since I've disabled CF for the domain so can you remove the cdn flag for this instance.

Thank Ryan.

**Comment by Bnyro** [comment]
Done, thanks for the update.

**Comment by Ry3nlNaToR** [comment]
Hi, due to change of circumstances in my personal life, the instance piped is no longer active, can you remove it from the list.

Ryan
