### ISSUE TITLE
Piped vedio share url didn't carry meta data.

### ISSUE THREAD

**Issue by KSinghPro** [TeamPiped/Piped#3082]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Here is an piped vedio share url,
![Screenshot_2023-10-28_231243](https://github.com/TeamPiped/Piped/assets/96082996/b5acf98d-590a-4d42-b7ab-d1ffc3421fd5)
As you can see it didn't carry any vedio meta data.
Here is an invidious video share url
![Screenshot_2023-10-28_231449](https://github.com/TeamPiped/Piped/assets/96082996/cf143b39-cc0d-4b02-ad37-b3a4d35e87ea)
As you can see it carry's vedio meta data.

### To Reproduce

Go to piped.video
Share a vedio url
When shared it didn't carry's any video meta data .
As shown in above screenshot.

### Expected behavior

When shared, it should show vedio meta data just like how invidious does it.
As shown in the screenshot above.

### Logs/Errors

N/A

### Browser, and OS with Version.

All

**Comment by n-ce** [comment]
I think this is due to the fact that Invidious pages are server-side rendered and the server provides necessary opengraph data for those snapshots, while I am not sure but i think piped is client-side rendered so it does not has this ability.

**Comment by Bnyro** [comment]
#1362
