### ISSUE TITLE
You can't click on GitHub icon on search page

### ISSUE THREAD

**Issue by jcubic** [TeamPiped/Piped#309]
On the search page, there is an infinite scroll and you have a footer that is no accessible. On order to click on GitHub to create this issue I've had to open dev tools since the link is not present in HTML source code.

**Comment by FireMasterK** [comment]
What would the solution for this even be?

I really don't want to move it to the top..

**Comment by jcubic** [comment]
I think that top is the only option. But those are just two icons. They don't take up much space.

**Comment by jcubic** [comment]
The other idea is to use position: fixed on left or right but top is much better idea.
