### ISSUE TITLE
Feed does not update subscribed videos

### ISSUE THREAD

**Issue by manuelkamp** [TeamPiped/Piped#3094]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When i log in on my self hosted piped instance, the feed is now over 24 hours old and it does not get updated with new videos from channels i subscribed. it worked fine before, nothing has changed (server is up and running for 23 days since last restart). If i go to a channel, which has a newer video, which is currently not in my feed, i can see it. after I go back to my feed, this video(s) from the channel i went to before are then added in the feed.

### To Reproduce

open local piped instance and log in.
go to feed and find out it is outdated.

### Expected behavior

feed shows new videos from subscribed channels as it did 24 hours ago.

### Browser, and OS with Version.

edge, firefox, lg smart tv

**Comment by manuelkamp** [comment]
Issue was I deployed geoblock on my reverseproxy. Adding an exception for the two backend subdomains (and only having geoblock active for the frontend) resolved it.

**Comment by cpressland** [comment]
@manuelkamp I'm also seeing this behaviour and mine is a fresh instance without any geoblocking stuff. Are you sure modifying this didn't restart Piped causing the issue to resolve itself?

**Comment by cpressland** [comment]
Sorry @manuelkamp it looks like I've just misunderstood something fundamental, #707

**Comment by manuelkamp** [comment]
Geoblock is running on my reverse proxy server (LXC). I did not touch the LXC with Piped to resolve my issue. It cannot be restarted, since it does not know anything about my reverseproxy LXC... your issue is another one and not related to mine

**Comment by manuelkamp** [comment]
maybe look out for lines like this in your reverse proxy, this lead me to my problem (they had status 451, which is the status my reverse proxy returns for geoblocked IPs.
`74.125.209.8 - - [02/Nov/2023:00:00:28 +0100] "POST /webhooks/pubsub HTTP/1.1" 204 0 "-" "FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)"`
