### ISSUE TITLE
Support autotranslated captions

### ISSUE THREAD

**Issue by Facni** [TeamPiped/Piped#3097]
### Describe the feature

Add support for the youtube's autotranslated captions.
see: https://github.com/TeamNewPipe/NewPipeExtractor/issues/977
https://github.com/TeamNewPipe/NewPipeExtractor/commit/efce384d9bbf66737c89bb9a4c2cff82c280aabe

### Why would this be useful to add?

Piped captions can't be translated using a web browse so It would be great  support captions translation for people who don't understand the captions language.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Facni** [comment]
There seems to be already implemented in newpipeextractor
see: https://github.com/TeamNewPipe/NewPipeExtractor/issues/977
https://github.com/TeamNewPipe/NewPipeExtractor/commit/efce384d9bbf66737c89bb9a4c2cff82c280aabe

**Comment by Bnyro** [comment]
They are supported, they are just not shown as auto-generated.
