### ISSUE TITLE
Set Quality on iOS

### ISSUE THREAD

**Issue by vanitysys28** [TeamPiped/Piped#310]
Was checking, and only saw a mean to change quality of video in the preferences, but it doesn't seem to be applied to the playback. Is there any browser to use in order to do that change or it's not an option on iOS as of now?

**Comment by FireMasterK** [comment]
Well, you're in bad luck since the only reason you don't have a quality selector is that DASH won't work due to iOS(/Apple) not supporting MSE extensions.
