### ISSUE TITLE
Use defined Docker network

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#3133]
### Describe the feature

Please use the network range defined in Docker

### Why would this be useful to add?

Networks such as 172.16.0.0/12 or 10.0.0.0/8 are used for large networks and therefore usually also for VPN connections. 

For local communications within a private network, there is the address range 192.168.0.0/16.

I have configured my Docker installation like this. However, after restarting Docker and rebuilding the piped container, piped still uses 172.18.0.0/16.

### Additional context

The Docker project itself has a problem with network topology. For whatever reason, 172.17/16 is used as the default network.
The correct subnet for this use case would be 192.168/16. Anyway.
 
At some point docker people realised that the use of addresses in 172.17/12 causes problems with company networks or a VPN to another network. For this reason, Docker allows to define the subnet to be used.

This can be defined in `/etc/docker/daemon.json`, for example:
```
{
	"live-restore": true,
	"bip": "192.168.7.1/24",
	"default-address-pools": [{
		"base": "192.168.7.0/24",
		"size": 24
	}]
}
```
It would be great if piped could use the defined network.

Maybe it also works by modifying the `docker-compose.yml`.  However, I assume that the individual containers use hard-coded addresses and therefore the containers are also statically configured.

Thanks for help and possible solution :-)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FireMasterK** [comment]
Hi, the docker-compose files does not define a network, and hence shouldn't it use what you've configured in your daemon?

https://github.com/TeamPiped/Piped-Docker/blob/main/template/docker-compose.nginx.yml
https://github.com/TeamPiped/Piped-Docker/blob/main/template/docker-compose.caddy.yml
