### ISSUE TITLE
Fallback instances list

### ISSUE THREAD

**Issue by Dunexus** [TeamPiped/Piped#3138]
### Describe the feature

Allow selecting an ordered list of instances. If one throws an error, try the next automatically in the background.

### Why would this be useful to add?

By selecting multiple instances, it adds redundancy and user face error less often.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by SebiTalent04** [comment]
The extension Libredirect does exactly that.

**Comment by SollyBunny** [comment]
> The extension Libredirect does exactly that.
@SebiTalent04 

If you're talking about this [libredirect](https://libredirect.github.io/), I'm not sure how you mean.

If I understand the problem correctly, that instances fall over, it would be nice to have a fallback list so you dont have to go to preferences

For me, all but the "official" instance have horrible uptime, with the official one having bad latency, if this were to be implemented it would also be nice to, if it's taking +5s to load a video, to attempt a different instance at the same time.

**Comment by n-ce** [comment]
Yes, I have also implemented this in my player for error casss. However for the 'loading too long' part was very difficult for me to implement I tried many tricks but eventually had to remove auto switching for slow loading. The main reason because there is no stable way to tell if it's the instance that is slow or the user's network being slow or just the server warming up.

**Comment by SecularSteve** [comment]
> The extension Libredirect does exactly that.

I'm pretty sure he means something among the terms of "built-in" and "automatic".

I'd personally love to have a built-in meta-solution that switches known instances every 10 seconds in case of errors.

Probably ping-dependent.

**Comment by Bnyro** [comment]
That's out of scope for the project, Piped is meant to be used per instance due to the fact that user data like subscriptions and playlists are stored on those.

For other use cases external addons like LibRedirect should be the ones cycling between different instances.

**Comment by Dunexus** [comment]
> Piped is meant to be used per instance

Piped frontend and other frontends such as LibreTube allow to choose a different instance for authentication.
Some instance even have registration disabled and are only meant to provide video playback.

Of course, instances for authentication are **not** interchangeable as there is no federation of accounts but instances for retrieving videos and medata are. Being able to cycle between different instances based on the liveness of the current instance could help reducing errors to the end user.
