### ISSUE TITLE
Can't create playlist

### ISSUE THREAD

**Issue by burtek** [TeamPiped/Piped#3142]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Can't create playlist. Doesn't work in /playlists and within 'add to playlist' > 'create playlist' modal.

### To Reproduce

1. Go to https://piped.video/playlists
2. Click Create Playlist
3. Enter anything in the name field and click OK

### Expected behavior

Playlist should be created and should appear on the screen. It should also appear in the 'add to playlist' list

### Logs/Errors

![image](https://github.com/TeamPiped/Piped/assets/2940958/cd187733-2d06-477c-8050-8ab1a7021060)

### Browser, and OS with Version.

FF 119  / LMDE 6

**Comment by FireMasterK** [comment]
Hi, I'm unable to reproduce this issue. It was likely caused by a temporary outage. Please let me know if you still face this issue, and I'll reopen the issue.

**Comment by burtek** [comment]
Yeah, it works now
