### ISSUE TITLE
Feature Request : Add Filter to Feeds for Sorting

### ISSUE THREAD

**Issue by FrozenVertx** [TeamPiped/Piped#315]
Hi,
As shown in title I want to request to filter main feed, As of now it's a little bit messy New videos on top and old below. I don't have problem with that but a little bit sorting is good if available. For Example, Make a filter to sort feed content according to Recent,Channel,Popular etc. If i choose to channel filter then Channel Name must be appear as heading  and its videos is in inner area something like tree view. Its really handy if you want any particular channel updates.

If implementation is not possible then leave it, its just a request.

**Comment by FireMasterK** [comment]
Note: I was too lazy to create a tree view
