### ISSUE TITLE
Access Front End Via Tailscale

### ISSUE THREAD

**Issue by the-arkhive** [TeamPiped/Piped#3153]
### Describe the feature

I don’t know if this is really a bug, a missing feature, or I’m stupid. Maybe all 3. I host a few services on my home network and I use Tailscale to access them remotely. I wanted to do the same with Piped. I followed the docker self host instructions, and I have all green check marks when I run everything in docker. I can see nginx is running because I can visit port 8080 from a browser, using both localhost and the machines Tailscale address on another machine. I get the generic “Welcome to nginx” screen, but I cannot figure out how to actually access the Piped front end. The address I defined when setting up Piped does not work, both on the local machine and via my tail net. I don’t expect it to work over Tailscale, but I feel like there should be a way for me to access it. This is a case of simply having to put the right combination of address and port in or do I need some sort of special configuration to get Piped serving over Tailscale??

### Why would this be useful to add?

Access my instance remotely without exposing any ports or traffic to The Internet

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Please get in touch for support via one of https://github.com/TeamPiped/Piped#public-chat-roomscommunities, the issue tracker is not meant to be used for support when self-hosting.
