### ISSUE TITLE
Bug: Missing comments section under videos

### ISSUE THREAD

**Issue by MacCZ** [TeamPiped/Piped#316]
Hello, 

I've currently noticed that the comments section below the videos is missing. Is this a bug or is it a temporary error?
Also, is there any plan to modify the look of the comments for mobile devices so that the user doesn't have to scroll all the way down for comments?

**Comment by FireMasterK** [comment]
See: https://github.com/TeamNewPipe/NewPipeExtractor/issues/688

**Comment by r-a-y** [comment]
> Also, is there any plan to modify the look of the comments for mobile devices so that the user doesn't have to scroll all the way down for comments?

Yeah, I think comments should be listed before related videos on mobile. Or the ability to easily collapse related videos would be a suitable workaround.

**Comment by FireMasterK** [comment]
Fixed.

> > Also, is there any plan to modify the look of the comments for mobile devices so that the user doesn't have to scroll all the way down for comments?
> 
> Yeah, I think comments should be listed before related videos on mobile. Or the ability to easily collapse related videos would be a suitable workaround.

Create a new issue for this please.
