### ISSUE TITLE
Add metadata to video pages

### ISSUE THREAD

**Issue by moonleay** [TeamPiped/Piped#3161]
### Describe the feature

Make page metadata contain infos about the video.
For example: title, uploader, upload date and (part of) the description.
Currently it just returns 'piped' as the title and 'An alternative privacy-friendly YouTube frontend which is efficient by design.' as description.

### Why would this be useful to add?

This would improve the experience when linking piped form 3rd party sites and they try to fetch, what the link is about.

### Concept(s)

Make the metadata more consistent with the metadata youtube provides.

This is the metadata, which piped provides:
![1700496958_grim](https://github.com/TeamPiped/Piped/assets/74376181/cf3877e0-0810-4d92-9abf-4110c70d20f6)
And this is what YouTube provides:
![1700496982_grim](https://github.com/TeamPiped/Piped/assets/74376181/96bc504f-0bd5-4029-b916-e822c81efa0a)

(These screenshots are taken from the Discord Dev tools, since I am not aware of a better way to see the metadata of websites currenty)

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
#1362
