### ISSUE TITLE
Search Bar is duplicated

### ISSUE THREAD

**Issue by Facni** [TeamPiped/Piped#3167]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

![image](https://github.com/TeamPiped/Piped/assets/112446096/65855e8b-3cf9-4770-a4cd-15f615abea46)
The search bar is under piped logo too.

### To Reproduce

1. Open Piped.video
2. Then see it

### Expected behavior

Show just one search bar

### Browser, and OS with Version.

Firefox 121 Endeavouros.

**Comment by FireMasterK** [comment]
It seems like this is a regression from #3165
