### ISSUE TITLE
+18 Videos aren't working anymore

### ISSUE THREAD

**Issue by warnerbryce** [TeamPiped/Piped#317]
With the last Piped version i can't watch +18 Videos.

I got a java.lang.NullPointerException and no logs in my server

Here is a link to a +18 video : /watch?v=-or4WhpXx_k

**Comment by Metz-2** [comment]
Can confirm. e.g. can not watch e.g. this: /watch?v=JRiLk9qw59Y
only get `java.lang.NullPointerException`

**Comment by FireMasterK** [comment]
Fixed in https://github.com/TeamPiped/Piped-Backend/commit/b29ba8aa76af72408d8d4b265c5e3099f06a417b.

Fix will be deployed on the official server in a few minutes.
