### ISSUE TITLE
Search functionality not working

### ISSUE THREAD

**Issue by hugoghx** [TeamPiped/Piped#3175]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

After updating PipedBackend in my stack, the search functionality stopped working. In the UI, you get an endless spinner. The reason is that the search response contains no items now. See example response:

curl 'https://pipedapi.kavin.rocks/search?q=test&filter=all'

```json
{
    "items": [],
    "nextpage": "{\"url\":\"https://www.youtube.com/youtubei/v1/search?key=xxxxxxxxxx&prettyPrint=false\",\"id\":\"xxxxxxx\",\"ids\":null,\"cookies\":null,\"body\":null}",
    "suggestion": "",
    "corrected": false
}
```

### To Reproduce

1. Open official instance.
2. Use the search functionality to search for anything

### Expected behavior

Search results show up

### Browser, and OS with Version.

Win11 10.0.22621 Build 22621, Chromium-based browser

**Comment by FireMasterK** [comment]
Closing this with https://github.com/TeamPiped/Piped-Backend/pull/739
