### ISSUE TITLE
Put the current timestamp in the URL

### ISSUE THREAD

**Issue by bosc0** [TeamPiped/Piped#3188]
### Describe the feature

Automatically update the URL to the timestamp of the media's current time. This enables later resuming of audio/video playback without logging in or by utilizing local storage. 

### Why would this be useful to add?

This feature is particularly useful to resume playback when consuming long music sets, podcasts, talks, lectures, or live streams. 

### Concept(s)

This Firefox extension offers said functionality and could be used as inspiration: https://github.com/nkestrel/mediaurltimestamper 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by anewuser** [comment]
Hi. You just need click on the `Share` button and then right-click on the URL with the current timestamp to bookmark it:

![timestamp](https://github.com/TeamPiped/Piped/assets/6733770/a100c242-6789-410e-8c6b-0b57aa878f0c)
