### ISSUE TITLE
RSS Feeds

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#321]
It would be great to have a RSS Feed for Piped **but the Content should be played on the Player created by Piped** instead of the YouTube Player which **invidious does** with Description and Still with SponsorBlock API.

If not possible, How about creating a Private News Feed instead of feeds for Individual channels with SponsorBlock API as GitHub does ?

**Comment by FireMasterK** [comment]
Have you tried clicking on the rss icon on the feed page? That feed should open it as an Piped page.

**Comment by Loki-L1130** [comment]
There is no Feed icon as far as I noticed. And When trying to find for such feed using my [RSS Feed Reader extension](https://addons.mozilla.org/en-GB/firefox/addon/rss-reader-extension-inoreader/). It shows No Feeds Found

**Comment by FireMasterK** [comment]
![Screenshot_20210728-153022_Bromite~2.png](https://user-images.githubusercontent.com/20838718/127303978-bc465ed3-402f-48e7-980e-c716910ec9e8.png)

**Comment by Loki-L1130** [comment]
Was it available as Per Channel wise without having an User Account

**Comment by FireMasterK** [comment]
No, there never was and never will be. Please use youtube's rss feed and an extension to redirect URLs to Piped. I'm not looking forward for Piped to be hammered with RSS requests.

**Comment by Loki-L1130** [comment]
Okay, If so then using RSS Feed from Piped Account will Play content in the Piped Player or will it redirect to the Website ?

If using the RSS Feed in Mobile will it bring the thing to Apps such as NewPipe App, YouTube App or Piped Website ?

**Comment by FireMasterK** [comment]
> Okay, If so then using RSS Feed from Piped Account will Play content in the Piped Player or will it redirect to the Website ?

It will take you to Piped's website, where you can watch the video.

> If using the RSS Feed in Mobile will it bring the thing to Apps such as NewPipe App, YouTube App or Piped Website ?

You can choose between NewPipe and a Browser. Obviously, the YouTube app wouldn't be an option as this would be a Piped link.

**Comment by Loki-L1130** [comment]
> It will take you to Piped's website, where you can watch the video.

Why not play it within the RSS Reader itself ?

> You can choose between NewPipe and a Browser. Obviously, the YouTube app wouldn't be an option as this would be a Piped link.

Does it applied for YouTube Vanced & will it in open in YouTube ++ for iOS installed via IPA File ?

**Comment by FireMasterK** [comment]
> Why not play it within the RSS Reader itself ?

That would lead to a sub-par experience and would require extracting 100s of videos every time the feed is generated.

> Does it applied for YouTube Vanced & will it in open in YouTube ++ for iOS installed via IPA File ?

I have no idea.

**Comment by Loki-L1130** [comment]
Okay, Will Piped link open in FreeTube for Destop Directly like MAgnet Links in respective Torrent Downloadin Applications or https://t.me to Telegram App ?

In Short, Piped Link --->>FreeTube App installed on Desktop

**Comment by FireMasterK** [comment]
Do you mean you want a button to open in FreeTube?

**Comment by Loki-L1130** [comment]
Yes, I do mean that. Is it possible to do so far. Was there a Firefox Extension to do so.

**Comment by Duckbilled** [comment]
I tried to add the rss link in my account's feed, but it seems not to work as there is no feed to be found. Am I doing something wrong?

**Comment by Loki-L1130** [comment]
@Duckbilled Piped, Will only show you the RSS Feed with Piped as Title and URL as Hyperlink in the Title because the @FireMasterK do not want the server to be overloaded with RSS.

If you use RSS Feed on PC, Then use YouTube Feeds and use Piped Redirects Extension to replace the YouTube Player with Piped or use Invidious Feeds and use the Extension it will replace the Invidious Player with Piped.

**Comment by FireMasterK** [comment]
You're expected to use the URL which goes like: https://pipedapi.kavin.rocks/feed/rss?authToken=REDACTED.

**Comment by Duckbilled** [comment]
Hmm strange, that is the one I used (just tried again), but doesn’t seem to work. Does it have something to do with freshrss?

tried in both netnewswire (desktop and ios app) and the freshrss website.
