### ISSUE TITLE
(Chromium) Account creation does not autosave passwords

### ISSUE THREAD

**Issue by alpenamilch** [TeamPiped/Piped#3214]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When account is registered it does not autosave (or the browser does not prompt).

Tested: Chromium  119.0.6045.199 (linux)

### To Reproduce

- https://piped.video/register
- Supply username password
- Register

### Expected behavior

Chromium prompts (Offer to save passwords)

### Browser, and OS with Version.

Chromium  119.0.6045.199 ( ubuntu linux)

**Comment by Bnyro** [comment]
This is not reproducible, tested with `chromium-124.0.6367.60` - probably an issue with your browser installation.
