### ISSUE TITLE
Captions Unavailable

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#322]
Captions are unavailable for any videos in Piped and the option is also not available in Preferences, While captions are still available in YouTube.

**Comment by FireMasterK** [comment]
You find captions in the 3 dots on the player.

I could not replicate this on https://piped.kavin.rocks/watch?v=qTrfMHaI3Dk

**Comment by Loki-L1130** [comment]
But it is not available if you play the Video from Trending or from Search.

**Comment by FireMasterK** [comment]
Can you give an example video URL?

**Comment by Loki-L1130** [comment]
https://piped.kavin.rocks/watch?v=UPy1JvCzdyI & https://www.youtube.com/watch?v=UPy1JvCzdyI

**Comment by FireMasterK** [comment]
Closing this as this issue no longer happens :)
