### ISSUE TITLE
Comment continuation requires scrolling to end of page

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#324]
This is because the comments section occupies the entire width.

**Comment by MacCZ** [comment]
There should be easy solution. For example creating button like this - 
![DCD7A01D-92EC-4AE6-A887-37ED5766D5E3](https://user-images.githubusercontent.com/50764475/127620450-3e1652bc-d9f3-4ad6-aad6-badf0fb18050.jpeg)

**Comment by FireMasterK** [comment]
That's not the issue here, this only affects desktops.
