### ISSUE TITLE
No Instances available.

### ISSUE THREAD

**Issue by Facni** [TeamPiped/Piped#3240]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

There are no Instances in the preference page
![image](https://github.com/TeamPiped/Piped/assets/112446096/a5581f5b-c0a0-43a0-834c-c082980bb134)

### To Reproduce

1. Open a Piped instance like piped.video
2. Go to preference
3. See

### Expected behavior

Be able to change between instances

### Browser, and OS with Version.

Firefox 122.0a1 endevouros
Firefox 121 Android 11

**Comment by BlackLight** [comment]
I can confirm that this behaviour also occurs on my instance - at least since yesterday.

**Comment by MLGamer011** [comment]
Currently mine is not working as well, I am on chrome though so idk if it has been fixed for chrome yet.

**Comment by FireMasterK** [comment]
This was caused by one of my servers getting broken, I had to reinstall it from scratch: https://github.com/TeamPiped/instances-api/issues/67#issuecomment-1852783528

It should be back now! :)
