### ISSUE TITLE
IPv6 address rotation

### ISSUE THREAD

**Issue by codenyte** [TeamPiped/Piped#3242]
### Describe the feature

A documentation page on [docs.piped.video](https://docs.piped.video/) explaining how to set up Piped with IPv6 address rotation to avoid YouTube IP address blacklisting

### Why would this be useful to add?

YouTube tries to ban all IP addresses of all Piped instances so they can force users to use the official website/app. IP rotation would avoid IP blocking and make Piped much more reliable. That would significantly improve the user experience. Good and reliable privacy front-ends like Piped are needed, especially now that Google wants to force everyone to watch their crappy ads. When I recommend Piped to other people, I often get complaints because [videos aren't loading](https://github.com/TeamPiped/Piped/issues/2809) and the experience is bad, as mentioned before, IP rotation would address this issue.

### Concept(s)

- Invidious has a guide that explains how to set this up: https://docs.invidious.io/ipv6-rotator/
Piped should add something similar to their documentation.

- Create a fork [Invidious' IPv6 rotator](https://github.com/iv-org/smart-ipv6-rotator) and adapt it to work with Piped

- The [Piped instances API](https://github.com/TeamPiped/instances-api) should also indicate whether an instance has IPv6 rotation enabled or not

- Make IPv6 rotation a part of the install guide (if applicable for the instance)

### Additional context

Btw, I love Piped. You guys are doing great work!

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by FarisZR** [comment]
Also, a way to force piped to use IPv6 would be great.
As I noticed that Piped seems to always use IPv4, even when the container has IPv6 connectivity.

**Comment by Deon-Trevor** [comment]
> How did you set this up initially? Did you use the [Invidious smart-ipv6-rotator](https://github.com/iv-org/smart-ipv6-rotator)?

Yes, had used the [Invidious smart-ipv6-rotator](https://github.com/iv-org/smart-ipv6-rotator), [Cloudflare Proxy](https://developers.cloudflare.com/dns/manage-dns-records/reference/proxied-dns-records/) and [CDN](https://www.cloudflare.com/en-gb/application-services/products/cdn/) ONLY.
