### ISSUE TITLE
Comment replies are not visible

### ISSUE THREAD

**Issue by Mhowser** [TeamPiped/Piped#326]
Replies to comments are not visible currently. Can you add this feature, please?

**Comment by FireMasterK** [comment]
We'd have to wait for https://github.com/TeamNewPipe/NewPipeExtractor/pull/576 to get merged, and before this the comments fix for NewPipe.

**Comment by FireMasterK** [comment]
Now, we require just changes in the frontend here to get this implemented.

**Comment by Mhowser** [comment]
Great! Is there an issue where we can track that?

**Comment by Mhowser** [comment]
Ah, I thought you were referring to the UI v2 changes, oops lol.

**Comment by FireMasterK** [comment]
Closing with 8ea56aa0b9de5344217038006127c91f10a432ac.
