### ISSUE TITLE
Minimize Description by Default

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#328]
It would be great, If Description for Videos is minimized by Default because when scrolling to look for Comments. It makes and takes a Long Scroll which is a little annoying.

**Comment by Loki-L1130** [comment]
@FireMasterK You just closed this issue. But I am not a Front-End Developer & what do I get from the [Commit](https://github.com/TeamPiped/Piped/commit/96950e61e78484847fab13e006c9df66eccf851a) is that you Descriptions for Videos is minimized by Default. Am I getting it Right ?

**Comment by FireMasterK** [comment]
No, you have an option to get this behaviour as a preference. 
![Screenshot_20210730-160154_Bromite~2.png](https://user-images.githubusercontent.com/20838718/127640640-ac9f0bd4-f783-41f8-9e4f-b800f8bb27b0.png)
