### ISSUE TITLE
New instance: piped.nezumi.party

### ISSUE THREAD

**Issue by argrat** [TeamPiped/Piped#3283]
### Api Url

https://pipedapi.nezumi.party

### Instance location

Italy,🇮🇹

### CDN (not required)

- [ ] My instance does use a CDN.

### Instance owner

- [X] I am the owner of the instance.

### Other details

- Frontend: piped.nezumi.party
- API: pipedapi.nezumi.party
- Proxy: pipedproxy.nezumi.party

**Comment by FireMasterK** [comment]
Your instance has been added to the list, thank you for hosting an instance!

**Comment by argo-v5** [comment]
This instance is not running anymore, you may remove it from the list
