### ISSUE TITLE
A download video button

### ISSUE THREAD

**Issue by epicgamermanns** [TeamPiped/Piped#3289]
### Describe the feature

A button to download a video

### Why would this be useful to add?

it would allow people to watch videos offline

### Concept(s)

idk

### Additional context

idk

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Duplicate of #616
