### ISSUE TITLE
Login results in `525: No Reason Phrase` or `502: Bad Gateway` error

### ISSUE THREAD

**Issue by guemax** [TeamPiped/Piped#3293]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I am trying do login on the official Piped instance with my account. After entering my username and password and clicking on the "Login" button, nothing happens.

### To Reproduce

1. Open https://piped.video/login
2. Enter your username and password
3. Click the "Login" button

### Expected behavior

You should get logged in and get redirected to the trending/feed page.

### Logs/Errors

```
XHRPOST
https://pipedapi.kavin.rocks/login
[HTTP/2 502 Bad Gateway 168ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pipedapi.kavin.rocks/login. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

### Browser, and OS with Version.

LibreWolf 116.0.2 on NixOS
Firefox 116.0.3 on NixOS
Brave 1.61.109 on Windows 11

### Additional context

When already being logged in, the feed page keeps loading, and the console shows a `525` response as well. Sometimes I get an `502` instead of `525` when trying to log in.

**Comment by Facni** [comment]
Same
Firefox Nightly 123.0a1 on EndeavourOS
Firefox 121 on Android 11

**Comment by Facni** [comment]
It's already working for me.

**Comment by guemax** [comment]
Confirmed, also working on my computer. :+1:  However, it would've been interesting to know what caused this problem...

Nonetheless I'll to close this issue.

**Comment by guemax** [comment]
The issue appeared again, with the same error message. I am therefore unable to login on kavin.rocks.

**Comment by sihma** [comment]
Tried logging in multiple times on the course of one month. Using (Manjaro) Chromium, Firefox, and a simple webkit browser on Android (two different networks) and I just can't login.

Seems like an issue from Cloudflare. Could this issue be opened again?
