### ISSUE TITLE
Performance - As a newcomer what i learned!

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#333]
So finally i managed to do a switch from using kevins api and proxy to my own. And i must say the performance difference is enormous. Feed, Trending as well as videos themselfs loads as fast as they would on youtube. I am very happy with the performance!

If you have any issues with performance with default api, proxy. Try self hosting, its pretty easy to setup and works great.

**Comment by FireMasterK** [comment]
Cool! I just hope you aren't hosting it on a lan :)

**Comment by IvRRimum** [comment]
Nah, i got a server for that

**Comment by IvRRimum** [comment]
:D
