### ISSUE TITLE
The Video time should change as i change playback speed.

### ISSUE THREAD

**Issue by ballszu** [TeamPiped/Piped#3343]
### Describe the feature

I would like to see the video time change as i change the playback speed. 
Like if its a 10 minute video and i set the speed to 2X, the video duration should change to 5 minutes.
(And also should show time left)

### Why would this be useful to add?

This would be useful for many people who want to save time and see how much time they will be saving on changing playback speed.
Personally as a student this will be really helpful 🙏 

### Concept(s)

Similar to how mpv changes time duration automatically 

### Additional context

Thankyou

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Sorry, that's not planned due to the fact that
- the remaining time is handled by the player library
- the current behavior is the canonical one across (almost) all streaming platforms.
