### ISSUE TITLE
The latest version cannot load data / cannot play any video on LibreTube 0.21.1.

### ISSUE THREAD

**Issue by nanedi** [TeamPiped/Piped#3344]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The latest version cannot load data / cannot play any video on LibreTube 0.21.1.

### To Reproduce

The latest version cannot load data / cannot play any video on LibreTube 0.21.1.

![Screenshot_20240117_115712_LibreTube](https://github.com/TeamPiped/Piped/assets/3816371/f40ada2f-601d-4c4a-bec7-4ba87b30de8c)

### Expected behavior

Play a video.

### Browser, and OS with Version.

A14 with LibreTube 0.21.1

**Comment by FireMasterK** [comment]
There haven't been any changes in the backend since a month: https://github.com/TeamPiped/Piped-Backend/commits/master/
I'd first check if your API is responding fine, try requesting the healthcheck endpoint on your instance: https://pipedapi.kavin.rocks/healthcheck

**Comment by nanedi** [comment]
@FireMasterK 

Web player is ok.

YT has also been updated recently.

This is very strange!

Thanks
