### ISSUE TITLE
Its broken

### ISSUE THREAD

**Issue by MRpickle2** [TeamPiped/Piped#3345]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

 Every time i want to watch something it ether wont load the video or it says error code 1003. this has been happening for like the past 3 days. also im stuck in school all the time with no regular youtube. HELP PLS

### To Reproduce

just try to use it .it has been  on    https://sites.google.com/view/pizzalearns/apps/youtube        if you need the link

### Expected behavior

 thought it would keep working but i guess not

### Logs/Errors

it keeps saying error code 1003

### Browser, and OS with Version.

chrome browser and os

### Additional context

I need entertainment please. if you can get to this soon that would be awesome. thank you!

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2915

**Comment by MRpickle2** [comment]
thank you!

**Comment by MRpickle2** [comment]
sorry to bug you again, but it still dosent work. this time it just
wont play for a few seconds and then it slaps me the error code 1003 again

**Comment by MRpickle2** [comment]
oh and it wont load sometimes

**Comment by MRpickle2** [comment]
nevermind its working again. sorry
