### ISSUE TITLE
New instance: piped.ngn.tf

### ISSUE THREAD

**Issue by ngn13** [TeamPiped/Piped#3359]
### Api Url

https://piped.ngn.tf

### Instance location

Turkey,🇹🇷

### CDN (not required)

- [ ] My instance does use a CDN.

### Instance owner

- [X] I am the owner of the instance.

**Comment by Bnyro** [comment]
Added, thanks for hosting an instance!

**Comment by ngn13** [comment]
@Bnyro my instance is now using a CDN

**Comment by ngn13** [comment]
@Bnyro sorry for pinging you again, no longer using a CDN

**Comment by ngn13** [comment]
@Bnyro sorry for pinging you again, my instance will stay down until #3658 gets solved, i can't keep it up because it gets my IP blacklisted, which also breaks my invidious instance

please feel free to remove the instance from the list

**Comment by ngn13** [comment]
@Bnyro
