### ISSUE TITLE
YouTube playlist does not load (video page)

### ISSUE THREAD

**Issue by MAZ01001** [TeamPiped/Piped#3367]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When starting any video from a YouTube playlist, the playlist panel does not show on the page, and when the video is finished, it does not play the next one and ends playback as if there were no playlist.

### To Reproduce

1. Open any playlist page like <https://piped.video/playlist?list=PLTfxJETd3IiArIOQSSYLAsYXui34D1cnW>
2. Choose any video to play
3. Observe that the playlist panel is missing
4. After the video ends, it does not play the next

### Expected behavior

The playlist panel should be visible on the video page.
The next video in the playlist should play after it finishes.

### Logs/Errors

>
> Uncaught TypeError: Cannot read properties of null (reading 'value')
> at o.onsuccess (index-ccwGqChL.js:22:33935)
>

(<https://piped.video/assets/index-ccwGqChL.js>:22)

<details><summary>Stack trace</summary>

|                      |                            |
| -------------------- | -------------------------- |
| o.onsuccess          | @ index-ccwGqChL.js:22     |
| IndexedDB (async)    |                            |
| (anonymous)          | @ index-ccwGqChL.js:22     |
| getLocalPlaylist     | @ index-ccwGqChL.js:22     |
| getPlaylist          | @ index-ccwGqChL.js:22     |
| getPlaylistData      | @ WatchVideo-qMEXsplC.js:1 |
| mounted              | @ WatchVideo-qMEXsplC.js:1 |
| (anonymous)          | @ index-ccwGqChL.js:2      |
| ln                   | @ index-ccwGqChL.js:2      |
| st                   | @ index-ccwGqChL.js:2      |
| t.__weh.t.__weh      | @ index-ccwGqChL.js:2      |
| tf                   | @ index-ccwGqChL.js:2      |
| nf                   | @ index-ccwGqChL.js:2      |
| Promise.then (async) |                            |
| ef                   | @ index-ccwGqChL.js:2      |
| ra                   | @ index-ccwGqChL.js:2      |
| (anonymous)          | @ index-ccwGqChL.js:2      |
| Gi                   | @ index-ccwGqChL.js:1      |
| Cu                   | @ index-ccwGqChL.js:1      |
| Po                   | @ index-ccwGqChL.js:1      |
| set value            | @ index-ccwGqChL.js:1      |
| U                    | @ index-ccwGqChL.js:6      |
| (anonymous)          | @ index-ccwGqChL.js:6      |
| Promise.then (async) |                            |
| q                    | @ index-ccwGqChL.js:6      |
| A                    | @ index-ccwGqChL.js:6      |
| install              | @ index-ccwGqChL.js:6      |
| use                  | @ index-ccwGqChL.js:2      |
| (anonymous)          | @ index-ccwGqChL.js:22     |

</details>

### Browser, and OS with Version.

Google Chrome: 120.0.6099.225 (Official Build) (64-Bit) (cohort: Stable)
Firefox: 122.0 (64-Bit)
on Windows 10

**Comment by FireMasterK** [comment]
Closing this with #3361
