### ISSUE TITLE
Piped doesn't work in Mozilla Firefox 55.0.2 for Android 4.0.4 (Ice Cream Sandwich)

### ISSUE THREAD

**Issue by EgorKuzevanov** [TeamPiped/Piped#3381]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Piped does not work in Mozilla Firefox 55.0.2 (2017) on old Samsung Galaxy S Duos (GT-S7562) smartphone (2012) running Android 4.0.4 (Ice Cream Sandwich)

### To Reproduce

1. I launch Firefox 55.0.2.
2. I enter into the address bar: https://piped.video
3. I get a blank black page.

### Expected behavior

Trends and search bar

### Browser, and OS with Version.

Mozilla Firefox 55.0.2 (2017) on old Samsung Galaxy S Duos (GT-S7562) smartphone (2012) running Android 4.0.4 (Ice Cream Sandwich)

**Comment by Daxy7** [comment]
Javascript has had updates since then, so this is probably unfixable unless they make a legacy version

**Comment by Bnyro** [comment]
Yes, we don't intend to explicitly support old browser versions - obviously they lack a lot of features and are not 100% compatible with VueJS.
