### ISSUE TITLE
Recommendations/related streams broken

### ISSUE THREAD

**Issue by aia80212** [TeamPiped/Piped#3382]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Recommendation section is empty and the API returns empty `relatedStream`

### To Reproduce

1. Open any video, for example, at this URL: https://piped.video/watch?v=eUCm4wKarpQ
2. Observe lack of recommendations
3. Make an API request: https://pipedapi.kavin.rocks/streams/dtp6b76pMak
4. Observe `relatedStreams:    []`

### Expected behavior

API returning a populated list of `relatedStrams` instead of an empty one and piped fronted displaying recommendations for video.

### Browser, and OS with Version.

Not applicable

### Additional context

This problem seems to also affect invidious: https://github.com/iv-org/invidious/issues/4415#issue-2109347282

**Comment by Pamilg8** [comment]
https://github.com/libre-tube/LibreTube/discussions/5580#discussion-6161969

**Comment by aia80212** [comment]
Recommendations are working again. It appears that YouTube has resolved the issue.
