### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by amogusussy** [TeamPiped/Piped#3388]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When I open piped.video in any browser, I get a message saying something along the lines of `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

### To Reproduce

1. Open piped.video
2. Sign in
3. Go to the feed
4. Open dev-tools
5. Look at the the console/network tab

### Expected behavior

Everything should load normally.

### Logs/Errors

    Access to fetch at 'https://pipedapi.kavin.rocks/feed?authToken=AUTHTOKEN' from origin 'https://piped.video' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
    
    GET https://pipedapi.kavin.rocks/feed?authToken=AUTHTOKEN net::ERR_FAILED 504 (Gateway Timeout)

### Browser, and OS with Version.

Librewolf & un-googled-chromium both using flatpak.

**Comment by Bnyro** [comment]
That indicated that the Piped node is down, which should not be reported here but via the Matrix room.

**Comment by amogusussy** [comment]
@Bnyro I think there should be a try/catch statement somewhere that checks for this then.
Right now, it only shows an endless loading gif, which gives the impression that there's something going on in the background, when there isn't.
I think it should just have a piece of text telling the user that the server is likely down.
