### ISSUE TITLE
piped.kavin.rocks API is still down

### ISSUE THREAD

**Issue by Hate9** [TeamPiped/Piped#3389]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

As in https://github.com/TeamPiped/Piped/issues/2803, which is closed for apparently no reason, https://pipedapi.kavin.rocks/ returns a "bad gateway" error.

### To Reproduce

Go to https://pipedapi.kavin.rocks/streams/FbNvIirNaQY, or any other pipedapi.kavin.rocks url.

### Expected behavior

The api returns content normally.

### Browser, and OS with Version.

Firefox 122.0-1, Google Chrome 121.0.6167.85, and Ungoogled Chromium 121.0.6167.85, all on EndeavourOS

**Comment by Bnyro** [comment]
That's not a project issue, please report it with your location via the Matrix room (linked in the README.md).
