### ISSUE TITLE
Quick Instance Switcher Button & How to Unify Accounts

### ISSUE THREAD

**Issue by mohamadali-halwani** [TeamPiped/Piped#3397]
### Describe the feature

A simple button, with one click, allows you to switch to the best working instance (if the current instance isn't working for some reason).

### Why would this be useful to add?

This would save me the hassle of going to preferences everytime an instance stops working. It might not be an issue in the instance itself, but in the ISP that blocks traffic to some domains/servers in some kountries for pholitical reasons.

### Concept(s)

Place it anywhere as long as it's accessible from any page or video.

### Additional context

Is there any news regarding multi-instance sync? or unifying accounts among instances?
Thanks 

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
> A simple button, with one click, allows you to switch to the best working instance (if the current instance isn't working for some reason).
>
Not planned, see https://github.com/libre-tube/LibreTube/issues/4184#issuecomment-1626354789.

> Is there any news regarding multi-instance sync? or unifying accounts among instances?
>
No, and it's never been planned either.
