### ISSUE TITLE
it did it  again

### ISSUE THREAD

**Issue by MRpickle2** [TeamPiped/Piped#3403]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

videos load sometimes but error code 1002 shows up instantly when it does load.

### To Reproduce

https://sites.google.com/view/pizzalearns/apps/youtube its on this website, but try to watch something.

### Expected behavior

For the videos to load and work.

### Logs/Errors

I didn't look

### Browser, and OS with Version.

chrome

### Additional context

Sorry for asking again, but it is down.

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/2915
