### ISSUE TITLE
Filter group dropdown is not working on feed

### ISSUE THREAD

**Issue by khusroohayat** [TeamPiped/Piped#3425]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Filter group dropdown is not working on feed

### To Reproduce

https://piped.video/feed

### Expected behavior

Filter group dropdown should filter videos

### Browser, and OS with Version.

Brave

**Comment by ACR-Jeff** [comment]
I am having the same issue on Firefox, Librewolf and Floorp browsers, The only time the groups seem to be functional is within Subscriptions, Yet this doesn't allow for viewing recent videos, Etc.

**Comment by mastazi** [comment]
I save my channel groups and subscriptions to a private git repo so I can see if there are changes over time. From what I've seen the format of the channel_groups was changed recently. The identifier for the Youtube channel is now a longer string than it was before.
I think whomever implemented that change, forgot the feed screen.
In other parts of the website, filtering by channel groups works, for example in the subscriptions screen it works https://piped.kavin.rocks/subscriptions
