### ISSUE TITLE
Comments showing "Avatar" as user avatar and "null" as text on some videos

### ISSUE THREAD

**Issue by shrugal** [TeamPiped/Piped#3429]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

On some videos the comments all show the text "Avatar" in place of the user avatar, and "null" where the comment text should be. The weird thing is that some video comments work find on my local instance but not on the official one, and some are the other way around. I could also swear that I've seen the same video sometimes showing correct comments and sometimes not, but I'm not sure.

![grafik](https://github.com/TeamPiped/Piped/assets/710525/a0faf8d2-d157-45f0-bb0d-b3216a2429b9)

The comments API request on the video page returns a list of empty comment entries, but when I open the API URL separately it returns the comments correctly (see below).

### To Reproduce

1. Open video URL, e.g. https://piped.video/watch?v=0RZVPiCLRd4
2. Scroll down to comments
3. They show up, but all look like described above

### Expected behavior

Comments should show the correct user avatar and text.

### Logs/Errors

Here's the output from the comments API request (https://pipedapi.kavin.rocks/comments/0RZVPiCLRd4) on the video page and in a separate tab:

https://gist.github.com/shrugal/5b1b48440dc45e329caa14db2ff0a0bc

### Browser, and OS with Version.

Firefox 123.0 on Windows 11

**Comment by shrugal** [comment]
> I could also swear that I've seen the same video sometimes showing correct comments and sometimes not, but I'm not sure.

Just checked the video again, and it does show the correct comments both locally and on the official instance now.

**Comment by Dheatly23** [comment]
I also experience this too. Here's some things that i found:

1. It happens sometimes, very inconsistently. Makes it very hard to debug.
2. It also happens to NewPipe too. So i guess the problem is in NewPipeExtractor.

**Comment by Bnyro** [comment]
Yes, the issue is tracked at https://github.com/TeamNewPipe/NewPipe/issues/10808.

**Comment by ktlknss** [comment]
I have this too. but for most, if not all, videos I want to look at the comment of
