### ISSUE TITLE
Able to see a Youtube user's community tab

### ISSUE THREAD

**Issue by strangersdangers** [TeamPiped/Piped#3436]
### Describe the feature

I would love it if the Piped interface has a feature where you can see the community tab from a Youtube user

### Why would this be useful to add?

This would give the other Piped users to see what a YouTube user is posting on the community tab

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Facni** [comment]
This is duplicated; see Issue #622.
