### ISSUE TITLE
iPad mini screen

### ISSUE THREAD

**Issue by RouterCFW** [TeamPiped/Piped#344]
Hello there is an issue on the iPad mini screen because when you scroll down when the site is in the default 100% zoom the suggested videos are under the description not at the side 
This is what it looks like 

![](https://i.ibb.co/ZJDyq6Z/879-FEEA2-D0-E3-4-C43-AEDE-96-F28083295-D.jpg)

**Comment by vachan-maker** [comment]
Yes, it looks better now. Thanks
