### ISSUE TITLE
Kavin.Rocks Instance gone? (probably not a bug?)

### ISSUE THREAD

**Issue by Nationalgeographic** [TeamPiped/Piped#3442]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

First I was not able to load the feed.
I jused the Kavin.rocks instance to authenticate via piped.video.

It's not a bug, but the instance is missing in the instance list.
https://pipedapi.kavin.rocks/healthcheck says, the instance is okay.

### To Reproduce

Open https://piped.video/preferences
check instance list,
see no instance.

### Expected behavior

The instance should be visible.

### Browser, and OS with Version.

Firefox
Brave
Vivaldi

Fedora 39, Plasma spin.

**Comment by CapitaineHadd0ck** [comment]
The kavin.rocks instance is working great. It is the /feed section that in empty.

**Comment by Nationalgeographic** [comment]
> The kavin.rocks (piped.video) instance is working great. It is the /feed section that is empty/loading forever.

It started with the endless loading loop, but then I got logged/kicked out, and since my login credentials are bound to kavin.rocks (official), aswell the instance is missing in the instance list, so I concluded that it's not available. But it was just a thought. So, then, actually I have no idea what's going on.

**Comment by Nationalgeographic** [comment]
The instance is back in the list. I can now authenticate again. Closing this.

**Comment by guemax** [comment]
It would've been interesting to know what caused the instance to disappear. A fairly recent pull request I opened (#3293) was already fixed before anyone explained the root cause, so I decided to close it. However, it seems to happen quite often that the feed cannot be loaded for a few hours/days.
