### ISSUE TITLE
What does this error mean : "This instance does not have a geo restriction checker set in its configuration"

### ISSUE THREAD

**Issue by Cade66** [TeamPiped/Piped#3448]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The "bug" -- but is it a bug -- appears on all working Piped instances, yet not on YouTube itself.
First time I encounter this issue.
Video is not displayed and reason is: This instance does not have a geo restriction checker set in its configuration

### To Reproduce

The original YouTube video is : https://www.youtube.com/watch?v=gDJuT0AKCfI
The tested Piped instance video is : https://piped.privacydev.net/watch?v=gDJuT0AKCfI but issue with all Piped instances.
The official Piped instance video is : https://piped.video/watch?v=gDJuT0AKCfI (but here no video nor message, must be the instance's overall failure)
The video is not displayed and message is : _This instance does not have a geo restriction checker set in its configuration_

### Expected behavior

Video correctly displayed, especially that it is handled by YouTube servers.

### Logs/Errors

org.schabi.newpipe.extractor.exceptions.GeographicRestrictionException: This instance does not have a geo restriction checker set in its configuration
	at me.kavin.piped.server.handlers.StreamHandlers.streamsResponse(StreamHandlers.java:234)
	at me.kavin.piped.server.ServerLauncher.lambda$mainServlet$10(ServerLauncher.java:126)
	at io.activej.http.AsyncServlet.lambda$ofBlocking$0(AsyncServlet.java:43)
	at io.activej.promise.Promise.lambda$ofBlocking$12(Promise.java:249)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)

### Browser, and OS with Version.

Firefox 115.8.0 ESR on Windows 7-64BIT

**Comment by Bnyro** [comment]
The instance host didn't set up https://github.com/TeamPiped/region-restriction-checker.
