### ISSUE TITLE
Subscribe to playlists

### ISSUE THREAD

**Issue by shaedrich** [TeamPiped/Piped#3473]
### Describe the feature

It would be nice to know, when a video was added to (or removed from) a playlist

### Why would this be useful to add?

Currently, you can subscribe to channels, whose newly uploaded videos will appear in your feed, but you can't get updates from playlists

### Concept(s)

Not sure, if that necessarily feeds in the feed, but there should be some kind of notification, maybe the 🔔-Button like on YouTube, or at least an email.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's out of scope for the project. We already have something similar called playlist bookmarks, which allows you to remember playlists for the future.

Apart from that you can use Piped's RSS feeds for that.
