### ISSUE TITLE
Can the subtitle translation function be adapted? For example, access the immersive translation plug-in

### ISSUE THREAD

**Issue by zhl111** [TeamPiped/Piped#3474]
### Describe the feature

Add subtitle translation function

### Why would this be useful to add?

Breaking out of the information cocoon

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Out of scope.
