### ISSUE TITLE
it is playing the sound it is not showing the video

### ISSUE THREAD

**Issue by 372405** [TeamPiped/Piped#3497]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

![Screenshot 2024-03-22 8 30 48 AM](https://github.com/TeamPiped/Piped/assets/130566973/88e964eb-514d-44da-898a-e68ff9922dae)

### To Reproduce

https://piped.video/watch?v=5wTXI9e4NAw&listen=1

### Expected behavior

![Screenshot 2024-03-22 8 30 48 AM](https://github.com/TeamPiped/Piped/assets/130566973/fd15bc63-ef12-4ee9-a2e5-df71515fbc04)

### Logs/Errors

![Screenshot 2024-03-22 8 30 48 AM](https://github.com/TeamPiped/Piped/assets/130566973/1b775dac-7930-4bd9-b231-3f5088cbee9c)

### Browser, and OS with Version.

![Screenshot 2024-03-22 8 30 48 AM](https://github.com/TeamPiped/Piped/assets/130566973/8a3978e1-6211-4d86-8d0c-1f221b78c25e)

### Additional context

![Screenshot 2024-03-22 8 30 48 AM](https://github.com/TeamPiped/Piped/assets/130566973/a6554809-7619-4037-b752-54ea96c8410d)

**Comment by matt-laird** [comment]
Looking at your provide URL, it seems this is correct behaviour has your only streaming audio (i.e with the param `&listen=1`)
Also in future don't be a dick and just send images in place of actual info of issue ticket fields.

**Comment by matt-laird** [comment]
@Bnyro to close
