### ISSUE TITLE
Show tooltip/hover text over 'creator has liked/replied' icons

### ISSUE THREAD

**Issue by opusforlife2** [TeamPiped/Piped#3498]
### Describe the feature

When hovering over the heart icon/channel icon in comments, Piped should show a tooltip like "The creator has liked/replied to this comment".

### Why would this be useful to add?

Currently, it can be confusing what those icons are there for.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Kaynec** [comment]
I think for that you need to add translation for all languages, the code is not very complicated but adding text for all locales is a challenge.
