### ISSUE TITLE
comment section starts with avatar nulls

### ISSUE THREAD

**Issue by foxjaw** [TeamPiped/Piped#3503]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

![Screenshot_20240323-110633](https://github.com/TeamPiped/Piped/assets/150133625/13f082b5-1f69-4a4c-956c-320d06bfd58e)

### To Reproduce

Comments section ?

### Expected behavior

First I'm trying to understand whether those garbages comments actually exist or not. Isn't it supposed to be regular comments ?

### Browser, and OS with Version.

On all platforms

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/3429
