### ISSUE TITLE
New instance: piped.reallyaweso.me

### ISSUE THREAD

**Issue by AlexPewMaster** [TeamPiped/Piped#3522]
### Api Url

https://pipedapi.reallyaweso.me

### Instance location

Germany

### CDN (not required)

- [ ] My instance does use a CDN.

### Instance owner

- [X] I am the owner of the instance.

### Other details

Hi, I would like to add my own instance to the instance list. It would be awesome if it could get added!

**Comment by Bnyro** [comment]
I tried to test the instance, but all my requests seem to be timing out?

**Comment by AlexPewMaster** [comment]
> I tried to test the instance, but all my requests seem to be timing out?

Hi, sorry for the late reply! I fixed the issue, please take a look at my instance again.
