### ISSUE TITLE
Need help with showing just the player in SwiftUI.

### ISSUE THREAD

**Issue by atpugvaraa** [TeamPiped/Piped#3526]
### Official Instance

- [x] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I am making an iOS app to play music via youtube but that didn't go well so i am here using piped but the problem is that i don't know which link to access the player from... right now it shows the website instead of the player if self.
Also is the adblock built in or would i have to enable it somehow.

### To Reproduce

Currently using this url: https://piped.video/watch?v=\(videoID) [i know it is the wrong one]

https://pipedapi.kavin.rocks/streams/\(videoID) this just shows the json structure.

### Expected behavior

I want to show the actual player instead of the frontend of the website.

### Browser, and OS with Version.

Browser: N/a
iOS 17.2.1

### Additional context

This is my first ever experience with apis or swiftui so i am not sure what has to be done in order for this to work fine.

**Comment by Bnyro** [comment]
You should probably use the `hls` field in the `/streams/{videoId}` response. See https://developer.apple.com/streaming/ on how to use it.

However, there's already an iOS app supporting Piped called Yattee, and if you're searching for someone to help you with the app, this certainly isn't the right place.

**Comment by atpugvaraa** [comment]
Noted! Thanks alot for helping out.
