### ISSUE TITLE
Black Screen on official instance

### ISSUE THREAD

**Issue by erazemk** [TeamPiped/Piped#353]
I tried accessing https://piped.kavin.rocks, but all I get is a black background. I don't block JS, but to make sure an extension wasn't the problem I tried launching piped in a temporary Firefox profile and on mobile data on my phone (to make sure my network isn't the problem). Every time only the black screen was shown, so I think this might be an issue with the instance.

I don't know any other piped instance links by heart, so I couldn't check if this problem occurs on all instances.

**Comment by FireMasterK** [comment]
Fixed, there was an issue in two commits that I pushed today, sorry about that!

**Comment by erazemk** [comment]
Thanks for the quick fix :)
