### ISSUE TITLE
the videos will not load so I cannot watch them

### ISSUE THREAD

**Issue by 372405** [TeamPiped/Piped#3563]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

the videos will not load so I cannot watch them it is working for this video https://piped.video/watch?v=lCpszkhqV-o 

### To Reproduce

https://piped.video/watch?v=HScJ6K89g_U I don't know how to see the errors

### Expected behavior

the video listing Me watch it

### Logs/Errors

I don't know how to see the errors
![Screenshot 2024-04-22 9 16 24 AM](https://github.com/TeamPiped/Piped/assets/130566973/c2e51b6f-0013-49e3-aef0-f79718ba23cb)

### Browser, and OS with Version.

so google

### Additional context

it will not let me also make an account

**Comment by Gadg8eer** [comment]
Able to reproduce with ALL Piped videos using Firefox.

**Comment by Insprill** [comment]
I'm also able to reproduce this with all videos on the official instance with Firefox v125.0.2. Searching for videos results in the same infinite loading screen. My private instance is working fine.

**Comment by 372405** [comment]
I don't have that it is happening again

**Comment by 372405** [comment]
ok
________________________________
From: Bnyro ***@***.***>
Sent: Tuesday, April 30, 2024 4:25 PM
To: TeamPiped/Piped ***@***.***>
Cc: DANIEL WADSWORTH ***@***.***>; Author ***@***.***>
Subject: [ External ]Re: [TeamPiped/Piped] the videos will not load so I cannot watch them (Issue #3563)




CAUTION: This email originated from outside of Erie's Public Schools. Do not click on links or open any attachments until you have confirmed with the sender and know the content is safe. Never reply to an outside message with any personal information including your password or phone number. Do not send money or gift cards....

Did you try clearing the browser cache?

See #3545<https://github.com/TeamPiped/Piped/issues/3545>
