### ISSUE TITLE
Newpipe channel groups importable

### ISSUE THREAD

**Issue by foxjaw** [TeamPiped/Piped#3566]
### Describe the feature

Newpipe subscriptions have the channel groups too. We can import the subs from Newpipe. But unfortunately not the channel groups from it.

### Why would this be useful to add?

Can't regroup the subs into groups again and again. With newpipe's data export in place. Let piped utilize that data to make channel groups too.

### Concept(s)

Newpipe has export data in the form .db file. If there's a way to parse this file please look into the channel groups section too.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned as long as NewPipe only allows exporting groups in a .db file, sorry.

As soon as NewPipe has support for exporting as `.csv` or `.json`, this is considerable. (LibreTube has support for this btw...)
