### ISSUE TITLE
I cannot build the frontend image correctly from the Dockerfile myself

### ISSUE THREAD

**Issue by amirianos** [TeamPiped/Piped#3567]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Hello everybody. Recently, I've been working on this project, and I want to run it on my local machine. Everything was perfect until I tried to build the frontend image from source using Docker. After building it with 'docker build --no-cache -t NAME:TAG .', I replaced the old Docker image name and tag with the new one in the docker-compose file. However, after running it, I noticed that although the trending page loads, it only shows a black blank page.

### To Reproduce

1-build image from source code
2-replace image name and tag inside of docker-compos file
3-up this docker compose file

### Expected behavior

 Could someone please help me troubleshoot this issue?

### Browser, and OS with Version.

Mozilla

**Comment by Bnyro** [comment]
Why are you trying to build the docker image yourself instead of just using `pnpm dev` for development?

The docker image works fine for me, so whatever does not work is related to your changes and not this repository.
