### ISSUE TITLE
A simple docker-compose file with no reverse proxy

### ISSUE THREAD

**Issue by mattogodoy** [TeamPiped/Piped#3570]
### Describe the feature

I want to create a self-hosted instance for private use, so I don't want to expose it to the internet.

### Why would this be useful to add?

It would be great to have a simple docker-compose file that could be copy/pasted into a server and spun up with a simple "docker compose up -d" command, with no need to configure reverse proxies, TLS, etc. Just my server's private IP and its port.
I've seen many users asking for the same, but I can't find a way to do it. I've tried manually changing things and creating my own compose.yaml file, but I get some errors.

Could we have an official simple docker-compose file in the documentation?
Let me know how I can help!

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
The subscription feed won't work when your server is not accessible from the outside.

And how do you want to differentiate between proxy, backend and frontend? Do you want to run them on different ports?

And why do you want to use Piped if you're only running it locally? Couldn't you just use NewPipe instead?

**Comment by mattogodoy** [comment]
All very valid points!
Sorry, I'm new to Piped and I didn't know about the limitations when not
exposing my instance.

I'll check NewPipe. Thanks for your help!
