### ISSUE TITLE
Return YouTube Dislike Not Working?

### ISSUE THREAD

**Issue by Metabot24** [TeamPiped/Piped#3574]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

The dislike shows a question mark instead of the number of dislikes

### To Reproduce

Open any instance of Piped and click on any video and the dislikes don't show. And I have confirmed it's an issue in EVERY available instance.

### Expected behavior

Dislikes should be visible.

### Browser, and OS with Version.

Opera Developer 111.0.5145.0. POP_OS 22.04

**Comment by ngn13** [comment]
Almost every instance is using [ryd-proxy.kavin.rocks](https://ryd-proxy.kavin.rocks/), which is currently down. Just be patient until @FireMasterK gets it back up and running.

**Comment by Bnyro** [comment]
It's functional again.
