### ISSUE TITLE
Piped proxy timeout

### ISSUE THREAD

**Issue by ngn13** [TeamPiped/Piped#3575]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Hello, I did a container update yesterday, and suddenly piped proxy started to timeout while loading videos.

### To Reproduce

1. Go to [piped.ngn.tf](piped.ngn.tf)
2. Open up the devtools network tab
3. Click on any video

You will see that some requests going to `pipedproxy.ngn.tf` timeouts. Which prevents the video to load.

### Expected behavior

The requests should not timeout.

### Logs/Errors

I don't know how to get the logs/errors for piped-proxy, it does not print out any information other than the "Running server!" message.

### Browser, and OS with Version.

Issue should be reproducible on any browser/OS. For the server I am using Docker AIO script with nginx.

### Additional context

I really didn't want to create an issue for this here (since it may be related to my setup), but I don't use Matrix and there is no other way for me to ask for help.

**Comment by amirianos** [comment]
I also have the same issue here
