### ISSUE TITLE
Add an option to rename subscription groups

### ISSUE THREAD

**Issue by abacabadabacaba** [TeamPiped/Piped#3578]
### Describe the feature

Currently, there is no way to rename subscription groups. I propose to add this functionality.

### Why would this be useful to add?

It is easier to rename a group than to create a new one and add each channel to it.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
Already possible, the icon just has been invisible.
