### ISSUE TITLE
Request confirmation before deleting subscription groups

### ISSUE THREAD

**Issue by abacabadabacaba** [TeamPiped/Piped#3579]
### Describe the feature

Currently, subscription groups are deleted without confirmation. I propose to add a confirmation dialog.

### Why would this be useful to add?

This would prevent deleting subscription groups accidentally.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by khusroohayat** [comment]
[https://github.com/khusroohayat/Piped/pull/1](url)

**Comment by Bnyro** [comment]
@khusroohayat You can just open a pull request at this repository here, you probably accidentally opened it at your own fork.

**Comment by khusroohayat** [comment]
[https://github.com/TeamPiped/Piped/pull/3596](url) @Bnyro
