### ISSUE TITLE
Feature Request: Playlists

### ISSUE THREAD

**Issue by AnaemicStar** [TeamPiped/Piped#358]
It would be good to be able to save videos to a Playlist.

**Comment by vachan-maker** [comment]
I would also love to see this feature. 

A watch later option would also be nice.

**Comment by Loki-L1130** [comment]
Also to play videos in the order of the playlist. Would be great.

**Comment by IceCodeNew** [comment]
> Also to play videos in the order of the playlist. Would be great.

Yeah, I'm looking for that feature too.

**Comment by trymeouteh** [comment]
Would like to see this also and be able to import/export playlist data.
