### ISSUE TITLE
Long word in comment extends page width beyond video player.

### ISSUE THREAD

**Issue by nutzboi** [TeamPiped/Piped#3586]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When someone posts a comment with a long enough word, the word goes behind and beyond the recommendations, extending the page width and making the page horizontally scrollable beyond the video player, controls and recommendations.

### To Reproduce

1. Open this URL at https://piped.kavin.rocks/watch?v=QsdXUcYRPJU
2. Scroll horizontally to the right, then vertically down until you encounter the long comment.
3. Observe the long comment that's extending the page :3

### Expected behavior

The word should should collapse and split into mulitple lines, maybe. This is how it looks like on YouTube.

![image](https://github.com/TeamPiped/Piped/assets/31652809/91af7df3-c46d-4bc5-908a-1a30466e0143)

### Browser, and OS with Version.

Latest Mozilla Firefox on latest Microsoft Windows.

**Comment by nutzboi** [comment]
this did NOT fix it lmao 
![image](https://github.com/TeamPiped/Piped/assets/31652809/f78b279e-d84a-49e0-a72e-3d97251a40b1)

**Comment by Bnyro** [comment]
![2024-05-06T22:59:13,783627959+02:00](https://github.com/TeamPiped/Piped/assets/82752168/5ba8c5a4-7738-457a-a6ed-81782aca5377)

Not sure what you tested, but it works as expected for me on Firefox. (kavin.rocks is not yet updated)

**Comment by nyanpasu64** [comment]
I'm getting this issue on watch?v=hfbfl0MlIAU (the official instance won't load right now), and fixed it locally using:

```css
    .comment > .comment-content, .flex > * {
        min-width: 0;
        overflow-wrap: break-word;
    }
    .comment-avatar {
        flex-shrink: 0;
    }
```

Note that this may have side effects because I had to change the properties of .flex children globally. (both the comment stretched, and the all-comments container stretched, and I had to modify both to impose page width on the comment's word lengths rather than the other way around.)
