### ISSUE TITLE
Search suggestions do not pop-up 

### ISSUE THREAD

**Issue by foxjaw** [TeamPiped/Piped#3588]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Search suggestions does not seem to appear while typing

### To Reproduce

1. Head to the search bar
2. Type something

### Expected behavior

The search suggestions should pop-up 

### Browser, and OS with Version.

Chrome v123.0.6312.106. Android 14

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/1463
