### ISSUE TITLE
Add entry support to onion hidden service

### ISSUE THREAD

**Issue by TNTBOMBOM** [TeamPiped/Piped#364]
Hi There,

Since the main website is behind cloudflare CDN , Cloudflare does support onion hidden services check: 

https://blog.cloudflare.com/cloudflare-onion-service/
https://blog.cloudflare.com/welcome-hidden-resolver/

If you want the Onion service (Tor hidden service) to handle its own CDN over Tor there is a way to do that using Onion Balance v3: 

https://onionbalance-v3.readthedocs.io/en/latest/v3/tutorial-v3.html

Using hidden services add the best protection for users security and privacy when visiting the website because: 

- DNS has many insecurities/flaws (Wikipedia provide tons of insecurities, As DNS never created to solve security issues):

https://en.wikipedia.org/wiki/Domain_Name_System#Security_issues

https://en.wikipedia.org/wiki/Domain_Name_System#Privacy_and_tracking_issues

- Same thing for TLS: (if not taking care for it)

https://piped.kavin.rocks/watch?v=5dhSN9aEljg

-----

Note: onion hidden service URL can be added as a header so users know about it: 

Onion Header: https://community.torproject.org/onion-services/advanced/onion-location/

ThX!

**Comment by FireMasterK** [comment]
Cloudflare's onionservice works as an `alt-svc` h2 header.

Although, I really love tor, streaming over tor would be a really bad experience!

It would make more sense to have an onionservice for the API instead if this was a concern.
