### ISSUE TITLE
installed instance, search find nothing. Please help how to troubleshoot

### ISSUE THREAD

**Issue by hanscees** [TeamPiped/Piped#3640]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Hi, I installed piped with dockers behind an nginx instance. 
I get the piped website, but have no idea what to do next and cant find documentation.

I type in " trees" in the search bar but nothing happens, except a spinning wheel.

Excuse my ignorance, I have no idea where to start troubleshooting.
 

### To Reproduce

1. search for trees on new vanilla docker piped instance
2. nothing happens

### Expected behavior

video's with trees appear? 

### Browser, and OS with Version.

brace 14.100 on debian 

### Additional context

no the bug is not reproducable on a working host and I have no idea what logs to look at first

**Comment by hanscees** [comment]
ooooh, wait. 
You have to add your own api in the instances under preferences
and then register. 

and then it works. 
Why doesnt the documentation say so?

**Comment by Bnyro** [comment]
> Why doesnt the documentation say so?
>
It doesn't tell you because your instance api url is set as the default if you followed the documentation properly.

**Comment by Bnyro** [comment]
If you need help with self-hosting, ask at https://matrix.to/#/#piped:matrix.org as per https://github.com/TeamPiped/Piped?tab=readme-ov-file#having-trouble.
