### ISSUE TITLE
When you add a video ID to the end

### ISSUE THREAD

**Issue by inoue64** [TeamPiped/Piped#3660]
### Describe the feature

I think it would be better to display the video page even if a video ID is specified at the end.

### Why would this be useful to add?

Even if you replace the shortened domain of youtu.be, it works the same as Piped.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned. Use LibRedirect or something similar for youtu.be links, our goal is compatibility for youtube.com links.
