### ISSUE TITLE
service "nginx" depends on undefined service "pipedfrontend": invalid compose project

### ISSUE THREAD

**Issue by tunloop** [TeamPiped/Piped#3678]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Following the self hosting instructions provided here https://piped-docs.kavin.rocks/docs/self-hosting/
and attempting to start the docker container, I get the following error:

```
# docker compose up -d
service "nginx" depends on undefined service "pipedfrontend": invalid compose project
```

### To Reproduce
```
root@server:/opt# git clone https://github.com/TeamPiped/Piped-Docker
Cloning into 'Piped-Docker'...
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (118/118), done.
remote: Compressing objects: 100% (48/48), done.
Receiving objects: 100% (186/186), 48.60 KiB | 2.86 MiB/s, done.
remote: Total 186 (delta 94), reused 75 (delta 70), pack-reused 68
Resolving deltas: 100% (110/110), done.
root@server:/opt# cd Piped-Docker
root@server:/opt/Piped-Docker# ./configure-instance.sh
Enter a hostname for the Frontend (eg: piped.kavin.rocks):
yt.mydomain.com
Enter a hostname for the Backend (eg: pipedapi.kavin.rocks):
ytapi.mydomain.com
Enter a hostname for the Proxy (eg: pipedproxy.kavin.rocks):
ytproxy.mydomain.com
Enter the reverse proxy you would like to use (either caddy or nginx):
nginx
root@server:/opt/Piped-Docker# docker compose up -d
service "nginx" depends on undefined service "pipedfrontend": invalid compose project
```
### Expected behavior

Docker is supposed to start, but does not despite following documentation.

### Browser, and OS with Version.

Debian 12
Docker Packages:
docker-buildx-plugin/bookworm,now 0.14.1-1~debian.12~bookworm amd64 [installed]
docker-ce-cli/bookworm,now 5:26.1.4-1~debian.12~bookworm amd64 [installed]
docker-ce-rootless-extras/bookworm,now 5:26.1.4-1~debian.12~bookworm amd64 [installed,automatic]
docker-ce/bookworm,now 5:26.1.4-1~debian.12~bookworm amd64 [installed]
docker-compose-plugin/bookworm,now 2.27.1-1~debian.12~bookworm amd64 [installed]

**Comment by Bnyro** [comment]
Fixed now.
