### ISSUE TITLE
Feature Request: Distinction and history of watched videos

### ISSUE THREAD

**Issue by shibattor** [TeamPiped/Piped#369]
Hello,
first of all, I would like to thank you for the best YT frontend. I love it and all its small things like my feed RSS and audio only mode.

My feature request
- mark already watched videos in some way so there is a clear distinction between watched and not watched videos
- create a page or list with history of watched videos

**Comment by FireMasterK** [comment]
This has been done in #370, could you test https://96b4e112.piped.pages.dev/ and let me know if there's something not working? (You'll have to enable it manually in the preferences)

**Comment by shibattor** [comment]
Damn, that was fast! Thank you, from my brief testing it seems like it is working. 
I have a few suggestions for improvements
- buttons for adding/removing from watched
- resume the watched video where it last ended (perhaps only when it was not watched till the end?)
- improved marking of watched videos (perhaps something like Freetube is doing?) 
![image](https://user-images.githubusercontent.com/87258997/130333680-685edcd0-3642-4430-a058-617f4045890d.png)

**Comment by shibattor** [comment]
Issues found
- watched videos are not marked as watched or show in the History until page is refresh with CTRL + R
- watched videos are marked as watched only on the Feed page (not on Trending, search results, channel details etc.)

**Comment by FireMasterK** [comment]
> buttons for adding/removing from watched
> resume the watched video where it last ended (perhaps only when it was not watched till the end?)

This would be better suited for a new issue since they are feature requests.

> improved marking of watched videos

It's currently like how it is on youtube.com, I'm not great at designing UIs, so if someone else wants to make it better, I'll let them do so.

> search results

I'm going to be ignoring these, for now, they'll be added once they're merged with `VideoItem.vue`.

> the history setting and the history itself is not preserved after user deletes cookies and site data

That's to be expected, these are saved locally.

The two bugs you've mentioned are fixed now, so I'm merging the PR and closing this now!

Thanks for testing!

**Comment by shibattor** [comment]
Alright, I will create a separate issues for the other stuff. Thank you for your awesome work and new features.
