### ISSUE TITLE
New instance: 

### ISSUE THREAD

**Issue by aquila0101** [TeamPiped/Piped#3692]
### Api Url

https://publichomelab1.nohost.me

### Instance location

Brazil

### CDN (not required)

- [ ] My instance does use a CDN.

### Instance owner

- [X] I am the owner of the instance.

**Comment by Bnyro** [comment]
Your API url is on the `api` subfolder which we don't currently have any support for, LibreTube for instance doesn't support this either.

It would be awesome if you could put the api on a different subdomain in order for your instance to be added to the list of public instances.
