### ISSUE TITLE
Channel image is not rendering

### ISSUE THREAD

**Issue by athiosh** [TeamPiped/Piped#3694]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Running the latest docker version on my server, everything seems to be working but on the subscription page all the channel image does not render.

![image](https://github.com/TeamPiped/Piped/assets/66545547/b3905a59-8342-4c6c-a3b7-80c7d03548ab)

### To Reproduce

Open Subscription page 

### Expected behavior

Channel image should display

### Browser, and OS with Version.

Running Brave
[Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by Bnyro** [comment]
Should be fixed by https://github.com/TeamPiped/Piped-Backend/pull/829

**Comment by athiosh** [comment]
Just checked and it is fixed. Thank you
