### ISSUE TITLE
Channel page and API methods for requesting channel information return -1 subscribers

### ISSUE THREAD

**Issue by Artem13327** [TeamPiped/Piped#3698]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Channel page and API methods for requesting channel information return -1 subscribers

### To Reproduce

1) Open any channel page or request information via API

### Expected behavior

._.

### Browser, and OS with Version.

Not applicable

**Comment by Bnyro** [comment]
The fix is at https://github.com/TeamNewPipe/NewPipeExtractor/pull/1170, so we'll need to wait for that.
