### ISSUE TITLE
import subs from other piped instances 

### ISSUE THREAD

**Issue by Brickboxing** [TeamPiped/Piped#3707]
### Describe the feature

If i have around 200 subs on one piped instance can i transfer those subs to another piped instance?

### Why would this be useful to add?

because some instances could go down and i dont want to individually sub to 200 channels again

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by Bnyro** [comment]
You can export and import subscriptions at `/subscriptions` via the `Export to JSON` and `Import from JSON/CSV` buttons.
