### ISSUE TITLE
Video refuses to play when default quality is not set to auto

### ISSUE THREAD

**Issue by st-am** [TeamPiped/Piped#3715]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When setting the default quality to anything other than auto, videos refuse to play and either infinitely load or the video progress bar goes fully or partially red, as if i've watched the video.

### To Reproduce

1. Set default quality to anything other than auto
2. Attempt to watch a video

### Expected behavior

Video plays

### Browser, and OS with Version.

LibreWolf 128.0-2 on Arch Linux

**Comment by trubeck** [comment]
> I actually have an opposite behavior: videos refuse to play when quality is auto, but setting quality to anything except auto resolves the issue. But I'm running my own instance.

I have the same behavior on [Adminforge](https://piped.adminforge.de). I'm accessing with Firefox 128.0 on Win 11.

**Comment by ChocolatePie698** [comment]
I'm having the same issue I think. But I receive an error when refreshing the page. Error 3015.

**Comment by bonswouar** [comment]
Same behavior here, Librewolf/Linux and Firefox/Windows, it seems it appeared in a quite recent update.
By the way setting it to auto by default and change it manually for each video works

**Comment by st-am** [comment]
> Same behavior here, Librewolf/Linux and Firefox/Windows, it seems it appeared in a quite recent update. By the way setting it to auto by default and change it manually for each video works

I tested it on Brave Browser and had the same issue, I prefer not to use the qualities on the video player because it has slightly compressed audio, while using the default qualities in Preferences, I didn't have this issue, and side note, when I go into the quality options on the video player and select what quality I want to use, while using a quality from the preferences tab, the quality says auto and selecting it shows none of the qualities are selected.

**Comment by ACR-Jeff** [comment]
Thank you for bringing this up. I was pulling my hair out trying to figure this out, I can confirm this is an issue and it solved my loss of hair issue.

**Comment by Kostrol** [comment]
Auto does not work properly either, it does not change with bandwidth or buffering and for me is just stuck playing at 240p for most of the instances I've tried, exception is official kavin libre.

**Comment by bonswouar** [comment]
> I prefer not to use the qualities on the video player because it has slightly compressed audio, while using the default qualities in Preferences, I didn't have this issue, and side note, when I go into the quality options on the video player and select what quality I want to use, while using a quality from the preferences tab, the quality says auto and selecting it shows none of the qualities are selected.

For me (using latest version) changing the quality manually on the video player does change the audio quality too, and it does show as selected in the player

**Comment by st-am** [comment]
> This seems to be fixed as of right now. I've opened 4-5 videos on the main instance and the bug is gone.

You're right, it's fixed,

**Comment by st-am** [comment]
nvm

**Comment by Kostrol** [comment]
CDN version?

The issue still persists for me for me for libre and a few other private instanced, one returned 3015 error. These video not playing issues are very nuanced and conflicting I find, a few videos will be stuck no many how refreshes or instance changes you do, and then you open a few recommended ones and they will start playing, I don't understand it.

**Comment by Atemu** [comment]
This happens on a private self-hosted instance for me, so it's certainly not a CDN issue. Though I do have a reverse proxy (nginx) in front of course.

**Comment by ChocolatePie698** [comment]
This is currently still happening. Not sure how to fix this.
