### ISSUE TITLE
Videos sometimes load but do not actualy play

### ISSUE THREAD

**Issue by Atemu** [TeamPiped/Piped#3729]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

When opening a video, it loads (buffer bar becomes visible and I see all 200s in the network log) but doesn't play, no matter what button I press play, skip or do anything else. No spinner is shown, it only shows the thumbnail.

Nothing in the logs.

This started happening in the last few days.

### To Reproduce

1. Open any video
2. Try to play it
3. Sometimes works, sometimes just gets stuck

### Expected behavior

It should play

### Browser, and OS with Version.

Firefox 128 on NixOS.

### Additional context

Locally hosted instance (docker-compose).

**Comment by hunkyburrito** [comment]
Same issue for me with Firefox 128 on Arch. Tried a couple different instances but it still happens. Choosing a specific resolution does load the video and play it though.

**Comment by ACR-Jeff** [comment]
It appears YT is trying to prevent using invidious instances, Other apps I use that use the Invidious api are having similar issues if not able to load at all from instances, Adding another instance some times solves it, But then later on it will stop working again, Possibly putting a time limit on connections?
