### ISSUE TITLE
Hide channels feature

### ISSUE THREAD

**Issue by thequver** [TeamPiped/Piped#3745]
### Describe the feature

Please add a possibility to hide specific channels from recommendation feed, search results and (optionally) comments made by those channels.

### Why would this be useful to add?

Sometimes you want to search for interesting content or see it in recommendations but instead only repetitive and annoying influencers videos or other clickbait spam appear there that you cannot avoid or block in any way. This feature will allow to clean up recommendations and search results and make them useful.

### Concept(s)

There are already chrome extensions for blocking channels on youtube but they no longer work seemengly after youtube internal updates.
Here is the specific extension example i've used before: https://chromewebstore.google.com/detail/channel-blocker/nfkmalbckemmklibjddenhnofgnfcdfp
You can see the way how they made the ui for blocking (a little X near the channel name). It was really convenient to use and I suggest to add the same thing to piped.

### Acknowledgements

- [X] I have searched the existing issues and this is **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this form.

**Comment by anewuser** [comment]
You can hide channels with [custom filters](https://github.com/gorhill/uBlock/wiki/Dashboard:-My-filters) for [uBlock Origin](https://addons.mozilla.org/addon/ublock-origin/):

```
! hide channels
piped.video## .video-grid > .flex:has( a[title="IGN"], a[title="MojoPlays"] a[title^="WatchMojo"] )

! hide shorts
piped.video## .video-grid > .flex:has( .thumbnail-left:has-text(Shorts) )
```

`title=` - exact title
`title^=` - any title that starts with...
`title*=` - any title that includes...
