### ISSUE TITLE
Do clients download sponsorblocked bits?

### ISSUE THREAD

**Issue by Latrolage** [TeamPiped/Piped#376]
Title wasn't clear. I mean do clients download parts of the stream which is going to be sponsorblock skipped?

Also, I took a look at the docs and it says that the proxy uses golang and stuff. But the self hosting thing tells us to use nginx (as a reverse proxy i'm assuming).

Is the proxy written in go something separate? What does it do?

also on an unrelated note, is "golang" the actual name of the programming language. I thought it was just "Go"

**Comment by FireMasterK** [comment]
> do clients download parts of the stream which is going to be sponsorblock skipped?

Yes. There's obviously room for improvement. 


> Is the proxy written in go something separate? What does it do?

Yes, it's used to stream videos and images from Google's servers. You're supposed to use both of them together.

> is "golang" the actual name of the programming language. I thought it was just "Go"

It's "Go", but you get significantly better search results when you search for something technical with "Golang".

Can I close this issue now?

**Comment by Latrolage** [comment]
Invidious, another front end to YouTube says that a protocol called DASH must be used when loading videos above 720p, which requires the content to be routed through their servers first, is this the same here?

**Comment by FireMasterK** [comment]
Yes, it's the same. Piped supports dash by default, and falls back to regular streams only incase a browser doesn't support MSE extensions.

**Comment by Latrolage** [comment]
Thanks FireMasterK!
