### ISSUE TITLE
doesn't work properly without JavaScript enabled!

### ISSUE THREAD

**Issue by MohammadJavad-AsnaAshari** [TeamPiped/Piped#3769]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

Hi. i wana login to Piped website, because of this error:
`Got error: "Sign in to confirm that you're not a bot"` 
but when i see my login page network response, i have this problem in login page!:
`We're sorry but Piped doesn't work properly without JavaScript enabled. Please enable it to continue.`
please solve this bug!

### To Reproduce

I search in google and find this solution:
```
new Vue({
    router,
    store,
    render: h => h(App)
}).$mount('#app');
```
i don't know about front-end side, but it's may help!

### Expected behavior

remove this problem please!
`Got error: "Sign in to confirm that you're not a bot"`
and if you can't, please add and fix login page!

### Browser, and OS with Version.

Google Chrome 128.0.6613.84, Linux Ubuntu 22.04

**Comment by brudermusscode** [comment]
I have JavaScript enabled, uBlock is turned off but it's still giving me this message
