### ISSUE TITLE
“Country” setting shouldn’t be called “country”

### ISSUE THREAD

**Issue by qwqtoday** [TeamPiped/Piped#3781]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

It includes places that shouldn’t be a country, which is a bit sensitive in some other places. 

### To Reproduce

1. Open the settings menu

### Expected behavior

It should be called “Country/Region”.

### Browser, and OS with Version.

Any browser

### Additional context

It is very scary, I can’t provide more information about this issue due to some reasons.

**Comment by Bnyro** [comment]
Only because you don't approve the existence of a country, it doesn't mean that everybody else does so too. If you want to do politics, do so, but don't bother open source projects with your convictions.

**Comment by qwqtoday** [comment]
> Only because you don't approve the existence of a country, it doesn't mean that everybody else does so too. If you want to do politics, do so, but don't bother open source projects with your convictions.

Hong Kong is not a country in anyway possible, but it’s included in the list

**Comment by qwqtoday** [comment]
@Bnyro why not just be safer because no one is going to double check every name in that list?
