### ISSUE TITLE
it is saying this I am logged in Got error: "Sign in to confirm that you're not a bot"

### ISSUE THREAD

**Issue by 372405** [TeamPiped/Piped#3794]
### Official Instance

- [X] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

![image](https://github.com/user-attachments/assets/800d29f4-04ff-49f1-92f9-442d3ba9dac9)

### To Reproduce

https://piped.video/watch?v=BFlYwm9khMo it is this 
![image](https://github.com/user-attachments/assets/9b8089c1-822a-4441-bb18-be308c9703fb)

### Expected behavior

the video playing

### Logs/Errors

I do not know how to do that

### Browser, and OS with Version.

crome 

### Additional context

![image](https://github.com/user-attachments/assets/197fcc7d-b0bd-4d29-bd93-e18a67451c8b)

**Comment by 372405** [comment]
please fix this I wont to yous the website for music

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/3658
