### ISSUE TITLE
ERROR:"sign-in to confirm abt bot"

### ISSUE THREAD

**Issue by robinbood** [TeamPiped/Piped#3808]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

i used 4 instances and i can't play a video and instead get the bot error  and when i sign-in ..it still gives me the same error

### To Reproduce

download libretube..use an intance..get the bot error..sign-in..get the bot error again..close the app

### Expected behavior

i expected to be able to watch the video ig

### Logs/Errors

really?

### Browser, and OS with Version.

android 14

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/3658

**Comment by robinbood** [comment]
well save me the reading and point me in the right direction brother

**Comment by nintendoit** [comment]
This is a known bug and solution is not yet available.SO, try another instance(may got lucky) or use another service that does not use piped(newpipe works at the moment).

**Comment by robinbood** [comment]
> This is a known bug and solution is not yet available.So, try another instance(may got lucky) or use another service that does not use piped(newpipe works at the moment).

idk if newpipe is as privacy friendly as piped or poketube
