### ISSUE TITLE
NOT LETTING ME WTACH MAH SHOW (PLS FIX I GOT NOTHING TO WATCH AT...school.)

### ISSUE THREAD

**Issue by klax74** [TeamPiped/Piped#3827]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

it keeps saying sign in to confirm your not a bot im watching or on piped through thw website i did not install if thats the issue like do we have a sign in button somewhere?

### To Reproduce

what i did is just go to a video and press it then the video is not there and all it says is sign in to confirm your not a bot

### Expected behavior

for my video to pop up

### Logs/Errors

where do i add it? the sign in thing???

### Browser, and OS with Version.

im on computer 

### Additional context

nothing to add here

**Comment by Bnyro** [comment]
https://github.com/TeamPiped/Piped/issues/3658
