### ISSUE TITLE
driver failed programming external connectivity on endpoint nginxproxymanager-app-1

### ISSUE THREAD

**Issue by ManOnTheWeb** [TeamPiped/Piped#3860]
### Official Instance

- [ ] The bug is reproducible on the [official hosted instance](http://piped.video/), or is API-related.

### Describe the bug

I follow the instructions to self-host with nginx. I'm on Fedora.
I start nginx and I start the containers but I receive this error:
`Error response from daemon: Cannot restart container d26241e764cb: driver failed programming external connectivity on endpoint nginxproxymanager-app-1 (992379575c1a119dc6efd0c75cd49650b983386c7dd5ac051eb995a8847bf945): failed to bind port 0.0.0.0:80/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use`

On the browser I have 502 Bad Gateway.

I noticed that I can't have both the containers and nginx working at the same time and I don't know why.
It used to work but since I deleted and reinstalled everything, it doesn't work anymore for me.

This is my http server configuration in /etc/nginx/nginx.conf:
```
server {
        listen       80;
        server_name  pipedvideo.[censored].org pipedapi.[censored].org pipedvideoproxy.[censored].org
        # root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        # include /etc/nginx/default.d/*.conf;

        location / {
                proxy_pass http://127.0.0.1:8080;
                proxy_set_header Host $host;
        }
}
```

What should I do?

### To Reproduce

1) Follow the instructions to self-host with nginx
2) Use `sudo systemctl restart nginx`
3) Use `docker restart $(docker ps -aq)`

### Expected behavior

I normally expect this to work and let me access my self-hosted Piped.

### Browser, and OS with Version.

Mozilla Firefox for Fedora 132.0 (64 bit)
Fedora Linux 41 (Workstation Edition), Linux 6.11.6-300.fc41.x86_64

**Comment by Bnyro** [comment]
That's not a Piped specific issue, you're just trying to bind two services to the same port which never works.

Usually, you want to configure nginx to reverse proxy to nginx proxy manager and Piped depending on the server name, but that's up to you and not related to Piped.
