### ISSUE TITLE
Feature Request: Ability to unsubscribe from all channels at once

### ISSUE THREAD

**Issue by rootedetc** [TeamPiped/Piped#391]
Since I mainly use Freetube to manage my subscriptions and watch videos, my subscriptions list on Piped gets outdated quickly.

Instead of checking for differences, I'd be great if there was an option to quickly unsubscribe from all channels at once, so I could import a fresh subscription list.

**Comment by FireMasterK** [comment]
Closing this with cbb68da79f189ca6dbb79f6bd028d278a1264a97.
