### ISSUE TITLE
Feature: Set default video playback speed

### ISSUE THREAD

**Issue by mizzunet** [TeamPiped/Piped#392]
Please add an option in Preferences to set default playback speed

**Comment by DeeHechEss** [comment]
Yea that is how it is set. I just tested it again myself and I see some flakiness.

If I pause and play a video it gets reset to 1x.
If I set it to something like 2x without pausing the video, the next video I play will do so at 2x, but the video after that just goes back to 1x.

**Comment by farverio** [comment]
Both my familiarity with frontend and vue are limited. I’m glad to help support a PR to fix this though. Unsure on testing suite or process. Looking at the components, it seems like an update to `src/components/Preferences.vue` (to add to user store for global default) and then injecting in `src/components/Player.vue` around line 264 would achieve the desired outcome.

Believe the product decision of  default speed is supported by similar Newpipe implementation I remember seeing. Not sure how Youtube implements, believe they use your last speed set as the default (think this is stored  server side as multiple devices have faster speed). Code should account for potential null values from clients that haven’t added a preference to mitigate supporting redundant default value for each user.

@DeeHechEss @FireMasterK thoughts?
