### ISSUE TITLE
Videos from LBRY are not proxied

### ISSUE THREAD

**Issue by imabritishcow** [TeamPiped/Piped#402]
When a video plays from LBRY, it is not proxied and the browser requests the video directly, exposing the user's IP address to LBRY's servers.
![Screenshot from 2021-09-01 22-28-16](https://user-images.githubusercontent.com/87500845/131772113-c8278921-8f24-4f56-826c-8efecafedf89.png)

**Comment by FireMasterK** [comment]
Proxying was previously enabled by default, but was disabled due to performance issues, I've made this opt-in since I don't think LBRY is that bad compared to YouTube, privacy wise.
