### ISSUE TITLE
There is something wrong with changing locale

### ISSUE THREAD

**Issue by vachan-maker** [TeamPiped/Piped#422]
Sometimes piped will automatically change the language to english even though a non english language is selected.

**Comment by FireMasterK** [comment]
Is there any specific language this happens with? Any certain way to reproduce this issue? The description you gave seems a bit too vague to understand a possible cause.

**Comment by vachan-maker** [comment]
> 
> 
> Is there any specific language this happens with? Any certain way to reproduce this issue? The description you gave seems a bit too vague to understand a possible cause.
Ok
Locale: Malayalam
Browser: Firefox Desktop
I launch Piped.
Piped is in English even though I have selected Malayalam.
I go to the settings, to check again and the language is already set to malayalam but Piped is showing everything in english
Changes the language to english and then changes it to malayalam.
Piped is now in malayalam. 
Closes Piped and then launch it again. Piped changes language to english.

**Comment by Bnyro** [comment]
Can't reproduce anymore, assuming it's been fixed.
