### ISSUE TITLE
[Bug] UI for subscriptions feed broken on Android

### ISSUE THREAD

**Issue by openwick** [TeamPiped/Piped#425]
Videos are rendering as a vertical lines as shown in the image  when clicked on feed. Tested on both firefox and bromite. Please fix.

![Screenshot_2021-09-07-11-46-58-031_org bromite bromite](https://user-images.githubusercontent.com/78715124/132294184-adc06e4a-2820-4694-a8bf-f843cd774ca9.jpg)

**Comment by FireMasterK** [comment]
This was caused due to 7211cad36921bddad6efa9101ed66d9035da92ac. Contributions/help on possible solutions are welcome!

**Comment by FireMasterK** [comment]
Closing as this was fixed a while back!
