### ISSUE TITLE
Incorrect views being displayed on Feed page.

### ISSUE THREAD

**Issue by vachan-maker** [TeamPiped/Piped#427]
On the feed page, the views of some of the videos from channels I have subscribed is shown as 0. But the videos have way more views what is being displayed.
![image](https://user-images.githubusercontent.com/65799568/132437460-4354fa7f-8c4e-4957-910d-1fb02471af8b.png)

**Comment by FireMasterK** [comment]
This is not an issue since it is by design to work this way, the only time views with be updated is when someone else clicks on that video or channel. This is because Piped doesn't use threads like Invidious to fetch channels, Piped uses only PubSub.
