### ISSUE TITLE
Don't show full title of videos if the title is too long.

### ISSUE THREAD

**Issue by vachan-maker** [TeamPiped/Piped#430]
For the videos being displayed on the feed page and trending page, the video titles are completely displayed. I think its better to only show a limited portion of the title to save space.

This will make the trending page on mobile devices feel less cramped, I think.

**Comment by IceDBorn** [comment]
I was thinking about it too, I think that after two lines the rest of the title should be hidden with "...".

**Comment by vachan-maker** [comment]
Thank you for implementing this.🎉
