### ISSUE TITLE
Option to have an Empty Landing page

### ISSUE THREAD

**Issue by Shadowspear123** [TeamPiped/Piped#439]
Hi. I think it would be very nice to have the option to set the default landing screen to a blank page. 

Semi-related: If you have a lot of subscriptions then when “Feed” is selected as the default landing page the whole site becomes very slow, laggy, and unresponsive.

**Comment by 1over137** [comment]
Why take away features unnecessarily?

**Comment by Bnyro** [comment]
You can set the home page to trending and the region to Iran, that does the job.
