### ISSUE TITLE
Feature request: Prevent registration

### ISSUE THREAD

**Issue by RealOrangeOne** [TeamPiped/Piped#440]
For selfhosted users, it'd be nice to prevent someone signing up and using their instance. Probably juts with a config item in `config.properties`.

**Comment by aspacca** [comment]
@RealOrangeOne

I setup a working instance with nginx as proxy with http basic auth that actually have the same outcome.

Tricky thing is that I had to use a single domain, with proxying by paths api server and ytproxy.

It is actually possible to define in `config.properties` the urls as `https://user:pass@domain.tld` but as far as I can get it the browser will complain about authentication in urls fetched by the frontend.

If you have interest in such a solution I can share the setup.

**Comment by FireMasterK** [comment]
Closing with https://github.com/TeamPiped/Piped-Backend/commit/ced7b0ee9ebeda88feaafa0ad44191752b92dcce
