### ISSUE TITLE
Feature request: Live streams - Live Chat

### ISSUE THREAD

**Issue by RobBrazier** [TeamPiped/Piped#443]
Could Live Chat be added to the scope of live videos and VODs - I see the bom proxy is proxying the livestream video data feed from googlevideo.com, so was hoping that it'd be possible to proxy the live chat data feed as well?

It seems to be coming underneath the following API call
**POST** https://www.youtube.com/youtubei/v1/live_chat/get_live_chat?key=[key] (not sure how specific the key is to user agent etc. as it's the same for two streams in incognito - might be a static value, just depending on the input)

This contains a worrying amount of advertising and tracking information in the POST request, but I think the main thing is a continuation id which is requested on initial load, this actually loads an iframe

e.g. https://www.youtube.com/live_chat?continuation=0ofMyANxGlhDaWtxSndvWVZVTlRTalJuYTFaRE5rNXlka2xKT0hWdGVuUm1NRTkzRWdzMWNXRndOV0ZQTkdrNVFSb1Q2cWpkdVFFTkNnczFjV0Z3TldGUE5HazVRU0FCMAGCAQIIBIgBAaAB4sXn3s_38gKyAQA%253D for a lofi girl stream (https://www.youtube.com/watch?v=5qap5aO4i9A)

I would paste an example response, but I'm hesitant as... it's google so who knows what's in there

**Comment by FireMasterK** [comment]
It's quite similar to https://github.com/TeamNewPipe/NewPipeExtractor/issues/469, the technical details should be submitted to NewPipeExtractor since Piped doesn't do any extractions on its own.

**Comment by RobBrazier** [comment]
Okay great thanks - I'll close this then as it definitely looks the same thing
