### ISSUE TITLE
Improve Captions

### ISSUE THREAD

**Issue by FrozenVertx** [TeamPiped/Piped#448]
Hi,
When a video is played with Captions ON then it display white text with black background. See below Screenshots of same video on same frame one on piped and other from youtube. As you captions black background is much bigger,take more space and less transparent as compared to youtube and it really annoying if you want see something in video inside captions. So my request is to **MAKE CAPTIONS MORE TRANSPARENT AND LESS SPACE HUNGRY**.

![piped](https://user-images.githubusercontent.com/72699730/133103634-b91fbd1a-8319-4448-ae05-03bf6ca8e5b6.png)
![yout](https://user-images.githubusercontent.com/72699730/133103656-d2f12049-abcc-4829-941c-0aba3ebdd477.png)

**Comment by Yolakalemowa** [comment]
even stranger behavior here. A very big box covers the entire screen:

![image](https://user-images.githubusercontent.com/41283612/152438606-0dd2836d-be4d-4d9e-a4f8-87d33f405954.png)

(btw, related to issue #759 , I also noticed that when CC is on, instead of the first word of title getting highlighted, now the first word in the captions takes priority lol... not sure if relevant but maybe helpful in finding the solution) @FireMasterK

**Comment by Loki-L1130** [comment]
As @Yolakalemowa I do have this issue. 

![Piped - Subtitle Overlay](https://user-images.githubusercontent.com/87981739/152467756-bb3da320-85c5-4db4-8bdb-4c83aece1824.png)

**Comment by Loki-L1130** [comment]
This is in another Instance - Silkky.

**Comment by Loki-L1130** [comment]
@FireMasterK Do you have any fixes on this ?

**Comment by Yolakalemowa** [comment]
@Loki-L1130 
huh any idea why was the issue closed?

**Comment by Yolakalemowa** [comment]
@Loki-L1130 

Sorry I'm new to github... I don't see a commit here and the problem is still happening with me. Is it solved on your end?

**Comment by Loki-L1130** [comment]
Yes. It is solved on the Kavin.rocks instance. Maybe it might take some time for other instances because They need to update those instances.

**Comment by Loki-L1130** [comment]
> Sorry I'm new to github...

According to your profile, You created the account in 2018 but you don't know about it - really ?

**Comment by Loki-L1130** [comment]
> @Loki-L1130 Loki, you have no idea who I am. My account is old yes but I'm not a tech person and barely understand how to navigate this site, and FOSS and all related terminology. Why would I lie about that? lol
> 
> You can see from all my other comments if they're visible.

Yeah, I do understand. Just asking why didn't you made a trip across the site.

Sorry, If I made any Offense.

**Comment by Yolakalemowa** [comment]
@Loki-L1130 no worries... I'm learning slowly.
