### ISSUE TITLE
[Bug] Video Player Icons not displayed in Firefox

### ISSUE THREAD

**Issue by 0lhi** [TeamPiped/Piped#452]
Firefox does not display the Symbols for Pause/Play in the video player. Instead, the words *play_arrow*, *volume_up*, *fullscreen* and *more_vert* can be seen.

![Piped](https://user-images.githubusercontent.com/74732674/133787003-86f0ebfc-c471-4783-a191-b3d911fc82b5.png)

Using Firefox 92.0 on Linux Mint 20.

**Comment by FireMasterK** [comment]
I couldn't replicate this on Firefox on Arch Linux, the only possible cause I see for this is something is blocking `fonts.kavin.rocks`.

**Comment by Wohlstand** [comment]
The same Firefox 92 on Linux Mint, the same thing works fine

**Comment by lordkitsuna** [comment]
i see this is a old bug but was just kinda closed without resolution. i just self hosted an instance and i am also getting this. oddly enough if i do a full refresh (ctrl+F5) it fixes itself but on any new video it will have this problem at first and i am unable to figure out why so far. has anyone else run into this and figured out what was causing it?

**Comment by f-x1-1** [comment]
The bug persists on all instances I have tested so far, icons display perfectly on other browsers.

**Comment by FireMasterK** [comment]
> The bug persists on all instances I have tested so far, icons display perfectly on other browsers.

It sounds like you're blocking 3rd part fonts 😕

**Comment by f-x1-1** [comment]
> 

I've fixed it by changing `browser.display.use_document_fonts value` to 1. By default it was set to 0.

**Comment by FireMasterK** [comment]
> I've fixed it by changing `browser.display.use_document_fonts` value to 1. By default it was set to 0.

Its default value is actually `1`, that's likely due to a user.js that you're using
