### ISSUE TITLE
Feature Request: Volume Normalization.

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#484]
Youtube and other streaming platform support volume normalization, where the site automatically adjusts a video's volume to make all videos have similar loudness. Also known as ReplayGain. The loudness target is -14 LUFS. [Read more about it here.](https://en.wikipedia.org/wiki/Audio_normalization)
If you right click a video on Youtube and select "Stats for nerds", there is a "Volume/Normalized" line that shows how Youtube normalizes that video's loudness. Unfortunately it seems Piped hasn't supported this yet, resulting in some videos have very loud audio compared to others. I wonder if developers can pull this info from Youtube API and add to Piped, or something.

**Comment by Long-FA** [comment]
Bump it up in case devs forgot.

**Comment by Bnyro** [comment]
Not supported by Shaka: https://github.com/shaka-project/shaka-player/issues/4082
