### ISSUE TITLE
SponsorBlock api not working

### ISSUE THREAD

**Issue by RouterCFW** [TeamPiped/Piped#487]
SponsorBlock Is bugged and is no longer skipping segments of videos

**Comment by FireMasterK** [comment]
https://status.sponsor.ajay.app/ it's not an issue in Piped, so I'm closing this hence.

**Comment by RouterCFW** [comment]
> https://status.sponsor.ajay.app/ it's not an issue in Piped, so I'm closing this hence.

Oh Sorry . I’ve saved this website in case it happens again so I can check
