### ISSUE TITLE
Add instance api.piped.silkky.cloud.

### ISSUE THREAD

**Issue by TheSilkky** [TeamPiped/Piped#488]
Hello, can you please add our instance to the official list?

**Instance Name:** Silkky.Cloud
**URL:** https://api.piped.silkky.cloud
**API Location:** Finland
**CDN:** Cloudflare

**Note:** The front-end is using a slightly modified [source-code](https://github.com/silkkycloud/Piped-Frontend). I will add a list of changes for transparency.

**Comment by FireMasterK** [comment]
You have extra trailing `/` in the config for the PROXY_PART property.
See https://github.com/TeamPiped/Piped-Backend/blob/master/config.properties#L8

**Comment by TheSilkky** [comment]
Fixed

**Comment by FireMasterK** [comment]
Added, thanks!

**Comment by FireMasterK** [comment]
Something I noticed was you weren't using Cloudflare to cache the API responses.
You should add a page rule like this to do that:
![image](https://user-images.githubusercontent.com/20838718/135072921-ccdd1fc9-f90f-4bbd-8353-72abd1bdb7e4.png)

**Comment by TheSilkky** [comment]
That's weird, I already added that rule for `api.piped.silkky.cloud/*`. Does it need to cover the proxy to? `*.piped.silkky.cloud/*`

**Comment by FireMasterK** [comment]
No, but I do see this:
![image](https://user-images.githubusercontent.com/20838718/135077114-701d3d38-0e72-44ff-a616-4833b0336b2b.png)

When using https://piped.kavin.rocks/?instance=https://api.piped.silkky.cloud, it's strange indeed!

**Comment by TheSilkky** [comment]
When I set `*.piped.silkky.cloud/*` it started working for the proxy responses:
![proxy](https://user-images.githubusercontent.com/77580166/135084387-077eb416-1639-4d41-b711-c7c78dacfb21.png)

But it's still bypassing the api responses:
![api](https://user-images.githubusercontent.com/77580166/135084496-7f4742ec-bf6f-44fc-8967-d174dc88009d.png)

**Comment by FireMasterK** [comment]
Something is just odd since usually, it should work like that!

> Also does it make sense to cache proxy responses?

Yes, as long as you have storage for that, why not! (Here, it's Cloudflare so it doesn't matter)
