### ISSUE TITLE
Change the italian translation for subscriptions to "iscrizioni"

### ISSUE THREAD

**Issue by federico2407** [TeamPiped/Piped#489]
On src/locales/it.json:
-Row 33 "Visualizza le iscrizioni"
-Row 61 "Iscrizioni"
"Abbonamenti" in italian usually means something you pay for, "Abbonammenti" with two "m" is wrong

**Comment by IceDBorn** [comment]
You can change it yourself

**Comment by IceDBorn** [comment]
https://hosted.weblate.org/projects/piped/frontend/it/

**Comment by FireMasterK** [comment]
Please use weblate, the link is above!
