### ISSUE TITLE
JSONObject["result"] not found.

### ISSUE THREAD

**Issue by poleznosti** [TeamPiped/Piped#502]
instead of showing a video site returns this message

> JSONObject["result"] not found.

if i click "show more" it returns

> org.json.JSONException: JSONObject["result"] not found.
> 	at org.json.JSONObject.get(JSONObject.java:572)
> 	at org.json.JSONObject.getJSONObject(JSONObject.java:782)
> 	at me.kavin.piped.utils.ResponseHelper.getLBRYStreamURL(ResponseHelper.java:953)
> 	at me.kavin.piped.utils.ResponseHelper.lambda$streamsResponse$3(ResponseHelper.java:131)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

this is how it looks now https://i.imgur.com/MkKSFBN.png

**Comment by FireMasterK** [comment]
Which video does this happen on?

**Comment by poleznosti** [comment]
i tried to watch https://piped.kavin.rocks/watch?v=XSfVdEedYSI
but for some reason right now it just works again. maybe i rushed in vain with the creation of the report and i just had to wait until everything worked.

**Comment by FireMasterK** [comment]
I've just fixed this in https://github.com/TeamPiped/Piped-Backend/commit/2c7baa0710eade7a742096f41cae7d55ede9972e.

This way, in case LBRY is having server issues, Piped does not get affected as a whole.
