### ISSUE TITLE
(Stuttering) Sounds Even When Muted

### ISSUE THREAD

**Issue by Mennaruuk** [TeamPiped/Piped#51]
Not sure why, but when I mute a video, I can still hear some sounds intermittently. This happens when I'm watching the video without pausing, but it can also happen shortly after resuming.
 
Example URL: https://piped.kavin.rocks/watch?v=VkhsFGswWNA

**Comment by FireMasterK** [comment]
Yes, I'm aware of this issue, it's related to #1.

I'm guessing you're using Firefox, if you use any chromium based browser it will not occour there.

However, I'm working on something to fix this for all browsers.

**Comment by Mennaruuk** [comment]
THANKS! Also, I'm not sure how dependent Piped is on Invidious, but the Invidious project has recently put out a PSA regarding deprecation of invidio.us and the using of the new official domain, [invidious.io](https://invidious.io). 

"invidio.us is now deprecated, invidious.io is the new domain.

The invidious-redirect website ( invidio.us ) is now https://redirect.invidious.io/

The instance API ( instances.invidio.us ) is now https://api.invidious.io/

The uptimerobot page ( uptime.invidio.us ) is now https://uptime.invidious.io/

https://git.invidious.io/ redirects to the Github page of the project: https://github.com/iv-org/invidious/

https://docs.invidious.io/ redirects to the documentation website of the project: https://github.com/iv-org/documentation/

https://invidious.io/ will become in the future a "project presentation" page (like https://searx.me/ ), we will use a markdown framework like Hugo.

Projects using something from invidio.us need to move to the new domain."

**Comment by FireMasterK** [comment]
Should be fine as we're completely independent from Invidious, we're dependant on NewPipeExtractor.

**Comment by FireMasterK** [comment]
Closing as this is fixed :)

**Comment by Mennaruuk** [comment]
Thank you!
