### ISSUE TITLE
video controls double for radio/live pages

### ISSUE THREAD

**Issue by poleznosti** [TeamPiped/Piped#514]
on radio pages video controls double, here is how it looks https://i.imgur.com/REJcq28.jpg

here is the link to example https://piped.kavin.rocks/watch?v=O8cow9fBNhk

however if you will go to audio version of the same page https://piped.kavin.rocks/watch?v=O8cow9fBNhk&listen=1 then UI will be fine.

**Comment by IvRRimum** [comment]
+1

**Comment by Loki-L1130** [comment]
> 
> 
> i replicate it on vivaldi, i dont use firefox. sorry i didnt mention it earlier.
> 
> here is another link for example https://piped.kavin.rocks/watch?v=Z4ehcw30stM and screenshot https://i.imgur.com/290hQOy.jpg
> 
> here is info about my browser according to vivaldi://about/
> Vivaldi 	4.3.2439.56 (Stable channel) (64 бита)
> Версия 	a5e19200dd37281958aeb652add7f226dc091ab3
> ОС 	Windows 7 Service Pack 1 (Build 7601.24535)
> JavaScript 	V8 9.4.146.21

Exact to issue #547.

**Comment by den7007** [comment]
Am on Firefox 94.0.2 on Windows 10 Pro and can confirm watching live videos, the controls also double similar to your photo.

**Comment by FireMasterK** [comment]
This should now be fixed with c87af466c85180768e8f9a465dfa12f2865e5e6c.
