### ISSUE TITLE
Self-host backend

### ISSUE THREAD

**Issue by DUOLabs333** [TeamPiped/Piped#516]
While I can self-host the frontend, I can't self host the backend. I could use Docker, but I want to be able to control it myself. I see in the relevant repository there is something about java, though it's not clear what to do.

**Comment by DUOLabs333** [comment]
I can probably get the backend to work, but how can I tell my frontend to connect to my backend.

**Comment by FireMasterK** [comment]
See: https://github.com/TeamPiped/Piped-Docker

You just run the `./configure-instance.sh` script
