### ISSUE TITLE
When typing Japanese in the search box, the query is submitted even though I have not finished typing

### ISSUE THREAD

**Issue by jloqfjgk** [TeamPiped/Piped#517]
#### Problem description

When typing Japanese, the user has to press Enter key to select the correct Hiragana / Katakana / Kanji representation.
If the user has finished typing and wants to submit the query, he has to press Enter key again for the actual submission.

However, on Piped the submit event is triggered when the Enter key is pressed during typing.

#### Steps to reproduce / Observed result

1. Visit any Piped instance
2. Switch to Japanese IME
3. Suppose the full query is "白い砂のアクアトープ", so enter "shiroisunano" ("しろいすなの" is displayed) and press Space
4. Choose the correct representation from the candidates ("白い砂の") and press Enter to use that candidate
5. Now the user wants to continue and type "アクアトープ", but due to the aforementioned issue, Piped already uses "白い砂の" to perform a search

#### Expected result

Enter key presses when typing should not trigger the submit event.

The user should be able to continue typing, and when he is ready and presses Enter, Piped should then proceed to perform a search.

#### Additional information

Please also refer to these issues:
* https://github.com/elm-community/html-extra/pull/12
* https://github.com/vueComponent/ant-design-vue/pull/4524

Perhaps this is the problematic part?
https://github.com/TeamPiped/Piped/blob/master/src/components/Navigation.vue#L95

**Comment by jloqfjgk** [comment]
Unfortunately, `https://91df18cb.piped.pages.dev/` does not fix the issue...

**Comment by FireMasterK** [comment]
Could you try https://52cc4378.piped.pages.dev/?

**Comment by jloqfjgk** [comment]
I also tried the new UI in #520.
The new UI does not have this issue, but the new UI won't perform any search. Even if I use English words for the query and press Enter, it just redirects to `https://ui-v2.piped.pages.dev/?`.

**Comment by FireMasterK** [comment]
Does https://21b548a0.piped.pages.dev/ fix the issue?

**Comment by jloqfjgk** [comment]
No, the bug is still present in `https://21b548a0.piped.pages.dev/`.

**Comment by FireMasterK** [comment]
Ok, I'm finally out of ideas. I've tried everything that I can.

I even tried the recommendation in https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event.

**Comment by jloqfjgk** [comment]
I am not sure how to fix it too, but can I use #614 as an area for testing (so that I can try different workarounds that I found and have Cloudflare generate a demo website)?

**Comment by FireMasterK** [comment]
Unfortunately, you can't use the bot since it works only for branches in this repository :/

You could, however, run `yarn install` and `yarn serve` to create a local environment to test changes!

**Comment by jloqfjgk** [comment]
Thank you very much!

I hope commit 1782778c5bc can fix this issue.
I created a local environment (`yarn install` and `yarn serve`) based on that commit, and it seems to work on Firefox and Chromium without regressions (no more problem when typing Japanese).

**Comment by FireMasterK** [comment]
Sorry for the late response - I've been slightly overwhelmed in real life, I've just merged the commit you mentioned.

**Comment by jloqfjgk** [comment]
Thank you very much! I can confirm that the official instance works great now.
