### ISSUE TITLE
A couple feature requests

### ISSUE THREAD

**Issue by travilingyoshi** [TeamPiped/Piped#521]
I like piped, especially compared to invidious, but I have a few feature requests that I think could be good for the service.
- [ ] Theater mode: one feature that's missed from both youtube and invidous is the toggle-able theater mode that makes the screen size wider. This is the feature I want most out of the layout, if possible.
- [ ] reddit comments: toggle-able reddit comments could be nice, but not necessary if not possible to implement.
- [ ] right click sharing. Youtube has a feature where you can right click the video and get some options to share (screnshot example: 
![image](https://user-images.githubusercontent.com/92283253/136725617-f1bbf2d1-fc3d-4860-b78a-a7294e81d86b.png)
). If not possible, maybe a share button somewhere below the title that serves the same function.
- [x] Work mode: an option to hide front page and side recommended videos, similar to the extension DF youtube (https://chrome.google.com/webstore/detail/df-tube-distraction-free/mjdepdfccjgcndkmemponafgioodelna)

**Comment by Bnyro** [comment]
Please open one issue per feature request, closing this one as it's hard to track.
