### ISSUE TITLE
the main instance fails to load videos and the related information

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#529]
I didn't see any existing issue — the main instance currently fails to load potentially all videos (the video title, video stream, description, date, view and like counts, comments). Channel and playlist pages appear to be unaffected. Changing the instance in the preferences resolved the issue.

>Loading...
>NaN views
>Invalid Date

example channel: https://piped.kavin.rocks/channel/UCoookXUzPciGrEZEXmh4Jjg ([one archived page](https://web.archive.org/web/20211012070644/https://piped.kavin.rocks/watch?v=A4FrgUN0KSs))

**Comment by Loki-L1130** [comment]
It seems to be working fine here.

**Comment by Mhowser** [comment]
I noticed the main instance not loading data a couple times this evening too. I changed regions with my VPN and everything is loading fine now. Must be some new rate limiting thing.
