### ISSUE TITLE
Use without Postgres?

### ISSUE THREAD

**Issue by DUOLabs333** [TeamPiped/Piped#531]
Is there a way to set up a Piped instance without needing Postgres? I don't need accounts, as I'm planning to use it for personal use.

**Comment by aspacca** [comment]
@DUOLabs333 

If you are looking for an embed db like me I've tested with hsqldb and h2

* hsqldb
`config.properties`
```
hibernate.connection.url: jdbc:hsqldb:file:hsqldb/piped;sql.syntax_pgs=true;sql.enforce_tdc_delete=false;sql.enforce_tdc_update=false;allow_empty_batch=true;sql.sys_index_names=true;hsqldb.applog=3;hsqldb.sqllog=3;hsqldb.write_delay=false;sql.lowercase_ident=true;hsqldb.default_table_type=cache
hibernate.connection.driver_class: org.hsqldb.jdbcDriver
hibernate.dialect: org.hibernate.dialect.HSQLDialect
hibernate.connection.username: username
hibernate.connection.password: password
```

* h2
`config.properties`
```
hibernate.connection.url: jdbc:h2:/app/h2/piped;TRACE_LEVEL_FILE=3;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
hibernate.connection.driver_class: org.h2.Driver
hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
hibernate.connection.username: username
hibernate.connection.password: password
```

you have to build your custom docker image changing depdency in `build.gradle`
* hsqldb
```
FROM adoptopenjdk/openjdk11:debianslim-slim AS build

WORKDIR /app/
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/TeamPiped/Piped-Backend.git .

RUN sed -i "s/implementation 'org.postgresql:postgresql:42.3.1'/implementation 'org.hsqldb:hsqldb:2.6.1'/g" build.gradle
RUN sed -i "s/5.4.30.Final/5.5.3.Final/g" build.gradle

RUN chmod +x ./gradlew && ./gradlew shadowJar

FROM adoptopenjdk/openjdk11:debianslim-jre-nightly

WORKDIR /app/

COPY --from=build /app/build/libs/piped-1.0-all.jar /app/piped.jar

EXPOSE 8080

CMD java -jar /app/piped.jar
```

* h2
```
FROM adoptopenjdk/openjdk11:debianslim-slim AS build

WORKDIR /app/
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y git && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/TeamPiped/Piped-Backend.git .

RUN sed -i "s/implementation 'org.postgresql:postgresql:42.3.1'/implementation 'com.h2database:h2:1.4.200'/g" build.gradle
RUN sed -i "s/5.4.30.Final/5.5.3.Final/g" build.gradle

RUN chmod +x ./gradlew && ./gradlew shadowJar

FROM adoptopenjdk/openjdk11:debianslim-jre-nightly

WORKDIR /app/

COPY --from=build /app/build/libs/piped-1.0-all.jar /app/piped.jar

EXPOSE 8080

CMD java -jar /app/piped.jar
```

> RUN sed -i "s/5.4.30.Final/5.5.3.Final/g" build.gradle

bump of hibernate from `5.4.30.Final` to `5.5.3.Final` is required due to https://hibernate.atlassian.net/browse/HHH-13788

**Comment by DUOLabs333** [comment]
Hmmm, interesting. Can hibernate be used as a dropin replacement for Postgres in other projects?

**Comment by aspacca** [comment]
it depends what do you mean with drop-in replacement.
hibernate is an ORM, so you have to build your project using it.
the piped backend already uses hibernate and hibernate supports changing db driver and dialect, but still the application must not run any native postgres query

piped backend happens to do it, indeed: https://github.com/TeamPiped/Piped-Backend/blob/master/src/main/java/me/kavin/piped/Main.java#L37

but in this case both hsqldb and h2 have support for postgres compatibility. the level of compatibility and parity features support is different between the two, and while in the specific case of piped that's not a problem, it could potentially be. that's the reason I didn't try to use sqlite, that has no such thing like a compatibility mode with postgres

**Comment by DUOLabs333** [comment]
Ok, nice. This may be a suitable replacement. So it does not create a server, but remains only on the file system/RAM?

**Comment by aspacca** [comment]
both h2 and hsqldb has support for file based db, that's the setup I posted the two config for

**Comment by DUOLabs333** [comment]
Awesome, I guess I can close this now.

**Comment by FireMasterK** [comment]
This isn't exactly done since you can't disable all database functionality in Piped.

**Comment by DUOLabs333** [comment]
What do you mean? This is a file-based DB, which though isn't SQLite, serves the same purpose.

**Comment by FireMasterK** [comment]
Don't you want to disable all database-related functionality? Your solution doesn't achieve that.

**Comment by DUOLabs333** [comment]
I guess you're right.
