### ISSUE TITLE
Where can I find the privacy policy?

### ISSUE THREAD

**Issue by h1tech** [TeamPiped/Piped#540]

**Comment by FireMasterK** [comment]
There's none currently, but the official instance keeps no logs on my servers, however, https://www.cloudflare.com/privacypolicy/ is applied since it does use Cloudflare.

**Comment by h1tech** [comment]
> 
> 
> There's none currently, but the official instance keeps no logs on my servers, however, https://www.cloudflare.com/privacypolicy/ is applied since it does use Cloudflare.

Ok, thanks!

**Comment by Lostname777** [comment]
Please tell me the instances that don't use cloudfare cdn @FireMasterK

**Comment by EdwardLangdon** [comment]
@Lostname777 You can find it the Wiki of this repo.
