### ISSUE TITLE
When currently playing video in audio only mode, display a video icon for the button to switch to watch the video

### ISSUE THREAD

**Issue by Poopooracoocoo** [TeamPiped/Piped#544]
Hope you consider this suggestion :-)

Note that I have enabled the option to default videos to play in audio only mode

**Comment by FireMasterK** [comment]
If you click on the headphones icon, that happens :)

**Comment by Poopooracoocoo** [comment]
I don't understand what you mean. 
Currently Piped displays a headphones icon regardless of what the button does which is misleading. My proposal is to display a video icon when the button will switch it to video mode.

**Comment by FireMasterK** [comment]
Sorry, I had misread the title, hence the confustion!
