### ISSUE TITLE
Problems in Live Streams

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#547]
In Live Stream, It is unable to rewind even a Few back and the Player is being overlapped by Controls with Long Number of Time and same Controls.

I think this should be fixed. Is it not possible as YouTube only Controls it ?

**Comment by FireMasterK** [comment]
You can track that at https://github.com/TeamPiped/Piped/issues/514.

**Comment by Loki-L1130** [comment]
For a reference, A picture regarding this.

![Screenshot 118](https://user-images.githubusercontent.com/87981739/141056751-1eedc896-e18f-4d11-9c36-d4454db28bdf.png)
