### ISSUE TITLE
New things to be added in Piped

### ISSUE THREAD

**Issue by ghost** [TeamPiped/Piped#550]
![Invidious Instance](https://user-images.githubusercontent.com/87981739/137887909-3058c6e5-e8fe-40f5-94b8-ef4ed3e1fd38.jpg)

The above picture pretty much explains everything. I presume so.

**Comment by FireMasterK** [comment]
I don't want to keep this open since these are technically issues in NewPipeExtractor, see https://github.com/TeamNewPipe/NewPipeExtractor/pull/279 and https://github.com/TeamNewPipe/NewPipeExtractor/issues/106.
