### ISSUE TITLE
Error in Tor Browser on safest settings

### ISSUE THREAD

**Issue by PandaCoderPL** [TeamPiped/Piped#552]
Around one or two weeks ago Piped stopped working correctly in Tor Browser on safest settings. After enabling JavaScript and refreshing the website, I see blank page and in developer tools there is an error about undefined variable. Can you please investigate this issue and let me know if you can fix this? Thank you in advance.

**Comment by PandaCoderPL** [comment]
That's what I was suspecting as well. Is there anything you can do about it? There should be some way to debug this part of code.

**Comment by PandaCoderPL** [comment]
I'm just letting you know that issues is fixed now, probably after some Vue.js update.

**Comment by FireMasterK** [comment]
Good to know!
