### ISSUE TITLE
Localize content items

### ISSUE THREAD

**Issue by milotype** [TeamPiped/Piped#554]
Localize decimal separators, date formats and plural forms for different languages

**dates**:
implement locale specific date formats
e.g. Croatian uses only two forms:
- dd. mm. yyyy. (without the leading zero and always a period and a space between date/month and month/year, period at the end of year)
- 21. listopada 2021.
- month three letters abbreviations are not common, in such cases i’d suggest to use the standard numerical date

**decimal separators**:
e.g. Croatian uses the period instead of the comma : 3.188.933 (number of views, likes, dislikes)

**plural forms**
Strings lika `n minute/hour/day/month ago` all need localized plural forms

I’m aware it’s a lot to do! I’m not a programmer so I unfortunately can’t really help. Maybe you can put it aside for future improvements. Cheers, Milo

**Comment by FireMasterK** [comment]
Time ago is now localized everywhere!

**Comment by milotype** [comment]
@FireMasterK Please implement my frist point in this issue. It is still not correctly resolved.
...
Croatian uses two forms for dates:

- dd. mm. yyyy. (without the leading zeros for day and month and always a period and a space between date/month and month/year, period at the end of year)
- 21. listopada 2021.

Month three letters abbreviations are not used in Croatian.
