### ISSUE TITLE
[Feature Request] Sort the videos of a channel by views

### ISSUE THREAD

**Issue by vachan-maker** [TeamPiped/Piped#558]
Sort the videos of a channel by the views of the videos. This feature is already available on YouTube.

**Comment by Yolakalemowa** [comment]
> Closing this as I don't want to track issues in NewPipeExtractor here, see [TeamNewPipe/NewPipeExtractor#106](https://github.com/TeamNewPipe/NewPipeExtractor/issues/106), although it's not about channels, they require the same implementation as search.

Hi there... any idea when might this get implemented on piped?
