### ISSUE TITLE
Support for OpenSearch search completion

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#561]
Useful links for myself: 

https://developer.mozilla.org/en-US/docs/Web/OpenSearch

https://web.archive.org/web/20210124073052/https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Supporting_search_suggestions_in_search_plugins

https://searx.be/autocompleter?q=test

**Comment by sdfg2** [comment]
Need to add to the documentation that self-hosters will need to edit opensearch.xml, or do some more sed in the dockerfile! (Unless I've missed something somewhere)
