### ISSUE TITLE
Copy URL at current timestamp

### ISSUE THREAD

**Issue by mascherone108** [TeamPiped/Piped#566]
A functionality that would make it easier to share videos with specific time in the video - instead of sending people link and then telling them to fast forward to that time.

**Comment by vachan-maker** [comment]
@mascherone108 Looks like @FireMasterK  already added this feature.

just add &t=time in seconds to start the video at a particular point/
 
Demo: https://piped.jae.fi/watch?v=T1y8cjigI4Y&t=59

**Comment by mascherone108** [comment]
Is it possible to at least put the time in a format such as 2m38s? If not, then it isn't really a user-friendly way. What do you do when you want to share a timestamp from an hour long video? You have to convert that to seconds first and then send it.

**Comment by toby3d** [comment]
It would also be nice to add end-of-segment support. Right now YouTube supports this in embed link only with `start`/`end` keys:
`https://www.youtube.com/embed/a-uVjkMlP_o?start=123&end=456`

**Comment by lucamp** [comment]
I was looking the same.
If this feature will be implemented, please make it clear that you are sharing the url with the time. For instance NewPipe has the same icons for both: one is the url and the other is the url + time, so it's confusing.

Thanks for piped and great job
