### ISSUE TITLE
Disable AutoPlay on Embeds

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#576]

**Comment by Loki-L1130** [comment]
@FireMasterK This seems to work but the AutoPlay is not working for Shorts Videos like in the Issue for Piped Redirects. See here : https://github.com/TeamPiped/Piped-Redirects/issues/10 I am saying about Video 2. To be Precise Shorts by LTT.

**Comment by Loki-L1130** [comment]
If the AuroPlay and Window Size is Fixed. We can close the Issue in Piped redirects.

**Comment by Loki-L1130** [comment]
This issue sometimes stops Autoplay and sometimes not for Regular Videos.

**Comment by Loki-L1130** [comment]
@FireMasterK This seems to work but the AutoPlay is not working for Shorts Videos like in the Issue for Piped Redirects. See here : TeamPiped/Piped-Redirects#10 I am saying about Video 2. To be Precise Shorts by LTT.

If the AutoPlay and Window Size is Fixed. We can close the above Issue in Piped redirects repo.

This issue sometimes stops Autoplay and sometimes not for Regular Videos. This is based on Videos being AutoPlayed in RSS reader not in External Sites.
