### ISSUE TITLE
Clearing History

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#584]
Give an Option for Clearing History saved locally.

**Comment by vachan-maker** [comment]
One way to do this is by clicking on the **clear cookies and site data** button. This will clear the history and will also log you out. 
On Firefox, you can access this by clicking on the padlock icon

![image](https://user-images.githubusercontent.com/65799568/139538228-0cb12efd-0eb7-4bd5-9932-e464aa60c6b1.png)

**Comment by Loki-L1130** [comment]
I know that but I have preferences made using Cookies and I do not use an account. Just want to clear the History without altering other Preferences

**Comment by vachan-maker** [comment]
This is kind of complicated but it works
1. Open developer tools of your browser or just right click and select inspect element
2. Select **storage**
3. On the left side, select **IndexedDB**
4. Then select piped.kavin.rocks --> piped-db(default) -->Watch History
5. Right click and select Delete all. 
6. You can also delete individual items.
![image](https://user-images.githubusercontent.com/65799568/139540773-e873693f-693a-4c68-a367-85a53ef2bafb.png)

**Comment by Loki-L1130** [comment]
Great, This is what I need, anyway I am looking for a implementation.
