### ISSUE TITLE
Displaying Subscriber Count

### ISSUE THREAD

**Issue by FireMasterK** [TeamPiped/Piped#587]
I've neglected this feature for a while now...

**Comment by FireMasterK** [comment]
Blocked by: https://github.com/TeamNewPipe/NewPipeExtractor/pull/796

**Comment by B0pol** [comment]
Where is it displayed?? I can’t find it

**Comment by michaelskyba** [comment]
> Where is it displayed?? I can’t find it

It's on the subscribe button.

![temp](https://user-images.githubusercontent.com/57649592/198882613-88ce536e-0b29-4ff3-8073-25fca326d56f.png)
