### ISSUE TITLE
Dockerless

### ISSUE THREAD

**Issue by sdfg2** [TeamPiped/Piped#590]
I know you've answered this before, but it needs mentioned again.

What are the dependencies, sources, and compilation requirements?  (Note I'm not asking for install instructions)

There are many, many reasons someone might not want to use a docker image (not least needless duplication of resource use), and with correct development practises any piece of software can be kept up to date outside of any kind of container.  I mean, we were doing that for a good 30 years before docker was even around :-)

**Comment by FireMasterK** [comment]
I highly discourage such setups, due to convenience reasons.

You require Java (preferably OpenJ9 for lower memory usage), Golang, Postgres, Varnish and, a reverse proxy of your choice.

For the building instructions, you can see the `Dockerfile` for instructions.

**Comment by sdfg2** [comment]
Thanks for that, does that build all the components of piped (backend, frontend etc) or are each of them individual builds?

**Comment by FireMasterK** [comment]
I forgot about the frontend, you'll require nodejs and yarn to build that, and need to host it as a static webpage, everything needs to be built and, run/wired together individually.

**Comment by sdfg2** [comment]
and what about the proxy

**Comment by FireMasterK** [comment]
That requires Golang, see https://github.com/FireMasterK/http3-ytproxy, you just run `go build main.go`

**Comment by sdfg2** [comment]
Are there any other components I should know about?

**Comment by FireMasterK** [comment]
Not that I can recollect of.
