### ISSUE TITLE
Support preivew images in embedded videos

### ISSUE THREAD

**Issue by helpthemfix** [TeamPiped/Piped#601]
Hey there!

Some news sites use YouTube videos' thumbnails as the lead image of the article's thumbnail. However, when I use a Piped re-directer like -Privacy redirect- the image is blocked and not routed through Piped.

Is it possible to support?

Many thanks!

**Comment by FireMasterK** [comment]
I could not replicate this with https://addons.mozilla.org/en-US/firefox/addon/piped-redirects/ and https://jsfiddle.net/xb37ua0c/.

It's likely an issue with Privacy Redirect or your browser configuration.

It works as expected:
![image](https://user-images.githubusercontent.com/20838718/140593925-3c2ff4b6-2a2e-4ac9-898f-df61f0e2c53b.png)
