### ISSUE TITLE
font problem in firefox and derivatives

### ISSUE THREAD

**Issue by jedi2610** [TeamPiped/Piped#603]
the buttons does not load when i don't allow pages to load their own fonts in firefox and it's derivatives. here's what it looks like. is there any fix for this? can you guys use other fonts or something?
![2021-11-07-11-08-27](https://user-images.githubusercontent.com/30691152/140655713-74e7b515-7c69-45c3-a63b-90f6c9a4b4aa.png)

**Comment by jedi2610** [comment]
![2021-11-07-11-12-50](https://user-images.githubusercontent.com/30691152/140655769-0bfe0192-ba92-4124-900e-659952eb2078.png)
i basically have this box unchecked in `about:preferences` under font settings

**Comment by FireMasterK** [comment]
No, sorry. That's not under my control.
