### ISSUE TITLE
Button to open full Piped page from an embedded video.

### ISSUE THREAD

**Issue by catwithbanana** [TeamPiped/Piped#611]
Sometimes when watching an embedded video I want to open the video page so I can continue watching in a separate window or tab. The YouTube embedded player has a YouTube button, and the Invidious embedded player has an Invidious button that take you to the corresponding page.

I can't find any way to open the video page when watching something with the embedded Piped player. Could a button be added?

I'm using Firefox + Privacy redirect to replace YouTube embeds.

**Comment by Loki-L1130** [comment]
There is no Such Functionality right now. Already being followed in this #https://github.com/TeamPiped/Piped-Redirects/issues/4 

You can use [Piped-Redirect](https://addons.mozilla.org/en-US/firefox/addon/piped-redirects/) as it is made by the Piped Team Officially.
