### ISSUE TITLE
IOS support ?  

### ISSUE THREAD

**Issue by Flashpok** [TeamPiped/Piped#623]
hi,
Your project is fantastic !
On IOS (IPAD, I test with Firefox and Safari), video doesn't launch. Any help ?
Thank you !

**Comment by FireMasterK** [comment]
I just tested it on Browserstack, with IOS 14 and Safari, it seems to be working just fine over there, including DASH support!

To debug the issue use the devtools and see the javascript console. (I don't own any IOS devices, I can't help you with that)

You may also be interested in using https://github.com/yattee/app

Let me know if you find something, and then I will re-open this issue.
