### ISSUE TITLE
[Feature Request] Ability to store subscriptions and subscribe locally (without creating an account)

### ISSUE THREAD

**Issue by unbeatable-101** [TeamPiped/Piped#632]
Was brought up in #privacyguides-lounge:matrix.org, seems like a good idea to me.

**Comment by Mhowser** [comment]
I agree with this, at least there should be a way to create an account that requires no user data upfront, like how Mullvad VPN works, you just click generate account and it gives you a random account ID with no email requirement.

**Comment by FireMasterK** [comment]
This, unfortunately, won't be done, the reason being there needs to be some kind of activity tracker on users, to remove inactive users, which is a complex problem to solve efficiently, I had thought about this idea if before creating Piped, and decided to just stick to usernames and passwords.

Piped asks for no personal data whatsoever, it only asks for a username and a password.

**Comment by unbeatable-101** [comment]
Couldn't it just be stored in the browser like history is?

**Comment by FireMasterK** [comment]
No, the server needs to keep track of channels, to be able to generate a feed.
