### ISSUE TITLE
Clickable timestamps in comment sections don't work

### ISSUE THREAD

**Issue by mascherone108** [TeamPiped/Piped#637]
It works in video descriptions, but not in comment sections.
Examples - there should be comments that timestamp the whole video:
- https://piped.kavin.rocks/watch?v=wf807bOwsyU
- https://piped.kavin.rocks/watch?v=rnoWjHbenYs

**Comment by slavaGanzin** [comment]
@mascherone108 It works for me. Maybe your browser is blocking something (try to look into console). And for quick test just rty to open this link in regular and private tab.

https://piped.kavin.rocks/watch?v=wf807bOwsyU&t=4248

**Comment by mascherone108** [comment]
@slavaGanzin I'm not sure if we are on the same page here. Links fast-forwarding the video to a specific time using the &t= in URL work just fine. That is not the issue I have here.
When you open the second example I provided, it has both the video description with timestamps and a comment under the video with the same thing. However, the comment doesn't turn the timestamps into clickable links, which they correctly do from the video description. Here's a screenshot - left side is the video description and the right side is a comment: https://i.imgur.com/gf1HmV1.png

**Comment by slavaGanzin** [comment]
@mascherone108 my bad. You are right.

**Comment by CrazyVideoGamer** [comment]
And, for the working timestamps, they should be in short form (HH:MM:SS)
