### ISSUE TITLE
Returning Dislikes

### ISSUE THREAD

**Issue by Mhowser** [TeamPiped/Piped#643]
https://github.com/Anarios/return-youtube-dislike

This extension brings back the dislike count, any possibility you can use this after YouTube removes the API?

**Comment by FireMasterK** [comment]
I'm more interested in https://github.com/ajayyy/SponsorBlock/issues/1039

Also: https://github.com/TeamNewPipe/NewPipeExtractor/pull/753 as a temp solution

**Comment by FireMasterK** [comment]
Progress: https://github.com/TeamPiped/RYD-Proxy

**Comment by FireMasterK** [comment]
Poll for users, closes on July 1: https://cryptpad.fr/form/#/2/form/view/ut34ymlgT256fL1IvJ7qKeDo+EbuDWPewnynop0ygxk/

**Comment by IronMaltese** [comment]
I don't understand the benefits of picking the second option, since isn't the first choice easier and instances will be able to choose whether to implement it or not

**Comment by FireMasterK** [comment]
It's more of an option for people who don't like the idea of supporting a closed-source backend that collects IP addresses (but YouTube is most definitely far worse).

I think the first option makes the most sense too.

**Comment by IronMaltese** [comment]
> It's more of an option for people who don't like the idea of supporting a closed-source backend that collects IP addresses and pseudonymous identities (but YouTube is most definitely far worse).
> 
> 
> 
> I think the first option makes the most sense too.

It would've been better if Sponsorblock could've implemented this functionality, but the demand for this feature is definitely there, so as long as it's private and optional for instances I'm fine with either implementation

**Comment by FireMasterK** [comment]
> It would've been better if Sponsorblock could've implemented this functionality, but the demand for this feature is definitely there, so as long as it's private and optional for instances I'm fine with either implementation

Yeah, I really wanted to go with CrowdRate instead of RYD, but it's sadly abandoned :/

**Comment by zisra** [comment]
Any updates to this?

**Comment by FireMasterK** [comment]
> Any updates to this?

It's complete, dislikes are returned already.
