### ISSUE TITLE
Invalid Host Error while accessing from a domain

### ISSUE THREAD

**Issue by Albonycal** [TeamPiped/Piped#645]
I'm selfhosting this, it works by accessing it from the "IP" but when I try to access it via a domain 
it shows "Invalid Host Error"

**Comment by FireMasterK** [comment]
Did you follow https://piped-docs.kavin.rocks/docs/self-hosting/?

**Comment by Albonycal** [comment]
nah.. I ran `yarn serve`

**Comment by Albonycal** [comment]
hmm weird debian things I guess.. 😂 that's why I prefer arch

**Comment by Albonycal** [comment]
yep it was "weird debian problem" works properly after update ;) 
will test and then update the status of this issue
thanks

**Comment by FireMasterK** [comment]
Closing this issue, let me know if there's any issues.

**Comment by Albonycal** [comment]
![image](https://user-images.githubusercontent.com/67057319/143376296-1497e64f-3c2e-4bd2-9404-56d08c39220d.png)
Ok so the frontend is up, but I think the backend is not working? 
I "forwarded" the nginx proxy

**Comment by FireMasterK** [comment]
You don't have a DNS record for your API hostname: https://pipedapi.albony.xyz/trending?region=US

**Comment by Albonycal** [comment]
Do I have to point it to the same nginx instance?

**Comment by FireMasterK** [comment]
Yes, that's right!

**Comment by Albonycal** [comment]
made a pipedapi.albony.xyz
which other subdomains do I have to make?

**Comment by FireMasterK** [comment]
pipedproxy.albony.xyz but you seem to already have that, so all good!

**Comment by Albonycal** [comment]
yea I figured it out ;)
Thank you 😀
