### ISSUE TITLE
How can I delete my Piped account?

### ISSUE THREAD

**Issue by AlexMini2517** [TeamPiped/Piped#653]
How can I delete my Piped account? Sorry for opening a issue here, but I didn't manage to find a way to contact help.

**Comment by ChunkyProgrammer** [comment]
It's not possible atm. It's the only thing missing from this login feature #349

**Comment by FireMasterK** [comment]
This is now possible if you use the API via an external program or https://github.com/libre-tube/LibreTube! I'm closing this in favor of #1183
