### ISSUE TITLE
[Question] A way to set up only the api from the instance

### ISSUE THREAD

**Issue by QuartzWarrior** [TeamPiped/Piped#654]
I want to only set up the API, as I just want to use the API to fetch data for applications.

**Comment by FireMasterK** [comment]
This should be simple to do:
```
git clone https://github.com/TeamPiped/Piped-Backend
cd Piped-Backend
docker-compose up -d
```
Your instance will be up at 127.0.0.1:8080

**Comment by QuartzWarrior** [comment]
Thanks!

**Comment by QuartzWarrior** [comment]
```Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dpiped-backend%22%3Atrue%7D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied```
When running `docker-compose up -d`.
OS info: Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1025-oracle aarch64)

**Comment by FireMasterK** [comment]
You have docker setup without permissions for your user, maybe run it as root, or add your user to the docker group.

**Comment by QuartzWarrior** [comment]
k, thx
