### ISSUE TITLE
Peertube support

### ISSUE THREAD

**Issue by Axeltherabbit** [TeamPiped/Piped#659]
I would like to have peertube supported like NewPipe has.

**Comment by Loki-L1130** [comment]
They do support LBRY for Channels which already have one there. Like All Things Secured, The Linux Experiment, Techlore. So, I think this could be the best bet.

**Comment by FireMasterK** [comment]
There are no plans to support Peertube, I want to keep Piped focussed on YouTube. If I wanted to support other platforms, (such as twitch, for example, I would create another frontend).

For LBRY support, the video is played from LBRY instead of YouTube, but the actual content is from YouTube.
