### ISSUE TITLE
Videos sometimes just skip ahead

### ISSUE THREAD

**Issue by flexagoon** [TeamPiped/Piped#673]
Sometimes I watch a video on Piped, and it just randomly skips a minute or two. That is very annoying since I have to manually go back to where it was.

**Comment by FireMasterK** [comment]
This is actually because of [SponsorBlock](https://sponsor.ajay.app/) and is intended behaviour since it's enabled by default. You can disable it in the Preferences menu.

**Comment by flexagoon** [comment]
Thanks!
