### ISSUE TITLE
feature request: clickbait remover (DeArrow integration)

### ISSUE THREAD

**Issue by fawni** [TeamPiped/Piped#678]
[pietervanheijningen/clickbait-remover-for-youtube](https://github.com/pietervanheijningen/clickbait-remover-for-youtube)

basically replaces the thumbnail with a frame in the video (start, middle or end of the video) and formats the title to all lowercase or capitalized sentences/words

**Comment by FireMasterK** [comment]
> I am also interested in this. What are your thoughts on this idea @FireMasterK 

I'd accept a PR for this, I have other things with higher priority currently unfortunately.

**Comment by float3** [comment]
This would be a good feature

**Comment by Insprill** [comment]
Is this still relevant now that there's support for DeArrow?

**Comment by fawni** [comment]
i can't get the DeArrow feature to work personally but if that's somehow on my end then yes this issue should be closed

**Comment by Insprill** [comment]
As far as I know (and correct me if I'm wrong), DeArrow only works in the Piped UI, not in other apps (e.g. Yattee) unless it's implemented there. It's been working fine for me on my instance, and on the official instance.

**Comment by fawni** [comment]
tried again just now and it worked! closing

**Comment by float3** [comment]
I would still like this to be implemented
