### ISSUE TITLE
Error 403 using tor

### ISSUE THREAD

**Issue by loclaess** [TeamPiped/Piped#687]
The rss feed can't be accessed using a tor socks5 proxy :

Error while retrieving http://pipedapi.kavin.rocks/feed/rss?authToken=*** : HTTP response code said error 403

The problem seem to be cloudflare trying to verify If I'm humain, but no human is gonna want to read an rss raw xml anyway.

**Comment by FireMasterK** [comment]
Could you try now? There's been a change to the firewall rules.

**Comment by loclaess** [comment]
It works perfectly, thanks you very much! Didn't expect instant resolution :D
