### ISSUE TITLE
RSS feed has no link

### ISSUE THREAD

**Issue by loclaess** [TeamPiped/Piped#688]
Hello, this is an exemple of rss entry from my feed :

` <entry>

    <title>[Découverte] TIMBERBORN - Un castor dans la brume!</title>

    <author>

      <name>Bazar du Grenier</name>

      <uri>https://pipedapi.kavin.rocks/channel/UCCMxHHciWRBBouzk-PGzmtQ</uri>

    </author>

    <id>https://pipedapi.kavin.rocks/watch?v=k-IsttGiTr0</id>

    <updated>2021-12-19T17:00:24Z</updated>

    <published>2021-12-19T17:00:24Z</published>

    <dc:date>2021-12-19T17:00:24Z</dc:date>

  <entry>`

\<uri> and \<id> have the channel and video link but those are pipedapi link.
Would it be possible to have a \<link> entry with a reference to the piped [video](url) link?

Right now my rss feed reader only show the following and doesn't have any link to open.

>Feed: Piped - Feed
>Title: [Découverte] TIMBERBORN - Un castor dans la brume!
>Author: Bazar du Grenier
>Date: Sun, 19 Dec 2021 18:00:24 +0100

**Comment by Loki-L1130** [comment]
Refer #321

**Comment by FireMasterK** [comment]
Should be fixed with https://github.com/TeamPiped/Piped-Backend/pull/149 and https://github.com/TeamPiped/Piped-Backend/pull/150.
