### ISSUE TITLE
Does RSS feeds work?

### ISSUE THREAD

**Issue by lua-rocks** [TeamPiped/Piped#698]
I subscribed to RSS feeds through my email client (Claws Mail with RSS plugin) to see notifications of new videos, but new videos are coming out without notifications and I can't figure out why. I also subscribe to several feeds from other sites and they works fine.

**Comment by unbeatable-101** [comment]
When I used it with thunderbird, there wasn't a link to the videos, but now the feed doesn't even validate.
<img width="1079" alt="Screen Shot 2021-12-24 at 15 27 01" src="https://user-images.githubusercontent.com/58151048/147371538-fb6cfaef-46bf-4052-ab99-869f63b307bc.png">

**Comment by FireMasterK** [comment]
Is there any tool to validate a feed?

**Comment by FireMasterK** [comment]
Related: https://github.com/TeamPiped/Piped-Backend/pull/150

**Comment by unbeatable-101** [comment]
> Is there any tool to validate a feed?

Oh yeah, I meant to post the link https://validator.w3.org/feed/

**Comment by FireMasterK** [comment]
Let me know if there are any more issues!

**Comment by lua-rocks** [comment]
@FireMasterK Thank you so much! Everything works perfect now 😊
