### ISSUE TITLE
Timestamps with "s" at the end of link don't work

### ISSUE THREAD

**Issue by Latrolage** [TeamPiped/Piped#706]
https://piped.kavin.rocks/watch?v=zsdPYFPTdw0&t=2000s

https://piped.kavin.rocks/watch?v=zsdPYFPTdw0&t=2000

Top one does not work like the button one.

**Comment by FireMasterK** [comment]
This will be fixed when https://github.com/TeamPiped/Piped/pull/683 is merged.
