### ISSUE TITLE
localhosting could be more convenient

### ISSUE THREAD

**Issue by Broeckelmann** [TeamPiped/Piped#710]
Would be nice if I could localhost this like nitter, bibliogram, libreddit, etc. with a simple prebuild one liner.
For example Libreddit `docker run -d --restart unless-stopped --name libreddit -p 6060:8080 spikecodes/libreddit` and I can instantly go on localhost:6060 and throw it into the privacy redirect plugin. 

Something like that would be really neat and probably increase number of users and maybe reduce traffic on the main-instance piped.kavin.rocks, which could save some money but I don't know how expensive the server is so it's just a guess. 

Would this be possible or too hard to implement? (maybe something nitter-style like could work with just one .conf file)

**Comment by FireMasterK** [comment]
Piped isn't really designed to be locally hosted, it requires multiple services in docker - the frontend, the backend, Postgres (/ another database supported by Hibernate), ytproxy, and finally, optional but highly recommended for public use - varnish.

It was designed to be horizontally scalable, which is the reason for the complexity.

**Comment by mmjee** [comment]
With that being said it's not impossible to locally host, you could totally configure api.piped.localhost as 127.0.1.1 and run the backend on that, and likewise for all other services.

**Comment by Broeckelmann** [comment]
Okay, thanks for answering. 👍

**Comment by sdfg2** [comment]
I think one of the backends needs public access for pubsub support.  But then, pubsub should be optional imo.
