### ISSUE TITLE
FF 95.0.2 all background videos start whenever a new one does

### ISSUE THREAD

**Issue by bradmurray** [TeamPiped/Piped#712]
On firefox 95.0.2 on OSX if I have paused videos in other tabs any time I open a new video (on piped.kavin.rocks) all of the background videos also start. It happens every time I start a new video.

**Comment by FireMasterK** [comment]
Hi,

This is intensional behaviour since this is currently the auto-updating mechanism. (all tabs reload to update)

I'm looking at ways to improve this in the future.

**Comment by Loki-L1130** [comment]
But it seems to be often, When I have loaded about 10 Tabs. The tab reloads about 3 Times within 5 Minutes.
