### ISSUE TITLE
Add piped.mint.lgbt to the instance list

### ISSUE THREAD

**Issue by mintphin** [TeamPiped/Piped#715]
Hi! I'm now hosting a new instance for Piped. Could you please add it to the instance list?

**Instance Name:** piped.mint.lgbt
**Instance API URL:** https://pa.mint.lgbt/
**Instance Location(s):** 🇨🇦
**CDN:** No

Thank you!

**Comment by FireMasterK** [comment]
Added, thanks for hosting!
