### ISSUE TITLE
Concerns about bandwidth

### ISSUE THREAD

**Issue by NebulaBC** [TeamPiped/Piped#717]
I have been thinking about setting up a piped instance (already running but private) and putting it behind a CDN. If I go to this effort I would consider making it public, although I use azure edge CDN (not the cheapest) and am concerned about how much bandwidth the insurance would use, with the video proxy and all. How much bandwidth does the official or other public instance use?

On a similar topic, what would I have to do to block bots on caddy. On invidious I had to have a running copy of Nginx bad bot blocker, but what would I need for caddy?

And as a bonus to make this question a three parter, when I set up my instance with a cdn, where will I have to point it? My azureedge domain or the custom domain added to it (or somewhere in between) should I cdn just the api or the proxy and front end too

**Comment by unixfox** [comment]
The bandwidth usage highly depends on the amount of users. What is going to be very bandwidth intensive is the proxy of the video stream from YouTube to the users.

According to the [donation page](https://liberapay.com/kavin) of piped:
> Piped handles 5 TB of ingress bandwidth every day

But this is when thousands of users are using the instance. Yours is going to have a very small amount at first if it is not popular, so you can't expect that much bandwidth usage.

I would highly not recommend hosting that on Azure (nor on any expensive cloud provider) when the bandwidth is very pricey though.

About caddy and blocking bots, you aren't required to use caddy. You can host piped with NGINX: https://piped-docs.kavin.rocks/docs/self-hosting/

**Comment by NebulaBC** [comment]
Ok, In that case I will keep my instance private for now. About caddy, I’m interested in using it, I was just asking what I would use to block scrapers and bots. I know that I could use nginx but I was curious if you needed a blocklist or if it was pre set up like let’s encrypt is with caddy

**Comment by FireMasterK** [comment]
Hey Nebula, sorry for the late response.

While hosting Piped, only the API has to be cached by the CDN, so the bandwidth usage with the CDN would be insignificant since it's just JSON content.

However, the video playback's proxy uses a lot of bandwidth. (5TB ingress, and 4TB egress) If you're using Azure's compute services for hosting the backend and proxy instances, that will be extremely expensive since Azure charges up to $0.12 per GB of egress bandwidth depending on the region.

I hope this answers your question!

**Comment by NebulaBC** [comment]
I use the US east region, so it costs $0.0475 USD (100GB/$4.75). Which is pretty reasonable pricing for me, as long as it stays at like 1TB per month or less, which seems practical for a instance that is not being advertised (at least from what I would guess).

**Comment by FireMasterK** [comment]
I forgot to mention, those bandwidth figures are per day! I would highly recommend using a different hosting provider for public usage, such as [BuyVM](https://buyvm.net/kvm-dedicated-server-slices/) or even [Hetzner](https://www.hetzner.com/cloud), which doesn't charge per GB of bandwidth.

**Comment by NebulaBC** [comment]
> I forgot to mention, those bandwidth figures are per day! I would highly recommend using a different hosting provider for public usage, such as [BuyVM](https://buyvm.net/kvm-dedicated-server-slices/), [OVH](https://www.ovhcloud.com/en/vps/) or even [Hetzner](https://www.hetzner.com/cloud), which doesn't charge per GB of bandwidth.

Thank you for the suggestion. I think for now I will stay private, and maybe change to a different host if I ever make it public.
