### ISSUE TITLE
Add sponsorblock section in preferences

### ISSUE THREAD

**Issue by B0pol** [TeamPiped/Piped#72]
In this section, you should be able to:
- [x] enable / disable sponsorblock completely
- [x] enable / disable some specific categories
- [ ] change API url

**Comment by FireMasterK** [comment]
Changing API url would be a though one, considering it's done server side (K-anonimity hash calculations)

**Comment by FireMasterK** [comment]
I'm considering downloading and using the database instead of using the API, this way we won't be affected by downtimes. (like how it is down currently.)

**Comment by FireMasterK** [comment]
I'm not too keen on allowing to change the API URL currently, for now, everything else is implemented.
