### ISSUE TITLE
Not playing properly on Ubuntu Firefox

### ISSUE THREAD

**Issue by dik23** [TeamPiped/Piped#724]
Firefox 96.0 (64-bit).  Ubuntu 20.04

Videos play for around 5-6s before the picture freezes and the sound continues, even when using private windows.  The same video plays fine on Chromium Version 97.0.4692.71 (Official Build) snap (64-bit)

This is pretty inconsistent but if I take [this video](https://piped.kavin.rocks/watch?v=qHVkD3_fPtk) as an example the first time I open the url in Firefox it freezes at around 5-6s.  The video always plays fine in Chromium.  I have had it play ok a couple of times while bug spotting here but it usually fails.  Other videos seem to work sometimes but not others

I have found the same across different instances of Piped

**Comment by Latrolage** [comment]
Do you have vaapi enabled? If you open console, what does it say when it freezes?

**Comment by dik23** [comment]
Setting media.ffmpeg.vaapi.enabled to false fixed it.  Thanks for your help
