### ISSUE TITLE
issue with frontend "No such file or directory"

### ISSUE THREAD

**Issue by sebastianmuell** [TeamPiped/Piped#729]
I encounter the following issue with the latest piped-frontend image from 1337kavin/piped-frontend:

`sed: /usr/share/nginx/html/js/*: No such file or directory`

Steps to reproduce:

git clone https://github.com/TeamPiped/Piped-Docker
cd Piped-Docker
./configure-instance.sh
docker-compose up -d

**Comment by FireMasterK** [comment]
You seem to have an old version of the templates, run the following:
```
cd Piped-Docker
git pull
./configure-instance.sh
docker-compose down && docker-compose up -d
```
that should fix your issue!

**Comment by sebastianmuell** [comment]
Thank you very much,  the commands fixed the issue!
