### ISSUE TITLE
[REQUEST] Search Mode

### ISSUE THREAD

**Issue by merlin555** [TeamPiped/Piped#734]
Hello,

Can you please at "Content of Main page",
add the "Search" mode ?

Can you add a Quick Access feature for the "Search" Mode ?
I often have problems with my MediaPlayerbox, (Zidoo Z1000 Pro + Tonix)
use the buttons to go to "Search" icon.
Mouse Mode is awkward with my players.
I have Android on my players (9.x and 7.x)

Thanks !

I'm totally excited about your app !
Keep it up..

Greetings..

 Merlin

**Comment by FireMasterK** [comment]
I'm sorry, but I don't understand what you mean by switch the windows

**Comment by merlin555** [comment]
Sorry, my English is not so good.

I have just edited this point in the post and taken away.
Is not important.

Thank you !
