### ISSUE TITLE
Videos unplayable on iOS

### ISSUE THREAD

**Issue by Mennaruuk** [TeamPiped/Piped#74]
Videos are unplayable on iOS. Tested on iPhone X. Also the design is a bit off at the top, both in portrait and landscape layouts.

![9DBF0F9C-21F3-4643-9845-F87148A8397A](https://user-images.githubusercontent.com/52135169/109181212-ac36cf80-7759-11eb-91dc-93762f5adfe3.jpeg)

**Comment by FireMasterK** [comment]
According to this image, it should be supported 🤔
![image](https://user-images.githubusercontent.com/20838718/109186893-64469580-77b7-11eb-94a8-f7bdc650f22b.png)

I don't have an iOS device, testing/debugging this would be quite difficult for me.

**Comment by Mennaruuk** [comment]
I'm thinking this is because of webm. [iOS cannot play webm](https://news.ycombinator.com/item?id=16319651).

**Comment by FireMasterK** [comment]
https://9to5mac.com/2021/02/18/apple-adds-webm-video-playback-support-to-safari-with-macos-big-sur-11-3/

It should work soon then 😃

Let me know what it shows here: https://www.webmproject.org/detect/

**Comment by FireMasterK** [comment]
In addition, I believe the player will automatically fall back to mp4 incase it can't play webm, which means it's likely not the issue here

**Comment by Mennaruuk** [comment]
> https://9to5mac.com/2021/02/18/apple-adds-webm-video-playback-support-to-safari-with-macos-big-sur-11-3/
> 
> It should work soon then :smiley:

Wow, this is quite recent. Thank you for alerting me to it! The more you know.

> Let me know what it shows here: https://www.webmproject.org/detect/

![F2CC5DE5-A6F8-4C9B-BD64-D0CC8143](https://user-images.githubusercontent.com/52135169/109212155-2c226100-777d-11eb-8480-0ec1eee097de.jpg)

> In addition, I believe the player will automatically fall back to mp4 incase it can't play webm, which means it's likely not the issue here

Yeah, I wouldn't rule out a problem with iOS Safari. It can get pretty sucky at playing videos sometimes.

**Comment by RouterCFW** [comment]
iOS videos work completely fine for me

**Comment by Mennaruuk** [comment]
> iOS videos work completely fine for me

Do you know how you got them to work? I'm still getting no playback.

https://user-images.githubusercontent.com/52135169/112737324-1779ea00-8f30-11eb-8705-fcd97aaf3817.MP4

**Comment by RouterCFW** [comment]
I’m on iOS 14.5 developer beta so maybe that’s the difference I’m not sure

**Comment by RouterCFW** [comment]
Also I use the https version of the site

**Comment by Mennaruuk** [comment]
Yeah, I think this issue might be resolved in an upcoming iOS update. I tried HTTPS, but the problem persisted. Thanks for debugging this!

**Comment by FireMasterK** [comment]
That's great to know!

**Comment by lewis149** [comment]
I'm also on iOS 14.5 beta and I can't play anything either.

**Comment by mmarfil** [comment]
Any chance to have videos to fallback to mp4? It seems rather unlikely iOS will support webm, not even the last iOS 15 beta seem to… 🙃

**Comment by FireMasterK** [comment]
The thing is it should already be doing so.

However since I don't use a IOS device, I have no idea what may be wrong.

You may use https://developer.apple.com/safari/tools/ to show me the exact error which occurs in the console tab.

**Comment by swgrrt** [comment]
I have an iPhone 6s and a 6th gen iPad both running iOS 14.6 / iPadOS 14.6.
On the iPad I can play videos just fine, but on the iPhone I have the issues described above.
Is there anything I can do on my devices to help solve this issue?

**Comment by FireMasterK** [comment]
> Is there anything I can do on my devices to help solve this issue?

You may use https://developer.apple.com/safari/tools/ to show me the exact error which occurs in the console tab.

Just a screenshot should be enough usually.

I can't do this myself since I don't own use any iOS devices.

**Comment by swgrrt** [comment]
Normally you need a MacOS computer with Safari for using these developer tools. Although I found this guide on how to use them on linux: [https://onestepcode.com/debugging-ios-on-linux/](url)

With the iPhone 6s I got the following output in the console (see also the attached screenshot):
`​ Unhandled Promise Rejection: shaka.util.Error {
  "severity": 2,
  "category": 3,
  "code": 3016,
  "data": [
    4,
    null,
    null
  ],
  "handled": false
}
(anonymous) @ [native code]:1
promiseReactionJob @ [native code]:1
AKedOLQbbFXXb2bcVnVmqakf11QDKfc-fm4L-rwQrZYiXg=s176-c-k-c0x00ffffff-no-rw:1 GET https://pipedproxy-ams.kavin.rocks/ytc/AKedOLQbbFXXb2bcVnVmqakf11QDKfc-fm4L-rwQrZYiXg=s176-c-k-c0x00ffffff-no-rw?host=yt3.ggpht.com 400`
![iPhone6s](https://user-images.githubusercontent.com/67275401/124479954-0f3f0f80-dda7-11eb-81d8-2f6bfac1c923.png)


With the iPad this is the console output:
`AKedOLQbbFXXb2bcVnVmqakf11QDKfc-fm4L-rwQrZYiXg=s176-c-k-c0x00ffffff-no-rw:1 GET https://pipedproxy-ams.kavin.rocks/ytc/AKedOLQbbFXXb2bcVnVmqakf11QDKfc-fm4L-rwQrZYiXg=s176-c-k-c0x00ffffff-no-rw?host=yt3.ggpht.com 400`
![iPad](https://user-images.githubusercontent.com/67275401/124479963-123a0000-dda7-11eb-8869-284bd6e21a2a.png)

I hope that this information is useful. If you need any further investigation just let me know.

**Comment by FireMasterK** [comment]
Could you try the same thing, but on https://1789f5b0.piped.pages.dev/?

It basically contains a debug build of shaka-player, which will give me logs that I can report to shaka-player with.

**Comment by swgrrt** [comment]
There you go :)

iPhone 6s log file: 
[iPhone6s_1789f5b0.piped.pages.dev-1625514166700.log](https://github.com/TeamPiped/Piped/files/6766048/iPhone6s_1789f5b0.piped.pages.dev-1625514166700.log)

iPad log file:
[iPad_1789f5b0.piped.pages.dev-1625514254028.log](https://github.com/TeamPiped/Piped/files/6766049/iPad_1789f5b0.piped.pages.dev-1625514254028.log)

**Comment by FireMasterK** [comment]
I've figured out the issue thanks to the guys over at Shaka-Player.

iOS does not support MSE (Media Source Extensions), a key component required for Dash.

As a solution for this, I will add a way to play the muxed streams (limited to 720p and 360p). I hope in the future iOS adds support for MSE, because iPad OS already supports them.

**Comment by FireMasterK** [comment]
Could someone test https://993b00d3.piped.pages.dev/?

This version should technically fix the issue

**Comment by swgrrt** [comment]
> Could someone test https://993b00d3.piped.pages.dev/?
> 
> This version should technically fix the issue

Yes, on this site the videos play without issues on my iPhone 6s.

Thanks a lot :)

**Comment by FireMasterK** [comment]
Thanks for testing!

This should be fixed now! :)
