### ISSUE TITLE
Some videos dont play in opera

### ISSUE THREAD

**Issue by IvRRimum** [TeamPiped/Piped#750]
https://piped.kavin.rocks/watch?v=fx2ibMnQZdY&t=5s

Opera, really anoying(have to open with firefox for this video).

**Comment by FireMasterK** [comment]
I could not replicate this on Opera on Linux. Version: 83.0.4254.19
The video plays as expected, please take a look at the JavaScript console logs to see if there's anything

**Comment by FireMasterK** [comment]
Closing due to the lack of a response.
