### ISSUE TITLE
 Error in Minimize/Show Recommendations buttons

### ISSUE THREAD

**Issue by milotype** [TeamPiped/Piped#751]
**Problem:**
It seems to me, that the functions for the buttonts `Minimize Recommendations` and  `Show Recommendations` are swapped and should work exactly opposite of how they work currently.

- Currently, when `Minimize Recommendations` is active, there are no recommendations listed below.
![Minimize Recommendations](https://user-images.githubusercontent.com/43657314/150518768-5d26b166-73e9-4d67-a51f-401cad4f7de7.png)

- Currently, when `Show Recommendations` is active, recommendations are listed below.
![Show Recommendations](https://user-images.githubusercontent.com/43657314/150518781-7b3fa1f3-c8e1-417e-8d4e-c2155d8bab1f.png)

**Solution:**
The buttonts `Minimize Recommendations` and  `Show Recommendations` should work exactly opposite of how they work currently. Pressing the first one should hide the recommendations, pressing the second one should show them.

**Comment:**
The buttons `Minimize Description` and `Show Description` work as expected! Pressing the first one hides the descriptions, pressing the second one shows them.

**Comment by FireMasterK** [comment]
It's correct and is the expected behaviour, "Show Recommendations" is displayed when the recommendations are already hidden, and vice versa for "Minimize Recommendations".

**Comment by milotype** [comment]
@FireMasterK OK, sorry for the confusion. I thought that "Recommendations" is the textual part (the comments), but they are obviously the listed "recommended" videos.
Sorry again.
