### ISSUE TITLE
Time gets blurry when seeking

### ISSUE THREAD

**Issue by Mennaruuk** [TeamPiped/Piped#755]
Behavior on Piped:

https://user-images.githubusercontent.com/52135169/150648613-9244ac32-71cd-4029-b275-4b9e7c8007a5.mp4

Behavior on YouTube:

https://user-images.githubusercontent.com/52135169/150648598-5b5fb9a6-f8a9-40c7-89ca-86fb4f84bf35.mp4

Thank you FireMasterK!

**Comment by FireMasterK** [comment]
Should be closed with c87af466c85180768e8f9a465dfa12f2865e5e6c.
