### ISSUE TITLE
Any hope for a solution to slow and non-continuous buffering?

### ISSUE THREAD

**Issue by Yolakalemowa** [TeamPiped/Piped#758]
First thank you for this awesome project! 

But I'm struggling to stick to it and recommend it due to how slow it is compared to YT and the fact that it doesn't continue to buffer when it's paused and only buffers short segments. 

I also find that I have to keep refreshing the page cause it very often gets stuck buffering... :(

Is there any hope to solve that?

**Comment by FireMasterK** [comment]
I'd recommend setting a default quality in the selector, and increase the buffering time to 120 seconds, it should help significantly.

**Comment by IceDBorn** [comment]
@FireMasterK The buffering time resets all the time for me

**Comment by FireMasterK** [comment]
> @FireMasterK The buffering time resets all the time for me

Hence why you should set a default quality, when the quality changes due to the abr, the buffer is cleared.

**Comment by Yolakalemowa** [comment]
> I'd recommend setting a default quality in the selector, and increase the buffering time to 120 seconds, it should help significantly.

thanks I will try that for a while and see if it improves the situation. Btw is there a way to save preferences without logging in?

**Comment by FireMasterK** [comment]
> thanks I will try that for a while and see if it improves the situation. Btw is there a way to save preferences without logging in?

Yes, preferences are stored locally on your computer.

**Comment by Yolakalemowa** [comment]
> > thanks I will try that for a while and see if it improves the situation. Btw is there a way to save preferences without logging in?
> 
> Yes, preferences are stored locally on your computer.

then it must be that hardened (ArkenFox user.js) Firefox is the reason it's resetting every time?

**Comment by FireMasterK** [comment]
> then it must be that hardened (ArkenFox user.js) Firefox is the reason it's resetting every time? 
> 

It must be, Piped uses the localStorage API to store preferences.
