### ISSUE TITLE
Default Homepage(feed) not working

### ISSUE THREAD

**Issue by Addictc** [TeamPiped/Piped#770]
I've changed the default homepage to feed instead of trending, however when I click the piped logo I still get sent to trending

**Comment by Loki-L1130** [comment]
Yes, This is happening on other instances like @TheSilkky. But when you enter via URL or Bookmark it goes to feed when set as Homepage. It happens only when clicking the Piped Logo as mentioned.

**Comment by FireMasterK** [comment]
Closing with 826bdf4997a5ea9efb4d8aa21f5b88e6cf9089d7.
