### ISSUE TITLE
[Feature Request] Continuous scrolling for feed

### ISSUE THREAD

**Issue by KidoVin01** [TeamPiped/Piped#771]
Currently the feed seems to only show videos up till 1 week old.

It would be nice user can continuously scroll through old feed, similar to how it works in individual channels.

**Comment by FireMasterK** [comment]
That's impractical since that would require making 100s of requests concurrently per request, however I could increase the feed retention to something larger, like a month.

**Comment by KidoVin01** [comment]
(Low Priority) I am not sure how the backend for Piped works but maybe the functionality could be referenced from Freetube and/or Newpipe since they are able to provide such functionality.

**Comment by FireMasterK** [comment]
You now get 30 days of feed :tada:

**Comment by KidoVin01** [comment]
I seem to still have only 2 week old feeds. 
I cleared cookies and cache on Firefox and it did not seem to fix it.

**Comment by FireMasterK** [comment]
The old feed retention was 10 days, it's been 2 days since the fix, you will have to wait 18 more days to have a month's worth of feed.
