### ISSUE TITLE
Add a small badge to indicate a video is a live stream

### ISSUE THREAD

**Issue by vachan-maker** [TeamPiped/Piped#772]
- It would be useful to add a small badge or icon to indicate if a video is a livestream.
- In the channel video page, top priority could be given to a livestream video and it will be helpful if this video is displayed first.

Currently the best way to tell if a video is a livestream is by looking at the timestamp, it shows -1:59 or by looking at the thumbnail/title.
![image](https://user-images.githubusercontent.com/65799568/151661425-0db9c7d8-3c7f-4882-86c7-f59c76bcced1.png)
![image](https://user-images.githubusercontent.com/65799568/151661452-978295c1-cab9-4891-9937-354f995a9260.png)

**Comment by FireMasterK** [comment]
Closing this with 9b18f2eff2b84059cf657e0e168587160623324e.
