### ISSUE TITLE
Change the button bg-color in light mode

### ISSUE THREAD

**Issue by rootedetc** [TeamPiped/Piped#777]
When light mode is applied, the text on certain buttons is quite unpleasant to read.

**Currently**:

<img width="508" alt="Screenshot 2022-02-01 at 14 10 13" src="https://user-images.githubusercontent.com/61841347/151975224-e89bfff7-3fd6-489a-a783-c04696fbc5aa.png">

I recommend changing the bg-color (when light mode is applied) to a brighter color.

**Recommended change**:

<img width="509" alt="Screenshot 2022-02-01 at 14 12 10" src="https://user-images.githubusercontent.com/61841347/151975291-118391d6-7510-4004-8b72-31fc851b3422.png">

The one I used is `#e8e8e8`, and I would also recommend changing the bg-color of the search form to have color consistency.

**Comment by FireMasterK** [comment]
You should clear your site data / remove the service worker.

It should look like this after:
![image](https://user-images.githubusercontent.com/20838718/152102649-c5436987-aeab-4325-97ad-eff65331dab0.png)
