### ISSUE TITLE
Cookie(s) rather than localStorage for Options

### ISSUE THREAD

**Issue by Cade66** [TeamPiped/Piped#778]
Hi,

Best first : Piped is truly amazing. I've tested it with YouTube videos, channels and even live streams : all open flawlessly (tested with `piped.kavin.rocks` only).
No lag, brilliant. Up to now Piped seems to be far more reliable than Invidious servers, even the two of them I consider over time as the best (`invidious.snopyta.org` and `yewtu.be`), proxy option enabled (of course).

Question secondly : registered or not, options are saved in the user's localStorage. This is bothering for anyone clearing Offline website data on Firefox exit. Maybe are options handled by a 3rd-party cookie? I block 3rd-part cookies if that's the culprit.

You won't switch to cookies just for me so the question is : are there any parameters (as with Invidious) I could add to piped (page, redirection) to include at least some of the options (I have in mind mainly _comments_, _playerAutoPlay_ and _quality_.)

Thanks!

**Comment by FireMasterK** [comment]
Hey, I have added a page in the documentation to address all the available URL parameters at https://piped-docs.kavin.rocks/docs/parameters/

Hope it helps!

I don't think I will be replacing the usage of localStorage with cookies as that would require a lot of rewriting of code, and would add a Cookie header for each request, which could potentially be used to track users, so I won't be doing that.

**Comment by Cade66** [comment]
That documentation on URL parameters for _Pipe_ is exactly what I was searching for, sure does help, thanks!
I had searched, didn't find. But searching is not my first quality :=)
Long life to Piped, and bravos to the team.

**Comment by FireMasterK** [comment]
> I had searched, didn't find

That's because I had added it just prior to posting that comment :P
