### ISSUE TITLE
Instances in a json file

### ISSUE THREAD

**Issue by ManeraKai** [TeamPiped/Piped#787]
It's for [LibRedirect](https://github.com/libredirect/libredirect). We have an automatically updatable [lists file](https://github.com/libredirect/instances/blob/main/data.json). We need the instances to be in a json file for it to work if you can.

**Comment by FireMasterK** [comment]
You should be able to parse the markdown file using code, an example of how it's done in the frontend is available at https://github.com/TeamPiped/Piped/blob/85e2296dc410fd20375d623465900c55b5483da9/src/components/Preferences.vue#L202-L221.

**Comment by ManeraKai** [comment]
That list only contains api links.

**Comment by ManeraKai** [comment]
Also, this one isn't working fine: https://piped.moomoo.me

**Comment by ManeraKai** [comment]
@FireMasterK ?

**Comment by Loki-L1130** [comment]
> Also, this one isn't working fine: https://piped.moomoo.me

May be you could leave it as a Broken Instance. And check back later if it works and re-add it to the Instance list.

**Comment by ManeraKai** [comment]
> May be you could leave it as a Broken Instance.

I did that, but I need an automated way of doing it to make the extension reliable, I don't want to guess every subdomain. Just a simple list with all the public instances like what invidious has: https://api.invidious.io/

**Comment by Loki-L1130** [comment]
You mean like this Link for Invidious, Piped should have one like this or a `.json` file in the repo. Which will be easy for developers - right ?

**Comment by ManeraKai** [comment]
yes

**Comment by FireMasterK** [comment]
> That list only contains api links.

This is to be expected since, I don't want to have to deal with policing AGPL violations, like how Invidious does currently. I've iterated this before at https://github.com/TeamPiped/Piped/issues/716#issuecomment-1008289541

You can force the frontend to use a specific instance, for example like: `https://piped.kavin.rocks/watch?v=yrGR11TDRYM&instance=https://api.piped.silkky.cloud`

**Comment by FireMasterK** [comment]
https://piped-instances.kavin.rocks/ now exists.

**Comment by ManeraKai** [comment]
> https://piped-instances.kavin.rocks/ now exists.

I'll use it but it won't be all automated. ex: https://pa.mint.lgbt/ web interface is https://piped.mint.lgbt/
