### ISSUE TITLE
SponsorBlock feature request

### ISSUE THREAD

**Issue by ThomasDNguyen** [TeamPiped/Piped#788]
Hi, just wanna say thanks for maining such an awesome project.  
.
Also, I'd like to make some QoL feature request to how SponsorBlock is implemented in piped.  
- It would be nice if the sections that will be skipped is highlighted in the timeline and the user can choose to skip them either always or manually with a hotkey.
- I noticed that if I click on the timeline to go to a certain section, the current implementation of SB in piped will no longer work. I think this should be changed because it's very common for people to either fastforward or rewind by clicking on the timeline.

**Comment by danielriddell21** [comment]
To rework your 1st point, maybe having the option in the settings to choose prompt. This would give the user the option to skip or not https://github.com/TeamPiped/Piped/issues/894
