### ISSUE TITLE
Video pauses when using Keys.

### ISSUE THREAD

**Issue by Loki-L1130** [TeamPiped/Piped#789]
When Playing a Video in Piped, and if I want to adjust the Audio using the Up and down arrow keys. Video pauses automatically and this is so annoying in my Opinion.

**Comment by FireMasterK** [comment]
Any way to replicate this issue? I tried using Brave on Linux, and it works just fine.

**Comment by Loki-L1130** [comment]
I am using the Silkky Instance. Just watch some video. While the video is playing Try to increase the volume using Up and down arrow keys. The Video pauses.

**Comment by Loki-L1130** [comment]
@TheSilkky The Issue works. Thanks for looking into this. But why so late ?

**Comment by TheSilkky** [comment]
@Loki-L1130 Someone in my Discord server told me about this today

**Comment by Loki-L1130** [comment]
> @Loki-L1130 Someone in my Discord server told me about this today

I see, So, you don't check notifications regularly in Github.

What was the cause actually ?
