### ISSUE TITLE
[Feature request] Setting to use Youtube embeded video player

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#794]
Please add an setting to use the Youtube embedded video player to watch videos on Piped and not have Piped grab and process the videos for the users privacy.

I use Brave for a browser, a VPN and other privacy technologies and I am not afraid of using Youtube or connecting to it. However I like Piped for its degoogled subscription feed to Youtube channels. Such a setting can help reduce the load on a Piped server for not needing to process the video for the users privacy.

**Comment by Loki-L1130** [comment]
You mean like the YouTube Player that Invdious uses. Your comment seems somewhat confusing eventhough I do get a grasp. Elaborate if you could.

**Comment by Loki-L1130** [comment]
You mean If you want to use Piped Player in the pages that YouTube embedded videos. Use Privacy Redirect or wait for Libredirect to support chromium in few releases.

**Comment by FireMasterK** [comment]
Hey, this will not be supported since the following:
1. Not all videos can be played in an embedded player
2. Google still tracks you, using cookies and JS event logging

**Comment by trymeouteh** [comment]
Does the audio or video player on Piped require server processing or is all done client side on the users end in the browser? That is the only reason for this suggestion to make instances not requiring as much resources to stay online.

**Comment by FireMasterK** [comment]
> Does the audio or video player on Piped require server processing

They do require server processing, however, that shouldn't be a problem unless you have bandwidth restrictions.

**Comment by trymeouteh** [comment]
Does it process the entire video file itself or just metadata?

**Comment by FireMasterK** [comment]
> Does it process the entire video file itself or just metadata?

The video is streamed.

**Comment by trymeouteh** [comment]
An alternative to consider
https://github.com/TeamPiped/Piped/issues/1835

**Comment by trymeouteh** [comment]
https://github.com/TeamPiped/Piped/issues/990
