### ISSUE TITLE
Comment YouTube Link

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#799]
Please add a Youtube Link for every comment in the comment section

For Example
https://www.youtube.com/watch?v=v2AC41dglnM&lc=Ugjwdns-pGdDMngCoAEC

**Comment by Loki-L1130** [comment]
Good First Issue but AFAIK youtube doesn't do this. Maybe it does as I haven't ever gone to youtube since I started using Piped.

**Comment by FireMasterK** [comment]
YouTube doesn't do this, and NewPipeExtractor doesn't support this, I'll reconsider/revisit this when things change.

**Comment by trymeouteh** [comment]
Its a feature on Invidious comments, you will see a YouTube link on every comment in invidious
