### ISSUE TITLE
Channel Tabs

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#802]
Please add the tabs that are available on channels youtube page such as Videos, Playlists, Community, Channels, About

**Comment by Loki-L1130** [comment]
This is pretty much the 
Duplicate of #550

**Comment by FireMasterK** [comment]
I'd want this to be added upstream in NewPipeExtractor first - https://github.com/TeamNewPipe/NewPipeExtractor/issues/501
