### ISSUE TITLE
Channel & Playlist View On Youtube Button

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#803]
Please add a button on channel pages & playlist pages to view the channel/playlist on youtube.com

**Comment by Loki-L1130** [comment]
Please elaborate about channel pages.

Playlist is currently being in the works. You can view a Playlist in Piped but you can play in a order or shuffle the order.

**Comment by Loki-L1130** [comment]
I get it, now.

**Comment by thecashewtrader** [comment]
I could implement this, blocked for the same reason as https://github.com/TeamPiped/Piped/issues/1611#issuecomment-1296262909

**Comment by thecashewtrader** [comment]
@FireMasterK could you close this too? It doesn't seem to be closed automatically.
