### ISSUE TITLE
Hide Videos On Homepage, Recommended Videos Settings

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#806]
To make Youtube less addictive, please add settings to show/hide the following...

- Videos on Homepage
- Reccomended Videos (Videos along the side of a video page)

Newpipe app has these settings and so does Invidious. These settings can help with making the platform less addictive.

**Comment by Loki-L1130** [comment]
For the first one. I think Subscribing to some channels and setting the Homepage as feeds will help you.

For recommended videos alongside, video. For that, @FireMasterK made it alongside the comments.

**Comment by trymeouteh** [comment]
The "Show Comments" setting only enable/disables the comments. It would be nice to have a settings to hide the videos that are alongside where the comments appear.

**Comment by FireMasterK** [comment]
Closing this with #1218, you can't hide the homepage, however, but you can change it by default to show your feed.
