### ISSUE TITLE
How to self-host

### ISSUE THREAD

**Issue by LivingWithHippos** [TeamPiped/Piped#82]
Hello, how can I self-host piped? Is it still too soon to have a docker-compose? I've noticed there's also a dockerized backend version.

**Comment by FireMasterK** [comment]
Hi,

There is a docker-compose at https://github.com/TeamPiped/Piped-Backend/blob/master/docker-compose.yml

You need to create two A records:
- one for the proxy
- one for the API

In short, it's a bit difficult to self-host currently.

You have to download the `docker-compose.yml` and `config.properties` to a directory.

Then run `sudo mkdir -p /var/run/ytproxy/`

Then, run `chown -R www-data:www-data /var/run/ytproxy/` # can be nginx:nginx if you some distros / the mainline version

then look at /etc/passwd for the user and group id:
It would look like this:
```
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
```

Now, run:
```
docker run -d --network=host -v "/var/run/ytproxy/:/app/socket" --user 33:33 --restart unless-stopped 1337kavin/ytproxy:latest # change the user accordingly, from your passwd file
```

For the Nginx configuration, you should use the following as a Snippet.
```
/etc/nginx/snippets/ytproxy.conf

if ($request_method = OPTIONS ) {
   return 200;
}
proxy_buffering on;
proxy_set_header Host $arg_host;
proxy_ssl_server_name on;
proxy_set_header X-Forwarded-For "";
proxy_set_header CF-Connecting-IP "";
proxy_hide_header "alt-svc";
sendfile on;
sendfile_max_chunk 512k;
tcp_nopush on;
aio threads=default;
aio_write on;
directio 2m;
proxy_hide_header Cache-Control;
proxy_hide_header etag;
proxy_http_version 1.1;
proxy_set_header Connection keep-alive;
proxy_max_temp_file_size 0;
access_log off;
proxy_pass http://unix:/var/run/ytproxy/http-proxy.sock;
```

And for the API and proxy, you can put them in one file:
```
server {
    listen 80;
    listen 443 ssl http2;
    ssl_certificate /etc/ssl/certs/kavin.rocks.pem;
    ssl_certificate_key /etc/ssl/private/kavin.rocks.key;
    ssl_early_data on;
    server_name pipedproxy-bom.kavin.rocks;

    location ~ (/videoplayback|/api/v4/) {
       include snippets/ytproxy.conf;
       add_header Cache-Control private always;
       proxy_hide_header Access-Control-Allow-Origin;
    }

    location / {
       include snippets/ytproxy.conf;
       add_header Cache-Control "public, max-age=604800";
       proxy_hide_header Access-Control-Allow-Origin;
    }
}

server {
    listen 80;
    listen 443 ssl http2;
    ssl_certificate /etc/ssl/certs/kavin.rocks.pem;
    ssl_certificate_key /etc/ssl/private/kavin.rocks.key;
    ssl_early_data on;
    server_name pipedapi.kavin.rocks;

    location / {
       proxy_pass http://127.0.0.1:8080;
    }
}
```

And then update your `config.properties` to reflect the proxy URL.

To test, you can then visit:

```
https://api.domain.tld/trending
https://api.domain.tld/?host=icanhazip.com
```

Regarding the frontend, there shouldn't be a need to as you should be able to just switch instances :)


Let me know if you have any issues, I'm aware this is a complicated setup process.

**Comment by LivingWithHippos** [comment]
Thanks! Working with my previous yotter/ytproxy configuration I was able to set this up with caddy. Trending gives me a json list and icanhazip.com gives me the ip.

> Regarding the frontend, there shouldn't be a need to as you should be able to just switch instances :)

I'm missing this. You mean I should change instance on piped.kavin.rocks?

**Comment by FireMasterK** [comment]
> I'm missing this. You mean I should change instance on piped.kavin.rocks?

Yes, that's right, I'll add an option for custom instances later today.

**Comment by pred2k** [comment]
@LivingWithHippos would you be so kind to share your caddy config with us?
I'm trying to spin up piped from one docker-compose file that includes everything and would make it dead simple to deploy it. But i've still got some trouble understand the components and connecting them together.

**Comment by LivingWithHippos** [comment]
> @LivingWithHippos would you be so kind to share your caddy config with us?

I wanted to wait for the instance to try it before posting but anyway this should be okay:

```css
# piped
api.domain.tld {
  # test with https://api.domain.tld/trending  
  reverse_proxy piped:8080
}

proxy.domain.tld {
  # test with https://proxy.domain.tld?host=icanhazip.com
  @ytproxy path /videoplayback* /api/v4/*

  route {

    header @ytproxy {
      Cache-Control private always
      CF-Connecting-IP ""
    }

    header / {
      Cache-Control "public, max-age=604800"
      -Access-Control-Allow-Origin
    }

    reverse_proxy unix//var/run/ytproxy/http-proxy.sock {
      header_down -etag
      header_down -alt-svc
    }
  }
}
```

And in the docker compose of caddy you need to mount the youtube proxy folder

```yaml
services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /docker/yotter/ytproxy:/var/run/ytproxy
       ....
```

Where `/var/run/ytproxy` is the one you need to pass to the caddyfile (`reverse_proxy unix//var/run/ytproxy/http-proxy.sock`) and `/docker/yotter/ytproxy` is the folder you mounted from the youtube proxy compose file


```yaml
  ytproxy:
    image: 1337kavin/ytproxy:latest
    restart: unless-stopped
    volumes:
      - "/docker/yotter/ytproxy:/app/socket"

```

Piped's compose is like the one in this repo. I tried translating the optimizations from nginx to caddy 2 but I don't know how it will turn out. It already works for Yotter so it should be ok for piped.

**Comment by FireMasterK** [comment]
Translating
```
if ($request_method = OPTIONS ) {
   return 200;
}
```
Is really important for performance. I believe you could use a Matcher with a respond with caddy. If this is infesible, I could implement it in the ytproxy itself.


Regarding switching instances, it's a bit complicated to implement, but I will get it done by the end of this week.

In the meantime, if you know how to use the devtools, you can open the application tab, then the localstorage tab, then set the `apiUrl` manually. 


If there's enough interest, I could adapt this config to improve performance and include it in the documentation aswell.

**Comment by LivingWithHippos** [comment]
Could't find the apiUrl voice to edit, do I have to add it?

For caddy here is the [respond part](https://caddyserver.com/docs/caddyfile/directives/respond) and here is a [thread](https://caddy.community/t/help-set-up-a-wordpress-bypass-with-a-static-cache/7917/23) where he match POST.

I made this and it's accepted by caddy, still don't know if it'll work

```java
@postcall {
    method post
}

respond @postcall 200
```

**Comment by FireMasterK** [comment]
> Could't find the apiUrl voice to edit, do I have to add it?

Switch instances in the preference page to any random one once and then it should :)

> I made this and it's accepted by caddy, still don't know if it'll work
> 
> ```java
> @optionscall {
>     method OPTIONS
> }
> 
> respond @optionscall 200
> ```

If this command doesn't have any output, it's working 😃:
```
curl -X OPTIONS https://proxy.domain.tld/videoplayback
```

**Comment by FireMasterK** [comment]
A correction: the variable is actually called `instance` and not `apiUrl`.

**Comment by LivingWithHippos** [comment]
> If this command doesn't have any output, it's working 

Seems to be working

> A correction: the variable is actually called instance and not apiUrl.

I can apply it but I get CORS errors, maybe I can't do it from a different domain or maybe me/you have to edit the ‘Access-Control-Allow-Origin’ header

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://api.domain.tld/videoplayback?expire=1615301684&ei=1DdHYIDTEaHB8gPG7qXYBQ&ip=............&id=o-AO-W1dYazbsnwhD2Y13wilfTrGZa25VuXo_GGU36wmKB&itag=251&source=youtube&requiressl=yes&mh=2J&mm=31%2C29&mn=sn-5oxmp55u-8pxe%2Csn-4g5e6nz7&ms=au%2Crdu&mv=u&mvi=2&pl=24&gcr=de&vprv=1&mime=audio%2Fwebm&ns=k16elnIEzTjtyGeX0Yk6LuwF&gir=yes&clen=1010533&dur=81.661&lmt=1615240361437238&mt=1615279148&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5531432&n=fdv-WjBwO_2ZyIOB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAI3nHpBLkGvp0ZaJydLN6m0L9YKy0L8rHj3D2jMtQFlKAiEAz1fzUyTXLpYyafABeCc4Un48hagJErdAazl7XqaHR1s%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIhAJYuZUDRGEUWG9DUS0Hr2MTESuDD9cw0zFtSQ1I8t8T-AiBox2eN_kVVhLJbf1TR8vYfiDTpwRsLk-CZuIwgYmqb4w%3D%3D&host=r2---sn-5oxmp55u-8pxe.googlevideo.com. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by FireMasterK** [comment]
Try adding these to the proxy:
```
header Access-Control-Allow-Origin *
header Access-Control-Allow-Headers *
```

**Comment by LivingWithHippos** [comment]
Nice. Current Caddyfile:

```python
# piped
api.domain.tld {
  # test with https://api.domain.tld/trending  
  reverse_proxy piped:8080
}

proxy.domain.tld {
  # test with https://proxy.domain.tld/?host=icanhazip.com

  @ytproxy path /videoplayback* /api/v4/*

  @optionscall {
    method OPTIONS
    }

  header Access-Control-Allow-Origin *
  header Access-Control-Allow-Headers *

  route {

    header @ytproxy {
      Cache-Control private always
      CF-Connecting-IP ""
    }

    header / {
      Cache-Control "public, max-age=604800"
      -Access-Control-Allow-Origin
    }

    respond @optionscall 200

    reverse_proxy unix//var/run/ytproxy/http-proxy.sock {
      header_down -etag
      header_down -alt-svc
    }
  }
}
```

I still haven't checked if the other headers modifications are working

**Comment by FireMasterK** [comment]
This is now done, see https://piped-docs.kavin.rocks/docs/self-hosting/#docker-compose-caddy-aio-script!

Thanks to @AtomHare for the help!
