### ISSUE TITLE
changing default trending country on a self-hosted instance

### ISSUE THREAD

**Issue by FarisZR** [TeamPiped/Piped#820]
hi, i currently self host piped, and the trending page always shows US content
is there a way to change the default country?

**Comment by FireMasterK** [comment]
Do you mean for a browser with fresh cookies? Currently, this isn't possible.
If you would like to change it for yourself, that's currently possible at the preferences page at https://piped.kavin.rocks/preferences#ddlCountrySelection

**Comment by fariszr** [comment]
Yup i mean to change it instance-wide

**Comment by Bnyro** [comment]
Closing in favor of  #2904
