### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by AcousticBirthdayCake** [TeamPiped/Piped#829]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Videos won’t play on the offical instance but can play on other instances.

### To Reproduce

Click play on a video on the offical instance.

### Expected behavior

I expected the video to play

### Logs/Errors

No logs

### Browser, and OS with Version.

Safari on iOS 15.3.1

### OS

iOS 15.3.1

**Comment by FireMasterK** [comment]
Thanks for the report, this was a serious issue!
