### ISSUE TITLE
Stopped working on all devices

### ISSUE THREAD

**Issue by Yolakalemowa** [TeamPiped/Piped#833]
Hi,

Piped just stopped working now... I can only see vids on homepage but no videos work at all...

I tested on several devices and browsers. 

plz try to replicate?

**Comment by FireMasterK** [comment]
Fixed, that's not good!

**Comment by Yolakalemowa** [comment]
@FireMasterK thanks that was fast. May I ask what was wrong exactly?

**Comment by FireMasterK** [comment]
I'm not sure, I didn't take a proper look, I had restarted the backend services, I did make some database changes an hour ago, that could be why
