### ISSUE TITLE
Sign In and Feed not working

### ISSUE THREAD

**Issue by AcousticBirthdayCake** [TeamPiped/Piped#846]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Can’t sign in and the feed won’t work. Also, the subscriptions seem to be gone.

### To Reproduce

Sign in/ Check feed/ check subscriptions

### Expected behavior

To be able to log in and feed to work.

### Logs/Errors

No logs

### Browser, and OS with Version.

Safari iOS 15.3.1

**Comment by AcousticBirthdayCake** [comment]
Signing in and feed seems to work on other instances but not piped.kavin.rocks

**Comment by AcousticBirthdayCake** [comment]
Looks like it has been fixed.

**Comment by FireMasterK** [comment]
This should now be fixed with https://github.com/TeamPiped/Piped-Backend/pull/199 :tada:
