### ISSUE TITLE
404. Not Found io.activej.http.HttpError: HTTP code 404: Not found

### ISSUE THREAD

**Issue by Deon-Trevor** [TeamPiped/Piped#847]
Hello all. I'm hoping to host my own instance of Piped but no matter which method i use i'm getting stuck at the same place. After following all the steps when i finally launch it i get a
```
404. Not Found
io.activej.http.HttpError: HTTP code 404: Not found

ActiveJ 5.1
```

I am currently using ```Docker-Compose with Nginx``` but i got the same problem with both the ```Docker-Compose Caddy AIO script``` and  the ```Docker-Compose Nginx AIO script```

My api is at ```api.piped.mysite.com``` and the proxy is at  ```proxy.piped.mysite.com```.  Everything else is as instructed on 
```ipns://piped-docs.kavin.rocks/docs/self-hosting/``` 

Not sure where i'm missing it. Please help. And let me know if you need any more info to help troubleshoot but everything is set up pretty much mile how the guide says.

**Comment by mmjee** [comment]
Are you actually opening the frontend URL? That's usually what you get when you make a request to the backend instead of the frontend. The backend I suppose is working fine.

**Comment by Deon-Trevor** [comment]
I am opening the front-end. The backend does not show anything besides an error when opened.

```
api.piped.mysite.com uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

tried with the frontend's ssl certs and also using unique certs for the api and the proxy but the result is the same. The behaviour above is for the frontend

**Comment by FireMasterK** [comment]
What reverse proxy are you using? Nginx? From what I can tell, the reverse proxy in front of Piped is causing issues.

**Comment by FireMasterK** [comment]
https://piped-docs.kavin.rocks/docs/self-hosting/#docker-compose-nginx-aio-script is the guide expected to be followed for such an instance

You just would need to change the the Nginx config like so:
```
server {
    listen 80;
    server_name piped.mysite.com;

    location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name proxy.piped.mysite.com;

    location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_set_header Host $host;
    }
}

server {
    listen 80;
    server_name api.piped.mysite.com;

    location / {
       proxy_pass http://127.0.0.1:8080;
       proxy_set_header Host $host;
    }
}
```

and finally, get certbot to include SSL certificates.

**Comment by Deon-Trevor** [comment]
I've made some progress, thanks. I'm still stuck but we have some progress nonetheless. Now both the api and proxy are showing the:

```
404. Not Found
io.activej.http.HttpError: HTTP code 404: Not found

ActiveJ 5.1
```

As you had mentioned. Although the frontend is also, still, showing the same.

**Comment by Deon-Trevor** [comment]
Fixed the problem right up! Many thanks to everyone for helping. Cheers!!!!
