### ISSUE TITLE
Somehow piped.kavin.rocks redirects to http://localhost:8080/ipns/ which fails ipfs resolve

### ISSUE THREAD

**Issue by slrslr** [TeamPiped/Piped#855]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

IPNS error

### To Reproduce

I open https://piped.kavin.rocks/watch?v=ZRAStnf4AMA
In Firefox web browser i am redirected to http://localhost:8080/ipns/piped.kavin.rocks/watch?v=ZRAStnf4AMA
(I am using IFS companion addon) and running IPFS ( http://127.0.0.1:5001/webui/ shows Connected to IPFS )

Yet that page i am redirected to shows:
`ipfs resolve -r[ /ipns/piped.kavin.rocks/watch](https://ipfs.io/ipns/piped.kavin.rocks/watch): no link named "watch" under SomeLongStringHere`

also i have seen:
`ipfs resolve -r[ /ipns/piped.kavin.rocks/watch](https://ipfs.io/ipns/piped.kavin.rocks/watch): context deadline exceeded`

### Expected behavior

no error

### Logs/Errors

-

### Browser, and OS with Version.

Latest firefox-esr 91.6.0esr from Debian stable

**Comment by FireMasterK** [comment]
Ensure you have this enabled:
![image](https://user-images.githubusercontent.com/20838718/155325256-054bde34-0f6c-4b3f-9fa6-1a9c3ea76bff.png)

**Comment by slrslr** [comment]
You have closed this, yet i already have yours mention thing enabled. So it should not be the cause.

**Comment by FireMasterK** [comment]
It worked out of the box for me, not sure what wrong then. Either ways this isn't an issue in Piped, but rather in IPFS companion.

**Comment by slrslr** [comment]
@FireMasterK please kindly check the issue linked above this comment of mine. They have explained how You may fix this. Maybe reopen.

**Comment by FireMasterK** [comment]
It's impossible to fix it that way since piped has URLs like /channel/channelId, etc. However, I've tried something else: https://github.com/TeamPiped/Piped/commit/a56e4e05361fac283b098ef1eecc04e3fa49607d

It should fix the issue too. (albeit, a 404 status code will be thrown)
