### ISSUE TITLE
Open URL in Piped when search query is a YouTube URL 

### ISSUE THREAD

**Issue by mhmdanas** [TeamPiped/Piped#861]
I searched and didn't find any issues about this, but I apologize in advance if my search failed somehow.

Basically, my request is this: if you paste a YouTube link (e.g. https://youtube.com/watch?v=dQw4w9WgXcQ) into the search bar and then press enter, Piped opens the video page. You can see NewPipe's behavior for reference.

I guess implementing this for other kinds of URLs (e.g. channel URLs) would be nice too.

**Comment by mhmdanas** [comment]
Woah, that was quick. Thanks!

**Comment by Loki-L1130** [comment]
@FireMasterK How about also addding just part after after 'v=' too

**Comment by mhmdanas** [comment]
@FireMasterK the regex doesn't seem to keep in mind that the video ID can contain `-`.

**Comment by mhmdanas** [comment]
Bumping for my comment above.
