### ISSUE TITLE
Subscriptions are not saved, I am logged in.

### ISSUE THREAD

**Issue by lonely-ux** [TeamPiped/Piped#872]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

I made my account, then went to subscribe to the channels I enjoy. After a while of subscribing, I went to check the feed and the subscriptions section only to realize that I was not subscribed to anything? I am logged in and I cling on the subscribe button but after a couple refreshes I am unsubscribed again. Librewolf at fault but not sure how to fix.

### To Reproduce

Use Librewolf browser basically.

### Expected behavior

subscriptions are to be saved when logged in, and stay saved.

### Logs/Errors

Failed to register/update a ServiceWorker for scope ‘https://piped.kavin.rocks/’: Storage access is restricted in this context due to user settings or private browsing mode. (from console in Librewolf)

### Browser, and OS with Version.

Librewolf on Arch.

### Additional context

As said in the Errors section, it is the browser causing the issue however i am noob and cant figure where to go to make an exception for Piped. Sorry if wrong place to ask, will delete issue if necessary.

**Comment by FireMasterK** [comment]
I can replicate this issue when creating a new account (however, it doesn't affect old ones), thanks for the report! I should get this resolved soon.

**Comment by FuzzyGrim** [comment]
I'm having the same issue on my self-hosted instance. I found another problem, which I think it is related to this, is that the import subscriptions button doesn't work, let me know if I should create another issue for that.

**Comment by FireMasterK** [comment]
> I'm having the same issue on my self-hosted instance. I found another problem, which I think it is related to this, is that the import subscriptions button doesn't work, let me know if I should create another issue for that.

That should be fixed too!
