### ISSUE TITLE
Back button behavior

### ISSUE THREAD

**Issue by Mennaruuk** [TeamPiped/Piped#879]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Minor issue: The Back button in preferences redirects users to homepage. The correct behavior is to return to the previous page.

### To Reproduce

1. [Open a random video](https://piped.kavin.rocks/watch?v=r93stUU8yXA)
2. Click _Preferences_
3. Click Back button

### Expected behavior

Return to previous page (much like the browser back button)

### Logs/Errors

No errors.

**Comment by FireMasterK** [comment]
https://user-images.githubusercontent.com/20838718/158695912-aff4f3ca-40e9-4083-8991-d5b395cb3f76.mp4

I don't see any issues here.

**Comment by Mennaruuk** [comment]
Yeah, swiping is the best thing to do. The Back button at the top-left side of preferences takes me back to the homepage on the computer, and on my iPhone X it doesn't work, but this is such a tiny issue. Closing! Thanks.
