### ISSUE TITLE
Freetube support?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [TeamPiped/Piped#888]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

It's not a bug per say. I'm just here to see if there is hope to see support for freetube in the future?

Piped seems promising and I want to self-host it but because it does not play nicely with freetube I could not host it and I hosted invidious instead.

Some folks already asked freetube and they already said: https://github.com/FreeTubeApp/FreeTube/issues/1527#issuecomment-912040673 so it's only you left in hope I can see finally piped and freetube work together

  

### To Reproduce

-

### Expected behavior

-

### Logs/Errors

-

**Comment by FireMasterK** [comment]
Closing this as this isn't a Piped issue :)

If they intend on implementing support for Piped, they may find https://github.com/TeamPiped/OpenAPI/blob/main/swagger.yaml useful

**Comment by EsmailELBoBDev2** [comment]
Freetube dev team says they won't implement piped because invidious already there 
and you say won't change API to match invidious 

It's dead end :joy: so I think I will self host both :grin:

**Comment by FireMasterK** [comment]
Well, the good thing is when you have your own Piped instance, there's almost no reason to use Freetube :P (since you own your subscriptions anyways)

**Comment by EsmailELBoBDev2** [comment]
Hmm about that, piped has issue with subscriptions https://github.com/TeamPiped/Piped/issues/1130

And invidious for whatever reason slow with me so only hope is actually freetube :p
