### ISSUE TITLE
Download video thumbnail button

### ISSUE THREAD

**Issue by trymeouteh** [TeamPiped/Piped#889]
Please add a button which will grab the largest thumbnail image of a video and have it be downloaded to your computer.

**Comment by Bnyro** [comment]
You can just download it by right clicking it and choosing "Save Image As":
![image](https://user-images.githubusercontent.com/82752168/184120536-93acdea4-4e73-4f13-bdd5-95ee126372fa.png)

**Comment by trymeouteh** [comment]
> You can just download it by right clicking it and choosing "Save Image As": ![image](https://user-images.githubusercontent.com/82752168/184120536-93acdea4-4e73-4f13-bdd5-95ee126372fa.png)

This is not the large thumbnail, but a smaller image of the thumbnail.
