### ISSUE TITLE
Feature Request: SponsorBlock add prompt option

### ISSUE THREAD

**Issue by danielriddell21** [TeamPiped/Piped#894]
Currently Piped has the option to skip or none for sponsorblock. It would be great to have a prompt option as well which will display a skip button instead of the current automatic skipping.

This is similar functionality to viewtube.io

The idea behind it is sometimes you don't always want to skip, so this would but the skipping into the hands of the user.

**Comment by danielriddell21** [comment]
ViewTube added the functionality in: https://github.com/ViewTube/viewtube-vue/pull/253

**Comment by trymeouteh** [comment]
To allow users to customise the SponsorBlock settings and choose what segments to auto skip, what ones to manual skip, etc would be terrific. Just like the browser extension
