### ISSUE TITLE
UI semi-randomly breaks on searches

### ISSUE THREAD

**Issue by luphoria** [TeamPiped/Piped#898]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

If you make a lot of UI interactions with searches, the UI will break completely.
![image](https://user-images.githubusercontent.com/60309933/158195728-0cb1a1ee-fc7f-40d0-925a-5e085a8ab329.png)
It could be related to the 404s in the console but I very much doubt it.
The error message displays a second time if you click on Feed again. There is no way to "fix" the UI, but it works totally fine if you simply reload the page.

### To Reproduce

1. Open Piped (any instance)
2. Use the UI to make a search
3. Click on "Feed"
4. Repeat step 2 and 3 until it breaks

### Expected behavior

Search results display

### Logs/Errors

```
TypeError: Cannot read properties of null (reading 'nextSibling')
    at nextSibling (runtime-dom.esm-bundler.js:36:31)
    at A (runtime-core.esm-bundler.js:5571:20)
    at Ft (runtime-core.esm-bundler.js:5537:13)
    at ce (runtime-core.esm-bundler.js:5521:17)
    at $ (runtime-core.esm-bundler.js:5593:13)
    at ce (runtime-core.esm-bundler.js:5494:13)
    at y (runtime-core.esm-bundler.js:2442:13)
    at I (runtime-core.esm-bundler.js:2455:17)
    at Proxy.<anonymous> (runtime-core.esm-bundler.js:2563:21)
    at Wa (runtime-core.esm-bundler.js:893:44)
```

### Browser, and OS with Version.

Chrome 98 (Windows)
ungoogled-chromium 98 (Linux)
Firefox (Linux)
Chrome for Android
Firefox for Android

**Comment by hp77-creator** [comment]
Does it have something to do with so many API calls in a short instance of time? My initial guess is on that one.

**Comment by luphoria** [comment]
> Does it have something to do with so many API calls in a short instance of time? My initial guess is on that one.

I don't think so. My initial description doesn't make much sense, but it has (seemingly) nothing to do with the number of requests, or speed of requests. I will often be watching a video, finish it, and click the Piped icon, to a suddenly broken UI

**Comment by FireMasterK** [comment]
I haven't seen this in a few weeks now, let me know if this happens again!
