### ISSUE TITLE
Account able to be created without a password

### ISSUE THREAD

**Issue by GBT7** [TeamPiped/Piped#900]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Using LibreTube, I was able to register an account which does not have a password, and I cannot change the password. I have signed out and signed in and subscribed to content on this account to verify that it is indeed an account without a password, and it is.

This is not reproducible on the web frontend, it only works when registering through the LibreTube app. The webpage does not allow sign-in with a passwordless account, while LibreTube does.

### To Reproduce

1. Open the LibreTube app on Android
2. Click Login/Register in Home
3. Type in a username not currently in use, leave the password field blank
4. Click Register

### Expected behavior

LibreTube will sign you into an account without a password. The username of said account will be marked as taken, and all subscriptions when signed into the passwordless account will be kept and shown when signing back into LibreTube using the passwordless account. The password is not able to be reset.

### Logs/Errors

Trying to sign into a passwordless account through the web interface gives the prompt "undefined"

**Comment by FireMasterK** [comment]
This has been fixed.
