### ISSUE TITLE
502 Bad Gateway Error on some clients with self host with AIO script

### ISSUE THREAD

**Issue by sdfg2** [TeamPiped/Piped#904]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Getting 502 on some clients, but not others.

Worked fine at first, then it started doing it on my main browser vivaldi, so I switched to chromium just for piped (so vivaldi wasn't working but chromium was, on the same host), then chromium started doing it so I tried firefox and now it's doing it.  Vivaldi mobile on two other hosts, and the LG browser all work fine without that error.

Tried clearing cache, data, cookies etc.

I'm running self-hosted docker-compose with the AIO script, and it's not a 502 on my nginx, it must be the internal one in the docker.  No idea how to find logs or debug a docker.

### To Reproduce

Go to my instance.
Get 502 error.

### Expected behavior

It works.

### Logs/Errors

n/a

### Browser, and OS with Version.

Server docker-compose AIO nginx self hosted on Arch.
Clients as described.

**Comment by FireMasterK** [comment]
Have you figured this out? Is there any reproducible way to test this issue?

**Comment by sdfg2** [comment]
Nope, I moved to [https://github.com/ViewTube/viewtube-vue](url) because of the problems.

**Comment by rderensy** [comment]
I don't think it's reproducible easily but I get that a lot. It works on my computer but not on my phone, sometimes the other way around and so on. It's annoying when I'm not home to restart nginx.
