### ISSUE TITLE
Autoplay preference doesn't work

### ISSUE THREAD

**Issue by sdfg2** [TeamPiped/Piped#906]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

With the preference option Autoplay turned to off, videos will still autoplay when clicked on them.

### To Reproduce

Go to piped.kavin.rocks
Go to preferences
Turn off "Autoplay Video"
Go back
Click on a video
The video will start playing immediately.

### Expected behavior

The video doesn't play until I hit play.

### Logs/Errors

n/a

**Comment by Victor239** [comment]
Can confirm I have this issue too on Linux Kubuntu Firefox v100.

**Comment by EdwardLangdon** [comment]
@Victor239 When using Libredirect or anyother extensions, Piped Embeds do not autoplay.

**Comment by Victor239** [comment]
@EdwardLangdon it does for me when I test on a webpage with about 20 embeds, let me know if there's any other info you need for debugging.

**Comment by EdwardLangdon** [comment]
I am not sure. I don't have the issue. If so, Check this in `about:preferences#privacy` and then select this setting and Comment back.

![image](https://user-images.githubusercontent.com/101938856/167235715-386371b2-05c0-4d19-bb41-cd48ba2d6996.png)

**Comment by Victor239** [comment]
Yes, that's my default also.
