### ISSUE TITLE
Add database check to /healthcheck endpoint

### ISSUE THREAD

**Issue by TheSilkky** [TeamPiped/Piped#908]
Returning a 500 status code from `/healthcheck` when the database is unreachable should help with the database timeout bug, this way Docker can be configured to automatically reschedule the container when it fails the healthcheck.

**Comment by FireMasterK** [comment]
Related: I thought about potential causes for this issue, and thought it could potentially be that sessions aren't closed properly when exceptions occur.

**Comment by FireMasterK** [comment]
I hope https://github.com/TeamPiped/Piped-Backend/pull/222 has fixed the connection issues, please report if it isn't!

**Comment by FireMasterK** [comment]
Re-opening as this isn't really implemented
