### ISSUE TITLE
Question on setting this up with NPM

### ISSUE THREAD

**Issue by balajeek** [TeamPiped/Piped#914]
I already have NPM setup with two sites with ssl.  I would like to setup piped and I followed the docs under section "Docker-Compose with Nginx" 

I am not sure at the step where it says to "create an nginx snipper...".
where should i have to create those ytproxy.conf, piped.conf  ?

any help would be appreciated. thanks for the awesome project.
excited to use youtube without google.

**Comment by FireMasterK** [comment]
You should instead follow this instead of that guide: https://piped-docs.kavin.rocks/docs/self-hosting/#docker-compose-nginx-aio-script

This would host the entire stack and is a lot easier.
