### ISSUE TITLE
Subscription Imports

### ISSUE THREAD

**Issue by CalebJohnathen** [TeamPiped/Piped#918]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When trying to import your subscriptions, Piped doesn't add them to your feed.

### To Reproduce

Import your subscriptions from a file (both YouTube and NewPipe didn't work)

### Expected behavior

I should see my subscriptions in my feed but I dont

### Logs/Errors

No errors are thrown

**Comment by adguardgirl** [comment]
I have the same issue. Came here to report the problem.

**Comment by luphoria** [comment]
Just gonna chime in additional info - this has broken at some point within this past week. I imported subscriptions only a few days ago, and noticed it was broken

**Comment by FireMasterK** [comment]
Fixed in https://github.com/TeamPiped/Piped-Backend/commit/b1e875bcf5ac3ec323b2e4a7e5e1e47a583b2f1a
