### ISSUE TITLE
Custom playback speed

### ISSUE THREAD

**Issue by zisra** [TeamPiped/Piped#923]
It would be useful if I could set playback speed to x10 or even x50

**Comment by barkoder** [comment]
That would be nice.

Meanwhile, there are extensions that do this too.  
At least on the desktop.

Here's a pretty good FOSS extension that I use for Firefox - https://addons.mozilla.org/en-US/firefox/addon/playback-speed/

I'm sure there are FOSS ones for chromium too.

Cheers :)

**Comment by Bnyro** [comment]
You can now press `Shift` and `s` at the same time to open a dialog which allows setting a custom playback speed.
