### ISSUE TITLE
Make the subtitles background on Piped a bit more transparent, just like on YouTube

### ISSUE THREAD

**Issue by Linerly** [TeamPiped/Piped#934]
![Piped subtitles](https://user-images.githubusercontent.com/47475676/160063806-be5d6aa1-a66e-422d-9f5e-181eb865e8e0.png)
![YouTube subtitles](https://user-images.githubusercontent.com/47475676/160064172-c4ed2ed1-b6c2-4e44-811e-179e1309e33b.png)

**Comment by barkoder** [comment]
If you don't mind using [Stylus](https://addons.mozilla.org/en-US/firefox/addon/styl-us/) also available on Chromium, then use 

    .shaka-text-wrapper span span {
    background-color: #0003 !important;
    }

Apply it to

URLs on the domain - `piped2bbch4xslbl2ckr6k62q56kon56ffowxaqzy42ai22a4sash3ad.onion`

URLs on the domain - `piped.kavin.rocks`

After you save, you'll see a tiny box to the left of `#0003` . Clicking it will have a color-wheel pop up. You could fiddle with the transparency slider, if it's too bright/dark.

Cheers :)

**Comment by Linerly** [comment]
I just noticed that the subtitles in Piped is now similar like on YouTube
![image](https://user-images.githubusercontent.com/47475676/183898755-3d8d7dd8-f569-444b-8315-de1fc98d3e69.png)
