### ISSUE TITLE
Feed and videos won’t load

### ISSUE THREAD

**Issue by AcousticBirthdayCake** [TeamPiped/Piped#935]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The feed won’t load and the videos are won’t also load. The Trending page loads but when you click on a video, it just says loading.

### To Reproduce

Check Feed

Trending Page > Click on video

### Expected behavior

For the Feed to load and videos to load.

### Logs/Errors

No logs

### Browser, and OS with Version.

Safari iOS 15.4

**Comment by AcousticBirthdayCake** [comment]
Looks like pipedapi.kavin.rocks/feed doesn’t load

**Comment by FireMasterK** [comment]
This is due to one of the servers running out of space, a fix is in progress.

**Comment by AcousticBirthdayCake** [comment]
Seemed to be fixed now
