### ISSUE TITLE
Any plans for supporting replicant OS?

### ISSUE THREAD

**Issue by lerdem** [TeamPiped/Piped#954]

**Comment by FireMasterK** [comment]
Are there any issues?

**Comment by lerdem** [comment]
i guess, this issues  should be addressed to `libretube` repo. But i will try here. 
I am getting error message `Unfortunately, LibreTube has stopped.`

**Comment by FireMasterK** [comment]
You should create an issue at https://github.com/libre-tube/LibreTube/issues

This is an issue tracker for the frontend at https://piped.kavin.rocks/
