### ISSUE TITLE
Add my instance

### ISSUE THREAD

**Issue by datanomi** [TeamPiped/Piped#959]
Front-end: https://piped.mha.fi/
API: https://api-piped.mha.fi
Proxy: https://proxy-piped.mha.fi

Hosted from Sweden with Cloudflare CDN

**Comment by FireMasterK** [comment]
Your instance seems to be showing an uptime status page, although was fine a minute back

**Comment by FireMasterK** [comment]
Added, thanks for hosting an instance!

**Comment by datanomi** [comment]
Yeah sorry, I messed up something with nginx. It's fixed now.
