### ISSUE TITLE
Displays no video with API 404

### ISSUE THREAD

**Issue by dirkf** [TeamPiped/Piped#967]
### Official Instance

- [ ] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

The site JS fails in SeaMonkey 2.53.11.1. Fetching details of the video fails with 404, and no video is displayed. At http://piped.kavin.rocks/watch?v=BaW_jenozKc, the video is found and displayed.

Also, it's (not) reproducible.

### To Reproduce

1. Open https://piped.moomoo.me/watch?v=BaW_jenozKc in SM 2.53.11.1 (platform should be irrelevant)
2. Observe missing video
3. Open developer tools (F12 or Ctrl+Shift+I).
4. Reload the page
5. Observe the console messages

### Expected behavior

Display test video, as in YT, Invidious.

### Logs/Errors

The network resources giving 404 correspond to the Promise rejections logged:
1. https://piped2api.moomoo.me/streams/BaW_jenozKc
2. https://piped2api.moomoo.me/sponsors/BaW_jenozKc?category=%5B%22sponsor%22%2C%22interaction%22%2C%22selfpromo%22%2C%22music_offtopic%22%5D
3. https://piped2api.moomoo.me/comments/BaW_jenozKc

At the official instance, https://pipedapi.kavin.rocks/streams/BaW_jenozKc (etc) is used with status 200.

```console
06:50:13.062 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://piped2api.moomoo.me/sponsors/BaW_jenozKc?category=%5B%22sponsor%22%2C%22interaction%22%2C%22selfpromo%22%2C%22music_offtopic%22%5D. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
06:50:13.094
Unhandled promise rejection 
TypeError
columnNumber: 0
fileName: ""
lineNumber: 0
message: "NetworkError when attempting to fetch resource."
stack: ""
__proto__: Object { stack: "", … }
0	_u https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:16083
	cc https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:17535
	sc/</e< https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:17700
	Uu https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:16145
	sc/< https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:17648
	<anonymous> https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:13288
	ma https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:13039
	wa https://piped.moomoo.me/assets/polyfills-legacy.061b5ef1.js:1:13101
polyfills-legacy.061b5ef1.js:1:16083

06:50:13.079 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://piped2api.moomoo.me/comments/BaW_jenozKc. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

...

06:50:13.302
Unhandled promise rejection 
TypeError
columnNumber: 0
fileName: ""
lineNumber: 0
message: "NetworkError when attempting to fetch resource."
   [...same details as above...]
polyfills-legacy.061b5ef1.js:1:16083
06:50:13.491
Unhandled promise rejection 
TypeError: NetworkError when attempting to fetch resource.
   [...same details as above...]
polyfills-legacy.061b5ef1.js:1:16083
```

### Browser, and OS with Version.

SeaMonkey 2.53.11.1, Linux x86

**Comment by FireMasterK** [comment]
Works fine on the official instance:

https://user-images.githubusercontent.com/20838718/162639385-066192a0-576b-470b-81bb-fd28314dbe19.mp4

Works fine when selecting moomoo.me as an instance.

https://user-images.githubusercontent.com/20838718/162639502-a267dbc8-a6b6-4f37-a8e9-471b05221425.mp4

Just a notice that only the official frontend at piped.kavin.rocks is supported. The instance URL you showed seems to have something misconfigured by the instance operator, hence reaching an incorrect API URL.
