### ISSUE TITLE
[info] Is this possible to use an external (invidious/piped/proxy) on the video ?

### ISSUE THREAD

**Issue by BirdInFire** [TeamPiped/Piped#982]
Hello,

I want to know if this possible to use an external (invidious/piped/proxy) on the video, because if i understand the instance proxy from the client perspective, but the server himself connect to google for streaming video, but since i would like an self hosted instance (to have my subscription in one place), without authorizing google domain into my network (i have blocked all google domain and use internal redirection for their api to ubreak website).

If it's impossible can you transform this into a feature request ?

Thanks

**Comment by moom0o** [comment]
preferences -> instance selection?

**Comment by BirdInFire** [comment]
> preferences -> instance selection?

It's mean it will proxy the video through this instance ? (not very clear in the preference panel).

**Comment by FireMasterK** [comment]
> it will proxy the video through this instance

Yes, it will

**Comment by BirdInFire** [comment]
> > it will proxy the video through this instance
> 
> Yes, it will

Thanks !! 
(if i can only recommend a little question mark who say it since (for me) instance selection isn't very clear on what this settings do)
