### ISSUE TITLE
Question : Very slow on self host.

### ISSUE THREAD

**Issue by BirdInFire** [TeamPiped/Piped#989]
My internet connection is quite fast (clearly not fiber, but i can launch at least 8 or 10 youtube / invidious video at the same time without any of them falling under 1080p) of stuttering.

The question is : 
Why is when i'm self host (so in "custom mode") the video are buffering every 2 second (even with 10 second preload into settings (uped it to 30).
My server do not have reached a bottlenek (cpu a 12% and ram a 25% (during the test), ethernet a 1%)
And my bandwidth used (internet) is less than 3% during the test.

I have used last version of the docker images.
(and disabled all security like SSO (in case) but do not solve the problem

if have followed step by step the config guide (and understand it).

if i switch to another instance on the same front end it's blazing fast (but since piped proxy also the account to them, the selfhost become totally useless ... (i do not even understand the utility of using another instance if we want to self host, i had hoped it proxied only video, but not the case).

Thanks for any help.

**Comment by FireMasterK** [comment]
Is there any way you could potentially share the instance URL? (Maybe privately, via https://github.com/TeamPiped/Piped#contact)

The official instance also uses HTTP/3 via a custom build script at https://github.com/FireMasterK/nginx-http3, which does improve performance a bit.

**Comment by BirdInFire** [comment]
> How do i use http3 for self-host ? `./test-build.sh` created only 2 images. Is this good idea for us to use? Also, you're using nginx-1.16.1?

will say that soon have upgraded to fedora 36 since so i have to try again.

**Comment by BirdInFire** [comment]
> Is there any way you could potentially share the instance URL? (Maybe privately, via https://github.com/TeamPiped/Piped#contact)
> 
> The official instance also uses HTTP/3 via a custom build script at https://github.com/FireMasterK/nginx-http3, which does improve performance a bit.

After test on latest of fedora / piped version same slow problem on custom instance (on even more powerfull server on another network (in fibre)

**Comment by FireMasterK** [comment]
I would use a DNS nameserver like dnscrypt. 

https://github.com/TeamPiped/Piped#contact

**Comment by FireMasterK** [comment]
I would use a DNS resolver like dnscrypt. That can have an impact for API response times.

You can also privately message me your API URL at https://github.com/TeamPiped/Piped#contact

**Comment by BirdInFire** [comment]
> I would use a DNS resolver like dnscrypt. That can have an impact for API response times.
> 
> You can also privately message me your API URL at https://github.com/TeamPiped/Piped#contact

Will try that, ask myself if it's the ISP the problem, i will try to proxy by my phone over 4G, to see if the speed change.

**Comment by FireMasterK** [comment]
Is this still an issue?

**Comment by FireMasterK** [comment]
Is this still a problem on the new rust based proxy? If it still is, it's likely your internet, and I don't think I can do anything.

To use it on Piped-Docker, you have to `git pull`, `docker-compose down`, `./configure-instance.sh`, `docker-compose up -d`
