### ISSUE TITLE
Option to turn Off/On proxy.

### ISSUE THREAD

**Issue by RiversideHollow** [TeamPiped/Piped#990]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

Our ISP provides extra speed to google's regional caching, otherwise watching a video is very unwatchable.

An option able to turn Off/On the piped-proxy would be really helpful. I hope.

Thank you.

### To Reproduce

1. Go to setting.

2. No option to turn off or on the proxy.

### Expected behavior

Video would load directly from google's server and we would get the extra caching speed provided by our ISP. Hopefully.

### Logs/Errors

...

**Comment by upalse** [comment]
Wouldn't that kinda defeat the point? I think more useful would be if proxy instances indicated which IX they're peering with so as to make choosing close one less awkward. As it stands now, you have to awkwardly traceroute / look at as path of each to find one that's reasonably fast.

As for people unfortunate enough to have no instance nearby, they can always light a candle in the dark, and start their own...

**Comment by trymeouteh** [comment]
I would like this and suggested this before.

https://github.com/TeamPiped/Piped/issues/794

**Comment by Myned** [comment]
It's worth mentioning that LibreTube, an Android Piped client, has implemented this in https://github.com/libre-tube/LibreTube/pull/3290
I do not know whether this is translatable to the browser, however.

My use case is for buffering and stability purposes, even at the cost of privacy without a VPN. I selfhost an instance, but the IP of my VPS is consistently error 429'd by Google for random videos (I use both local and cloud DNS caches, and this does not occur with public instances). The ability to choose a proxy instance separate from the authentication instance is great, but there is no reliable way to determine which instances are stable enough, and even when found, there is no guarantee of uptime. It's inconvenient to reload the page or switch the proxy in the settings when encountering buffer issues, which are frequent to the tune of every video with longer-form content.

Stability unfortunately seems to come with the territory of selfhosted services, especially when dealing with streaming video; this appears to be the main problem that overriding the proxy aims to solve, so if there is an alternative solution that keeps privacy intact, then I am all for it.

**Comment by Bnyro** [comment]
Closing in favor of https://github.com/TeamPiped/Piped/issues/2817
