### ISSUE TITLE
Music channels are not handled correctly

### ISSUE THREAD

**Issue by D3SOX** [TeamPiped/Piped#992]
### Official Instance

- [X] The bug is reproducable on the [official hosted instance](http://piped.kavin.rocks/) or is API related.

### Describe the bug

When subscribing to a music channel, you don't see the published videos in your feed because they are actually uploaded from a "sub-channel"

### To Reproduce

1. Login on Piped
2. Subscribe to a music channel that recently published a video (e.g. https://piped.kavin.rocks/channel/UCiGm_E4ZwYSHV3bcW1pnSeQ)
3. Look in your feed, the uploaded video does not show up

### Expected behavior

When you subscribe to the "parent-channel" it should show the videos in your feed, and it should also be shown as the uploader.
See https://piped.kavin.rocks/watch?v=H_hgw-V-wBI, you can see that video on the parent-channel page but when you click it, it shows https://piped.kavin.rocks/channel/UCDGmojLIoWpXok597xYo8cg as the uploader channel

### Logs/Errors

 Not applicable

### Browser, and OS with Version.

Firefox 99.0.1 on Arch Linux.

### Additional context

I'm not sure if it happens with other music channels. I only tested it with Billie Eilish.

Original YouTube links:
- Parent-channel: https://www.youtube.com/c/BillieEilish (https://www.youtube.com/channel/UCiGm_E4ZwYSHV3bcW1pnSeQ)
- Sub-channel: https://www.youtube.com/user/BillieEilishVEVO (https://www.youtube.com/channel/UCDGmojLIoWpXok597xYo8cg)
- Test video: https://www.youtube.com/watch?v=H_hgw-V-wBI (shows the parent-channel as uploader)

**Comment by Bnyro** [comment]
Not possible as rejected by NewPipe.
