### ISSUE TITLE
Add Support for Switching Languages in Audio

### ISSUE THREAD

**Issue by IkelAtomig** [TeamPiped/Piped#999]
If you see this video in Piped - https://www.youtube.com/watch?v=3jS_yEK8qVI, The Audio is a Different Language, While in Youtube, It's english and I can switch Audio tracks. I use silkky.cloud Instance.

**Comment by FireMasterK** [comment]
Closing with https://github.com/TeamPiped/Piped/commit/5a268b26bd13c844bb8b183837152f130cb42c52.

**Comment by Latrolage** [comment]
is it really added, I still can't see it on the main instance with the given link?
